### PR TITLE
Rename current_resource method on Chef::Resource as current_value.

### PR DESCRIPTION
**Pull request by mcquin**
Resolves https://github.com/chef/chef/issues/3897

@jkeiser @jaymzh @chef/client-core

### CODE REVIEW

**Comment by lamont-granquist** [comment]
dammit i really want that method, we also RFC'd this and approved it.

**Comment by coderanger** [comment]
@lamont-granquist Go go gadget Chef 13? :-(

**Comment by mcquin** [comment]
We can't name it `current_resource` and maintain its desired behavior without introducing confusion with `Chef::Provider`'s `current_resource`. @jkeiser and I thought about renaming it to `current_value`, but we were hesitant to introduce a new method name because method names are forever.

What do you think about calling it `current_value`?

**Comment by coderanger** [comment]
I was the one that requested it be `resource` to reinforce the connect with `load_current_resource`. I still stand by that :-/

**Comment by mcquin** [comment]
On a provider, it's `load_current_resource` and `current_resource`. On a resource, we have `load_current_value`. Why shouldn't it be `current_value`?

**Comment by lamont-granquist** [comment]
well, there's something a little odd with it:

```
res = file "/tmp/foo.txt" do
  mode 0644
end
```

returns a resource -- the new_resource

```
res = file "/tmp/foo.txt" do
  mode 0644
end.resource
```

then returns a resource -- the current_resource

but when i read that last one it reads to me like it should just return itself...

"if i build a resource and call the resource method to return a resource i get...  a different resource?"

**Comment by lamont-granquist** [comment]
This morning 'current_value' is making sense to me.  What is being returned isn't really the current_resource either since its a resource that we construct which is very much like the current_resource but its not `equal?` to the current_resource so calling it something else seems fine.

**Comment by mcquin** [comment]
Method renamed `current_value`.

**Comment by jkeiser** [comment]
Better than not having it. And it fits reasonably well with what you'd need to do for other types. :+1: and *sooooo* glad we don't have to remove it, it makes the world so nice.

**Comment by thommay** [comment]
:+1:

**Comment by lamont-granquist** [comment]
@jkeiser you should probably amend the RFC

**Comment by jaymzh** [comment]
Late to the game here... but :+1: 
I'll test a nightly build today if I get a chance.

**Pull request merged**
