### PR TITLE
Make cron provider work when Chef is run as non-root user.

### PR DESCRIPTION
**Pull request by kwilczynski**
Also, move it onto Chef::Mixin::ShellOut.

Signed-off-by: Krzysztof Wilczynski <krzysztof.wilczynski@linux.com>

### CODE REVIEW

**Comment by kwilczynski** [comment]
@lamont-granquist I will move this to my own fork too.

**Comment by lamont-granquist** [comment]
@kwilczynski you want to fix this up or should we close this?

**Comment by kwilczynski** [comment]
@lamont-granquist don't close. I will finish this (it's still broken, technically). Sorry for the delay, by the way.

**Comment by btm** [comment]
@kwilczynski poke.

**Comment by kwilczynski** [comment]
@btm let me look into this again. I am sorry. I got swamped with things.

**Comment by kwilczynski** [comment]
@btm can you assign this to me? (somehow)

**Comment by btm** [comment]
Github doesn't let you assign issues to people who aren't in the organization. :(

**Comment by thommay** [comment]
Closing due to old age. @kwilczynski if you have cycles to get back to this feel free to reopen and finish up. Thanks!

**Pull request closed without merging**
