### PR TITLE
Can I maintain things?

### PR DESCRIPTION
**Pull request by jdmundrawala**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
U Can Haz :+1:

**Comment by nathenharvey** [comment]
@smurawski @jonlives @jaymzh @tyler-ball @danielsdeleo @mcquin can we get a few more :+1:'s here?

**Comment by tyler-ball** [comment]
:+1: :guitar: :rocket:

**Comment by danielsdeleo** [comment]
:+1:

**Comment by justanshulsharma** [comment]
i also wanna become maintainer :lollipop:

**Comment by jonlives** [comment]
:+1: to @jdmundrawala, yay!

**Comment by jonlives** [comment]
@justanshulsharma you'll probably want to submit yourself as a separate PR :)

**Comment by nathenharvey** [comment]
Once @smurawski signs off on the Windows bit this should be good to merge

**Comment by smurawski** [comment]
:+1:  of course

**Pull request merged**
