### PR TITLE
Add Rubinius to Build Matrix with Allowed Failure

### PR DESCRIPTION
**Pull request by bjfish**
Please add Rubinius to the build matrix with failure allowed.

I would like to ensure Chef builds on Rubinius. Thank you.

### CODE REVIEW

**Comment by samrees** [comment]
This is excellent thank you.

**Comment by lamont-granquist** [comment]
It looks like this is blowing up when trying to install ruby-shadow on rubinius which is not very useful for us and doesn't help with determining how well chef itself supports rubinius or not

**Comment by bjfish** [comment]
@lamont-granquist There is currently a pull request open to hopefully fix ruby-shadow on rubinius https://github.com/apalmblad/ruby-shadow/pull/24

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @bjfish

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by lamont-granquist** [comment]
still looks like ruby-shadow fixes have not been merged

**Comment by bjfish** [comment]
ruby-shadow now has fix released in the latest version: https://github.com/apalmblad/ruby-shadow/pull/24#issuecomment-146000788

**Comment by thommay** [comment]
@bjfish can you rebase onto master and then we'll review and merge this. Thanks!

**Comment by coderanger** [comment]
RSpec isn't officially supported on Rubinius so this seems unlikely to be super helpful.

**Comment by lamont-granquist** [comment]
lets try merging this after a rebase.  we can turn it back off again if it isn't useful.

**Comment by btm** [comment]
This was merged in #4239

**Pull request closed without merging**
