### PR TITLE
Fix chomp error for nil class

### PR DESCRIPTION
**Pull request by piyushawasthi**
wrt https://github.com/chef/chef/issues/6165

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@mwrock this looks correct?  once this is fixed, nil values as versions in the generated hash should turn into nil values in e.g. installed_version and that should be handled fine by the rest of the package provider machinery...

**Comment by ferventcoder** [comment]
This may be incorrect upon a closer look - I'm guessing something is breaking due to a trial message showing through, even with `-r`.

**Comment by ferventcoder** [comment]
But this could also be correct.
It may be better to discard any that don't have versions.

**Comment by mwrock** [comment]
I think this is good. As @ferventcoder mentions, these error cases are likely because of some text completely unrelated to a individual package. We could also discard those items, but even if we don't they should not interfere with the valid packages in the hash.

**Comment by lamont-granquist** [comment]
and now that we've dropped 2.2 was can finally use the ruby 2.3 safe navigation operators...

**Pull request merged**
