### PR TITLE
Lcg/run levels

### PR DESCRIPTION
**Pull request by lamont-granquist**
closes #1642

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by coderanger** [comment]
If we are adding this, it should be added to all service providers where it makes sense and should be a fatal error is specified for a provider that doesn't support it.

**Comment by lamont-granquist** [comment]
We already decided to merge #1642, this is just the work to rebase, add a changelog and add the one missing spec

**Comment by coderanger** [comment]
Okay, should add the fatal error for other providers then.

**Pull request merged**
