### PR TITLE
add create and delete actions for windows_service

### PR DESCRIPTION
**Pull request by jasonwbarnett**
### Description

adds `:create`, `:delete`, and `:configure` actions to the `windows_service` resource.

### Issues Resolved

- #2518
- https://tickets.opscode.com/browse/CHEF-3865#

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by btm** [comment]
Thanks @jasonwbarnett, looks like you've put some work and thought into this.

Appveyor is still broken here, but you'll see on Travis that `win32/windows/constants` isn't part of the standard library. The win32 gems are only dependencies on Windows, so you'll need some conditionals and/or rspec filters around those requirements.

Please look at adding unit and functional test coverage for the new actions. There are some changes to existing functionality here so fixing up functional tests first could help ensure we don't have regressions.

And take a look at [RFC082](https://github.com/chef/chef-rfc/blob/master/rfc082-deprecation-policy.md) regarding deprecating functionality.

**Comment by jasonwbarnett** [comment]
@btm I wanted to submit it to get feedback sooner, rather than later. I'll be sure to update functional test and add new unit/functional tests.

There are a ton of constants in the win32-service gem. Does it make sense to copy those constants into the chef code base to eliminate the dependency across all operating systems? I'm looking for a little guidance here.

**Comment by btm** [comment]
If you're going to use most of the constants, I'd probably copy the file in and copy the license and copyright in it. I'll check internally if we're okay with that license-wise.

**Comment by btm** [comment]
Yeah, we'd be okay with copying that constants file to Chef in regards to licensing.

**Comment by thommay** [comment]
Thanks for this great addition!

**Comment by lamont-granquist** [comment]
So this needed a bunch of rspec work to fix travis + appveyor, things got very angry + red

**Comment by jasonwbarnett** [comment]
I’ll try to fix this up at some point. I just haven’t had time to finish this work fully.

**Comment by jasonwbarnett** [comment]
ok- starting to work on this now. I'll let you know when I have a solid suite of tests covering new functionality + existing tests working :)

**Pull request merged**
