### PR TITLE
Remove myself as a maintainer.

### PR DESCRIPTION
**Pull request by mcquin**
I am unable to keep up with maintainer responsibilities. Please `@mention` me if there are issues or pull requests I can provide feedback on, I'm completely available for questions and providing feedback as needed. =)

@chef/client-core

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:+1:?

**Comment by danielsdeleo** [comment]
Sadly, :+1:

**Comment by jaymzh** [comment]
=(

:+1:

**Comment by btm** [comment]
:+1:

**Comment by jonlives** [comment]
:+1:  :(

**Comment by ranjib** [comment]
:+1:

**Comment by btm** [comment]
Merged as 8bb31f986e19d108485312e6b20524b38f2facae. Thanks @mcquin.

**Pull request closed without merging**
