### PR TITLE
Adding omnibus-chef to core maintainer projects

### PR DESCRIPTION
**Pull request by tyler-ball**
\cc @chef/maintainers

### CODE REVIEW

**Comment by thommay** [comment]
Please update the toml file not the (generated) markdown file.

**Comment by tyler-ball** [comment]
@thommay Updated!  Should I do something to generate the md file?

**Comment by danielsdeleo** [comment]
:+1: modulo whatever stuff needs to be done to sync the files and so on.

**Comment by ranjib** [comment]
:+1:

**Comment by thommay** [comment]
@tyler-ball `rake maintainers:generate`

**Comment by thommay** [comment]
:+1:

**Pull request merged**
