### PR TITLE
remove unreachable code

### PR DESCRIPTION
**Pull request by lamont-granquist**
fixes some Linting cops:

* Lint/UnreachableCode
* Lint/Loop
* Lint/LiteralInCondition
* Lint/AmbiguousRegexpLiteral
* Lint/DefEndAlignment
* Lint/BlockAlignment

### CODE REVIEW

**Comment by jdmundrawala** [comment]
:+1:

**Comment by ranjib** [comment]
```ruby
until ignorer
end
```
?

there are couple of other places dead codes are marked, like the noop resource attribute etc. should we nuke them as well?

**Comment by ranjib** [comment]
:+1: btw

**Comment by lamont-granquist** [comment]
Okay that's enough for today.

SCOPE IS ONLY THESE FEW LINT CHECKS FOR NOW, THIS PR IS NOT A BIKESHED IM NOT FIXING ANYTHING ELSE IN THIS PR.

Sorry for screaming, but I want a thumbs up / thumbs down just on these edits.  Keep the ADHD turned down low, I'm sure we can all find a million other things to fix.

@chef/client-engineers @chef/client-core review

**Comment by lamont-granquist** [comment]
And @ranjib that's not really directed at you, that's directed at everyone, I just want to keep edits like this very bikeshed low.  There's a huge bikeshed we could open up again for the nth time on having rubocop built into travis and how to go about it, and this isn't the PR to have that discussion again either.

Just trying to use some of the good out of rubocop to slowly improve code quality.

**Comment by danielsdeleo** [comment]
That's fine :+1:

**Comment by ranjib** [comment]
@lamont-granquist no worry :-) i was not asking to do that in this PR, i found couple of marked dead code earlier, and i was not sure whether we can raise PR's to erase them.

**Comment by stevendanna** [comment]
:+1:

**Comment by lamont-granquist** [comment]
Yeah if you can find dead code its good to pull it.  However, its always possible that someone may be using the code as a library or subclassing it (particularly in knife code).  This was the only code that static analysis found which was really dead.

**Pull request merged**
