### PR TITLE
Return empty array if no service  unit files found on systemd backed distros

### PR DESCRIPTION
**Pull request by ranjib**
https://github.com/chef/chef/issues/3934

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:+1: 

could use a spec test to not regress.

**Comment by lamont-granquist** [comment]
@chef/client-core could use this getting reviewed and merged for Chef 12.5.0

**Comment by danielsdeleo** [comment]
Yup, could use a spec to prevent regressions. Also, does the command have specific exit codes for different failure conditions or any other characteristics we could use to make sure when we `rescue Mixlib::ShellOut::ShellCommandFailed` we're only dealing with the case that no services are found?

**Comment by jkeiser** [comment]
@ranjib @lamont-granquist I went through and broadened the provider_resolver tests so they could include this case. Now instead of mocking the service_provider results, we mock the files and commands that get run by them (mocking the outside world). This allowed me to add a test for "systemctl list-unit-tests returns exit code 1".

This branch has your fix and the test fixes: https://github.com/chef/chef/pull/3972

**Comment by ranjib** [comment]
i'll close this then.

**Pull request closed without merging**
