### PR TITLE
Drop privileges before creating files in solo mode

### LINKED ISSUE #8360: Chef solo with --user drops permissions after it has created artifacts
## Description
When using `chef-solo --user foo --recipe-url` the cache directory (and others) has to be preconfigured to be owned by 'foo'.

## Chef Version
14.11.21

## Platform Version
Ubuntu Linux 18.04.2

## Replication Case
from @teknofire:

create /tmp/solo.rb:
```
file_cache_path "/tmp/chef-solo/cache/"
file_backup_path "/tmp/chef-solo/backup/"
cookbook_path "/tmp/chef-solo/recipes/cookbooks/"
log_level :info
```
then run:
```
chef-solo --format doc --recipe-url https://github.com/teknofire/chef-solo-test/releases/download/v1.0/chef-solo.tar.gz --user opscode --override-runlist 'recipe[testing]' --config /tmp/solo.rb 
```

## Client Output
```
[2019-04-11T16:48:57-04:00] INFO: About to change privilege to opscode
[2019-04-11T16:48:57-04:00] INFO: Started chef-zero at chefzero://localhost:1 with repository at /tmp/chef-solo/recipes
  One version per cookbook

[2019-04-11T16:48:57-04:00] FATAL: Errno::EACCES: Permission denied @ dir_s_mkdir - /tmp/chef-solo/cache
```

### PR DESCRIPTION
**Pull request by btm**
Fixes #8360

for discussion

### CODE REVIEW

**Comment by tas50** [comment]
Any idea why we previously kept this permission setup out of legacy mode?

**Comment by btm** [comment]
@tas50 this moves it out of the legacy mode portion of the conditional. The other half of the conditional that calls `Chef::Application::Client.new.run` is the chef-zero mode, and everything in `run`, including ` setup_application` is called again a second time. That happens to be #6375 and doesn't have an easy solution 

In general when running daemonized I think it's common to read/write some files as root before you drop privileges, like secrets. I'm not sure I'd want to change that behavior in Chef::Application itself which gets inherited into Chef::Application::Client. But Solo doesn't daemonize, so I think it's fine to drop privileges then create the files in that regard. But I don't know if that would break another use case. I can't think of one that would work though.

**Comment by lamont-granquist** [comment]
So why is there the same setup_application method in Chef::Application::Client which is not called from Chef::Application::Client#run?  Because now chef-solo-legacy and chef-solo-zero both are doing this, but chef-client is not.  And chef-solo (both ways) should support the same daemonization options as chef-client, at least in principle.

**Comment by btm** [comment]
@lamont-granquist Chef::Application::Client inherits run from Chef::Application, which does call setup_application.

https://github.com/chef/chef/blob/master/lib/chef/application.rb#L65

**Pull request merged**
