### PR TITLE
Remove use_inline_resources

### PR DESCRIPTION
**Pull request by coderanger**
This removes `use_inline_resources`. This also means the `action :name do ... end` syntax is available to all providers instead of just via LWRPBase. If you want to avoid this mode, use the `def action_name ... end` syntax instead.

### CODE REVIEW

**Comment by tas50** [comment]
What happens if use_inline_resources is there? Not an error hopefully?

**Comment by coderanger** [comment]
It's currently an error, I can add it back as a no-op though :)

**Comment by coderanger** [comment]
But the alternative to `use_inline_resources if defined?(use_inline_resources)`

**Comment by tas50** [comment]
Having this not break the world would be ideal. Deprecation + a FC warning will clean up most of it before Chef 14 where you can just delete it.

**Comment by coderanger** [comment]
Yep, just added that.

**Comment by coderanger** [comment]
Will fix #3123 when merged.

**Comment by coderanger** [comment]
Should be ready for review, though it will need a deprecation page made before release.

**Comment by thommay** [comment]
Might be good to have a test that ensures the deprecation warning fires as expected, otherwise 👍

**Comment by thommay** [comment]
OK, so we just had a long conversation about we want to do this deprecation. If we put this deprecation in as things stand, any cookbook that wants to have tests with deprecation_warnings_as_errors and still support 12 and 13 will have to wrap `use_inline_resources` in a `Gem::Version.compare` or similar, which is pretty user hostile.
How do you feel about either making `use_inline_resources` a null method for right now, or wrapping the deprecation warning up so it'll only start firing after 13.6?

**Pull request merged**
