### PR TITLE
Removed after_created and added test to recipe_spec

### PR DESCRIPTION
**Pull request by nsdavidson**
Accidentally deleted the branch, closing #2157

### CODE REVIEW

**Comment by stevendanna** [comment]
This fixes #2047 

@danielsdeleo @lamont-granquist While I can see the benefit of putting this in define_resource_requirement, `validate_source` is currently called in the set_or_return here: https://github.com/nsdavidson/chef/blob/Issue-2047/lib/chef/resource/remote_file.rb#L57

Given that is the standard interface we provide for resource attributes, I think we should merge this unless one of you know a way in which this change would lead to incorrect behavior or unless one of you have the time to take on the changes you want.

:+1: from me.

**Comment by lamont-granquist** [comment]
yeah i think that looks fine, it should then go through the normal delayed set_or_return handling where its validated when its accessed the first time.

**Comment by sean-horn** [comment]
@danielsdeleo @lamont-granquist  Are we planning on this going out in the next release? Should I add it to the milestone for 12.1.0 ? 

Zendesk 3259

**Comment by danielsdeleo** [comment]
Yeah, that's fine

**Comment by lamont-granquist** [comment]
looks like it needs a rebase

**Comment by sean-horn** [comment]
@nsdavidson Please rebase. It looks like we are ready to merge after that.

**Comment by btm** [comment]
Rebased into master as 702af11fcd38cb8d769f30e9cb5f4bf8dd667e21

**Comment by g12megha** [comment]
I tried using 
 remote_file "#{Chef::Config['file_cache_path']}/sqlanywhere_ga.tgz" do
     source lazy {"http://www.yahoo.com"}
    mode "0644"
     end
But it shows the same error [2016-03-18T20:45:16+00:00] DEBUG: Re-raising exception: Chef::Exceptions::InvalidRemoteFileURI - #<Chef::DelayedEvaluator:0x000000041c7628@/var/lib/monsoon/repos/mobilesecuredevelopment/nile/chef/cookbooks/sms-sqlanywhere/recipes/linux.rb:7> is not a valid `source` parameter for remote_file. `source` must be an absolute URI or an array of URIs.

Has this issue been resolved ?

**Pull request closed without merging**
