### PR TITLE
Log platform along with client version and pid.

### PR DESCRIPTION
**Pull request by randomcamel**

### CODE REVIEW

**Comment by coderanger** [comment]
Might be worth including it in the "pretty" error output too, since people usually just paste that into bug reports.

**Comment by jrunning** [comment]
I've updated this PR re: @coderanger's comments. It now appends a `Platform` section to the pretty error output, e.g.:

```text
Platform:
---------
x86_64-darwin14.0
```

I also added some tests.

**Comment by tyler-ball** [comment]
:+1:

**Comment by randomcamel** [comment]
:+1: That is slick. =)

**Pull request merged**
