### PR TITLE
Add myself as a core maintainer

### PR DESCRIPTION
**Pull request by itmustbejj**
Signed-off-by: Josh Hudson <jhudson@chef.io>

### Description

Add myself as a core maintainer.

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by itmustbejj** [comment]
@chef/client-core

**Comment by lamont-granquist** [comment]
travis failed, lulz...

**Comment by thommay** [comment]
@chef/maintainers thumbs please!

**Comment by stevendanna** [comment]
gif-keyboard-10077690529311962234

**Comment by smurawski** [comment]
We just need one more of @btm @fujin @jaymzh @jaym @jkeiser @jonlives @mcquin @ranjib @tduffield @tyler-ball to approve for merge

**Pull request merged**
