### PR TITLE
Revert user home management PRs

### PR DESCRIPTION
**Pull request by jkeiser**
These PRs need some more baking on various OS's and are preventing current builds from getting out.

- #5122
- #5231
- #5232

### CODE REVIEW

**Comment by lamont-granquist** [comment]
can we not?   it shouldn't take me that long to get back to green again today.

**Comment by jkeiser** [comment]
@lamont-granquist happy to oblige if you think it can be merged within a few hours--but the rest of the project is suffering test coverage and it's not actually hard to revert a revert.

**Comment by lamont-granquist** [comment]
it shouldn't take that long

**Comment by jkeiser** [comment]
@lamont-granquist :+1:

**Comment by jkeiser** [comment]
(And let me know how I can help!)

**Pull request closed without merging**
