### PR TITLE
Chef Core maintainers: ++fujin

### PR DESCRIPTION
**Pull request by fujin**
per https://github.com/chef/chef/pull/2710#issuecomment-73626709

I have a Fedora environment at work currently (fleet of about 250) so would considering putting myself forward for those if I end up maintaining a lot of Redhat-specific crap.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:+1:

**Comment by ranjib** [comment]
:+1:

**Comment by btm** [comment]
:+1:

**Comment by joemiller** [comment]
werd

**Comment by damm** [comment]
:thumbsdown:

Good thing my opinion doesn't count :)

**Comment by fujin** [comment]
@damm I introduced you to Chef after learning Merb with you, via the Feather project. I showed you a home in a community that did not exist. You've made your own choices - but they do not affect me, nor Chef, and I'm thankful I'm able to put our time together behind me.

I don't know where we ever went wrong, but I consider the time we worked together to be the worst possible examples of job-security through obfuscation, malpractice and worse; I was thankful to see you relieved of your post. It took some effort, but we automated every single piece of shit you left in your wake.

I hope to never inherit an installation tainted by you again. I have blocked you on all communication mediums. I will aggressively give a negative character reference toward you in the event I that I am requested of one, although this seems extremely unlikely.

Please feel free to avoid any direct communication with me in the future. I would not mind if you disassociated yourself with the project entirely, including giving up your squatting on the Supermarket.

Good day,

--aj

**Comment by adamhjk** [comment]
As one of the oldest contributors to Chef, and a current contributor, with (so far) universal support (including mine) - AJ should absolutely be a maintainer.

As a community, we have a code of conduct, we have multiple governance documents, and plenty of ways to work together - and to work through our issues.

**Pull request merged**
