### PR TITLE
Adding returns property to chocolatey_package resource

### LINKED ISSUE #5030: chocolatey_package resource now reports non-zero as failure in successful scenarios
## Description

I mentioned this before in April to @mwrock - https://github.com/chocolatey/choco/issues/512. 0.9.10 just released today and folks are going to start reporting breakages even though we noted it in our release notes and tried to give plenty of notice to folks that it was coming (2 months notice in this case).

Here is the relevant portion of the [ChangeLog](https://github.com/chocolatey/choco/blob/master/CHANGELOG.md#0910-june-17-2016) (under breaking changes):

> - Exit with the same exit code as the software being installed - see [#512](https://github.com/chocolatey/choco/issues/512)
> 
> There are more exit codes from Chocolatey now that indicate success -`0`, `1605`, `1614`, `1641`, and `3010`. You may need to adjust anything you were using that would only check for 0 and nonzero.
> If you need the previous behavior, be sure to disable the feature `usePackageExitCodes` or use the `--ignore-package-exit-codes` switch in your choco commands.
## Platform Version

Windows 
## Replication Case

Install a package with Chocolatey 0.9.10 that would exit with 3010 indicating reboot, which is now considered a successful exit code by Chocolatey.
## Client Output

The resource thinks there is an error.

### PR DESCRIPTION
**Pull request by Vasu1105**
### Description

Added 'returns' property to chocolatey_package

### Issues Resolved

#5030 

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by btm** [comment]
Travis failure looked like an unrelated timeout, I restarted the job:

```
 1) redirection When the Chef server has a role and another server redirects to it with 302 knife list /roles returns the role
     Failure/Error: @redirector_server, @redirector_server_thread = start_app_server(app, 9018)
     
     Timeout::Error:
       execution expired
     # ./spec/support/shared/integration/app_server_support.rb:36:in `sleep'
     # ./spec/support/shared/integration/app_server_support.rb:36:in `block in start_app_server'
     # ./spec/support/shared/integration/app_server_support.rb:35:in `start_app_server'
     # ./spec/integration/knife/redirection_spec.rb:39:in `block (4 levels) in <top (required)>'
```

**Comment by btm** [comment]
@mwrock, @smurawski , @stuartpreston, review?

**Comment by NimishaS** [comment]
@mwrock , fixed the review comment.

**Comment by NimishaS** [comment]
Created https://github.com/chef/chef/pull/5703 and https://github.com/chef/chef-web-docs/pull/377 too

**Pull request merged**
