### PR TITLE
Chef 12.1.0

### PR DESCRIPTION
**Pull request by jdmundrawala**

### CODE REVIEW

**Comment by btm** [comment]
:+1:

**Comment by lamont-granquist** [comment]
DOC_CHANGES.md?

**Comment by jdmundrawala** [comment]
@lamont-granquist https://github.com/chef/chef/commit/f1d51fca4f5d1e7bfb6c66e0f181535774ee551a#diff-4a11ee028440aff81c1f8937bec62f8d

**Comment by lamont-granquist** [comment]
'k :+1:

**Pull request merged**
