### PR TITLE
Fix knife on windows (rebased against master)

### LINKED ISSUE #3272: knife subcommands do not work anymore on Windows (since Chef 12.3.0.rc.0)
Im trying to run `knife cookbook` or `knife cookbook --help` to get more info about the cookbook subcommands, but it fails like this:
```
C:\Repos\_github\bills-kitchen\target\build\repo\vagrant-workflow-tests\playground\sample-toplevel-cookbook>bundle exec knife cookbook --help
FATAL: Cannot find sub command for: 'cookbook --help'
Available subcommands: (for details, knife SUB-COMMAND --help)

** KNIFE COMMANDS **
Usage: C:/Repos/_github/bills-kitchen/target/build/home/.chefdk/gem/ruby/2.1.0/bin/knife (options)

** PATH-BASED COMMANDS **
knife xargs [COMMAND]
```

My `Gemfile` looks like this:
```
source 'https://rubygems.org'
gem 'chef', '12.3.0.rc.0'
```

and it's using the right version, too:
```
C:\Repos\_github\bills-kitchen\target\build\repo\vagrant-workflow-tests\playground\sample-toplevel-cookbook>bundle exec knife -v
Chef: 12.3.0.rc.0
```

This is happens on my Windows machine only, on my Ubuntu it works like a charm.

Can anyone with a Windows at hand reproduce this?

### PR DESCRIPTION
**Pull request by tknerr**
This fixes #3272 (knife subcommands don't work on windows)

See https://github.com/chef/chef/pull/3277 for the original PR against 12.3-stable

### CODE REVIEW

**Comment by jdmundrawala** [comment]
:+1:

**Comment by tyler-ball** [comment]
:+1:

**Comment by tyler-ball** [comment]
Can you update these examples to include 'chef-xxx-universal-mingw32' like @ksubrama mentions in #3278?

**Comment by tknerr** [comment]
@tyler-ball @ksubrama yep, I will add another test case for the "universal" gems.

I'm also considering to relax the regex a bit, to support more than two dashes. I have no list of available / existing `RbConfig['RUBY_PLATFORM']` values available, but I [suspect](http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/17139) they might contain more than two `-` inbetween

**Comment by tknerr** [comment]
@tyler-ball @jdmundrawala @ksubrama what do you think about relaxing the regex?

From: `%r{/chef-#{Chef::VERSION}(-\w+)?(-\w+)?/}.freeze`
To: `%r{/chef-#{Chef::VERSION}(-\w+)*/}.freeze`

**Comment by ksubrama** [comment]
That seems reasonable to me.  From what I know, the Gem::Platform class (that's used in gemspec) has 3 fields: cpu, os and version which may or may not be present and if they are present, they are '-' separated.  You could just add another (-\w+)? but *shrug* I'm also not really worried about accidentally over-matching another gem that just magically happens to start with the name "chef-<version-string>".  Is this some weird security scenario we'd need to worry about?  Somebody going out and making gems like chef-12.2.1-1-lololpwnd-whatever ?

**Comment by ksubrama** [comment]
Merged as e19aacce268f37e147228a379396b3adb4f648ce

**Pull request closed without merging**
