### PR TITLE
Add --profile to all rspec rake tasks

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by coderanger** [comment]
How much does this slow down the (already slow) tests?

**Comment by jkeiser** [comment]
@coderanger not sure yet :) I wasn't expecting it to be bad, since the only visible effect of the option is to tell you how long the top 10 slowest tests took.

**Comment by jkeiser** [comment]
@coderanger it looks like no difference (line noise).

Ruby 2.2 tests:
- current master: 8:57 (https://travis-ci.org/chef/chef/builds/106332694)
- this branch: 8:50 (https://travis-ci.org/chef/chef/builds/106335645)

Ruby 2.1 tests:
- current master: 22:35 (https://travis-ci.org/chef/chef/builds/106332694)
- this branch: 23:06 (https://travis-ci.org/chef/chef/builds/106335645)

**Comment by coderanger** [comment]
:+1: I get antsy when I see "profile" since that can mean Very Bad Things™ :)

**Pull request closed without merging**
