### PR TITLE
Deprecate Cisco platforms

### PR DESCRIPTION
**Pull request by scotthain**
Signed-off-by: Scott Hain <shain@chef.io>

### Description

Chef Client will no longer be built or tested on Cisco platforms.

@chef/engineering-services 

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by shortdudey123** [comment]
Curious as to why

**Comment by scotthain** [comment]
@shortdudey123 - the quick answer is there is a maintenance cost associated with building, testing, and integrating it with our internal pipelines.

**Comment by shortdudey123** [comment]
Gotcha, makes sense

**Comment by scotthain** [comment]
@shortdudey123 to be super clear, it is still 100% possible to build and use client on those platforms, we're just not providing packages in the future.

**Comment by shortdudey123** [comment]
Thats what i assumed :)

**Pull request merged**
