### PR TITLE
Change inspect to string to be more human-readable.

### PR DESCRIPTION
**Pull request by cmluciano**
Should close [Issue 2863](https://github.com/chef/chef/issues/2863)

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core @chef/client-engineers can we get a couple :+1: on this?

**Comment by lamont-granquist** [comment]
:+1:

**Comment by danielsdeleo** [comment]
:+1:

**Comment by tyler-ball** [comment]
:+1:

**Comment by ranjib** [comment]
:+1:

**Comment by jonlives** [comment]
:+1:

**Comment by cmluciano** [comment]
Thanks everyone :)

**Pull request merged**
