### PR TITLE
Move supermarket.getchef.com to supermarket.chef.io

### LINKED ISSUE #2777: knife cookbook site unshare redirect fails due to old supermarket.getchef.com domain.
knife cookbook site unshare my-cookbook
Do you really want to unshare the cookbook mycookbook? (Y/N)y
ERROR: Invalid Redirect: DELETE request was redirected from https://supermarket.getchef.com/api/v1/cookbooks/my-cookbook to https://supermarket.chef.io/api/v1/cookbooks/my-cookbook. Only GET and HEAD supp
ort redirects.
Change your server location in knife.rb to the server's FQDN to avoid unwanted redirections.

Looks like it's hard coded in a few spots in the various `knife cookbook site` knife commands.  Although I tried to manually change them to the right location but the unshare didn't work so maybe this is set elsewhere?  

https://github.com/opscode/chef/blob/master/lib/chef/knife/cookbook_site_unshare.rb#L44

### PR DESCRIPTION
**Pull request by juliandunn**
Minimally-fix #2777 

While @lamont-granquist's comment on that issue is correct (about ripping & refactoring), at least we shouldn't leave these commands in a broken state.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Better than nothin'...

:+1:

**Comment by lamont-granquist** [comment]
@chef/client-core @chef/client-engineers reviews

**Comment by ranjib** [comment]
:+1:

**Comment by jonlives** [comment]
:+1:

**Comment by jdmundrawala** [comment]
:+1: , though I feel like that should be pulled from a single place

**Pull request merged**
