### PR TITLE
Use dpkg-deb directly rather than regex

### PR DESCRIPTION
**Pull request by thommay**
This is based on @kwilczynski's work in #2434

### CODE REVIEW

**Comment by thommay** [comment]
ping @chef/client-core

**Comment by lamont-granquist** [comment]
yeah that looks fine to me.

you're updating the `@new_resource` which should be avoided but you're just preserving the behavior of the old code.  it could probably use a `#FIXME` above it if you don't have time to actually fix it now, those are kind of bad bugs which are often exposed by resource cloning in horrible ways.

**Comment by thommay** [comment]
@lamont-granquist i updated to not hit `new_resource`

**Comment by lamont-granquist** [comment]
if that works, its better, not sure what that code was doing or if you're gonna hit an edge case....

**Comment by lamont-granquist** [comment]
:+1:

**Comment by ranjib** [comment]
:+1:

**Pull request merged**
