### PR TITLE
windows does not have uname

### PR DESCRIPTION
**Pull request by lamont-granquist**
although appveyor does, so must have cygwin?

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@jdmundrawala @chef/client-core dunno why this isn't failing on appveyor...

**Comment by danielsdeleo** [comment]
:shipit:

**Comment by jdmundrawala** [comment]
C:\tools\Ruby200p598\bin\uname.exe

**Comment by jdmundrawala** [comment]
:+1:

**Comment by lamont-granquist** [comment]
Binary is not there in my ruby 2.1.5 install..

**Pull request merged**
