### PR TITLE
Add automated changelog, bump version

### PR DESCRIPTION
**Pull request by chefsalim**
This PR is getting us ready to release Chef 12.6.0
1. It adds infra to start using an automated process to generate change logs
2. It bumps up the Chef and Chef-Config release version to 12.6.0
3. The original change log has been preserved in HISTORY.md.

@lamont-granquist @tas50 @btm @jkeiser

### CODE REVIEW

**Comment by tas50** [comment]
We should make sure we cleanup the PR names and add the labels before we ship 12.6 so we get a more useful automated changelog.  The current one isn't very useful outside of dev circles

**Comment by lamont-granquist** [comment]
:-1: 

this generates a complete mess of the history which will be misleading and useless to users and we are not going to go through and fix it all.  all the mega-PRs are going to be collapsed into one PR and all the detail will be lost.

https://github.com/skywinder/github-changelog-generator/issues/304 is an absolute hard blocker for this.

i started off wanting to use github-changelog-generator for chef/chef, that's why i shipped it ffi-yajl and friends first, then went over to foodcritic and tried to do it with a long history file, and got blocked and stopped...

**Comment by lamont-granquist** [comment]
So this PR also wound up under 12.5.1 even though it hasn't been released yet and certainly isn't in 12.5.1 so there's some kind of bug there:

https://github.com/chef/chef/pull/4105

That PR also exemplifies a huge workflow issue when it comes to chef/chef and merging outstanding ready-to-merge PRs.  The reason why that happens is that doing the rebase and merge of all those PRs one-by-one is annoying as hell, but we can't just click the 'merge' button on those because in many cases those PRs ran their travis results against a fork of master that was 12 months in the past and even though there's still not merge conflict there's no guarantee the build is still green.  Going through 20 of those one by one is a terrible policy towards actually getting work done because I started doing that with #4096, #4097, #4098, #4099, #4100 until after 5 of them I got sick of it and cut #4105 to merge the remaining 16 PRs and got that one merge done faster than it took to merge the other five (roughly one day of work to do 5, and one day of work to do the next 16 in one go).

When I did that, I consciously thought to myself "well fuck it I guess we're not using github-changelog-generator this time around" with a mental note that we needed to discuss how to solve this problem.

The reason why is that now none of those PRs appear in the autogenerated CHANGELOG.  So for example I manually added #3650 to the CHANGELOG but github-changelog-generator threw it away.  I think we can add closed PRs into github-changelog-generator but that introduces noise in PRs that we closed and didn't merge and aren't really changes and there's no good way to distinguish between closed PRs that were actually added somehow and closed PRs that were abandoned/wontfixed.  We can start going through and start making it policy to add changelog_skip or wontfix or whatever tags to all the closed PRs that were never actually merged, but now we've got a huge history problem which is compounded by the bugginess with the since_tag.

**Comment by lamont-granquist** [comment]
So we've got:

- at least two bugs in github-changelog-generator to fix (the since_tag and the fact that it thinks #4105 is already released)
- we need to figure out how to integrate tagging merged PRs correctly going forwards that does not destroy the workflow of the poor bastard who is merging all the outstanding ready-to-merge PRs.

**Comment by lamont-granquist** [comment]
Ah I see, #4105 got "shipped" in "12.5.1-omnibus".

**Pull request closed without merging**
