### PR TITLE
Core: make delayed_action argument mandatory, remove misleading ivar introduced in PR that added delayed_action

### PR DESCRIPTION
**Pull request by lamont-granquist**
see https://github.com/chef/chef/pull/5443#issuecomment-253279021

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@coderanger `Array.new(nil)` gives `[]` which is just a no-op,  IDK if you had better behavior in mind...

**Comment by lamont-granquist** [comment]
i suppose we could just drop the default value and make it ArgumentError if you don't pass it an action.

**Comment by coderanger** [comment]
:+1: for making it required. That basically reduces this to being (well needed) sugar for `add_delayed_notification`.

**Comment by lamont-granquist** [comment]
done, travis willing...

**Comment by rhass** [comment]
@lamont-granquist Can you PR the merge as `enhancement` or `bug` for changelog generation in the next release? Thanks!

**Pull request merged**
