### PR TITLE
Chef 15: Fix order of connection before registering node

### PR DESCRIPTION
**Pull request by dheerajd-msys**
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>

Correct the order of `connection` before `registration`

## Description
Updates order of `connection`  before `registration` for any node, Ensures the `connection` object to be live.

## Related Issue
Fixes https://github.com/chef/knife-ec2/issues/579

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by Vasu1105** [comment]
@dheerajd-msys we register the client first and then go for connection. So this will change the current behavior.

**Comment by Vasu1105** [comment]
@dheerajd-msys I am working on with @btm in fixing the #8576. So may be we can close this PR.

**Comment by dheerajd-msys** [comment]
@Vasu1105 I guess there is a mismatch, connection to the machine should be established before registration of any machine/node to the chef server.

**Comment by Vasu1105** [comment]
@dheerajd-msys may be I am not sure. I have look around the code. @btm  any thoughts on this?

**Comment by Vasu1105** [comment]
What I see here in new bootstrap we are using connection to identify the platform so that we can use the right bootstrap_context. Due to which just to get that connection we have to call connection first but I am not sure how much this is in relation with bootstrap process.

**Comment by btm** [comment]
@dheerajd-msys is there a particular error this fixes? can you post the output here? there are a couple issues going around so we should be specific about which ones this intends to fix.

I made https://github.com/chef/chef/pull/8567 to fix https://github.com/chef/chef/issues/8534 but that caused https://github.com/chef/chef/issues/8576. I think that's what you're trying to fix here.

**Comment by btm** [comment]
The problem was that I was fixing the 'validator' bootstrap path and broke the 'validatorless' bootstrap path, which @marcparadise had been testing. So we need to test both.

**Comment by btm** [comment]
This tested working for me locally with both validatorless and validator bootstrap paths. :+1:

**Comment by dheerajd-msys** [comment]
Yes @btm I was trying to fix https://github.com/chef/knife-ec2/issues/579 which is same as https://github.com/chef/chef/issues/8576. And I have verified that this change works for 'validator as well as 'validator-less'. 👍

**Pull request merged**
