### PR TITLE
remove ruby 2.1 support

### PR DESCRIPTION
**Pull request by lamont-granquist**
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

### CODE REVIEW

**Comment by coderanger** [comment]
Hrm, so this is going to make Travis testing a lot harder for me :-/ Not sure if that's a reason to block it but test matrix management is going to be even worse than it is now.

**Comment by lamont-granquist** [comment]
the whack-a-mole of gems dropping support for 2.1 already is only going to get worse, and for berkshelf it is already pretty intractable to get ruby 2.3/2.4 support while supporting 2.1

and ruby 2.2 has been passing clean on travis for ages and is a pretty suitable ruby to test 12.x on if you need a single ruby to test on (which will inherently get some tests incorrect).   i'm reasonably certain we had clean tests on 2.2 long before we ever managed to get windows and omnibus-chef onto 2.1

for a pattern to use to test old chef versions against the version of chef they were released against you can copy this approach:

https://github.com/chef-cookbooks/compat_resource/blob/master/.travis.yml

now that i look at that i think we can inject `ruby 2.1.9` into the old rubies and modern bundler will actually be able to figure it out so i think that the old crap there can all be simplified a bit.

**Comment by coderanger** [comment]
Yeah, that's what I think I need to move to, just need to write some helpers to generate the travis matrix for each project because I have so many. Probably not an issue for anyone else though so :+1:

**Comment by lamont-granquist** [comment]
looks like we need to wait until ruby-2.3 lands in -current to make the kitchen tests happy

**Comment by lamont-granquist** [comment]
right so the way that i've used kitchen-appbundle-updater over kitchen-dokken means we're using the docker image with the prebaked chef-client rather than installing current from omnitruck.

**Pull request merged**
