### PR TITLE
Provide custom ssl_ca_cert to the Vault

### PR DESCRIPTION
**Pull request by jackivanov**
## Description
- Providing ssl_ca_cert helps to pull the secrets from self-hosted Vaults when the cert is signed internally
- It doesn't looks like /etc/chef/trusted_certs/ is honored when executing this library

## Related Issue
The output is intentionally truncated
```
OpenSSL::SSL::SSLError
----------------------
SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)

 42>>           vault_data = secret(name: kv_v2,
 43:                                service: :hashi_vault,
 44:                                config: vault_config)


System Info:
------------
chef_version=17.9.52
platform=ubuntu
platform_version=18.04
ruby=ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
program_name=/opt/chef/bin/chef-client
executable=/opt/chef/bin/chef-client


Running handlers:
[2023-04-14T13:16:31+00:00] ERROR: Running exception handlers
Running handlers complete
[2023-04-14T13:16:31+00:00] ERROR: Exception handlers complete
Infra Phase failed. 0 resources updated in 07 seconds
[2023-04-14T13:16:31+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
[2023-04-14T13:16:31+00:00] FATAL: ---------------------------------------------------------------------------------------
[2023-04-14T13:16:31+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
[2023-04-14T13:16:31+00:00] FATAL: ---------------------------------------------------------------------------------------
[2023-04-14T13:16:31+00:00] FATAL: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)
```

## Workaround
```
ENV['VAULT_CACERT'] = '/etc/ssl/certs/ca-certificates.crt'
vault_data = secret(name: kv_v2,
                    service: :hashi_vault,
                    config: vault_config)
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by johnmccrae** [comment]
Hi, can you add a couple of tests for this. Like add/remove/capture a failure when it's not used correctly, etc. You don't have to go bananas

**Review by jaymzh — CHANGES_REQUESTED** [review]
John requested some tests here, so requesting changes. Let us know if you need any guidance on that.

**Comment by johnmccrae** [comment]
still waiting on contributor

**Comment by johnmccrae** [comment]
chef-16 is winding down and the contributor appears to have abandoned the PR. Closing

**Pull request closed without merging**
