### PR TITLE
Raise NamedSecurityInfo related exception using HR result.

### PR DESCRIPTION
**Pull request by Aliasgar16**
Done.

Cherry-picked required commits from the [PR](https://github.com/chef/chef/pull/3808). I have added RSpecs for the functionality implemented in the [PR](https://github.com/chef/chef/pull/3808).

### CODE REVIEW

**Comment by Aliasgar16** [comment]
Can anyone take a look at Travis to identify the failure ?. The failures are not related to the changes made in this PR.

**Comment by mwrock** [comment]
Yeah they all look network latency related. Might try rerunning travis later.

**Comment by Annih** [comment]
Thank you @Aliasgar16 for rspec test :)

**Comment by btm** [comment]
I restarted the travis failure last night and now there are more timeouts, so I'm going to write travis off as unrelated on this PR.

@mwrock review?

**Comment by btm** [comment]
@Aliasgar16 I'm curious, did you try running the unit tests without `:windows_only` ?

**Comment by mwrock** [comment]
travis failures look temporal. Restarting them now.

**Pull request merged**
