### PR TITLE
fixes the timing on the chef-shell specs

### PR DESCRIPTION
**Pull request by lamont-granquist**
also makes timing errors hard errors

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core should knock a minute off of the current spec runs.

**Comment by danielsdeleo** [comment]
It'd be a good idea to do an ad-hoc build just to be sure this won't blow up on Solaris or whatever.

**Comment by tyler-ball** [comment]
:+1: other than fails

**Comment by danielsdeleo** [comment]
The errors are weird, looks like we broke knife bootstrap, but that's not related to the change here. :+1: on this patch.

**Comment by lamont-granquist** [comment]
Yeah master is broken due to #3365 at least.  I don't /think/ the test failures are related, but i'm hesitant to merge to master and break it worse right now.

I did actually run this through an ad-hoc, though, and it passed modulo two cosmic rays after i fixed the jankiness around draining stdout.

**Comment by jdmundrawala** [comment]
yes please :+1:

**Pull request merged**
