### PR TITLE
Fix knife client create

### LINKED ISSUE #11985: Bug: knife client create
## Description
 
https://github.com/chef/chef/pull/11241 broke knife client create. The method name indicates it's *or* but it's obvious from the [#check_writable_or_exists][2] method that it was implemented incorrectly and the [unit test][3] is validating the bad behavior. Additionally the [integration test change][4] is effectively implementing the workaround of "touching" the file before create. If the file does not exist (which it shouldn't) it will simply fail stating the file does not exist (which again, it shouldn't; this is a new client and we wish to save the key to the file that does not exist).

## Chef Version

v17.4.38

## Platform Version

Red Hat 7

## Workaround

Simply touch the file where you wish to save the new client key to.

```
$ touch /home/user/my-new-node-name.pem
$ knife client create my-new-node-name --file /home/user/my-new-node-name.pem --disable-editing --config /home/user/my-client-config.rb
```

## Replication Case / Client Output

```text
$ knife client create my-new-node-name --file /home/user/my-new-node-name.pem --disable-editing --config /home/user/my-client-config.rb -VVV
INFO: Using configuration from /home/user/my-client-config.rb
FATAL: File /home/user/my-new-node-name.pem does not exist.
```

[2]: https://github.com/chef/chef/blob/fb087a1dce8addb27fd2dd3eb134bc7f28e1f23f/knife/lib/chef/knife/client_create.rb#L108-L119
[3]: https://github.com/chef/chef/blob/fb087a1dce8addb27fd2dd3eb134bc7f28e1f23f/knife/spec/unit/knife/client_create_spec.rb#L187-L193
[4]: https://github.com/chef/chef/blame/fb087a1dce8addb27fd2dd3eb134bc7f28e1f23f/knife/spec/integration/client_create_spec.rb#L53

### PR DESCRIPTION
**Pull request by jasonwbarnett**
## Description

This fixes #11985

## Related Issue

- #11985

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Review by johnmccrae — COMMENTED** [review]
This looks pretty good, thanks for the fix.

**Comment by johnmccrae** [comment]
Jason, can you take a look at the errors in buildkite? The Ubuntu failure looks like it might be a code-defect. The Centos stuff is a busted builder, you can ignore that. I reviewed the code and approved.

**Comment by jasonwbarnett** [comment]
@johnmccrae I actually was still updating unit. I should have had the title labeled WIP.

I think it's ready for another review.

**Review by lamont-granquist — APPROVED** [review]

**Comment by tas50** [comment]
Thanks for tracking this down and fixing it @jasonwbarnett. I owe you some 🍻 at the next ChefConf

**Pull request merged**
