### PR TITLE
Fixed knife download cookbooks issue which used to corrupt the certificate files each time the command was fired.

### PR DESCRIPTION
**Pull request by Aliasgar16**
Fixes https://github.com/chef/chef/issues/5363
Signed-off-by: aliasgar16 aliasgar.batterywala@msystechnologies.com

### CODE REVIEW

**Comment by btm** [comment]
Nice job debugging @Aliasgar16. Any thoughts on a regression test for this behavior?

**Comment by lamont-granquist** [comment]
is this likely to cause line-ending issues when sharing text files between windows and unix?

**Comment by btm** [comment]
@Aliasgar16 said on CLOGENG-404 (internal) about the existing state:

> When a cookbook is downloaded through knife download cookbooks command, the files contained in the cookbook gets written in the Unix format and thereby results in difference in checksum of the files contained on the Chef_Server and on the local disk.

> Converting the file on the local disk into dos format results in correct checksum being returned.

**Comment by btm** [comment]
@Aliasgar16 We should clearly document what the current behavior is and what the resulting behavior is here in regard to line endings. If I create a file on linux, upload it, then download it on Windows and upload it, is it still the same line ending format?

@lamont-granquist wrote up a nice summary of line ending issues here: https://github.com/chef/chef/issues/4662

**Comment by Aliasgar16** [comment]
@btm @lamont-granquist I have tested multiple scenarios  for `line ending` issues against the fix for `knife download cookbooks` command, below are the results (with step-wise procedure that I have followed):

# Behavior with current Chef code
## Linux

**Step-1**: Create a cookbook and create a text file in that cookbook on Linux platform, upload the cookbook to ChefServer and then download the same cookbook on Windows platform.

**Step-2**: Check the file contents in the same cookbook on Windows and see if it only contains the LF character at the end of each line.
***Actual Result***: yes, it contains only LF character at the end of each line in the file on Windows.

**Step-3**: Upload the same file again from Windows.

**Step-4**: Download that same file on Linux.

**Step-5**: Check the file contents on Linux and see if it only contains the LF character at the end of each line.
- **Scenario-1**: Upload from Windows without editing the file

***Actual Result***: yes, it contains only LF character at the end of each line.
- **Scenario-2**: Upload from Windows after editing the file

***Actual Result***: yes, it contains only LF character at the end of each line.

## Windows

**Step-1**: Create a cookbook and create a text file in that cookbook on Windows platform, upload the cookbook to ChefServer and then download the same cookbook on Linux platform.

**Step-2**: Check the file contents in the same cookbook on Linux and see if it contains the CRLF character at the end of each line.
***Actual Result***: yes, it contains the CRLF character at the end of each line.

**Step-3**: Upload the same file again from Linux.

**Step-4**: Download that same file on Windows.

**Step-5**: Check the file contents on Windows and see if it contains the CRLF character at the end of each line.
- **Scenario-1**: Upload from Linux without editing the file

***Actual Result***: no, it contains only LF character at the end of each line.
- **Scenario-2**: Upload from Linux after editing the file

***Actual Result***: no, it contains only LF character at the end of each line.

# Behavior with new Chef code with changes for `knife download cookbooks` command fix

## Linux

**Step-1**: Create a cookbook and create a text file in that cookbook on Linux platform, upload the cookbook to ChefServer and then download the same cookbook on Windows platform.

**Step-2**: Check the file contents in the same cookbook on Windows and see if it only contains the LF character at the end of each line.
***Actual Result***: yes, it contains only LF character at the end of each line in the file on Windows.

**Step-3**: Upload the same file again from Windows.

**Step-4**: Download that same file on Linux.

**Step-5**: Check the file contents on Linux and see if it only contains the LF character at the end of each line.
- **Scenario-1**: Upload from Windows without editing the file

***Actual Result***: yes, it contains only LF character at the end of each line.
- **Scenario-2**: Upload from Windows after editing the file

***Actual Result***: yes, it contains only LF character at the end of each line.

## Windows

**Step-1**: Create a cookbook and create a text file in that cookbook on Windows platform, upload the cookbook to ChefServer and then download the same cookbook on Linux platform.

**Step-2**: Check the file contents in the same cookbook on Linux and see if it contains the CRLF character at the end of each line.
***Actual Result***: yes, it contains the CRLF character at the end of each line.

**Step-3**: Upload the same file again from Linux.

**Step-4**: Download that same file on Windows.

**Step-5**: Check the file contents on Windows and see if it contains the CRLF character at the end of each line.
- **Scenario-1**: Upload from Linux without editing the file

***Actual Result***: yes, it contains CRLF character at the end of each line.
- **Scenario-2**: Upload from Linux after editing the file

***Actual Result***: yes, it contains CRLF character at the end of each line.


Please let me know your comments on this.

**Comment by lamont-granquist** [comment]
After refreshing my memory about this history of line endings via that write-up I did 6+ months ago, I think I agree this smells like the right thing to do.  In general I think we want to binmode everything, which fixes the bulk of the problems with files being mangled by binmode and is consistent, and then there's still that open issue to create a per-resource flag on file resources.

I suppose this might be a breaking change to some users, but the existing condition is also breaking in a way that also makes simple use cases impossible.  This may cause some users to show up with regressions, but I think that means we need to address #4662 and I'm not sure why the feedback.chef.io bug got closed since we should really fix that one.

**Pull request merged**
