### PR TITLE
Remote file download progress

### PR DESCRIPTION
**Pull request by brandocorp**
I took a stab at implementing this for #2812. I'm not sure how much I like the ProgressBar class, and it could definitely be trashed for something like ruby-progressbar.

I'm looking for feedback, let me know what you think and what needs to be better.

### CODE REVIEW

**Comment by ranjib** [comment]
this is only useful when chef is invoked manually, via tty. Current semantics will make this configurable based on resource attributes, may be its better to trigger this in doc formatter mode, which gets triggered based on TTY presence.

**Comment by lamont-granquist** [comment]
Yeah this should probably not use Chef::Log.info since info is not on the console by default and this would only wind up going into logs.  Be better to hook into the doc formatter.  This might be better implemented as its own event as well and then the progress bar class would be used by the doc formatter and the http class would only fire off events giving how much progress was done on the download.  I think you might also have to worry about the case when you're doing HTTP/1.0 downloads and do not have a Content-size field so cannot compute the %age.

**Comment by brandocorp** [comment]
Thanks @ranjib and @lamont-granquist. I appreciate the feedback and guidance! I will try and make some progress on this soon.

**Comment by brandocorp** [comment]
@ranjib @lamont-granquist, I ended up using an existing event hook `resource_update_applied` which seemed like a reasonable fit for this. 

I'm passing around the resource so I have access to its events. Is there a better way to send events?

**Comment by lamont-granquist** [comment]
We should take this over the line and add some specs and ship it.

**Pull request closed without merging**
