### PR TITLE
Document LCM certificate configuration example for ps_credential

### PR DESCRIPTION
**Pull request by adamedx**
I added an example to make the DSC LCM configuration prerequisite a little more obvious. cc @chefsalim, @jaym, @smurawski, @claire, @ksubrama.

### CODE REVIEW

**Comment by smurawski** [comment]
This example should either call out the other LCM features to configure (configurationmode and rebootnodeifneeded).  Configuration of the lcm is not cumulative, so if you just run the example, any other custom configuration will be reverted to the defaults.

**Comment by smurawski** [comment]
Example of the rest of the LCM configuration - https://github.com/smurawski/chefconf2015_dsc/blob/master/cookbooks/basic_website/recipes/lcm_setup_dsc_script.rb

**Comment by adamedx** [comment]
Ah, didn't know it wasn't cumulative, thank you. I will update.

**Comment by btm** [comment]
@adamedx is this finished?

**Comment by adamedx** [comment]
It's better than finished, it's obsolete since docs were already merged with this.

**Pull request closed without merging**
