### PR TITLE
dscl specs should only run on mac

### PR DESCRIPTION
**Pull request by jdmundrawala**
Not sure why travis didn't catch this, but i've broken specs on everything except mac.

### CODE REVIEW

**Comment by adamedx** [comment]
Looks good, you've validated that the spec still runs on macos?

**Comment by jdmundrawala** [comment]
Yep, runs on osx, and not run on windows

**Comment by tyler-ball** [comment]
:+1:

**Comment by tyler-ball** [comment]
:+1:

**Pull request merged**
