### PR TITLE
Ensure recipe-url works right in solo

### PR DESCRIPTION
**Pull request by thommay**
bonus fix for --ez .

cc @chef/client-maintainers

### CODE REVIEW

**Comment by smurawski** [comment]
👍 LGTM

**Comment by lamont-granquist** [comment]
kind of hurts my brain a bit.  how does solo.rb get invoked any more and what is the plan to kill it all with fire?

**Comment by thommay** [comment]
@lamont-granquist `--legacy-mode`; 13 (at the earliest).

**Comment by lamont-granquist** [comment]
👍

**Pull request merged**
