### PR TITLE
Rescue julia bot by whiltelisting rubocop and stove

### PR DESCRIPTION
**Pull request by ksubrama**
Julia bot seems to silently fail if it finds out-dated gems in the resolved Gemfile and hence has not been bumping our Gemfile in a couple days now.  Whilelist the gems that upset her for now.

### CODE REVIEW

**Comment by ksubrama** [comment]
@PrajaktaPurohit @tyler-ball @btm @randomcamel

**Comment by coderanger** [comment]
Any description of what happened perhaps?

**Comment by jkeiser** [comment]
@ksubrama do we actually intend to distribute stove?

**Comment by jkeiser** [comment]
@ksubrama never mind, it doesn't matter--it'll try to solve the dev deps together regardless of whether it's distributed / installed.

**Comment by randomcamel** [comment]
👍

**Comment by jkeiser** [comment]
:+1:

**Pull request merged**
