### PR TITLE
Support bootstrap attribute from json file ( replace of #3458 )

### PR DESCRIPTION
**Pull request by sawanoboly**
This PR is replace of #3458 .

When passed `@string` via --json-attributes, try read bootstrap attributes from file .

### CODE REVIEW

**Comment by patcon** [comment]
:+1:

**Comment by lamont-granquist** [comment]
Would prefer this as a separate option like --json-file (with -J if its available, or whatever).  We don't use the `@file` notation magic anywhere else.

**Comment by patcon** [comment]
Could we consider starting to use it, and if so, is this not as good a place as any to start? It's a widely understood pattern, and chef already has a perhaps overwhelming number of flags.

**Comment by lamont-granquist** [comment]
I'm not particularly attracted to it, and @thommay wasn't very hot on it either.  If you feel strongly about it, it'd be best to open an rfc against https://github.com/chef/chef-rfc/issues/new and show up to the community meeting and get it through the rfc process.  Then we'd have a policy document that said we should do this to point to where it was written down after we'd all gotten to argue about it.

**Comment by patcon** [comment]
:+1: Skipped around the code for other places this could be used, and this seemed to be the only relevant place. In light of that, let's just make the change @sawanoboly?

**Comment by patcon** [comment]
also, probably `--json-attributes-file`, right @sawanoboly? Since the arg name would be a bit ambigious if reading a script that used just `--json-file`

**Comment by sawanoboly** [comment]
I see. Is it OK for you that I rewrite this feature as new option `--json-attributes-file` ? @lamont-granquist

**Comment by sawanoboly** [comment]
Hmm...

I would like to merge json-attributes into json-attribute-file if set both to avoid conflict.
But I have no idea when json-attribute string is passed as Array. I think that it can't merge simply. What should I do?

**Comment by lamont-granquist** [comment]
If both are set you should either pick one or the other (and tell the user which one you picked), or just raise an exception.

**Comment by sawanoboly** [comment]
OK. Thanks.

**Comment by sawanoboly** [comment]
I've opened as new PR. #3900 
Thanks,

**Pull request closed without merging**
