### PR TITLE
Volunteer myself as a core maintainer

### PR DESCRIPTION
**Pull request by btm**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:+1:

**Comment by tyler-ball** [comment]
:+1: 

\cc @chef/client-core

**Comment by danielsdeleo** [comment]
:+1:

**Comment by jdmundrawala** [comment]
:+1:

**Comment by jonlives** [comment]
:+1:

**Comment by mcquin** [comment]
:100:

**Comment by btm** [comment]
https://github.com/chef/chef-rfc/blob/master/rfc030-maintenance-policy.md#maintainer-1
```
Have patches merged into the relevant subsystem
Be willing to perform the duties of a maintainer
Issue a pull request adding yourself to the MAINTAINERS file for your component
Receive an absolute majority of existing maintainers and lieutenants for your component :+1:
No veto from the component lieutenant
No veto from the current project lead
```

There's a :+1: from 6/7 of the current core maintainers and no veto's so I'm going to merge this in a bit.

**Pull request merged**
