### PR TITLE
Reduce size of nested JSON test to 252 deep

### PR DESCRIPTION
**Pull request by btm**
I got confused running git on the tester with my last commit for #3101.

This should clean it up.

### CODE REVIEW

**Comment by btm** [comment]
This passed on internal CI: http://manhattan.ci.chef.co/view/Chef/job/chef-test/54/

**Comment by btm** [comment]
@chef/client-core if I can get a couple :+1: on this, it makes manhattan green. This fixes #3101 by doing the same thing as #3102 but better.

**Comment by jdmundrawala** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Comment by tyler-ball** [comment]
:+1:

**Pull request merged**
