### PR TITLE
Break out Ohai in maintainers files and add myself

### PR DESCRIPTION
**Pull request by tas50**
https://github.com/chef/ohai/pull/687 was opened to create a maintainers file in Ohai and it was mentioned that it really should go in chef/chef as its own team.  Here it is.

### CODE REVIEW

**Comment by coderanger** [comment]
:+1: as long as that's actually the list of maintainers. Are more people than that are currently committing changes to Ohai.

**Comment by tas50** [comment]
I'd like to propose adding myself, but that will wait until after this PR

**Comment by tas50** [comment]
@coderanger I've updated this PR to also add myself and squashed the history down.

**Comment by thommay** [comment]
:+1:

**Comment by jkeiser** [comment]
:+1:

**Comment by thommay** [comment]
@sethvargo @jonlives @ranjib @btm @lamont-granquist @jtimberman @martinisoft @joemiller votes, please

**Comment by martinisoft** [comment]
:+1:

**Comment by btm** [comment]
:+1:

**Comment by jtimberman** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Pull request merged**
