### PR TITLE
12.4.0.rc.3

### PR DESCRIPTION
**Pull request by jdmundrawala**
cc @chef/client-maintainers

### CODE REVIEW

**Comment by lamont-granquist** [comment]
#3561 probably needs fixing.

**Comment by thommay** [comment]
also we should confirm or deny #3553

**Comment by jdmundrawala** [comment]
#3553 is unrelated to any of the changes that are going into 12.4.0
We shouldn't block for it

**Comment by jdmundrawala** [comment]
#3561 has a fixed that is merged in

**Comment by jkeiser** [comment]
:+1:

**Comment by danielsdeleo** [comment]
I'm not super in the loop right now about regressions but this change itself is fine :+1:

**Comment by tyler-ball** [comment]
:+1: 12.4.0 is out so I think this is only doc changes now

**Pull request closed without merging**
