### PR TITLE
Revert "Use new msys2 based devkit for windows"

### PR DESCRIPTION
**Pull request by neha-p6**
Reverts chef/chef#13038

### CODE REVIEW

**Comment by neha-p6** [comment]
Reverting the change has started creating the build on windows again, hence merging this PR.

**Comment by am185238** [comment]
Why was this reverted? This fixed a gem build issue in chef 17+

**Comment by neha-p6** [comment]
Reason  this change had to be reverted https://github.com/chef/chef/pull/13038#issuecomment-1180052392

**Comment by neha-p6** [comment]
On understanding the impact of reverting the change, we spent time in fixing the underlying issue causing the builds to fail. Thank you for bringing it to our attention and your understanding.
https://github.com/chef/chef/pull/13097

**Pull request merged**
