### PR TITLE
HTTP remote file provider should not fetch the file in --why-run mode

### PR DESCRIPTION
**Pull request by stuartpreston**
Signed-off-by: Stuart Preston <stuart@chef.io>

### Description

This change bypasses the logic that retrieves the content for remote files when used in --why-run mode.  Instead, just the outer converge_by message will be shown, i.e.:

```
Recipe: @recipe_files::C:/projects/repro/why_run_remote_file/repro.rb
  * remote_file[C:/Users/spreston\.chef\local-mode-cache\cache/push-jobs-client-2.5.0-1-x64.msi] action create
    - Would create new file C:/Users/spreston\.chef\local-mode-cache\cache/push-jobs-client-2.5.0-1-x64.msi
    - Would change dacl
    - Would change owner
    - Would change group
```

### Issues Resolved

Previously, the remote file was retrieved anyway for a checksum comparison even though it was not necessary to retrieve the whole file.  A number of cookbooks use remote_file internally to retrieve Chef installation files from our CDN and so this change benefits both Chef Software as well as customer bandwidth charges.

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [x] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
i'm suspicious this is not the correct way to do this, but i wrote a bunch of text and then thought about it in the context of cookbook_file/template resources where you do always have access to the files on disk, and you wouldn't want this behavior, which points towards modifications not being made in Chef::Provider::File itself, but in the content related classes under remote_file.  still this feels side-effecty in that we're relying on a nil tempfile to do the right thing in why-run mode, when that would probably be a hard error in other content classes.

definitely needs unit tests -- unfortunately, because the file provider unit tests are easily the worst code i've ever written (that taught me a lot about how to not write unit tests that bad).

**Comment by lamont-granquist** [comment]
So I guess the side effect of this is that why-run mode with remote_file will always report that the file would be updated even if it wouldn't?  And is there any behavior change around if the cache state exists or not?  Ideally if the cache state is there, we just trust it so if the checksum matches we report the file wouldn't be updated...

**Comment by lamont-granquist** [comment]
So to be clear the use case I'm thinking of is *not* the use case which was reported.  It is the use case for the second time, when you have the cache file available, and it has the checksum of the target file in it.  In that case we would still want to blindly trust that the actual remote_file has not been updated.  But we can do a comparison between the target file and the cached checksum and if they match assume it would not be updated.  I think the existing code would report it always might be updated, so with a remote_file resource in the run list anywhere the why-run output would always be 'dirty' and never 'clean' -- which even if its a pile of lies, users are going to want to see that immediately after a successful convergence (particularly one which was fully idempotent with zero resources updated) that they get zero resources to be updated out of why-run.   I think otherwise we'll get lots of questions...

**Comment by stuartpreston** [comment]
Agreed and thanks as ever for the comments - the original problem spotted with why-run mode is that it will stream the remote file *before* storing the checksum. In some cases (e.g remote_file on the Chef Client which was the original reason for this PR) this means hundreds of megs of download just to get a checksum.  If we changed to store the Etag from the HTTP response we may get further but this involves a significant refactoring.  It would be my preference in why-run more not to attempt any ‘real’ retrieval of the file concerned, but not sure what’s compatible with this second use case.

**Comment by stuartpreston** [comment]
Closing this after triage discussion - significant reworking of the RemoteFile provider would be required to accomplish this.

**Comment by lamont-granquist** [comment]
To capture discussion at least for my future memory self:

- we should look at the actual file on disk and compare to the checksum in the json the remote_file resource writes out -- if it fails, there's no question and we should why-run that it changes and avoid any disk access.
- similarly if the file doesn't exist on disk we can short-circuit everything and why run that it would change because that's easy to do.
- we can pull only the etags off the actual remote file and compare that to the json and if it changes then remote that it would why-run -- but this would still mean one network hit per why-run call (although we could avoid downloading the entire file).  this would be more correct, but it would mean network access so spamming 30,000 why-run CCRs would still potentially DDoS a remote service briefly.

that's a lot more than this PR was setting out to try to do though.

**Pull request closed without merging**
