### PR TITLE
use File.basename rather than reimplementing

### PR DESCRIPTION
**Pull request by thommay**
cc @chef/client-core am I missing something obvious?

### CODE REVIEW

**Comment by thommay** [comment]
Right now this loses the error handling if the name doesn't end in .json, but that feels we're relying on a side effect to enforce file naming.

**Comment by lamont-granquist** [comment]
You could also add `raise "Invalid name #{name}: must end in .json" unless name =~ /\.json$/`

**Comment by lamont-granquist** [comment]
:+1:

**Comment by lamont-granquist** [comment]
wtf is wrong with appveyor?

**Comment by coderanger** [comment]
This would also change things if you feed it a path with `/` in it. The original code leaves it intact, this does not.

**Comment by coderanger** [comment]
Should probably be `File.extname` instead of `basename`.

**Comment by thommay** [comment]
Gonna close this for now, this pattern is all over ChefFS.

**Pull request closed without merging**
