### PR TITLE
ISSUE #3435 - Close old logfile before creating a new one

### PR DESCRIPTION
**Pull request by cachamber**
Possible fix for https://github.com/chef/chef/issues/3435

In essence, check to see if a logging instance exists before creating a new instance.  If so, close the old instance before opening the new one.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Is there a better way to check than Chef::Log.info? that looks like you're getting a side effect and its not the API that i'd expect to call and it fails my does-it-make-sense-still-in-12-months test.  Nothing about the name '#info?' suggests that you're directly testing for presence.

**Comment by lamont-granquist** [comment]
We'd also need a  spec test around this.

I also wonder if its better to put that logic into Chef::Log.init rather than in Chef::Application#configure_logging so that its more generally applied anytime Chef::Log is used.

**Comment by irvingpop** [comment]
hey @cachamber any progress on this one?

**Comment by cachamber** [comment]
@irvingpop  - No update.  I haven't had cycles to spend on it yet.  I expect to have some time in the next week or so.

**Comment by thommay** [comment]
@cachamber hey, are you still interested in getting this finished up?

**Comment by thommay** [comment]
Just merged a change to mixlib-log that should resolve this.

**Pull request closed without merging**
