### PR TITLE
fix Lint/UnusedMethodArgument

### PR DESCRIPTION
**Pull request by lamont-granquist**
prepends '_' to all unused method arguments, autogenerated from rubocop.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-engineers @chef/client-core 

this might be an interesting bikeshed courtesy of rubocop.   this autofixes all unused method arguments to prepend '_' to all of them.  the majority of them seem to be in formatter code where it is deliberate.  trying to remove the arguments from the rest of them will be costly because you're making an API change (and in some cases may be deliberate to avoid a breaking change).  what this change does get you is now it'll be easy to look at the method signature and see that there's an unused argument so that when a dev is working on a piece of code they can see that there's an opportunity to simplify the code.

the argument against it would be that it suppresses all the warnings and hides the information, but i sincerely doubt anyone will ever go through this list and use it as a todo list for triaging all the unused method args and actually filtering them by necessary or breaking change or doing the work to remove them.

**Comment by danielsdeleo** [comment]
Hrm. So I have warnings for unused local variables (not exactly the same as this, but similar) turned on in vim and I like that quite a bit. But this seems to be catching a lot of abstract and semi-abstract methods which exist for documentation purposes as much as anything. From the perspective of hoping that we one day have everything documented well enough that a developer would get a lot of value out of our yard/rdoc API docs, this change is a net negative because it adds/would add noise to the docs. Is there an alternative to rubocop's super ugly comments to opt a class or method out of this rule?

**Comment by lamont-granquist** [comment]
I think the choices in this one are to prepend the underscore like this does, litter all the abstract methods with lots of rubocop hash comments, or just ignore it.  The rubocop hash comments is the clear worst solution there, so if this patch doesn't go in, I'd vote to just ignore the rule.

As an aside the unused local variables in vim thing sounds cool, what plugin are you using for that?

**Comment by danielsdeleo** [comment]
Been using the default Janus stuff. I just upgraded it a few months ago and got it for free.

**Comment by jaymzh** [comment]
:+1:  I love this. I love rubocop.

**Comment by jaymzh** [comment]
(except for their stupid insistence on the newer brokener hash syntax in ruby, we disable that rule)

**Comment by danielsdeleo** [comment]
I'm :-1:  on this, most of these aren't "bad," the methods are intentionally abstract (or semi-abstract). If we could easily exempt files or classes from this, I'd be in favor.

**Comment by smurawski** [comment]
@chef/maintainers We've got a :-1: on this, so it needs an absolute majority of maintainers (at least 6 as of now) to move forward.

**Comment by jonlives** [comment]
I kinda like the easiness of telling that method arguments are unused, but it's not idea if it's gonna add noise to the docs. I don't feel particularly strongly on the subject though so gonna :+1: it - we have the rubocop warnings now, and the docs are sadly a bit of a more long-term project it seems.

**Comment by lamont-granquist** [comment]
:+1:  has 2
:-1:  has 1

i'm somewhat ambivalent and leaning towards dan's :-1: a little.

@chef/client-core @chef/client-engineers unless we get more :+1:'s i think this does not get merged.

i also need to work on collecting which of the lint cops we accept and which we don't.

**Comment by jaymzh** [comment]
These make the code more clear, enable us to auto-lint, and mean when people run rubocop on their own diffs a bunch of other crap doesn't show up.

Plus it's really nice to mark variables as "I don't plant to use this"

**Comment by lamont-granquist** [comment]
We can still autolint, but we'll need to add a .rubocop file which disables this cop.

**Comment by jaymzh** [comment]
I understand how rubocop works... but this is a commonly accepted practice in the ruby community, makes things more clear, and is super easy to autofix. I see no downside here.

**Comment by tyler-ball** [comment]
Because we can enforce rubocop use and we can't enforce IDE plugin use, I'm :+1: on this.  I also dont see yarddoc explaining `_resource` as a big negative.  If someone overwrites that method in a subclass and leaves the variable the same name, they will get a rubocop warning if they start referencing it.

**Comment by lamont-granquist** [comment]
@jdmundrawala @btm @thommay thoughts?

**Comment by thommay** [comment]
i'm net meh on this, but leaning :+1: for much the same reasons as @tyler-ball.

**Comment by stevendanna** [comment]
@danielsdeleo What if we put a .rubocop.yml file down with something like the following configuration:

```yaml
# Only abstract classes should be excluded!
# TODO: Remove when https://github.com/bbatsov/rubocop/issues/1601 is fixed
Lint/UnusedMethodArgument:
  Exclude:
    - lib/chef/event_dispatch/base.rb
```yaml

**Comment by sethvargo** [comment]
I think @danielsdeleo is right here - a cop that complains with unused local variables would be a definitely :+1:. However, unused method arguments are actually quite common, especially for abstract classes, and I do not buy the argument "but this cop is a commonly accepted practice in the ruby community", because it's not. In fact, this is more common than underscored-variables:

```ruby
def method(*)
  raise NotImplementedError
end
```

But it has the major disadvantage of being totally unintuitive to the reader. I'm :-1:.

**Comment by ranjib** [comment]
:-1:

**Comment by lamont-granquist** [comment]
Closing this, its too split.  Need to start working on a cop file and/or chefcop gem that disables this by default.

**Pull request closed without merging**
