### PR TITLE
Convert the 3694 warning to a deprecation so it will be subject to the usual deprecation formatting (collected at the bottom, can be made an error, etc).

### PR DESCRIPTION
**Pull request by coderanger**
Ping @chef/client-core  and @lamont-granquist in particular.

### CODE REVIEW

**Comment by coderanger** [comment]
It should be noted I haven't actually run this with a big, complex converge, we might want to tweak the message formatting to work better with how deprecation errors get shown. Thoughts?

**Comment by lamont-granquist** [comment]
i'm OOTO until mid-next-week...

**Comment by lamont-granquist** [comment]
( 👍 to the general idea, dunno about the formatting, i can check on some of my runs that still have a few 3694 errors and see how they look)

**Comment by lamont-granquist** [comment]
BTW, i'm generally not attached at all to the three line "banner" messages and certainly don't like what they do when they're transported to the bottom of the run, seems to create a mess...

**Comment by lamont-granquist** [comment]
LGTM :+1:

**Pull request merged**
