### PR TITLE
Fix #2663 - refactor to use shell_out in rpm provider

### LINKED ISSUE #2663: rpm_package provider no candidate version error
I have a resource that explicitly sets the provider based on platform. However, it appears as though the compiled resource does not honor this attribute. A package resource is compiled into yum_package, despite declaring the rpm provider. This only occurs on the chef 12 line (tested on 12.0.1).

```
==> c1_master: ================================================================================
==> c1_master: Error executing action `install` on resource 'yum_package[splunk-6.0.6-228831]'
==> c1_master: ================================================================================
==> c1_master:
==> c1_master: Chef::Exceptions::Package
==> c1_master: -------------------------
==> c1_master: No version specified, and no candidate version available for splunk-6.0.6-228831
==> c1_master:
==> c1_master: Resource Declaration:
==> c1_master: ---------------------
==> c1_master: # In /var/chef/cache/cookbooks/cerner_splunk/recipes/_install.rb
==> c1_master:
==> c1_master:  56: package node['splunk']['package']['name'] do
==> c1_master:  57:   source splunk_file
==> c1_master:  58:   provider node['splunk']['package']['provider']
==> c1_master:  59:   only_if(&manifest_missing)
==> c1_master:  60:   if platform_family?('windows')
==> c1_master:  61:     # installing as the system user by default as Splunk has difficulties with being a limited user
==> c1_master:  62:     options %(AGREETOLICENSE=Yes SERVICESTARTTYPE=auto LAUNCHSPLUNK=0 INSTALLDIR="#{node['splunk']['home'].gsub('/', '\\')}")
==> c1_master:  63:   else
==> c1_master:  64:     notifies :run, 'execute[splunk-first-run]', :immediately
==> c1_master:  65:   end
==> c1_master:  66: end
==> c1_master:
==> c1_master: Compiled Resource:
==> c1_master: ------------------
==> c1_master: # Declared in /var/chef/cache/cookbooks/cerner_splunk/recipes/_install.rb:56:in `from_file'
==> c1_master:
==> c1_master: yum_package("splunk-6.0.6-228831") do
==> c1_master:   provider Chef::Provider::Package::Rpm
==> c1_master:   action :install
==> c1_master:   retries 0
==> c1_master:   retry_delay 2
==> c1_master:   default_guard_interpreter :default
==> c1_master:   package_name "splunk-6.0.6-228831"
==> c1_master:   source "/var/chef/cache/splunk-6.0.6-228831-linux-2.6-x86_64.rpm"
==> c1_master:   timeout 900
==> c1_master:   flush_cache {:before=>false, :after=>false}
==> c1_master:   cookbook_name "cerner_splunk"
==> c1_master:   recipe_name "_install"
==> c1_master:   only_if { #code block }
==> c1_master: end
```

### PR DESCRIPTION
**Pull request by david-crowder**
Fixes #2663 by using shell_out instead of popen4

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:+1:

@chef/client-core @chef/client-engineers

**Comment by danielsdeleo** [comment]
:+1:

**Comment by jonlives** [comment]
:+1:

**Comment by tyler-ball** [comment]
:+1:

**Comment by jaymzh** [comment]
:+1:

**Comment by tyler-ball** [comment]
Merged in https://github.com/chef/chef/issues/2833

**Pull request closed without merging**
