### PR TITLE
Fix apt_repository for latest os version 16.10

### PR DESCRIPTION
**Pull request by afiune**
### Description
Great description and solution of the problem made by @jeremiahsnapp in
the below issue!

Closes https://github.com/chef/chef/issues/5831

I have validated this works fine for the following os:
* Ubuntu 14.04
* Ubuntu 16.04
* Ubuntu 16.10 (latest)
* Debian-6.0.10
* Debian-8.7 (latest)

Signed-off-by: Salim Afiune <afiune@chef.io>

### Issues Resolved

* COOL-685
* https://github.com/chef/chef/issues/5831

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by tas50** [comment]
@afiune Any idea how this works on Debian?

**Comment by thommay** [comment]
Nice fix, Salim. It needs chefstyle fixes, and it would be good to confirm on Debian 6 and Debian 8, at least.

**Comment by afiune** [comment]
Thanks @tas50 @thommay ... Chefstyle has been fix, I'll push it again as soon as I confirm functionality in Debian.

**Comment by afiune** [comment]
@tas50 @thommay Done! Test should pass this time... Take it away!

**Pull request merged**
