### PR TITLE
Fix dupe stdout_logger

### LINKED ISSUE #7184: Duplicate log lines created when redirecting STDOUT
## Description
An additional stdout_logger is getting created when redirecting STDOUT.

It looks like it's only happening when STDOUT is not a tty and is likely related to the refactoring in #5851 #6035 and #6752.

## Chef Version
chef-client 13.8.11
Not present in 12.21.26

## Platform Version
Centos 7.4

## Replication Case
relevant client.rb settings
```
# client.rb

log_level :info
log_location STDOUT
```
run `/opt/chef/embedded/bin/chef-client -c /etc/chef/client.rb`
and compare to the output from `/opt/chef/embedded/bin/chef-client -c /etc/chef/client.rb | head -30`

## Client Output
Print statement debugging:
```
diff --git a/lib/chef/application.rb b/lib/chef/application.rb
index b20766c..b94f398 100644
--- a/lib/chef/application.rb
+++ b/lib/chef/application.rb
@@ -151,9 +151,16 @@ def set_specific_recipes
     def configure_logging
       configure_log_location
       Chef::Log.init(MonoLogger.new(Chef::Config[:log_location]))
+      puts "NAOMI: Chef::Config[:log_location].is_a?(IO) is #{Chef::Config[:log_location].is_a?(IO)}"
+      puts "NAOMI: Chef::Config[:log_location].tty? is #{Chef::Config[:log_location].tty?}"
+      puts "NAOMI: !( Chef::Config[:log_location].is_a?(IO) && Chef::Config[:log_location].tty? ) is #{!( Chef::Config[:log_location].is_a?(IO) && Chef::Config[:log_location].tty?
+      puts "NAOMI: !Chef::Config[:daemonize] is #{!Chef::Config[:daemonize]}"
+      puts "NAOMI: want_additional_logger is #{want_additional_logger?}"
+      puts "NAOMI: Chef::Log.loggers before configure stdout logger looks like #{Chef::Log.loggers}"
       if want_additional_logger?
         configure_stdout_logger
       end
+      puts "NAOMI: Chef::Log.loggers after configure stdout logger looks like #{Chef::Log.loggers}"
       Chef::Log.level = resolve_log_level
     rescue StandardError => error
       Chef::Log.fatal("Failed to open or create log file at #{Chef::Config[:log_location]}: #{error.class} (#{error.message})")
```
if I run `/opt/chef/embedded/bin/chef-client -c /etc/chef/client.rb` without redirecting STDOUT the logs look fine:
```
[2018-04-24T11:27:09-07:00] INFO: Loading Chef event handlers
NAOMI: Chef::Config[:log_location].is_a?(IO) is true
NAOMI: Chef::Config[:log_location].tty? is true
NAOMI: !( Chef::Config[:log_location].is_a?(IO) && Chef::Config[:log_location].tty? ) is false
NAOMI: !Chef::Config[:daemonize] is true
NAOMI: want_additional_logger is false
NAOMI: Chef::Log.loggers before configure stdout logger looks like [#<MonoLogger:0x0000000002b9a9e0 @progname=nil, @level=2, @default_formatter=#<Logger::Formatter:0x0000000002b9a9b8 @datetime_format=nil>, @formatter=#<Mixlib::Log::Formatter:0x0000000002b9a670 @datetime_format=nil>, @logdev=#<MonoLogger::LocklessLogDevice:0x0000000002b9a990 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>>>]
NAOMI: Chef::Log.loggers after configure stdout logger looks like [#<MonoLogger:0x0000000002b9a9e0 @progname=nil, @level=2, @default_formatter=#<Logger::Formatter:0x0000000002b9a9b8 @datetime_format=nil>, @formatter=#<Mixlib::Log::Formatter:0x0000000002b9a670 @datetime_format=nil>, @logdev=#<MonoLogger::LocklessLogDevice:0x0000000002b9a990 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>>>]
[2018-04-24T11:27:09-07:00] INFO: Forking chef instance to converge...
[2018-04-24T11:27:09-07:00] INFO: Chef event run_start fired
[2018-04-24T11:27:09-07:00] INFO: *** Chef 13.8.11 ***
[2018-04-24T11:27:09-07:00] INFO: Platform: x86_64-linux
[2018-04-24T11:27:09-07:00] INFO: Chef-client pid: 2190917
```
but if I redirect STDOUT by running `/opt/chef/embedded/bin/chef-client -c /etc/chef/client.rb | head -30 ` the logs duplicate:
```
[2018-04-24T11:31:59-07:00] INFO: Loading Chef event handlers
NAOMI: Chef::Config[:log_location].is_a?(IO) is true
NAOMI: Chef::Config[:log_location].tty? is false
NAOMI: !( Chef::Config[:log_location].is_a?(IO) && Chef::Config[:log_location].tty? ) is true
NAOMI: !Chef::Config[:daemonize] is true
NAOMI: want_additional_logger is true
NAOMI: Chef::Log.loggers before configure stdout logger looks like [#<MonoLogger:0x00000000029514e0 @progname=nil, @level=2, @default_formatter=#<Logger::Formatter:0x00000000029514b8 @datetime_format=nil>, @formatter=#<Mixlib::Log::Formatter:0x00000000029510a8 @datetime_format=nil>, @logdev=#<MonoLogger::LocklessLogDevice:0x0000000002951490 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>>>]
NAOMI: Chef::Log.loggers after configure stdout logger looks like [#<MonoLogger:0x00000000029514e0 @progname=nil, @level=2, @default_formatter=#<Logger::Formatter:0x00000000029514b8 @datetime_format=nil>, @formatter=#<Mixlib::Log::Formatter:0x00000000029510a8 @datetime_format=nil>, @logdev=#<MonoLogger::LocklessLogDevice:0x0000000002951490 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>>>, #<MonoLogger:0x0000000002950a90 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x0000000002950a68 @datetime_format=nil>, @formatter=#<Mixlib::Log::Formatter:0x00000000029510a8 @datetime_format=nil>, @logdev=#<MonoLogger::LocklessLogDevice:0x0000000002950a40 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>>>]
[2018-04-24T11:31:59-07:00] INFO: Forking chef instance to converge...
[2018-04-24T11:31:59-07:00] INFO: Forking chef instance to converge...
[2018-04-24T11:31:59-07:00] INFO: Chef event run_start fired
[2018-04-24T11:31:59-07:00] INFO: *** Chef 13.8.11 ***
[2018-04-24T11:31:59-07:00] INFO: *** Chef 13.8.11 ***
[2018-04-24T11:31:59-07:00] INFO: Platform: x86_64-linux
[2018-04-24T11:31:59-07:00] INFO: Platform: x86_64-linux
[2018-04-24T11:31:59-07:00] INFO: Chef-client pid: 2203775
[2018-04-24T11:31:59-07:00] INFO: Chef-client pid: 2203775
[2018-04-24T11:31:59-07:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
[2018-04-24T11:31:59-07:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
```

### PR DESCRIPTION
**Pull request by nsdavidson**
I _think_ this resolves issue #7184

Basically reverting back to the previous logic of
`want_additional_logger?`. It was mentioned in the issue comments that
the comparison against `STDOUT` wasn't working, but it seems to work for
me currently on Centos7.

Signed-off-by: Nolan Davidson <ndavidson@chef.io>

### Description

Prevents duplicate stdout_loggers from being created when STDOUT is redirected.
```
# client.rb
#
log_level :info
log_location STDOUT
```
```
 chef-client -z -c /tmp/client.rb | head -100
[2018-06-28T15:50:22+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /src/chef.
[2018-06-28T15:50:22+00:00] INFO: Started chef-zero at chefzero://localhost:1 with repository at /src/chef
  One version per cookbook

Starting Chef Client, version 14.1.24
[2018-06-28T15:50:22+00:00] INFO: *** Chef 14.1.24 ***
[2018-06-28T15:50:22+00:00] INFO: Platform: x86_64-linux
[2018-06-28T15:50:22+00:00] INFO: Chef-client pid: 18037
[2018-06-28T15:50:22+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
[2018-06-28T15:50:33+00:00] INFO: Run List is []
[2018-06-28T15:50:33+00:00] INFO: Run List expands to []
[2018-06-28T15:50:33+00:00] INFO: Starting Chef Run for localhost
[2018-06-28T15:50:33+00:00] INFO: Running start handlers
[2018-06-28T15:50:33+00:00] INFO: Start handlers complete.
resolving cookbooks for run list: []
[2018-06-28T15:50:33+00:00] INFO: Loading cookbooks []
Synchronizing Cookbooks:
Installing Cookbook Gems:
Compiling Cookbooks...
[2018-06-28T15:50:33+00:00] WARN: Node localhost has an empty run list.
Converging 0 resources
[2018-06-28T15:50:33+00:00] INFO: Chef Run complete in 0.04621001 seconds

Running handlers:
[2018-06-28T15:50:33+00:00] INFO: Running report handlers
Running handlers complete
[2018-06-28T15:50:33+00:00] INFO: Report handlers complete
Chef Client finished, 0/0 resources updated in 11 seconds
```

### Issues Resolved

#7184 

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by btm** [comment]
Yeah this looks like a revert of https://github.com/chef/chef/pull/6752 specifically. It looks like that was added in 13.7.14 and #7184 was against 13.8.11.

So the question what's our answer for @lamont-granquist's comment in #7184 here https://github.com/chef/chef/issues/7184#issuecomment-384714476?

**Comment by lamont-granquist** [comment]
yeah i'd vastly prefer to move to the "is the log_location the default value?" check rather than being lazy and just reverting back to code which certainly was busted before (which makes me strongly suspect that this PR just winds up pushing around bugs backwards and forwards...)

**Comment by jaymzh** [comment]
I'm with @lamont-granquist - we have a workaround for now, and while we need to fix this, we don't want to re-break the previous case. :)

**Comment by nsdavidson** [comment]
Updated to check `log_location` default value. It's a little nasty, but I couldn't find a clean way to ask Chef::Config if a value was default or not. Happy to go another route if there's a better path, but this approach seems to work.

**Comment by lamont-granquist** [comment]
That does look like the right approach, although I could have sworn the idea behind having the defaults stored separate from the values was that you could inspect them.

Maybe all we did was have the reset function to set everything back to the defaults though and never got that far...

**Comment by lamont-granquist** [comment]
i added an `#is_default?` API to mixlib-config and pulled it in here.

there's some unrelated chefstyle offenses busted on master, but i think this is green

note that i haven't really tested this yet...  it would be useful to have someone manually verify

**Comment by nsdavidson** [comment]
Verified locally on CentOS 7.4 and it looks good.

**Pull request merged**
