### PR TITLE
Monkeypatch Win32::Registry methods delete_key, delete_value

### PR DESCRIPTION
**Pull request by adamedx**
Re-creation of #3870 for @mcquin because I couldn't force AppVeyor to re-run.
- Adds monkeypatches for Win32::Registry#delete_key and Win32::Registry#delete_value. 
- Rewrites Chef::Win32::Registry#delete_key to use Win32::Registry#delete_key.

(Note: Once this is merged, I will move the [Win32::Registry#write monkeypatch](https://github.com/chef/chef/blob/master/lib/chef/win32/unicode.rb#L62-L87) into `lib/chef/monkey_patches/win32/registry.rb` for consistency. Doing so here is outside the scope of this PR.)

### CODE REVIEW

**Comment by jaym** [comment]
not sure why it says appveyor is pending, it completed successfully

**Comment by jaym** [comment]
@adamedx i've added you as an admin to appveyor

**Comment by adamedx** [comment]
Well, AppVeyor still says its running (it's been hours), but the output shows that it passed. So this should be safe to merge @mcquin.

**Comment by mcquin** [comment]
I need one more review and +1 from @chef/client-windows before I can merge.

**Comment by smurawski** [comment]
:+1: :shipit:

**Comment by mwrock** [comment]
:+1:

**Comment by ksubrama** [comment]
:+1:

**Pull request merged**
