### PR TITLE
release 12.8.0 changelog

### PR DESCRIPTION
**Pull request by mwrock**

### CODE REVIEW

**Comment by coderanger** [comment]
Can we make whatever script generates this force initial caps on each line? It makes my ocdaesthetics glads cranky ;-)

**Comment by coderanger** [comment]
(not actually a :-1: just grumble grumble getoffmylawn :) )

**Comment by jkeiser** [comment]
@coderanger it just uses the titles of the bugs, so if you click on each bug and capitalize its title (or rename), next time we generate it will use the new titles :)

**Comment by jkeiser** [comment]
:+1:

**Pull request merged**
