### PR TITLE
another chefstyle catchup + pull master

### PR DESCRIPTION
**Pull request by lamont-granquist**
bunch of merges over the weekend need re-fixing again.

seems like pointing at master of chefstyle is probably a good idea to
start making people fix their code before merging.

### CODE REVIEW

**Comment by thommay** [comment]
:+1:

**Comment by lamont-granquist** [comment]
@chef/client-core this autofixes a bunch of merges that were made since friday.

also pulls master of chefstyle to start fixing these up-front rather than after-the-fact.

**Comment by danielsdeleo** [comment]
Looks like the kitchen tests currently fail with git-sourced gems in your Gemfile?

**Comment by lamont-granquist** [comment]
yeah i don't understand how though, and the kitchen-appbunndle-updater version we're running is ancient...   see #4426

**Comment by danielsdeleo** [comment]
AFAICT it's because there is no git on the box: https://travis-ci.org/chef/chef/jobs/103156314#L368

**Comment by lamont-granquist** [comment]
fixed

**Pull request merged**
