### PR TITLE
Pin bundler to 1.9.2 in appveyor.yml

### PR DESCRIPTION
**Pull request by jdmundrawala**
I broke universal gems in https://github.com/bundler/bundler/pull/3553

We can unpin once a fix is released

### CODE REVIEW

**Comment by tyler-ball** [comment]
:+1:

They merged your issue - any ETA on a release?

**Comment by jdmundrawala** [comment]
The issue is still open, that's just the merged PR that broke it

**Comment by lamont-granquist** [comment]
:+1:

**Comment by lamont-granquist** [comment]
merging because this is blocking/annoying me...

**Pull request merged**
