### PR TITLE
Support for Zypper multiple package install

### PR DESCRIPTION
**Pull request by gsaslis**
See #3570 for details

### CODE REVIEW

**Comment by lamont-granquist** [comment]
I'd prefer to not see another package provider written in this 'style'.   In #4106 I'm working on moving more of the logic into the base provider, cleanly, and not having the mess with arrays-vs-not-arrays polluting every single package provider.  I'll try to get that one into shape to be reviewed.

**Comment by gsaslis** [comment]
ok, not sure what you have in mind exactly, but it would definitely make sense to treat this type of feature on the `package` provider level, rather than an apt / yum specific feature. 

In fact, given the fact that the multi-package feature was only very recently introduced, I assumed this was already the case and that the common interface would be the array of package names (and versions) passed in, and it would then be the job of each of the providers to make sure it is correctly handled. 
In fact, this is how it is handled in apt & yum (if I'm not mistaken), so I just followed the existing pattern.  

In any case, if you see this as something that's not high in your priority list, I believe this PR would very well do for the meantime.. 

P.S: Thanks a lot for reviewing!!  ; )

**Comment by lamont-granquist** [comment]
I'm actually going to start working on making this easier.

Got distracted today because I'm working on `chocolatey_package` and I need to be able to easily do windows builds and was fixing my tooling.

**Comment by lamont-granquist** [comment]
accepted minor for now, it'll get closed when the other PR is merged.

**Pull request closed without merging**
