### PR TITLE
fix AIX package installs using a 'source' attribute

### LINKED ISSUE #3108: Installing AIX packages from source does not work
Executing the following resource does not work on Chef 12.1.1
```ruby
package 'foo' do
  source '/tmp/cfengine-community-3.6.4.0-aix_6.x.bff'
end
```
Chef client gives back
```
  * package[foo] action install (up to date)
```
```
-bash-4.3$ lslpp -L | grep cfengine
-bash-4.3$
```

Investigating if this worked on Chef 12.0.3

### PR DESCRIPTION
**Pull request by juliandunn**
Raise exception if a BFF provided by 'source' doesn't actually provide that package

Fixes #3108

### CODE REVIEW

**Comment by jdmundrawala** [comment]
:+1:

**Comment by juliandunn** [comment]
I still need to fix0r the tests.

**Comment by jdmundrawala** [comment]
I take back my :+1: until the tests pass

**Comment by juliandunn** [comment]
@jdmundrawala good to go now? and/or paging @lamont-granquist who is AIX maintainer

**Comment by lamont-granquist** [comment]
:+1:

**Pull request merged**
