### PR TITLE
Updated version of #2125 to fix CHEF-2911

### PR DESCRIPTION
**Pull request by jonlives**
This is a squashed and rebased version of #2835.

### CODE REVIEW

**Comment by jonlives** [comment]
@chef/client-core this is the squashed and re-based version of the approved #2835 - unfortunately I messed up my fork while doing that so the commits from #2835 aren't visible any more - I've verified that this PR contains exactly the same changes, but out of an abundance of caution I'd appreciate this being given a quick once over before I merge it.

**Comment by tyler-ball** [comment]
:+1:

**Comment by danielsdeleo** [comment]
:shipit:

**Comment by lamont-granquist** [comment]
:+1:

**Comment by jonlives** [comment]
That's quorum from EL maintainers, and 2 core maintainers too so IMMA MUUUURGIN MAH LAZAR!

**Comment by tyler-ball** [comment]
@jonlives I'm :+1:ing your comment

**Pull request merged**
