### PR TITLE
Need to run apt update on EC2 ubuntu images for acceptance tests

### PR DESCRIPTION
**Pull request by tyler-ball**
\cc @mwrock @chef/client-maintainers 

We need to run apt becuase thats what the [cookbook also does](https://github.com/chef-cookbooks/git/blob/master/.kitchen.yml#L18-L21)

### CODE REVIEW

**Comment by mwrock** [comment]
:+1:

**Comment by chefsalim** [comment]
:+1:

**Comment by lamont-granquist** [comment]
it'd be preferable to run the apt_update resource early in the run_list and exercise that going forwards

**Comment by tyler-ball** [comment]
@lamont-granquist doesn't the default recipe do that? https://github.com/chef-cookbooks/apt/blob/master/recipes/default.rb#L62

**Comment by lamont-granquist** [comment]
Nope, that's an execute resource running 'apt-get update'.

I mean use the built-in resource to do this:  https://github.com/chef/chef/pull/4422/files

**Comment by mwrock** [comment]
To (hopefully) get the pipeline green, I'm gonna merge as is. Based on what I can tell here, we'd want to either add the `apt_update` resource to the git cookbook or add a recipe in acceptance that runs the resource prior to the others.

**Pull request merged**
