### PR TITLE
appveyor for 12-stable

### PR DESCRIPTION
**Pull request by btm**
testing to see if it passes, cherry-pick of #2655

### CODE REVIEW

**Comment by nathenharvey** [comment]
@btm the appveyor build is failing.  Can you resolve that before we merge, please?

**Comment by lamont-granquist** [comment]
I'd suggest that the next release of 12 be 12.1.0 and that we abandon 12.0.x, which would make all this work go away.

**Comment by btm** [comment]
@lamont-granquist the only work remaining here is to disable the windows memory leak tests. Everyone who has touched them in the past doesn't believe they're providing value because the values were all set arbitrarily.

**Comment by lamont-granquist** [comment]
:+1:

**Comment by someara** [comment]
Request For Eyeballs @opscode/client-core @opscode/client-engineers

**Comment by jdmundrawala** [comment]
:shipit:

**Comment by btm** [comment]
@jonlives @jaymzh @tyler-ball @mcquin @danielsdeleo

**Comment by lamont-granquist** [comment]
are these all cherry-picks so that when we merge master into 12-stable we won't have excessive merge conflicts?

**Comment by jdmundrawala** [comment]
@lamont-granquist I honestly think that is a lost cause. Why are we merging master into 12-stable? I thought the plan was to abandon 12-stable and just use master.

**Comment by lamont-granquist** [comment]
That is the ultimate goal.  However, until we get there to doing more continuous releases we have to have 12-stable at least to drop security fixes onto.  We cannot just release master when we hit a security fix.  We already had an incident where we did that and we broke everyone and they couldn't use the security fix and we had to scramble and release again.

Until we have actually done the engineering to release nightlies we are still on the old process and we must have a 12-stable branch for security releases.

**Comment by jaymzh** [comment]
I don't have a lot of context on anything windows, but I'm all about more testing. So uh, :+1:  I guess? :)

**Comment by lamont-granquist** [comment]
I just closed the 12.0.4 milestone, so the next thing we do with 12-stable should be to merge master into 12-stable in prep for the 12.1.0 release.

**Comment by jdmundrawala** [comment]
@lamont-granquist is there anything in 12-stable that isn't already in master?

**Comment by lamont-granquist** [comment]
I keep yelling at people to never effing do that and that we always merge into master first to avoid this question ever being a problem.  Having said that, I don't think so.  We were only doing the stupid thing for some merges to chef-11.

**Comment by mcquin** [comment]
LGTM

**Comment by tyler-ball** [comment]
:+1:

**Comment by jonlives** [comment]
I'm in the same boat as @jaymzh with a yay more testing :+1: :p

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Pull request merged**
