### PR TITLE
Fix cookbook installation from supermarket on windows

### LINKED ISSUE #1753: knife cookbook site install fails on Windows in directories with spaces
The tar command cannot find the file and fails. The path parameter given to the command is not quoted.

    username@hostname /d/Box Sync/Projects/chef/chef-repo {chef-vendor-windows}                                      
    $ knife cookbook site install windows                                                                                 
    Installing windows to d:/Box Sync/Projects/chef/chef-repo/cookbooks                                                   
    Checking out the master branch.                                                                                       
    Pristine copy branch (chef-vendor-windows) exists, switching to it.                                                   
    Downloading windows from the cookbooks site at version 1.34.0 to d:/Box Sync/Projects/chef/chef-repo/cookbooks/windows
    .tar.gz                                                                                                               
    Cookbook saved: d:/Box Sync/Projects/chef/chef-repo/cookbooks/windows.tar.gz                                          
    Removing pre-existing version.                                                                                        
    Uncompressing windows version 1.34.0.                                                                                 
    ERROR: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'                      
    ---- Begin output of tar zxvf /d/Box Sync/Projects/chef/chef-repo/cookbooks/windows.tar.gz ----                       
    STDOUT:                                                                                                               
    STDERR: tar (child): /d/Box: Cannot open: No such file or directory                                                   
    tar (child): Error is not recoverable: exiting now                                                                    
    tar: Child returned status 2                                                                                          
    tar: Sync/Projects/chef/chef-repo/cookbooks/windows.tar.gz: Not found in archive                                      
    tar: Exiting with failure status due to previous errors                                                               
    ---- End output of tar zxvf /d/Box Sync/Projects/chef/chef-repo/cookbooks/windows.tar.gz ----                         
    Ran tar zxvf /d/Box Sync/Projects/chef/chef-repo/cookbooks/windows.tar.gz returned 2                                  

I found the same issue detailed in this issue:
https://tickets.opscode.com/browse/CHEF-4209

### PR DESCRIPTION
**Pull request by MichaelPereira**
- Fixes https://tickets.opscode.com/browse/CHEF-3394 by adding the `--force-local` option to tar
- Might fix #1753 with the added double quotes

Successfully ran the unit tests in spec/unit/knife/cookbook_site_install_spec.rb with the change.

Proof of the fix:
Proof of the fix

### CODE REVIEW

**Comment by thommay** [comment]
:+1: @chef/client-windows

**Comment by lamont-granquist** [comment]
:+1:

**Comment by smurawski** [comment]
:+1:

**Comment by danielsdeleo** [comment]
I think this will break BSD tar (Mac and probably *BSD):

```
tar zxvf apt-2.4.0.tgz --force-local
tar: Option --force-local is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
```

**Comment by danielsdeleo** [comment]
Unless this only runs on windows or I'm missing something?

**Comment by MichaelPereira** [comment]
@danielsdeleo You're right, it doesn't run on Windows only. The commit needs to be refactored to add the `--force-local` parameter only for Windows. I will try to look around the code base to see how it's done.

**Comment by MichaelPereira** [comment]
I verified that 48f7688 works on Windows on my local machine:

```
PS U:\.chef\cookbooks> knife cookbook site install chocolatey
WARNING: No knife configuration file found
Installing chocolatey to U:/.chef/cookbooks
Checking out the master branch.
Creating pristine copy branch chef-vendor-chocolatey
Downloading chocolatey from the cookbooks site at version 0.4.0 to U:/.chef/cookbooks/chocolatey.tar.gz
Cookbook saved: U:/.chef/cookbooks/chocolatey.tar.gz
Removing pre-existing version.
Uncompressing chocolatey version 0.4.0.
removing downloaded tarball
1 files updated, committing changes
Creating tag cookbook-site-imported-chocolatey-0.4.0
Checking out the master branch.
Updating d514eec..170e3e2
Fast-forward
 chocolatey/CHANGELOG.md                    |  11 +++
 chocolatey/README.md                       |  79 +++++++++++++++++
 chocolatey/attributes/default.rb           |   4 +
 chocolatey/libraries/chocolatey_helpers.rb |  24 ++++++
 chocolatey/metadata.json                   |   1 +
 chocolatey/providers/default.rb            | 134 +++++++++++++++++++++++++++++
 chocolatey/recipes/default.rb              |  74 ++++++++++++++++
 chocolatey/resources/default.rb            |  14 +++
 8 files changed, 341 insertions(+)
 create mode 100644 chocolatey/CHANGELOG.md
 create mode 100644 chocolatey/README.md
 create mode 100644 chocolatey/attributes/default.rb
 create mode 100644 chocolatey/libraries/chocolatey_helpers.rb
 create mode 100644 chocolatey/metadata.json
 create mode 100644 chocolatey/providers/default.rb
 create mode 100644 chocolatey/recipes/default.rb
 create mode 100644 chocolatey/resources/default.rb
Cookbook chocolatey version 0.4.0 successfully installed
```

**Comment by danielsdeleo** [comment]
LGTM now. :+1:

**Comment by thommay** [comment]
thanks @danielsdeleo, good catch!

**Pull request closed without merging**
