### PR TITLE
Fix some errant bashisms

### LINKED ISSUE #3408: Knife Bootstrap Improperly Detecting Existence of Chef Installation
When bootstrapping a fresh Ubuntu 14.04 node with chef, the _exists_ function improperly returns true and the boostrap script believes there is a chef-client executable in place:

```
Connecting to 10.1.1.2
10.1.1.2 -----> Existing Chef installation detected
10.1.1.2 Starting first Chef Client run...
10.1.1.2 sh: 333: chef-client: not found
```

Initial attempts to replace the script with bashisms such as _if [[ ! -f ..._ all of which result in the bootstrap script either constantly believing that a chef client is available, or always downloading a new one. I haven't spent any time digging the history here past current open issues in GH, but i assume someone has already beaten their head against the wall with this.

### PR DESCRIPTION
**Pull request by thommay**
Fixes #3408

### CODE REVIEW

**Comment by thommay** [comment]
cc @lamont-granquist @mcquin

**Comment by thommay** [comment]
without changes:
```
knife bootstrap -x ubuntu --sudo -i ~/.ssh/us-west-1 -N ip-172-31-6-219.us-west-1.compute.internal ec2-52-8-184-63.us-west-1.compute.amazonaws.com
Creating new client for ip-172-31-6-219.us-west-1.compute.internal
Creating new node for ip-172-31-6-219.us-west-1.compute.internal
Connecting to ec2-52-8-184-63.us-west-1.compute.amazonaws.com
ec2-52-8-184-63.us-west-1.compute.amazonaws.com -----> Existing Chef installation detected
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Starting first Chef Client run...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com sh: 229: chef-client: not found
[1]    13634 exit 127   knife bootstrap -x ubuntu --sudo -i ~/.ssh/us-west-1
```

with changes:
```
10:40 ~/work/chef % knife bootstrap -x ubuntu --sudo -i ~/.ssh/us-west-1 -t lib/chef/knife/bootstrap/templates/chef-full.erb -N ip-172-31-6-219.us-west-1.compute.internal ec2-52-8-184-63.us-west-1.compute.amazonaws.com
Creating new client for ip-172-31-6-219.us-west-1.compute.internal
Creating new node for ip-172-31-6-219.us-west-1.compute.internal
Connecting to ec2-52-8-184-63.us-west-1.compute.amazonaws.com
ec2-52-8-184-63.us-west-1.compute.amazonaws.com -----> Installing Chef Omnibus (-v 12)
ec2-52-8-184-63.us-west-1.compute.amazonaws.com downloading https://www.opscode.com/chef/install.sh
ec2-52-8-184-63.us-west-1.compute.amazonaws.com   to file /tmp/install.sh.1482/install.sh
ec2-52-8-184-63.us-west-1.compute.amazonaws.com trying wget...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Downloading Chef 12 for ubuntu...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com downloading https://www.opscode.com/chef/metadata?v=12&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
ec2-52-8-184-63.us-west-1.compute.amazonaws.com   to file /tmp/install.sh.1486/metadata.txt
ec2-52-8-184-63.us-west-1.compute.amazonaws.com trying wget...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_12.4.0-1_amd64.deb
ec2-52-8-184-63.us-west-1.compute.amazonaws.com md5	630a8752be2cb45c69b7880adb2340f1
ec2-52-8-184-63.us-west-1.compute.amazonaws.com sha256	2d66c27884658f851d43cec850b4951b4d540492be521ae16f6941be80e8b1e6
ec2-52-8-184-63.us-west-1.compute.amazonaws.com downloaded metadata file looks valid...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_12.4.0-1_amd64.deb
ec2-52-8-184-63.us-west-1.compute.amazonaws.com   to file /tmp/install.sh.1486/chef_12.4.0-1_amd64.deb
ec2-52-8-184-63.us-west-1.compute.amazonaws.com trying wget...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Comparing checksum with sha256sum...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Installing Chef 12
ec2-52-8-184-63.us-west-1.compute.amazonaws.com installing with dpkg...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Selecting previously unselected package chef.
(Reading database ... 51120 files and directories currently installed.)
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Preparing to unpack .../chef_12.4.0-1_amd64.deb ...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Unpacking chef (12.4.0-1) ...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Setting up chef (12.4.0-1) ...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Thank you for installing Chef!
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Starting first Chef Client run...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Starting Chef Client, version 12.4.0
ec2-52-8-184-63.us-west-1.compute.amazonaws.com resolving cookbooks for run list: []
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Synchronizing Cookbooks:
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Compiling Cookbooks...
ec2-52-8-184-63.us-west-1.compute.amazonaws.com [2015-06-25T09:41:36+00:00] WARN: Node ip-172-31-6-219.us-west-1.compute.internal has an empty run list.
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Converging 0 resources
ec2-52-8-184-63.us-west-1.compute.amazonaws.com
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Running handlers:
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Running handlers complete
ec2-52-8-184-63.us-west-1.compute.amazonaws.com Chef Client finished, 0/0 resources updated in 3.716825236 seconds
```

**Comment by ranjib** [comment]
:+1:

**Comment by jdmundrawala** [comment]
LGTM

cc @juliandunn

**Comment by mcquin** [comment]
YES! =)

**Comment by ksubrama** [comment]
:+1:

**Comment by juliandunn** [comment]
Give me till the end of the day to bootstrap a fresh AIX LPAR and I will report back. I'm very sorry for the errant bashisms that crept into this release.

**Comment by juliandunn** [comment]
[We're good.](https://gist.github.com/juliandunn/fc7d701c099b90a4d9c6) Merge away :+1:

**Pull request merged**
