### PR TITLE
Update `dpkg` provider to remove `DPKG_INFO` regular expression and let `dpkg-dep` handle package name.

### LINKED ISSUE #2417: dpkg_package with + in filename causes reinstall when not necessary
I created a ruby file called ```devel.rb``` which has the following content
```
dpkg_package "libtinfo5" do
  version "5.9"
  source "libtinfo5_5.9+20140118-1ubuntu1_amd64.deb"
  action :install
end

dpkg_package "tmux" do
  source "tmux_1.8-5_amd64.deb"
  action :install
end
```
I have the two deb package in the same directory as ```devel.rb``` which I downloaded from ubuntu mirror site:

http://mirrors.kernel.org/ubuntu/pool/main/n/ncurses/libtinfo5_5.9+20140118-1ubuntu1_amd64.deb
http://mirrors.kernel.org/ubuntu/pool/main/t/tmux/tmux_1.8-5_amd64.deb

When I run: ```chef-apply devel.rb -W -l debug``` there is a version mismatch reported and it reports that the package will get installed unnecessarily.

I seem to have narrowed this down to the deb file having a + within the filename.
For libtinfo5 dpkg reports 5.9+20140118-1ubuntu1
For libtinfo5 chef report 5.9.
It seems like chef stops at the first + instead of stopping at the _amd64.deb.

If possible could this behavior be changed so the version mismatch stops occurring and reinstalling of an already installed package not not performed.

I need to do this because I have to configure machines that have no internet access so I'm creating a cookbook that will contain deb packages because it can't see the ubuntu mirror sites.

### PR DESCRIPTION
**Pull request by kwilczynski**
This is as per the "Debian Policy Manual, Chapter 5 - Control files and their fields", see:

  https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

Fixes #2417.

Signed-off-by: Krzysztof Wilczynski <krzysztof.wilczynski@linux.com>

### CODE REVIEW

**Comment by kwilczynski** [comment]
@lamont-granquist I need to move this to my own fork too.

**Comment by btm** [comment]
@kwilczynski are you still working on this?

**Comment by kwilczynski** [comment]
@btm I have the changes, but I don't have the time to work on the tests migration to Rspec 3 at the moment. Are you in a rush?

**Comment by btm** [comment]
@kwilczynski no rush. it's been a few weeks so I'm checking in. If you're not familiar with 'transpec' it can do a lot/most of the test migration for you.

**Comment by thommay** [comment]
Closing in favour of #3498

**Pull request closed without merging**
