### PR TITLE
Interpolate `%{path}` in verify command

### PR DESCRIPTION
**Pull request by margueritepd**
See chef/chef#3232

### CODE REVIEW

**Comment by coderanger** [comment]
Can you add a comment indicating why there are two? Maybe that would give us a mild chance of remembering to remove the old one for Chef 13.

**Comment by ranjib** [comment]
@coderanger RFC says the variable name should be `path`. current implementation uses `file` . Keeping file as it is will ensure nothing breaks downstream

**Comment by stevendanna** [comment]
@ranjib I believe @coderanger was asking for a comment in the code for people who come across it later.  I'm :+1: on having a code comment about why we have two.

**Comment by coderanger** [comment]
Yes, we can't remove `file` until Chef 13, but we should eventually revisit to clean this up.

**Comment by ranjib** [comment]
@margueritepd that helper method name should be something different, in itself its not a test. may be platform_specific_command ?
@coderanger i cant think of a way to throw deprecation warning for file usage, else it would have helped..
:+1:

**Comment by ranjib** [comment]
@stevendanna ah .. got it now

**Comment by coderanger** [comment]
```ruby
Chef::Log.deprecate('%{file} is deprecated in favor of %{path}') if @command.include?('%{file}')
```

or something like that.

**Comment by margueritepd** [comment]
@coderanger comment and deprecation warning added, tests updated :)

I didn't use `Chef::Log.deprecation` because that throws an error apparently.

**Comment by mcquin** [comment]
@margueritepd there is a [configuration option](https://github.com/chef/chef/blob/master/chef-config/lib/chef-config/config.rb#L518-L522) for treating [deprecation warnings as errors](https://github.com/chef/chef/blob/master/lib/chef/log.rb#L41). It's best to use `Ohai::Log.deprecation`.

**Comment by margueritepd** [comment]
@mcquin back to using `deprecation`!

**Comment by mcquin** [comment]
:+1:

**Pull request merged**
