### PR TITLE
Update http.rb

### PR DESCRIPTION
**Pull request by infa-btan**
Signed-off-by: infa-btan <btan@informatica.com>

## Description
Fetch refers to chef::http.streaming_request on line 182. This function sets the tempfile to

stream_to_tempfile(url, http_response, tempfile, &progress_block) # lib/chef/http.rb: line 226

On line 546 of lib/chef/http.rb stream_to_tempfile closes the file. This means that the fetch function attempts to close the file a second time, causing an IOError

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by phiggins** [comment]
Hi, could you provide some example code that demonstrates the failure?

**Comment by lamont-granquist** [comment]
Yeah that's in the common path of just about every remote_file http request and has been stable for years, so its more than a bit weird that nobody else has reported this.  A repro case would be useful to validate that its a real bug.

**Comment by infa-btan** [comment]
This is the case where I saw the bug

remote_file("apache 8.5.58 tarball") do
action [:create_if_missing]
default_guard_interpreter :default
source ["http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.58/bin/apache-tomcat-8.5.58.tar.gz"]
declared_type :remote_file
cookbook_name "test"
path "/root/.chef/local-mode-cache/cache/apache-tomcat-8.5.58.tar.gz"
remote_domain nil
emote_user nil
owner nil
group nil
mode nil
headers {}
verifications []
end
     
     System Info:
       ------------
       chef_version=15.4.45
      platform=centos
     platform_version=7.8.2003
     ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
      program_name=/usr/bin/chef-client
      executable=/opt/chef/bin/chef-client

Error appears as 

================================================================================[0m
Error executing action `create_if_missing` on resource 'remote_file[apache 8.5.58 tarball]'
================================================================================[0m

IOError
 -------
 closed stream

What's odd is that this issue only occurs intermittently when i run this, even though this kind of thing should be consistent

**Comment by lamont-granquist** [comment]
What is the stacktrace.out on that?

**Comment by lamont-granquist** [comment]
Also closing a tempfile twice isn't an error:

```
[1] pry(main)> file = Tempfile.new('foo')
=> #<File:/var/folders/vl/7__gnv9x5sg745ntrsh0yglm0000gn/T/foo20201105-28404-1fkx1cs>
[2] pry(main)> file.close
=> nil
[3] pry(main)> file.close
=> nil
```

This looks more like the http connection was aborted early.

**Comment by infa-btan** [comment]
My stacktrace doesn't go further than that and I can't repro the error. Must have been a transitive network issue then

**Pull request closed without merging**
