### PR TITLE
Optionally check for cookbook dependencies when using knife cookbook upload

### PR DESCRIPTION
**Pull request by jasonwbarnett**
## Description

Sometimes you just want to upload cookbooks without worrying about whether or not the dependencies exist on Chef Infra Server. The actual call to check if all cookbooks exist is somewhat expensive on servers with a lot of cookbooks so giving folks the ability to bypass that could be useful for scaling.

## Related Issue

N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by jasonwbarnett** [comment]
@tas50 @lamont-granquist I have no idea if the check was implemented because it's a hard requirement or just attempting to push errors further left so users aren't wondering why their chef runs can't resolve cookbooks.

**Comment by lamont-granquist** [comment]
it used to not care by default i think and then everyone had a really bad time.  i think i'm okay with a flag to turn it off.  kind of your funeral if you go out of your way to bypass smoke checking.

your unit tests are blowing up though.

**Comment by jasonwbarnett** [comment]
> it used to not care by default i think and then everyone had a really bad time. i think i'm okay with a flag to turn it off. kind of your funeral if you go out of your way to bypass smoke checking.
> 
> your unit tests are blowing up though.

Thanks, @lamont-granquist. I'll fix the unit tests.

**Comment by jasonwbarnett** [comment]
@lamont-granquist please re-review. Things should be all in order now.

**Comment by jasonwbarnett** [comment]
@lamont-granquist @tas50 do you need anything else from me on this PR?

**Review by lamont-granquist — APPROVED** [review]

**Comment by tas50** [comment]
@jasonwbarnett can you rebase this?

**Comment by jasonwbarnett** [comment]
@tas50 rebased.

**Pull request merged**
