### PR TITLE
Migrate omnibus-chef project/software definitions for chef in here.

### PR DESCRIPTION
**Pull request by ksubrama**
This is one part of a larger set of changes to migrate omnibus-chef into chef/chef, chef-dk and push-jobs.  The files copied into this project from omnibus-chef and omnibus-software will eventually be simply deleted or marked as deprecated in case someone needs to make a legacy build.

### CODE REVIEW

**Comment by schisamo** [comment]
Test build passed across full matrix: http://manhattan.ci.chef.co/job/chef-13-trigger-ad_hoc/8/downstreambuildview/

**Comment by tyler-ball** [comment]
@ksubrama Can you squash this down to 1 commit?  Is there a reason we want to copy over the whole commit history from omnibus-chef?  I would rather have a commit that is a pointer to the old history rather than copying it into here.

OTT, :+1: and awesome job

**Comment by ksubrama** [comment]
@tyler-ball @jaym @schisamo @danielsdeleo Y'all should vote on history vs. not :)

I'm ok with leaving a note in the README pointing to omnibus-chef.

**Comment by lamont-granquist** [comment]
I'm slightly in favor of porting over the history

**Comment by schisamo** [comment]
The consensus with the group so far has been keep the history (my personal vote also).

**Comment by danielsdeleo** [comment]
I'm strongly in favor of keeping the history. I find I use it more frequently for omnibus stuff than anything else, because fiddling with CFLAGS and the like seems to be more likely to have unanticipated effects than we see with other kinds of software we make.

**Comment by schisamo** [comment]
Should probably update the CHANGELOG and then I'm :+1:

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Pull request merged**
