### PR TITLE
Added ssh_key to git

### PR DESCRIPTION
**Pull request by BackSlasher**
Uses gem 'git-ssh-wrapper' to generate wrapper file
Original idea by benburkert

Based on #52, but modernized a bit.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
I'm very hesitant to have a dep on a v0.0.1 gem in core chef.  Burned way too many times by gems which should supposedly be more stable (net-ssh/net-ssh-multi/json/etc).

**Comment by BackSlasher** [comment]
Should I recreate the same behaviour using chef resources (e.g. file)? Or
is it better we use plain ruby?

**Comment by lamont-granquist** [comment]
file resources are fine.  we tore out the recipe dsl from providers, though, in order to remove method_missing issues.  you have to manually roll them, e.g.:

https://github.com/chef/chef/blob/master/lib/chef/provider/ifconfig/debian.rb#L63-L66

**Comment by BackSlasher** [comment]
I thought about this problem a bit, and I have several design issues:
* I have a problem with Windows, since I'll have to wrap the original `SSH_GIT` with another script
* I'm not happy about creating a temporary wrapper / key file every time `run_options` is called, like in the original PR. I'll think about it and see if I can come up with anything nice.  
If I do, I'll open another PR

**Pull request closed without merging**
