### PR TITLE
Add global list option in knife user list

### PR DESCRIPTION
**Pull request by snehaldwivedi**
## Description

 Added a option to list global users `--global` in `knife user list` command

## Related Issue

https://github.com/chef/chef/issues/3517
https://github.com/chef/chef/issues/3513

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by snehaldwivedi** [comment]
@stevendanna  Just wanted to confirm do we need `--with-uri` option and `--global` option to be work together like
`knife user list --global --with-uri` ?

**Comment by stevendanna** [comment]
I think we should make `--with-uri` work in both cases as that flag currently works with the org-specific endpoint.

While for reasons of history, the `/users/` endpoint and the `/organizations/ORGNAME/users` endpoint are unfortunately different:

```
{
  "pivotal": "https://127.0.0.1/users/pivotal",
  "testuser": "https://127.0.0.1/users/testuser"
}
root@api:~# knife raw /organizations/testorg/users -c /etc/opscode/pivotal.rb 
[
  {
    "user": {
      "username": "testuser"
    }
  }
]
```

There is code in users_v1.rb to transform the org-specific response into the right format.  That code isn't perfect as it constructs the URIs client-side which is a bit dubious, but I don't see a good reason to break that now.

**Comment by snehaldwivedi** [comment]
@tas50 Can you please have a look into the PR for merge or if any more changes required form my side?

**Comment by snehaldwivedi** [comment]
@lamont-granquist Most of the part of card #3517 [](https://github.com/chef/chef/issues/3517) was already covered in PR [#10187](https://github.com/chef/chef/pull/10187), this PR covers one of the remeaning section [#3513](https://github.com/chef/chef/issues/3513).

Please have a look at it.

**Comment by marcparadise** [comment]
This also needs updating so that the PR contains only the changes, and not the original commits around knife opc integration.

**Comment by marcparadise** [comment]
Just one final question here - why are we bypassing the ruby API (Chef::User) in favor of directly accessing the REST endpoints?

**Comment by lamont-granquist** [comment]
Yeah, so `Chef::UserV1.list` should probably grow a flag like `Chef::UserV1.list(global: true)` if possible.

**Comment by snehaldwivedi** [comment]
@tas50 can you please confirm regarding https://github.com/chef/chef/issues/3513#issuecomment-832973692, if we are going to keep this functionality so I will continue working on review comments otherwise we can close PR and issue?

**Comment by snehaldwivedi** [comment]
@tas50 can you please confirm regarding https://github.com/chef/chef/issues/3513#issuecomment-832973692, if we are going to keep this functionality so I will complete review comments to if not we can close PR and issue?

**Pull request closed without merging**
