### PR TITLE
Add ksubrama to core chef maintainers list.

### PR DESCRIPTION
**Pull request by ksubrama**
/cc @smurawski @jdmundrawala @btm

### CODE REVIEW

**Comment by jdmundrawala** [comment]
:+1: I need more reviewers

**Comment by jdmundrawala** [comment]
Except I think you need to add yourself to the Windows maintainers as well, and somewhere in the people section

**Comment by jonlives** [comment]
:+1:

**Comment by btm** [comment]
@ksubrama updated the commit to add himself to the Windows maintainers instead of core due to my pleas for more Windows maintainers. Thanks dude. The PR title is out of date with the commit.

:+1: 

@jdmundrawala and I make an absolute majority for Windows, so you're in there. :)

You do need to add a people entry to the toml file though.

**Comment by smurawski** [comment]
:+1:  And I pushed a commit to add him to the people section.

**Comment by btm** [comment]
Look at that, a 100% approval rating from Windows maintainers!

**Comment by btm** [comment]
rebased and pushed to master as  6ce6c9543a2c6db4bc1aeecd8c561349496e1c4e and  a143d3099cfc19e666147b00387966e0698faf04.

Welcome @ksubrama. https://github.com/chef/chef/pulls?q=is%3Aopen+is%3Apr+label%3AWindows awaits you.

**Comment by btm** [comment]
@ksubrama welcome to @chef/client-windows too.

**Pull request closed without merging**
