### PR TITLE
add global and per-resource toggles for resource cloning behavior

### PR DESCRIPTION
**Pull request by lamont-granquist**
let us turn on and off resource cloning

### CODE REVIEW

**Comment by lamont-granquist** [comment]
still need to think through the behavior of notifications and should probably add a warning to notifications when it finds more than one resource and be a bit more verbose about which one gets picked.

also need to add a couple more tests

**Comment by coderanger** [comment]
I don't think offering a global option is helpful. Cookbook code will be written expecting one behavior or the other and changing it in a way the cookbook author can't control seems bad :-/

**Comment by lamont-granquist** [comment]
Lets you toggle it though and see what breaks in order to fix it (I'll certainly run with that setting and see what explodes).

**Comment by coderanger** [comment]
The problem is the person toggling it is very rarely the person that could or will fix things. If, right before Chef 13, we wanted to have some kind of "send me to the future to see what happens" feature flag I could get more behind that but I don't think this has more value than the existing deprecation warnings and the ability to make deprecation warnings into errors.

**Comment by lamont-granquist** [comment]
So I sorta view the Chef::Config option here as exactly the 'send me to the future' option...  I'll set it on my runs, I can set it to run it through internal CI acceptance testing, etc.  Even if its literally just an option for me to test with, i kinda want that option for me...

**Comment by lamont-granquist** [comment]
apparently @thommay just told me i volunteered to write another RFC...  *sigh*...   to the thursday meeting then....

**Comment by thommay** [comment]
In a lightning change of mind, let's just land this so we can use it for testing. Let's put some BIG FUCKING WARNINGS on this toggle if we document it.

**Comment by tas50** [comment]
We really need a way to turn cloning off so we can perform some extensive testing across the cookbook ecosystem including private customer cookbooks. This is a pretty big change and I'm afraid we're going to push it out with good intentions, but cause a huge amount of customer pain by accident. We don't need to document the flag for general usage. We just need to enable the ability to turn off cloning so we can test community cookbooks and customer support teams can test private cookbooks.

**Comment by lamont-granquist** [comment]
let me look through it again before mashing merge...

**Comment by lamont-granquist** [comment]
simplified PR, added scarier banner, we can also add a deprecation warning or remove the toggle entirely in Chef 13.

**Pull request merged**
