### PR TITLE
fix rspecs-ctrl-c

### LINKED ISSUE #2520: Chef's rspec tests not easily stopable
When running Chef's rspec tests via either:

    rake spec

or 

    rspec

The test run can become very hard to kill at the terminal.  Sending an interrupt (^c) simply causes the currently running test to fail and then proceeds to the next test.  Suspending the job (^z) and sending a SIGKILL to the rspec process works, but feels pretty ugly.

### PR DESCRIPTION
**Pull request by lamont-granquist**
we can't fork off tinyserver without a lot of work in the test
codebase, so instead save a copy of the old rspec signal handler and then
after tinyserver has started (and we're sure that rack has scribbled
over the signal handler), restore the rspec signal handler.

there's an obvious race if someone hits ctrl-c after tinyserver has
scribbled over the sigint handler but before we restore it, but this is
99.9% better of a solution than nothing.

closes #2520

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core review plz

**Comment by stevendanna** [comment]
omg yes

**Comment by jkeiser** [comment]
:+1:

**Comment by mcquin** [comment]
needs spec

**Comment by thommay** [comment]
:rocket: :clap:

**Pull request merged**
