### PR TITLE
Add ruby 2.1

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by jaym** [comment]
this will take a while to run, we should add more capacity for appveyor

**Comment by ksubrama** [comment]
/cc @chef/client-windows, @jkeiser (for wanting ruby 2.2).

I'll merge when we have enough concurrent instances to not hurt everyone else.

**Comment by jaym** [comment]
Let's rebase this to see how far it gets. Also, you can drop 2.2 for now as we're not shipping it with anything

**Comment by jaym** [comment]
Moving this along :+1: 
We'll do 2.1x64 if we ever decide to ship it, otherwise just jump to 2.2

**Pull request merged**
