### PR TITLE
Add initial roadmap per RFC030

### PR DESCRIPTION
**Pull request by btm**
https://github.com/chef/chef-rfc/blob/master/rfc030-maintenance-policy.md#roadmap

@chef/maintainers

### CODE REVIEW

**Comment by smurawski** [comment]
:+1:

**Comment by jonlives** [comment]
:+1:

**Comment by danielsdeleo** [comment]
:+1:

**Comment by danielsdeleo** [comment]
Though I guess as an LT you don't actually need any +1s?

**Comment by btm** [comment]
I was pausing for general feedback rather than explicit merge approval. :)

**Comment by btm** [comment]
rebased as 0a089f77adcf988fb43858ae0c446c31ab4727e5

**Pull request closed without merging**
