### PR TITLE
bump bunder + rubygems

### PR DESCRIPTION
**Pull request by lamont-granquist**
these versions pass in manhattan

### CODE REVIEW

**Comment by lamont-granquist** [comment]
i've got a related PR to allow them to float in chef/omnibus-software#576, but its kinda blocked on chef/omnibus#619

**Comment by lamont-granquist** [comment]
@chef/client-core need a :+1:

**Comment by jaym** [comment]
:+1: I would add a comment in the commit about why making this change is ok now

**Comment by ksubrama** [comment]
:+1:

I'm feeling quite happy I deliberately pinned bundler in chef-fips now :)
Just FYI - bundler 1.11+ breaks FIPS mode on windows for asinine reasons.  It's fine on the chef pipeline.

**Comment by lamont-granquist** [comment]
lolz

**Comment by lamont-granquist** [comment]
travis appears to be destroyed, i'm pretty sure this won't break anything...

caches are populated...

**Pull request merged**
