### PR TITLE
propose myself as a lieutenant

### PR DESCRIPTION
**Pull request by thommay**

### CODE REVIEW

**Comment by nathenharvey** [comment]
@sethvargo @btm @martinisoft here's another...

**Comment by sethvargo** [comment]
:+1:

**Comment by martinisoft** [comment]
:+1:

**Comment by btm** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1: but @adamhjk is the decider

**Comment by adamhjk** [comment]
Lets do it.

**Pull request merged**
