### PR TITLE
WIP: read roles from ruby files

### PR DESCRIPTION
**Pull request by thommay**
:construction: Would appreciate a review of the approach :construction:
Essentially, we can read ruby roles (and environments) from the filesystem, but they must map in to json objects in Chef Zero.

### CODE REVIEW

**Comment by thommay** [comment]
So `knife diff` gets a bit weird here - when we download a role "`foo`" we want to write `roles/foo.json`, because we're downloading json. But the canonical version of that role might be `roles/foo.rb`, and when we diff we want to compare `roles/foo.rb` to `/roles/foo.json` on the server. But it's ok for us not to have `roles/foo.json` on the filesystem, and we shouldn't mention it, as long as we have a valid source form of `foo`.

**Comment by thommay** [comment]
@jkeiser thoughts on this would be appreciated

**Comment by jkeiser** [comment]
@Thom may the biggest thing about the code: I would use the data handler to do to/from ruby so you don't have to specialize all the entry types.  Will comment more later

**Comment by thommay** [comment]
@jkeiser yeah, i didn't like the specialisation although I'm not entirely sure it won't be necessary anyway to deal with name mangling between the repo and the server.

**Comment by thommay** [comment]
Closing this, it's totally different now

**Pull request closed without merging**
