### PR TITLE
Replace output_of_command with shell_out! in subversion provider

### PR DESCRIPTION
**Pull request by gh2k**
output_of_command doesn't work properly on Windows (see chef/chef#1533)

### CODE REVIEW

**Comment by gh2k** [comment]
I'm not sure if it's better to break out the "svn.exe" changes into a separate commit. This may be related to a bug somewhere else, as I notice other providers (such as 'git') don't do this.

I'm not sure what the cause of this is, but without the '.exe', calls to svn on Windows explode with a 'CreateProcessW' I/O error.

**Comment by lamont-granquist** [comment]
could you add svn_binary to the resource as a tweakable and then just default in the provider to those values?

I did something similar here with yum_binary (but with some additional complexity due to the nature of package providers):

https://github.com/chef/chef/pull/3774/files

**Comment by gh2k** [comment]
@lamont-granquist This any better? I've played around with it in my test environment and it seems OK

**Comment by lamont-granquist** [comment]
Yep, LGTM :+1:

**Comment by lamont-granquist** [comment]
@chef/client-core needs review

**Comment by tyler-ball** [comment]
:+1:

**Comment by danielsdeleo** [comment]
LGTM :+1:

**Comment by gh2k** [comment]
Thanks for the merge

**Pull request merged**
