### PR TITLE
Bump dependencies to pick up InSpec 1.45.9

### PR DESCRIPTION
**Pull request by adamleff**
Signed-off-by: Adam Leff <adam@leff.co>

### CODE REVIEW

**Comment by tas50** [comment]
@adamleff I assume in 20 days there's been 10 new inspec releases so this can get closed out now?

**Comment by adamleff** [comment]
@tas50 hilarious... and yes, I'm going to close it an open new ones since I did a release today! :)

**Comment by btm** [comment]
@tas50 I think we need to find a bunch of inspec bugs to keep @adamleff busy so he stops being so good at shipping inspec.

**Comment by adamleff** [comment]
@btm don't tell anyone, but we're good at shipping because we keep fixing bugs.

**Pull request closed without merging**
