### PR TITLE
tags always an array; fix set_unless

### PR DESCRIPTION
**Pull request by lamont-granquist**
previously if the node had a { normal: { tags: nil } } that we read
since the key existed (but was nil) we would not initialize with an
array.  replacing the code with a call to node.set_unless revealed that
set_unless was similarly buggy.  fixed both issues by fixing set_unless.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
the other side of #4303

**Comment by coderanger** [comment]
This would still fail for `{"tags": "foo"}` or `{"tags": {}}`. I think we should probably return `Array(normal[:tags])` instead to catch both of these.

**Comment by lamont-granquist** [comment]
Hmmm, I don't think anyone does that or else we would have heard about it...

OTOH, likely nobody does that so its probably safe to change that behavior...

**Comment by coderanger** [comment]
If we want to define that `#tags` returns an array, we should make sure that's all it can return :)

**Comment by coderanger** [comment]
The only way I could imagine those happening is someone mis-editing the JSON via manual `knife node edit`.

**Comment by danielsdeleo** [comment]
sounds good :+1:

**Comment by coderanger** [comment]
:+1: I think. This is a bit weird because now `Node#tags` has a side effect rather than being an accessor, but I think that should be okay.

**Comment by coderanger** [comment]
To clarify for the future when someone complains, I think it is fair to say that we (Chef core) "own" `node.normal['tags']` so doing a transparent format upgrade is within scope for Chef's code.

**Comment by lamont-granquist** [comment]
Yeah, I thought about the "side effect" for a bit and pondered how much of a no-op Array.new was or not, and then just went for the trivial looking code.  I also like that it makes a strong statement - if you use the accessor you always get an Array and it will also always exactly match the underlying ivar (even if we have to fix it).

I also can't really imagine anyone complaining, but the only way to wind up complaining about this is to not use the public API...

**Comment by lamont-granquist** [comment]
travis failures are GCE's lack of IPv6 trolling us...

**Comment by coderanger** [comment]
:+1:

**Comment by thommay** [comment]
Thanks Lamont. :+1:

**Pull request merged**
