### PR TITLE
Powershell command wrappers to make argument passing to knife/chef-client etc. easier.

### PR DESCRIPTION
**Pull request by ksubrama**
Make argument parsing into ruby/chef binaries easier.

### CODE REVIEW

**Comment by ksubrama** [comment]
/cc @btm @jdmundrawala 

Please cc chef-client-core.

**Comment by smurawski** [comment]
It doesn't appear to actually wrap the commands to fix the issue https://github.com/chef/chef/issues/1687

**Comment by ksubrama** [comment]
Ok, I think I have another version which handles that case.  It doesn't handle pipeline objects yet.  I'll do that in a second pass.

**Comment by jdmundrawala** [comment]
This looks fine to me, however we might want to consider automatically generating these for all ruby bins. See https://github.com/chef/omnibus-chef/blob/master/config/software/shebang-cleanup.rb
:+1:

**Comment by ksubrama** [comment]
Yes that'd definitely be optimal.  I went with only these initially to be conservative and not accidentally affect the semantics of a whole bunch of binaries that might otherwise show up on the path such as with ChefDK.

**Comment by smurawski** [comment]
:-1:   trying any commands with more than one subcommand fails.  It's creating one string from the remaining args.
```powershell
Chef-PS chef-repo> knife node list
FATAL: Cannot find sub command for: '"node list"'
```

**Comment by ksubrama** [comment]
How are you running this?  I run knife node list and it works for me.

**Comment by ksubrama** [comment]
Apparently PS 5 changed some of the parsing behavior I was "working around".  Will work around the work around.

**Comment by ksubrama** [comment]
@smurawski This should be ready for another look.

**Comment by smurawski** [comment]
:+1: With limited testing on Server 2008 R2, Server 2012, and Server 2012 R2 this seems to do it and it appears to address #1687 Yay!

**Pull request merged**
