### PR TITLE
Add selinux_user and selinux_login resources

### PR DESCRIPTION
**Pull request by wheatevo**
This PR contains the following changes:

* Add `selinux_user` resource to manage SELinux users.
* Add `selinux_login` resource to manage OS login to SELinux user mapping.

Related to PR https://github.com/sous-chefs/selinux/pull/92

## Description

Existing resources in the Chef client do not allow managing SELinux users or SELinux user to OS login mappings. The new `selinux_user` and `selinux_login` resources enable this functionality.

### selinux_user

Provides ability to manage the security level, security range, and roles for a given SELinux user. Uses `semanage user` for implementation.

### selinux_login

Provides ability to manage the security range and associated SELinux user mapping for a given OS login. Uses `semanage login` for implementation.

## Related Issue

N/A, new feature

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by wheatevo** [comment]
Current test failure appears unrelated to these changes:

```
         * timezone[America/Los_Angeles] action set
           
           ================================================================================
           Error executing action `set` on resource 'timezone[America/Los_Angeles]'
           ================================================================================
           
           RuntimeError
           ------------
           There was an error running the timedatectl command
           
           Resource Declaration:
           ---------------------
           # In /opt/kitchen/cache/cookbooks/end_to_end/recipes/linux.rb
           
            26: timezone "America/Los_Angeles"
            27: 
           
           Compiled Resource:
           ------------------
           # Declared in /opt/kitchen/cache/cookbooks/end_to_end/recipes/linux.rb:26:in `from_file'
           
           timezone("America/Los_Angeles") do
             action [:set]
             default_guard_interpreter :default
             declared_type :timezone
             cookbook_name "end_to_end"
             recipe_name "linux"
           end
           
           System Info:
           ------------
           chef_version=18.1.1
           platform=amazon
           platform_version=2
           ruby=ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
           
```

**Comment by johnmccrae** [comment]
That error with amazonlinux and the timezones is something we're working on outside of this PR. I don't think we have decided what changed in the OS.

**Review by neha-p6 — DISMISSED** [review]
Thanks for this addition @wheatevo! 
Could you add an end_to_end recipe testing few cases for the resources? May be add a test user, update permission and then delete it?
[linux.rb](https://github.com/chef/chef/blob/main/kitchen-tests/cookbooks/end_to_end/recipes/linux.rb#L30) is the place where you can do that, which would run it under github action's kitchen tests. We are already installing and setting SElinux to "permissive" there.

**Comment by wheatevo** [comment]
Most integration test failures are due to an issue during self-signed certificate validation, but CentOS 6 is failing with the following:
```
       ---- Begin output of semanage user -a -L s0 -r s0 -R 'staff_r sysadm_r' se_map_test_u ----
       STDOUT: 
       STDERR: SELinux:  Could not downgrade policy file /etc/selinux/targeted/policy/policy.24, searching for an older version.
       SELinux:  Could not open policy file <= /etc/selinux/targeted/policy/policy.24:  No such file or directory
       libsemanage.semanage_reload_policy: load_policy returned error code 2.
       SELinux:  Could not downgrade policy file /etc/selinux/targeted/policy/policy.24, searching for an older version.
       SELinux:  Could not open policy file <= /etc/selinux/targeted/policy/policy.24:  No such file or directory
       libsemanage.semanage_reload_policy: load_policy returned error code 2.
       /usr/sbin/semanage: Could not commit semanage transaction
       ---- End output of semanage user -a -L s0 -r s0 -R 'staff_r sysadm_r' se_map_test_u ----
       Ran semanage user -a -L s0 -r s0 -R 'staff_r sysadm_r' se_map_test_u returned 1
```

Going to take a closer look at this.

**Comment by neha-p6** [comment]
> Most integration test failures are due to an issue during self-signed certificate validation, but CentOS 6 is failing with the following:

The self-signed certificate issue is now resolved. You can rebase to the latest `main` to fix it.

**Comment by wheatevo** [comment]
After rebasing, this is now passing the same tests as the main branch (all but Amazon Linux and the buildkite tests).

**Review by jaymzh — APPROVED** [review]

**Comment by tpowell-progress** [comment]
Applied "Waiting on Release" tag and assigned to myself while we restore the new release pipelines.

**Review by neha-p6 — APPROVED** [review]

**Pull request merged**
