### PR TITLE
convert additional resource methods to properties

### PR DESCRIPTION
**Pull request by lamont-granquist**
converts sensitive, retries, retry_delay and ignore_failure to
properties

### CODE REVIEW

**Comment by lamont-granquist** [comment]
i didn't convert `action`, `allowed_actions`, `guard_interpreter` or `provider` over -- seems like those would be odd as properties, particularly action which isn't itself declarative.  IDK tho.

**Comment by lamont-granquist** [comment]
@chef/client-core should go green in a few minutes and be ready for review (unless we get a Timeout Error)

**Comment by tas50** [comment]
@lamont-granquist  Does this mean a cookbook using those in a custom_resource will actually work on chef 13?

**Comment by lamont-granquist** [comment]
i believe a cookbook that overrides these will still continue to work and won't hit the method redefinition error, yes.  and supports was already handled in the other merged, PR so those won't actually be issues.

**Comment by tas50** [comment]
That makes my life a lot easier. Thanks

**Pull request merged**
