### PR TITLE
added /etc/network/routes persistence for route provider.

### PR DESCRIPTION
**Pull request by popsikle**
This extends route persistence to ubuntu and debian instead of just the redhat flavors.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @popsikle

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by popsikle** [comment]
I had a CLA signed back in the echosign days, I re-signed on the new fancy website.

**Comment by thommay** [comment]
I think I'm :-1: on this. I'd much rather we totally refactor the route provider to clean this up properly and provide an extensible way of progressing here. 

Does that make sense? I appreciate that our technical debt is going to wind up making your life harder, but I think long term this is better.

**Comment by smurawski** [comment]
https://github.com/chef/chef/issues/3994

**Pull request closed without merging**
