### PR TITLE
Move all ChefFS exceptions into a single file

### PR DESCRIPTION
**Pull request by thommay**
This leaves back compat requires to ensure nothing breaks.
cc @chef/client-core

### CODE REVIEW

**Comment by lamont-granquist** [comment]
👍

**Comment by danielsdeleo** [comment]
Should we deprecate the old files so we can delete them in 13.0?

**Comment by danielsdeleo** [comment]
:+1: either way though

**Comment by jkeiser** [comment]
:+1:, I like this!

**Comment by thommay** [comment]
@danielsdeleo now with bonus deprecations

**Pull request merged**
