### PR TITLE
Disabled mount tests on AIX

### PR DESCRIPTION
**Pull request by scotthain**
One cannot create a ramdisk in a WPAR, since it shares filesystem with the LPAR host. Since we use ramdisk for the test, mount tests only work in LPARs. In the future we should find a way to test this code.

@btm @jaym

### CODE REVIEW

**Comment by btm** [comment]
oh man, those WPARs these days.

:+1:

**Comment by lamont-granquist** [comment]
sigh :+1: 

if there's any way of doing loopback mounts on AIX to files, that could be used instead of a ramdisk.  

i think the only reason for a ramdisk in these is that its a temporary thing that you can mount and unmount...

**Comment by scotthain** [comment]
@lamont-granquist Yeah I looked at looking a loopback mount but that's going to take some serious time and testing just to get the test in the right place. I don't want to hold up the release because of that :(

**Comment by jaym** [comment]
:+1:

**Pull request merged**
