### PR TITLE
Chef-13: add Chef-14.0 deprecation for chef-solo legacy mode

### PR DESCRIPTION
**Pull request by lamont-granquist**
the task isn't finished until we can delete the code.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@coderanger resource cloning spec test attacks again

**Comment by coderanger** [comment]
Trololol brittle tests ftw.

**Comment by coderanger** [comment]
So putting this in makes ChefSpec's SoloRunner spam warnings. I vote we add an `unless defined?(ChefSpec)` for now, until ChefSpec gets updated, which in turn requires fixing some perf problems with zero or otherwise hacking around them in ChefSpec.

**Comment by coderanger** [comment]
This would also incorrectly impact people using the `chef_solo` provisioner in Kitchen, so maybe check `ENV['TEST_KITCHEN']` too.

**Comment by lamont-granquist** [comment]
IDK it feels like if we don't start nagging people it'll never get done.  up to @thommay

**Comment by coderanger** [comment]
So the specific issue is that (legacy) solo mode is still faster than zero mode for testing, not by a lot but if you're like me and run thousands of test runs a day even an extra 30 seconds on moving files around is a big change. I realize there very well might be no one else that this applies to, but putting in a warning that I can't silence that both spams on every spec running and makes `deprecations_as_errors` unusable (since it would always fire).

**Pull request closed without merging**
