### PR TITLE
Use user:password from http_proxy url first

### PR DESCRIPTION
**Pull request by jeremiahsnapp**
If the user and password are included in the http_proxy url then use them.
Otherwise use the http_proxy_user and http_proxy_pass values.

### CODE REVIEW

**Comment by in4mer** [comment]
Looks good. How long from a merge to this making it into a client package my team can install?

**Comment by ranjib** [comment]
build failure is due to apt /network stuff. 
:+1:

**Comment by jeremiahsnapp** [comment]
Is there anything else that needs to be done to get this PR merged?

**Comment by thommay** [comment]
:+1: I'll take this in the 12.3 branch i'm prepping

**Comment by thommay** [comment]
Oops, this work's already been done by @jonsmorrow in #3213

**Pull request closed without merging**
