### PR TITLE
Fix windows_path converging on every run

### PR DESCRIPTION
**Pull request by tas50**
Fixes https://github.com/chef/chef/issues/6526

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
Pinging @lamont-granquist since he brought this up in the original issue

**Comment by lamont-granquist** [comment]
appveyor tests are busted in ways that make me suspect this broke unit test mocking and started really messing with the path on windows or something...

**Comment by tas50** [comment]
I'll look into the specs for this tomorrow.

**Comment by tas50** [comment]
@lamont-granquist I rebased this and it's passing appveyor and ruby 2.4.2 in travis. It's the same old 2.3 failures that are failing. Any objection to merging this one now?

**Comment by lamont-granquist** [comment]
ah yeah this is trivial, i must have just been grouchy about red appveyor...

**Pull request merged**
