### PR TITLE
Fix bug where unset HOME would cause chef to crash

### LINKED ISSUE #3153: chef-client 12.2.0 fails to start without HOME environment variable
Just upgraded my Debian Wheezy systems to 12.2.0 and now get the following when trying to start the chef-client service.

```
[production-dfw] root@api-n01a:~ # service chef-client start
Starting chef-client : chef-client/opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:199:in `home': couldn't find HOME environment -- expanding `~' (ArgumentError)
        from /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:199:in `all_homes'
        from /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:161:in `home'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:36:in `gather_plist_dirs'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:40:in `<class:Macosx>'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:27:in `<class:Service>'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:26:in `<class:Provider>'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:25:in `<class:Chef>'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:24:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/providers.rb:93:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef.rb:25:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/bin/chef-client:23:in `<top (required)>'
        from /usr/bin/chef-client:51:in `load'
        from /usr/bin/chef-client:51:in `<main>'
^N failed!
````

### PR DESCRIPTION
**Pull request by jdmundrawala**
Fixes #3153 

cc @chef/client-core @chef/client-engineers

### CODE REVIEW

**Comment by ranjib** [comment]
:+1:

**Comment by btm** [comment]
:+1:

**Comment by btm** [comment]
@jdmundrawala I merged this to master. It looks like 12-stable is a little behind master, so we can decide next week what we want to do about that, i.e. merge master->12-stable or cherry-pick based on what kind of release we're doing.

**Comment by danielsdeleo** [comment]
@btm we were having issues with 12-stable so we created a 12.2 stable for this release. Should easily cherry pick.

**Comment by ksubrama** [comment]
:+1:

**Comment by acockrell37** [comment]
You guys might wanna figure out *today* what to do about it.   Anybody in AWS installing chef via the cloud-init omnibus install method is having a very bad day.   Omnibus is pulling the old rusty broken package, and it's failing like ballsauce.

**Comment by jdmundrawala** [comment]
the fix is going out today

**Pull request merged**
