### PR TITLE
Lcg/zypper package

### PR DESCRIPTION
**Pull request by lamont-granquist**
This updates zypper package to look like the rest of our package classes.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core this can use some review

**Comment by jkeiser** [comment]
:+1:

Might be interesting to see what happens if you move the provides lines out from package.rb into zypper_package.rb,

**Comment by thommay** [comment]
:+1:

**Comment by danielsdeleo** [comment]
LGTM :+1:

**Comment by jaymzh** [comment]
LGTM. Never heard of zypper though :)

**Comment by tyler-ball** [comment]
:+1: :shipit:

**Pull request merged**
