### PR TITLE
Update Release Announcements; Keep Dockerfile up-to-date

### PR DESCRIPTION
**Pull request by tduffield**
### Description

* Update the release announcement templates to remove kitchen language.
* Make sure that the default version in the Dockerfile is kept up to date with the latest stable release.
* Update the download URL for chef in the README.

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [x] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by btm** [comment]
I think we should put the kitchen-dokken directions in the README.md instead along with words about what you would use it for and not the release email templates that are going to go out a couple times a month.

If someone is already using kitchen-dokken, they already have that YAML and would know where to change the version. There isn't the same convenience of a link to the download site where you could just click it to get to the latest version, i.e. someone still has to copy the YAML to the correct place manually, and they're just going to change the version number rather than use the YAML template from a release post.

**Comment by tduffield** [comment]
@btm by that logic, should we remove the instructions on how to specify the version of chef for the normal chef provisioner as well?

**Comment by btm** [comment]
@tduffield yeah, that makes sense to me, it looks the same and doesn't seem like it bears repeating.

**Comment by btm** [comment]
@tduffield were you going to put those YAML blurbs in README.md?

**Comment by tduffield** [comment]
@btm I was but there's language in the README indicating that the README was intended to document development only. I tried to find a good place for it, but I didn't see a good place that wouldn't turn the README into a "These are all the different ways to use Chef" so I put a link to the image that has documentation on how to use it.

**Pull request merged**
