### PR TITLE
Add missing require statement in resource_resolver

### PR DESCRIPTION
**Pull request by ranjib**
/cc @lamont-granquist

### CODE REVIEW

**Comment by lamont-granquist** [comment]
This may collide with or duplicate work that @jkeiser is doing.

**Comment by ranjib** [comment]
so should i close this and monkey path on the consumer side? chef-lxc is failing due to this, i can definitely patch things on that side, add a require statement there instead.

**Comment by jkeiser** [comment]
I don't think I've fixed this; it should be OK to go by itself.

**Comment by jkeiser** [comment]
:+1:

**Comment by thommay** [comment]
:+1:

**Pull request merged**
