### PR TITLE
Remove the knife null plugin

### PR DESCRIPTION
**Pull request by tas50**
This is a pretty odd plugin that we're shipping. I suspect there's a reason for it so I opened this PR to get the conversation going.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
i think its for testing knife timing issues to see how much of it is just due to ruby module loading garbage

**Comment by tas50** [comment]
It came along with the hash functionality so I suspect that's true, but it's in the help page, which is less than great.

**Comment by lamont-granquist** [comment]
Yeah, this should stay in.   Hiding it from help is another kind of issue.

**Comment by stevendanna** [comment]
I'd be 👍 on figuring out how to hide it from help or to give it a clearer help message.  We could remove it but I do think it is useful to keep around.

Alternatively, we could make it a bit more useful by renaming it and having it print some diagnostic information; but then it is less useful for benchmarking and such.

**Comment by lamont-granquist** [comment]
yeah i think its utility is in benchmarking, so it really should just do nothing.

**Pull request closed without merging**
