### PR TITLE
Proposal to (re-)add myself as a core chef maintainer.

### PR DESCRIPTION
**Pull request by mcquin**
I'm back!

Also, I've been getting some PR review requests on Ohai lately. I'd like to be able to review and +1 them officially.

### CODE REVIEW

**Comment by thommay** [comment]
woop! :cake: :tada: :+1:

**Comment by btm** [comment]
YAY :+1:

**Comment by jdmundrawala** [comment]
:100:

**Comment by thommay** [comment]
merged and added to chef/client-core and chef/client-maintainers

**Pull request merged**
