### PR TITLE
Fixes GH-4955, allowing local gems with remote dependencies

### LINKED ISSUE #4955: Issue with new behavior of Chef Gem in 12.10.24-1
## Description

The behavior of `chef_gem` was changed when installing a local gem in #4847. If you're installing a local gem with remote dependencies, the installation fails because it only looks for those dependencies locally.

## Chef Version

12.10.24-1 

## Platform Version

Ubuntu 14.04.3 LTS

## Replication Case

You'll need to [build a gem](http://guides.rubygems.org/make-your-own-gem/) with some remote dependencies, sample `Gemfile`:

```
source 'https://rubygems.org'

gemspec

group :test do
  gem 'activesupport'
```

You'll need to build that gem and have it exist locally on your filesystem (`gem build`).

Then you need a cookbook that tries to install that gem.

```
chef_gem 'common-utils' do
  compile_time false	
  source '/tmp/gems/common-utils.gem'
  action :install
end
```

## Client Output

Client will error out complaining it can't find one of the gems (my experience yields the first one in alphabetical order, but if you have a more complicated set of dependencies that may not be true for everyone).

## Stacktrace

```
1463702555,,ui,message,    amazon-ebs: [2016-05-20T00:02:40+00:00] DEBUG: chef_gem[common-utils] common-utils not installed%!(PACKER_COMMA) installing 0.0.1
1463702555,,ui,message,    amazon-ebs:
1463702555,,ui,message,    amazon-ebs: ================================================================================
1463702555,,ui,message,    amazon-ebs: Error executing action `install` on resource 'chef_gem[common-utils]'
1463702555,,ui,message,    amazon-ebs: ================================================================================
1463702555,,ui,message,    amazon-ebs:
1463702555,,ui,message,    amazon-ebs: Mixlib::ShellOut::ShellCommandFailed
1463702555,,ui,message,    amazon-ebs: ------------------------------------
1463702555,,ui,message,    amazon-ebs: Expected process to exit with [0]%!(PACKER_COMMA) but received '2'
1463702555,,ui,message,    amazon-ebs: ---- Begin output of /opt/chef/embedded/bin/gem install /tmp/gems/common-utils.gem -q --no-rdoc --no-ri -v "0.0.1" --local ----
1463702555,,ui,message,    amazon-ebs: STDOUT:
1463702555,,ui,message,    amazon-ebs: STDERR: ERROR:  Could not find a valid gem 'activesupport' (>= 0) in any repository
1463702555,,ui,message,    amazon-ebs: ---- End output of /opt/chef/embedded/bin/gem install /tmp/gems/common-utils.gem -q --no-rdoc --no-ri -v "0.0.1" --local ----
1463702555,,ui,message,    amazon-ebs: Ran /opt/chef/embedded/bin/gem install /tmp/gems/common-utils.gem -q --no-rdoc --no-ri -v "0.0.1" --local returned 2
1463702555,,ui,message,    amazon-ebs:
1463702555,,ui,message,    amazon-ebs: Resource Declaration:
1463702555,,ui,message,    amazon-ebs: ---------------------
1463702555,,ui,message,    amazon-ebs: # In /home/ubuntu/staging_directory/cookbooks-1/application_install/recipes/install_common_utils.rb
1463702555,,ui,message,    amazon-ebs:
1463702555,,ui,message,    amazon-ebs: 16: chef_gem 'common-utils' do
1463702555,,ui,message,    amazon-ebs: 17:   compile_time false
1463702555,,ui,message,    amazon-ebs: 18:   source '/tmp/gems/common-utils.gem'
1463702555,,ui,message,    amazon-ebs: 19:   action :install
1463702555,,ui,message,    amazon-ebs: 20: end
1463702555,,ui,message,    amazon-ebs: 21:
1463702555,,ui,message,    amazon-ebs:
1463702555,,ui,message,    amazon-ebs: Compiled Resource:
1463702555,,ui,message,    amazon-ebs: ------------------
1463702555,,ui,message,    amazon-ebs: # Declared in /home/ubuntu/staging_directory/cookbooks-1/application_install/recipes/install_common_utils.rb:16:in `from_file'
1463702555,,ui,message,    amazon-ebs:
1463702555,,ui,message,    amazon-ebs: chef_gem("common-utils") do
1463702555,,ui,message,    amazon-ebs: package_name "common-utils"
1463702555,,ui,message,    amazon-ebs: action [:install]
1463702555,,ui,message,    amazon-ebs: retries 0
1463702555,,ui,message,    amazon-ebs: retry_delay 2
1463702555,,ui,message,    amazon-ebs: default_guard_interpreter :default
1463702555,,ui,message,    amazon-ebs: declared_type :chef_gem
1463702555,,ui,message,    amazon-ebs: cookbook_name :"application_install"
1463702555,,ui,message,    amazon-ebs: recipe_name "install_common_utils"
1463702555,,ui,message,    amazon-ebs: gem_binary "/opt/chef/embedded/bin/gem"
1463702555,,ui,message,    amazon-ebs: source "/tmp/gems/common-utils.gem"
1463702555,,ui,message,    amazon-ebs: end
1463702555,,ui,message,    amazon-ebs:
1463702555,,ui,message,    amazon-ebs: Platform:
1463702555,,ui,message,    amazon-ebs: ---------
1463702555,,ui,message,    amazon-ebs: x86_64-linux
1463702555,,ui,message,    amazon-ebs:
1463702555,,ui,message,    amazon-ebs: [2016-05-20T00:02:41+00:00] INFO: Running queued delayed notifications before re-raising exception
1463702555,,ui,message,    amazon-ebs: [2016-05-20T00:02:41+00:00] DEBUG: Re-raising exception: Mixlib::ShellOut::ShellCommandFailed - chef_gem[common-utils] (application_install::install_common_utils line 16) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0]%!(PACKER_COMMA) but received '2'
1463702555,,ui,message,    amazon-ebs: ---- Begin output of /opt/chef/embedded/bin/gem install /tmp/gems/common-utils.gem -q --no-rdoc --no-ri -v "0.0.1" --local ----
1463702555,,ui,message,    amazon-ebs: STDOUT:
1463702555,,ui,message,    amazon-ebs: STDERR: ERROR:  Could not find a valid gem 'activesupport' (>= 0) in any repository
1463702555,,ui,message,    amazon-ebs: ---- End output of /opt/chef/embedded/bin/gem install /tmp/gems/common-utils.gem -q --no-rdoc --no-ri -v "0.0.1" --local ----
1463702555,,ui,message,    amazon-ebs: Ran /opt/chef/embedded/bin/gem install /tmp/gems/common-utils.gem -q --no-rdoc --no-ri -v "0.0.1" --local returned 2
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:289:in `invalid!'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:276:in `error!'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/mixin/shell_out.rb:45:in `shell_out!'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/provider/package.rb:538:in `shell_out_with_timeout!'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/provider/package/rubygems.rb:544:in `install_via_gem_command'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/provider/package/rubygems.rb:524:in `install_package'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/provider/package.rb:100:in `block (2 levels) in action_install'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/provider/package.rb:226:in `multipackage_api_adapter'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/provider/package.rb:99:in `block in action_install'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/mixin/why_run.rb:52:in `add_action'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/provider.rb:176:in `converge_by'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/provider/package.rb:98:in `action_install'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/provider.rb:145:in `run_action'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/resource.rb:596:in `run_action'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/runner.rb:69:in `run_action'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/runner.rb:97:in `block (2 levels) in converge'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/runner.rb:97:in `each'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/runner.rb:97:in `block in converge'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/runner.rb:96:in `converge'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:667:in `block in converge'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:662:in `catch'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:662:in `converge'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:701:in `converge_and_save'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:281:in `run'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:285:in `block in fork_chef_client'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:273:in `fork'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:273:in `fork_chef_client'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:238:in `block in run_chef_client'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/local_mode.rb:44:in `with_server_connectivity'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:226:in `run_chef_client'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:290:in `loop'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:290:in `interval_run_chef_client'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:269:in `run_application'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:58:in `run'
1463702555,,ui,message,    amazon-ebs: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/bin/chef-solo:25:in `<top (required)>'
1463702555,,ui,message,    amazon-ebs: /usr/bin/chef-solo:51:in `load'
1463702555,,ui,message,    amazon-ebs: /usr/bin/chef-solo:51:in `<main>'
```

## Work around

If you manually call `chef_gem` with each of the network-required dependencies before calling the local gem, it'll make it through. However, any changes to the dependencies of the local gem will need to be mirrored in your recipe. 

Let me know if you guys need any more information.

Thanks!!

### PR DESCRIPTION
**Pull request by jyaworski**
Hi all. This should fix #4955.

### CODE REVIEW

**Comment by coderanger** [comment]
How does this not put things back the way they were before?

**Comment by jyaworski** [comment]
@coderanger it keeps this line:

https://github.com/chef/chef/pull/4847/files#diff-caced4dc48f86f296fd537ac50c65689R536

**Comment by coderanger** [comment]
I think this undoes the fix from before though. The whole point of the change was to better allow for "not on the internet" usage, so local means "no really don't use rubygems". I think the conclusion from earlier discussions on this (/cc @lamont-granquist) was that we need two flags for the two different behaviors ("only local" vs. "local but use rubygems for dependencies") because both behaviors are needed by different people.

**Comment by jyaworski** [comment]
@coderanger would setting :local to :both solve it? I'm not sure the order of it.

**Comment by coderanger** [comment]
@jyaworski Most of the Chef maintainer team is en route to ChefConf this weekend so might be a bit until others that know the RubyGems APIs better get a chance to weigh in.

**Comment by jyaworski** [comment]
@coderanger ping.

**Comment by coderanger** [comment]
@jyaworski I didn't write the original fix so I'm the wrong one to ping.

**Comment by jyaworski** [comment]
Tagging @PrajaktaPurohit and @ksubrama due to their involvement in the previous PR.

**Comment by loganmeetsworld** [comment]
@jyaworski we are currently looking into this.

**Comment by loganmeetsworld** [comment]
@jyaworski we have decided to revert the use of the `local` domain and use the default domain set by rubygems, as set out in this PR. However, I am wondering what the line `return false if Pathname.new(@new_resource.name).absolute?` adds to the revert of #4847. Can you expand on that? If it is an important case, we should probably add a test for that. If you decide to remove that line or add a test, then 👍 from me.

**Comment by jyaworski** [comment]
@loganmeetsworld that line was just to exit earlier if it's a local path. It's not strictly needed.

**Comment by loganmeetsworld** [comment]
@jyaworski If it's not part of the fix for this specific problem, let's take it out.

**Comment by jyaworski** [comment]
@loganmeetsworld done.

**Comment by jkeiser** [comment]
:+1:

**Comment by mwrock** [comment]
I added PR #5379 to "finish off" this fix. Since this still leaves the `--local` in the gem install for local file gem sources. Just checking if that was intentionally left out or if it was simply an oversight.

**Comment by moos3** [comment]
the --local is certainly a breaking change. That should only be set as a option. Needs to be removed. I have run into issues where chef_gem can't install anything thats a custom gem with remote dependencies.

**Pull request merged**
