### PR TITLE
Update URLs to chef.io

### PR DESCRIPTION
**Pull request by tas50**

### CODE REVIEW

**Comment by thommay** [comment]
lgtm :+1:

**Comment by sethvargo** [comment]
LGTM, but why was I assigned to this?

**Comment by lamont-granquist** [comment]
:+1:

**Comment by lamont-granquist** [comment]
@sethvargo its sort of a beta of trying to get maintainers to look at PRs

**Comment by lamont-granquist** [comment]
(you can safely ignore it for now)

**Pull request merged**
