### PR TITLE
windows_feature: Fix failures on windows 2008r2

### PR DESCRIPTION
**Pull request by kapilchouhan99**
Signed-off-by: Kapil Chouhan <kapil.chouhan@msystechnologies.com>

## Description
- Fixed minor bug
- Ensured chef-style on the code changes made

## Related Issue
Fixes: 
https://getchef.zendesk.com/agent/tickets/22056
https://chefio.atlassian.net/browse/MSYS-1006

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tas50** [comment]
Is this tested on 2012/2016/2019 as well?

**Comment by btm** [comment]
@tas50 the change is in an existing `older_than_win_2012_or_8?` conditional.

**Comment by tas50** [comment]
🤦‍♂

**Comment by tas50** [comment]
You think I could read the stuff I wrote

**Pull request merged**
