### PR TITLE
[WIP] Switch MAINTAINERS to be a TOML doc

### PR DESCRIPTION
**Pull request by thommay**
:construction: For review and discussion first :construction: 

This allows us to easily parse the maintainers file in a programatic
way, for things like updating github teams, autoassigning reviewers.

It deliberately doesn't fully list all the possible paths a team is responsible for - I'd expect maintainers to fill this in once the PR is merged.

### CODE REVIEW

**Comment by thommay** [comment]
(Stolen liberally from the Docker MAINTAINERS file)

**Comment by lamont-granquist** [comment]
:+1:

**Comment by smurawski** [comment]
:+1: Why not bring back ini files :)

**Comment by nathenharvey** [comment]
:+1:

**Pull request merged**
