### PR TITLE
CHEF-5372: Support specific run_levels for RedHat service

### PR DESCRIPTION
**Pull request by robbydyer**
https://tickets.opscode.com/browse/CHEF-5372

### CODE REVIEW

**Comment by ForestJay** [comment]
Is this ever going to get pulled in?  My use case is that I have a service to ensure graceful exit with AWS auto-scaling.  Without this change I'll need to use a bash command to run chkconfig.

**Comment by btm** [comment]
@ForestJay This isn't complete, so not as is.

I asked if service foobar is enabled for run level 3, what happens when this runs?
```
service "foobar" do
  action :enable
  run_levels 5
end
```

@robbydyer said chkconfig would typically end up with 3 and 5 enabled depending on the syntax, but it would make the most sense if Chef just left you with 5 enabled, because that's what you specifically asked for. b69c680 should have made that the case, but we need test coverage for that. The two tests that were added have to do with if we claim the service is enabled.

That is, we a test like:

```it "calls chkconfig to disable other enabled run levels when they are not included in run_levels"```

**Comment by ForestJay** [comment]
@btm, thank you for the clarification.  So, if I wanted to fix this, could I form @robbydyer 's change and add the tests?  Note, even if the answer is yes I'm not sure I'll find time for it.

**Comment by smurawski** [comment]
@ForestJay You can definitely take a stab at fixing this issue, but if you take @robbydyer 's commits we'll need a CCLA signed by him as well (via supermarket.chef.io).  

@robbydyer Are you still interested in getting this PR merged?  Do you need assistance in getting spec tests together?

**Comment by robbydyer** [comment]
I believe I've already signed the CCLA.

**Comment by btm** [comment]
@robbydyer I see your github account attached to the [rdyer](https://supermarket.chef.io/users/rdyer) account on Supermarket, which is attached to a CLA. So just make sure that the rdyer -at- tropo dot com email address that's being used in your git commits is listed on your Github account [under emails](https://github.com/settings/emails).

**Comment by lamont-granquist** [comment]
@robbydyer are you around to fix this up, otherwise i'll grab this and fix it up and merge it.

**Pull request closed without merging**
