### PR TITLE
Remove obsolete reference to chef-13. Add VERSION to gemspec.

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by ksubrama** [comment]
@chef/client-core @chef/engineering-services

**Comment by ksubrama** [comment]
Also /cc @chefsalim @tyler-ball @patrick-wright @sersut @jkeiser - shipit folks.  We need to VERSION file to be able to rune rake commands after appbundling.  If any of you are making similar VERSION changes in other repos, please add it to the gemspec.

**Comment by lamont-granquist** [comment]
:+1: no idea why CI hates you...

**Comment by schisamo** [comment]
:+1:

**Comment by btm** [comment]
:+1:

**Pull request merged**
