### PR TITLE
Use Mixlib::Shellout instead of Chef::Mixin::Command

### PR DESCRIPTION
**Pull request by DeWaRs1206**
Using C:\Users\Administrator>chef-solo -i 30 -s 5 -c C:/monsoon/solo.rb -j http://foo-bar/get-run -r http://foo-bar.com/cookbooks.tar.gz
failled with error : 
[2015-06-25T15:01:52+02:00] DEBUG: ---- End output of tar zxvf C:/chef/recipes.t
gz -C C:/chef ----
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:140:in `block in ou
tput_of_command': undefined method `exitstatus' for nil:NilClass (NoMethodError)

        from C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:122:in
 `chdir'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:122:in
 `output_of_command'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:101:in
 `run_command_and_return_stdout_stderr'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:79:in
`run_command'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/application/solo.rb:217
:in `reconfigure'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:58:in `r
un'
        from C:/opscode/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (requi
red)>'
        from C:/opscode/chef/bin/chef-solo:63:in `load'
        from C:/opscode/chef/bin/chef-solo:63:in `<main>'

using Mixlib::ShellOut instead of Chef::Mixin::Command solved the issue

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @DeWaRs1206

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by thommay** [comment]
@DeWaRs1206 Thanks for your submission. You'll need to update the failing tests - https://travis-ci.org/chef/chef/jobs/68317452#L1321 and ensure that you fix the formatting of your code.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by DeWaRs1206** [comment]
@thommay , I have fix failling test, not sure what you mean by "ensure that you fix the formatting of your code." 
Could you give me more details ? 
BR

**Comment by btm** [comment]
@DeWaRs1206 it looks like the 2nd commit you just pushed didn't have your correct email address (and name?) in it. Could you amend that commit with the same name/email as your first one and force push here?

What's the purpose of the "#tarcommand.run_command" comment line? Why the leading spaces?

As a minor detail you added an extra newline in `spec/unit/application/solo_spec.rb` that wasn't necessary.

**Comment by DeWaRs1206** [comment]
@btm anything else I need to do regarding this PR ?

**Comment by sethvargo** [comment]
This LGTM, but how did this get assigned to me?

**Comment by btm** [comment]
@sethvargo I believe @thommay has been working on having curry auto-assign PRs needing review. I'm not sure if it's been talked about outside of the IRC meetings yet. I'll poke him.

**Comment by sethvargo** [comment]
@btm ah okay. I was confused :smile:

**Comment by ranjib** [comment]
:+1:

**Comment by tyler-ball** [comment]
:+1:

**Pull request merged**
