### PR TITLE
Make local mode the default

### PR DESCRIPTION
**Pull request by jkeiser**
As per https://github.com/opscode/chef-rfc/pull/48

### CODE REVIEW

**Comment by thommay** [comment]
ping @jkeiser - do you still want to do this?

**Comment by jkeiser** [comment]
Yeah, I still think it's right ... but I haven't had the time to unrot this patch and I'm not sure how soon that will be.

**Comment by lamont-granquist** [comment]
also paging @jkeiser and leaving a note so it sorts to the bottom.

**Comment by lamont-granquist** [comment]
closing for now

**Pull request closed without merging**
