### PR TITLE
[MSYS-688] Fixed invalid date and Invalid starttime error

### PR DESCRIPTION
**Pull request by NimishaS**
### Issues Resolved

Fixes https://github.com/chef/chef/issues/6480 and https://github.com/chef/chef/pull/6312#issuecomment-337533074

### Check List

- [x] New functionality includes tests
- [ ] All tests pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by tas50** [comment]
There's a style failure here and a spec failure which looks unrelated, but you might want to double check locally

**Comment by NimishaS** [comment]
@tas50 , fixed chefstyle issues. The travis failures are not related to my PR. Verified the unit and functional specs of `windows_task` locally. They are working successfully.

**Comment by tas50** [comment]
@NimishaS Can we get a unit test that actually tests this behavior change?

**Comment by NimishaS** [comment]
@tas50 , added unit tests. Appveyor is failing for `rubygems_spec`: https://ci.appveyor.com/project/chef/chef/build/master-10692/job/863eb9mil62os0u4#L2328

**Pull request merged**
