### PR TITLE
Allow FIPS 140-2 OpenSSL FOM to build on PPC EL platforms

### PR DESCRIPTION
**Pull request by btm**
Resolves https://github.com/chef/customer-bugs/issues/257

### CODE REVIEW

**Comment by btm** [comment]
ad-hoc build: https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/546#4242e080-2cd1-4582-834a-bf0af7477f33

**Comment by tas50** [comment]
Looks like this doesn't work on ARM https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/546#6ef5e6bf-5933-473d-9080-dbe0d390218a

**Comment by lamont-granquist** [comment]
https://github.com/openssl/openssl/issues/11105 and will never work on aarch64 for this openssl version.

**Comment by tas50** [comment]
Maybe x86 and PPC would work?

**Comment by lamont-granquist** [comment]
yeah it sounds like everything it builds on it should be supported on.  that error message is the "we don't support FIPS on this architecture" error message.

**Comment by btm** [comment]
> yeah it sounds like everything it builds on it should be supported on. that error message is the "we don't support FIPS on this architecture" error message.

@lamont-granquist are you referring to this error specifically?

```
Error:
--
  |  
  | FIPS_text_start() returns NULL
  | gmake[4]: *** [Makefile.shared:169: link_a.gnu] Error 1
  | gmake[3]: *** [Makefile:357: do_linux-shared] Error 2
  | gmake[2]: *** [Makefile:310: libcrypto.so.1.0.0] Error 2
  | gmake[1]: *** [Makefile:111: shared] Error 2
  | gmake: *** [Makefile:287: build_crypto] Error 1

```

**Comment by btm** [comment]
new more specific build to exclude aarch64: https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/549#bd7c028c-7162-441a-9271-734b849b61ad

**Pull request merged**
