### PR TITLE
Backport #6351 to Chef-12

### PR DESCRIPTION
**Pull request by jaymzh**
### Description
Backport!

Signed-off-by: Phil Dibowitz <phil@ipom.com>

### CODE REVIEW

**Comment by jaymzh** [comment]
CC @chef/client-core and @lamont-granquist

**Comment by jaymzh** [comment]
Those tests look like transient errors to me, I restarted them.

**Comment by jaymzh** [comment]
2 of the 3 still fail.

One test seems to be within chef-zero:
```
Unknown key type. Must be String or OpenSSL::PKey::RSA. nil
```
I definitely am not touching any of that here.

The other is 'halite':

```
  1) Halite::SpecHelper#step_into without step-into there should be no ChefSpec resource-level matcher helper-created resource should raise NoMethodError
     Failure/Error: it { expect { chef_run.halite_test_helper('test' ) }.to raise_error NoMethodError }
       expected NoMethodError but nothing was raised
     # ./spec/spec_helper_spec.rb:240:in `block (5 levels) in <top (required)>'
```

Again, I don't think that's me....

**Comment by thommay** [comment]
Yeah, those are known on the 12 branch.

**Pull request merged**
