### PR TITLE
Update ui.rb

### PR DESCRIPTION
**Pull request by rreyes**
I think this is a bug.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @rreyes

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by ranjib** [comment]
@rreyes whats not working?
https://github.com/chef/chef/blob/master/lib/chef/knife/core/ui.rb#L35

**Comment by lamont-granquist** [comment]
using `stdout` and going through the `attr_reader :stdout` declaration is generally preferred than going directly to `@stdout` because in the former a typo like `stdoutt` will raise a NoSuchMethod error exception while `@stdoutt` will create a new instance variable.

**Comment by rreyes** [comment]
Hello. It might be my limited knowledge of Ruby but I believe attr_reader will create the instance variables which are reachable inside the object using the @ prefix. So stdout and @stdout is not the same. If you use stdout then it will not be referring to the variable created by attr_reader nor the one injected by the constructor hence your code is not allowing the user to inject their own stdout. But I could be wrong. Don't quote me.

**Comment by ranjib** [comment]
attr_reader creates a method which returns an instance variable with same name. it does not create the 

```ruby
class Foo
  attr_reader :x
end
```
irb
```sh
f= Foo.new
f.instance_variables # => []
f.x # => nil
f.instance_variables #=> []
```

so.. attr_reader does not create anything , from what i understand.

**Comment by lamont-granquist** [comment]
`attr_reader :x` creates:

def attr_reader
  @attr_reader
end

the ivar is autovivified the first time it is referenced like i mentioned.

closing this since its specifically against the code recommendations that we like to use (see lots of my old PRs on providers where i rip out most of the `@`-signs).

**Pull request closed without merging**
