### PR TITLE
Clarify warning

### PR DESCRIPTION
**Pull request by pburkholder**
A clearer error message here would have saved me significant time yesterday. See also #2963. Thanks, Peter

### CODE REVIEW

**Comment by lamont-granquist** [comment]
That's still pretty confusing.  I spent at least 5 mins trying to sort out what the issue was.  There's also a similar error code previously that should probably be clarified.

Maybe something like "Installing to the system rubygems requires shelling out to a gem binary, rubygems options hashes are not supported, please supply a string" would be more concise and understandable?

**Comment by btm** [comment]
so we can talk to rubygems either 1) through the ruby library or 2) calling out to the gem command. We can pass a hash for #1 directly to the library, but for #2 we have to pass a string of command line options.

also, users either want to install gems A) for use in Chef, or B) on the system for use by other programs.

If you're running gem_package, you've chosen B. If you're using Omnibus, you're in the wrong ruby, so you have to pass a string. If you're not using Omnibus, it's possible that you're running in the system ruby you also want the gem installed into. This isn't very common anymore, except on systems we don't produce omnibus packages for.

I'll come up with a suggestion after my next meeting.

**Comment by btm** [comment]
How about this:

Gem options should be passed to gem_package as a string instead of a hash when using this version of Chef because it runs under its own version of Ruby. A hash may only be used when installing a gem to the same Ruby installation that Chef is running under.

See https://docs.chef.io/resource_gem_package.html for additional information

**Comment by lamont-granquist** [comment]
That works for me.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by pburkholder** [comment]
@lamont-granquist I adopted your language, although I changed 'version' to 'install' since I felt that was clearer. Ok to merge?

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by btm** [comment]
@pburkholder let's change "Gem options should be passed..." to "Gem options must be passed..."

Can you make sure that your github account has your getchef.com email address attached to it so Curry can match your commits -> github -> supermarket -> ccla?

Finally, your phrasing of "ok to merge?" makes me wonder if you're aware of the process for the Chef repository or not. I know this patch seems trivial, but you need two up votes from [Maintainers](https://github.com/chef/chef/blob/master/MAINTAINERS.md), and then a Maintainer has to merge it for you.

https://github.com/chef/chef-rfc/blob/master/rfc030-maintenance-policy.md

That said, :+1: after changing should to must.

**Comment by pburkholder** [comment]
"should" changed to "must" and updated email addresses so CurryBot is happy.

**Comment by thommay** [comment]
:+1:

**Pull request merged**
