### PR TITLE
Fix condition of removing a group before user error.

### PR DESCRIPTION
**Pull request by cmluciano**
This should fix [issue 1586](https://github.com/chef/chef/issues/1586).
The issue is that if a group is removed before the user, the GID
remained and causes an error. This should remove the check for remove
actions.

If someone can think of a good test for this, I'd be happy to add one.

### CODE REVIEW

**Comment by smurawski** [comment]
@sersut You mentioned this approach on the source issue. Making this change breaks the existing test case around validating a group preference.  Rather than remove that validation for all platforms, should we have a different provider for OSX?

**Comment by smurawski** [comment]
@chef/maintainers Anyone want to weigh in on this proposed fix?
@jtimberman @tyler-ball - as MacOSX subsystem folks... any thoughts on whether this would require breaking out a Mac specific provider?

**Comment by jtimberman** [comment]
My understanding is that OS X already has its own user provider, `Chef::Provider::User::Dscl`.

**Comment by tyler-ball** [comment]
I think this is the appropriate fix, and I think it is fine to go in the base `Chef::Provider::User` class (which `Chef::Provider::User::Dscl` extends).

My thought is this: when deleting a user, do we _ever_ care if the group that user is in exists?  We're trying to remove the user, not validate that its state is correct.

If people agree with my logic, then the tests should be updated to match this new logic.  So I'm :+1: on this change and updating the tests.  Thoughts?

**Comment by cmluciano** [comment]
Whoops accidentally added this file to another PR

**Comment by lamont-granquist** [comment]
:+1:

**Comment by thommay** [comment]
:+1:

**Comment by btm** [comment]
@cmluciano I think the failing test gives a good idea on at least one test for this.

```
Failures:
  1) Chef::Provider::User convert_group_name should raise an error if we can't translate the group name during resource assertions
     Failure/Error: expect { @provider.process_resource_requirements }.to raise_error(Chef::Exceptions::User)
       expected Chef::Exceptions::User, got #<NoMethodError: undefined method `to_sym' for nil:NilClass> with backtrace:
         # ./lib/chef/mixin/why_run.rb:321:in `run'
         # ./lib/chef/provider.rb:144:in `process_resource_requirements'
         # ./spec/unit/provider/user_spec.rb:457:in `block (4 levels) in <top (required)>'
         # ./spec/unit/provider/user_spec.rb:457:in `block (3 levels) in <top (required)>'
     # ./spec/unit/provider/user_spec.rb:457:in `block (3 levels) in <top (required)>'
```

In this case you could have the same test but with the action set to :remove, and expect it not to raise an error.

For example:
```
diff --git a/spec/unit/provider/user_spec.rb b/spec/unit/provider/user_spec.rb
index 3811686..39d8838 100644
--- a/spec/unit/provider/user_spec.rb
+++ b/spec/unit/provider/user_spec.rb
@@ -452,11 +452,20 @@ describe Chef::Provider::User do

     it "should raise an error if we can't translate the group name during resource assertions" do
       expect(Etc).to receive(:getgrnam).and_raise(ArgumentError)
+      @provider.action = :create
       @provider.define_resource_requirements
       @provider.convert_group_name
       expect { @provider.process_resource_requirements }.to raise_error(Chef::Exceptions::User)
     end

+    it "does not raise an error if we can't translate the group name during resource assertions if we are removing the user" do
+      expect(Etc).to receive(:getgrnam).and_raise(ArgumentError)
+      @provider.action = :remove
+      @provider.define_resource_requirements
+      @provider.convert_group_name
+      expect { @provider.process_resource_requirements }.not_to raise_error
+    end
+
     it "should set the new resources gid to the integerized version if available" do
       expect(Etc).to receive(:getgrnam).with("999").and_return(@group)
       @provider.convert_group_name
```

**Comment by jaymzh** [comment]
Hey @cmluciano - we're waiting on you. :)

**Comment by cmluciano** [comment]
Hey sorry for the delayed response. I will try to push up a commit this week with a few tests.

**Comment by btm** [comment]
:+1:

**Comment by jaymzh** [comment]
lgtm

**Pull request merged**
