### PR TITLE
make appveyor retry bundle install

### PR DESCRIPTION
**Pull request by lamont-granquist**
try it three times before giving up

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core @chef/client-engineers review

**Comment by btm** [comment]
hah :+1:

**Comment by lamont-granquist** [comment]
If appveyor fails on this one I'll be so annoyed...

**Comment by jdmundrawala** [comment]
:+1:

**Comment by jdmundrawala** [comment]
That is if batch supports `||`

**Comment by jaymzh** [comment]
fuckyes. Thank you. :+1:

**Comment by lamont-granquist** [comment]
lollolol, right so windows .bat language is probably about to troll me.... hah...

**Comment by jdmundrawala** [comment]
I think it'll work:
```
C:\Users\vagrant>foo || bar
'foo' is not recognized as an internal or external command,
operable program or batch file.
'bar' is not recognized as an internal or external command,
operable program or batch file.
```

```
C:\Users\vagrant>c:\Ruby200\bin\true.exe || foo

```

**Comment by lamont-granquist** [comment]
Cool, looks like the appveyor run actually had a retry as well...

**Comment by jdmundrawala** [comment]
:ship:

**Comment by tyler-ball** [comment]
:100:

**Pull request merged**
