### PR TITLE
disable tests on 32-bit

### PR DESCRIPTION
**Pull request by lamont-granquist**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
these tests use some of the same artifacts as this test:

https://github.com/chef/chef/blob/master/spec/functional/resource/package_spec.rb#L92

so can't run on 32-bit.

this should fix jenkins 32-bit

**Comment by jaym** [comment]
:+1: i'm ok with this

**Comment by lamont-granquist** [comment]
testing this on ubuntu 64-bit is a bit useless (although i validated that they still run), so just merging since i can't make jenkins any worse...

**Comment by jaym** [comment]
also agree with that unless there's a typo in the code i reviewd

**Pull request merged**
