### PR TITLE
Fix for Chef 13 upload reversion.

### PR DESCRIPTION
**Pull request by coderanger**
Refs https://github.com/chef/chef/issues/6044

### CODE REVIEW

**Comment by coderanger** [comment]
Ping @chef/client-core for high-priority review.

**Comment by coderanger** [comment]
@danielsdeleo That might be hard, the bug doesn't show up in regression-able form using Chef Zero since Zero automatically does some data massage to fix things I think.

**Comment by coderanger** [comment]
I can add some unit tests for it at least though :)

**Comment by coderanger** [comment]
Hmm, trying to work out how the unit tests for version-specific manifest stuff works, might need help from @thommay

**Comment by danielsdeleo** [comment]
Yeah, I'm 100% cool with unit tests for this one

**Comment by thommay** [comment]
I've added tests for both manifest types and fixed a buglet in Manifest v0 roundtripping.

**Pull request merged**
