### PR TITLE
Expand the list of acceptance tests

### PR DESCRIPTION
**Pull request by chefsalim**
Add more acceptance tests to the list we run in jenkins - change to run all the test suites.

@chef/client-core @sersut @patrick-wright

### CODE REVIEW

**Comment by patrick-wright** [comment]
+1

**Comment by sersut** [comment]
Sweet! Does all four of the suites work with EC2?

**Comment by chefsalim** [comment]
@sersut yep!

**Comment by btm** [comment]
less is more? :+1:

**Pull request merged**
