### PR TITLE
Inspecting @node object to check the platform

### PR DESCRIPTION
**Pull request by NimishaS**

### CODE REVIEW

**Comment by coderanger** [comment]
This kind of magic needs a lot more justification and a loooot more tests. We already expose `Chef.node` as a global if we wanted to break encapsulation that far, but since a bunch of config stuff is used before the node object exists (let alone ohai running) this seems like it will produce temporary inconcsistent results.

**Comment by NimishaS** [comment]
@coderanger , we are trying to fix https://github.com/chef/chef/issues/5771.

There's already a PR https://github.com/chef/chef/pull/6030 for which Appveyor is failing. I created this PR mainly for debugging the issue.

**Comment by coderanger** [comment]
Probably use the chefclass global then, that has a much more defined life cycle.

**Comment by coderanger** [comment]
And I think we need to at least revisit this given we're adding the Chef sugar APIs to core which use only Ohai data, probably table this whole thing until Lamont is back?

**Comment by NimishaS** [comment]
Fixed the Appveyor issue in #6030. Closing this PR.

**Pull request closed without merging**
