### PR TITLE
fix some UselessAssignment cases

### PR DESCRIPTION
**Pull request by lamont-granquist**
some UselessAssignments identified by chefstyle

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core i'm going to break this up and could use some eyeballs.  pay particular attention to the knife subcommand loader one.

**Comment by lamont-granquist** [comment]
travis may fail, seeing some really weird spec failures locally...

**Comment by danielsdeleo** [comment]
:+1: I don't get why there's some and/or stuff straggling but the changes aren't wrong so NBD.

**Comment by lamont-granquist** [comment]
yeah, its my editor config, long story...

**Comment by lamont-granquist** [comment]
whoah reaction emojis directly on the messages...

**Pull request merged**
