### PR TITLE
Chefspec 5.0 is out. Remove fetching from git master

### PR DESCRIPTION
**Pull request by tas50**
Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
needs a `rake dependencies:update_gemfile_lock` i think

**Comment by tas50** [comment]
Trying to run that now. For some reason the depsolving has been taking 100% of a core for the last 45 minutes

**Comment by lamont-granquist** [comment]
recompiling nokogiri and dep-selector-libgecode?   it should only take a minute or two if those gems are already installed...

**Comment by jkeiser** [comment]
I think it was due to the recentness of the chef-provisioning / chef-provisioning-aws 2.0 releases (it was trying to bring in chef-zero 2.0 and failing because those want lower ones).

**Comment by jkeiser** [comment]
:+1:

**Comment by tas50** [comment]
With poise-boiler released this now passed

**Pull request merged**
