### PR TITLE
Allow people to pass in a 'source' to package rules

### LINKED ISSUE #3008: package resource fails to install local package specified with source attribute
Trying to install a local package with `package` resource and `source` attribute fails with `No candidate version available for ...`

Version 12.0.3 works fine. 12.1.0 does not.

### PR DESCRIPTION
**Pull request by jaymzh**
Fixes #3008

### CODE REVIEW

**Comment by jaymzh** [comment]
@lamont-granquist seem sane?

**Comment by lamont-granquist** [comment]
Seems sane and understandable to me.  Not certain how that broke, but probably some crazy side effect of some of the state somewhere, so this is better anyway.

I think I'm going to work on a func test for this.

**Comment by jaymzh** [comment]
Fucking appveyor. It's always broken.

**Comment by jdmundrawala** [comment]
All you had to do was curse at it...

**Comment by jaymzh** [comment]
github needs a like button for comments :)

**Comment by lamont-granquist** [comment]
:+1:

**Comment by ranjib** [comment]
:+1:

**Comment by jaymzh** [comment]
Woot. The 'milestone' here will be enough to get this cherry-picked, right @lamont-granquist  ?

**Comment by jdmundrawala** [comment]
We will take care of it

**Pull request merged**
