### PR TITLE
Add an 's' for quantity of 0 cookbooks.

### PR DESCRIPTION
**Pull request by anoadragon453**
### Description

Uploaded 0 cookbook. -> Uploaded 0 cookbooks.

Obvious fix.

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco> (due to 'Obvious fix')

### CODE REVIEW

**Comment by coderanger** [comment]
`==1 || >1` == `!= 1`.

**Comment by anoadragon453** [comment]
Changed to `upload_ok == 1 ? "" : "s"` for better readability.

**Comment by stevendanna** [comment]
@anoadragon453 Are you sure you pushed the commit you intended?  For github it is still showing up with the `upload_ok == 0 || upload_ok > 1` version.

**Comment by anoadragon453** [comment]
@stevendanna Whoops. Helps to actually `git add` things. That's what I get for running commands at 2 in the morning. Fixed now, thanks!

**Pull request merged**
