### PR TITLE
formally deprecate run_command

### LINKED ISSUE #3014: Deprecate Chef::Mixin::Command
We need to mark `Chef::Mixin::Command` with either `Chef::Log.deprecation` or `Chef::Mixin::Deprecation`.  While doing that, we need to remove all internal uses of it (but not remove it from `Provider` because that changes the public API).  Then we can remove the class entirely for 13.0.0

Source: https://github.com/chef/chef/pull/3012

### PR DESCRIPTION
**Pull request by lamont-granquist**
closes #3014

also improves the groupadd provider a bit

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core fairly simple reviewage

**Comment by tduffield** [comment]
Hey! This PR has broken about half of our tests in Jenkins :) We should look into fixing that!

**Comment by lamont-granquist** [comment]
i suspect the next three PRs fix that.

**Comment by lamont-granquist** [comment]
i need reviewage on #5674 and #5676 and after those are merged that'll clean up the rest of the uses of run_command i could find.

**Pull request merged**
