### PR TITLE
[Chef-18]Update all the dependencies as inspec-core update is getting blocked due to multiple gem dependencies

### PR DESCRIPTION
**Pull request by neha-p6**
## Description

This is to specifically bump `inspec-core` to `5.22.58`
`bundle update inspec-core --conservative` fails with `Bundler attempted to update inspec-core but its version stayed the same`. It seems to have interlocking dependencies hence doing an entire dependency update by running `rake dependencies:update_gemfile_lock` which runs `bundle lock --update --add-platform ruby x64-mingw-ucrt`

Also pull in latest `license_scout` in omnibus/Gemfile.lock as `cheffish` adds new dependency for gem `logger` which added to license_scout for license verification.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Review by tpowell-progress — CHANGES_REQUESTED** [review]
@neha-p6 can you rebase on `chef-18` and also capture your `bundle install` output? I know you mentioned having to allow a bunch of updates, just want to capture how those were introduced.

**Comment by neha-p6** [comment]
> @neha-p6 can you rebase on `chef-18` and also capture your `bundle install` output? I know you mentioned having to allow a bunch of updates, just want to capture how those were introduced.

@tpowell-progress I'm running `rake dependencies:update_gemfile_lock` which eventually does
`bundle lock --update --add-platform ruby x64-mingw-ucrt`

**Comment by neha-p6** [comment]
https://buildkite.com/chef/chef-chef-chef-18-validate-adhoc/builds/100

**Comment by neha-p6** [comment]
Latest adhoc buuild https://buildkite.com/chef/chef-chef-chef-18-validate-adhoc/builds/105

**Review by tpowell-progress — APPROVED** [review]

**Pull request merged**
