### PR TITLE
knife client create should check file permissions

### PR DESCRIPTION
**Pull request by snehaldwivedi**
## Description
Support user-friendly error checking on file permissions for `knife client create`
`knife user create` is already covered in [PR](https://github.com/chef/chef/pull/10187)

## Related Issue
https://github.com/chef/chef/issues/3514
https://github.com/chef/chef/issues/3517

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by phiggins** [comment]
This failing windows unit test looks related:

```
  1) Chef::Knife::ClientCreate run when clientname is passed with -f or --file should write the private key to a file
     Got 1 failure and 1 other error:
 
     1.1) Failure/Error: expect(filehandle).to receive(:print).with("woot")
 
            (Double "Filehandle").print("woot")
                expected: 1 time with arguments: ("woot")
                received: 0 times
          # ./spec/unit/knife/client_create_spec.rb:127:in `block (5 levels) in <top (required)>'
          # ./spec/spec_helper.rb:304:in `block (2 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # SystemExit:
          #   exit
          #   ./lib/chef/knife/client_create.rb:89:in `exit'
 
     1.2) Failure/Error: knife.run
 
          UnexpectedSystemExit:
            exit
          # ./lib/chef/knife/client_create.rb:89:in `exit'
          # ./lib/chef/knife/client_create.rb:89:in `run'
          # ./spec/unit/knife/client_create_spec.rb:129:in `block (5 levels) in <top (required)>'
          # ./spec/spec_helper.rb:304:in `block (2 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # SystemExit:
          #   exit
          #   ./lib/chef/knife/client_create.rb:89:in `exit'
```

https://buildkite.com/chef-oss/chef-chef-master-verify/builds/6073#1fc23a03-85f3-4c49-bb00-d6d434a32d4f/352-1282

**Comment by tas50** [comment]
@snehaldwivedi Should this PR contain all 10 commits?

**Comment by snehaldwivedi** [comment]
> @snehaldwivedi Should this PR contain all 10 commits?

@tas50 No it contain only https://github.com/chef/chef/issues/3514, I have created this branch by https://github.com/chef/chef/pull/10187 as I required code of it. [PR](https://github.com/chef/chef/pull/10187) is the base PR for merge part.

**Comment by snehaldwivedi** [comment]
@tas50 Can you please have a look into the PR for merge or if any more changes required form my side?

**Comment by phiggins** [comment]
@tas50 I think this PR builds off of #10187 and includes all the commits from that PR.

**Comment by tas50** [comment]
Yes we have 3 PRs in flight that are all working on the same code and it's very hard to track what we're trying to achieve with that. These should really all get closed at this point and the work should back to knife-opc. Get that clean. Figure out how to interact with these server objects without creating a large abstraction layer and then we can create a plan to move that into the client.

**Comment by snehaldwivedi** [comment]
@lamont-granquist Most of the part of card #3517 [](https://github.com/chef/chef/issues/3517) was already covered in PR [#10187](https://github.com/chef/chef/pull/10187). This PR covers one of the remeaning sections [#3514](https://github.com/chef/chef/issues/3514).

Please have a look at it.

**Comment by marcparadise** [comment]
Could you refresh this so that it contains only the changes from d3b1d51 and 
bcef863 ? It might be best to start a new branch and cherry-pick or re-apply the changes.

**Comment by snehaldwivedi** [comment]
@marcparadise I have created a new PR with required changes for this card [here](https://github.com/chef/chef/pull/11241), so closing this PR

**Pull request closed without merging**
