### PR TITLE
Add RHEL 8 (aarch64) Tester to Chef 16

### PR DESCRIPTION
**Pull request by christopher-snapp**
## Description
This PR adds the RHEL 8 (aarch64) Tester to Chef 16

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by christopher-snapp** [comment]
Here's an adhoc build for verification:

https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/198

**Comment by christopher-snapp** [comment]
So we now have buildkite capable of launching aarch64 instances which allowed the new `el-8-aarch64` tester to run:

https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/206

Unfortunately, that tester failed on what seems to be a valid issue in chef-infra.

@tas50 could you take a quick look at that tester failure to verify that it *shouldn't* block this PR from being merged?

**Comment by tas50** [comment]
@lamont-granquist it looks like all the dnf tests are going to need to be updated. They are hard coded to use filenames for x86 and this is failing on aarch.

**Comment by lamont-granquist** [comment]
closed via #9500

**Pull request closed without merging**
