### PR TITLE
Bootstrap debugging shows the commands you're running

### PR DESCRIPTION
**Pull request by pburkholder**
Make bootstrap debugging more useful

### CODE REVIEW

**Comment by pburkholder** [comment]
This would have saved me about an hour, maybe two, of head-scratching today.

**Comment by coderanger** [comment]
Should probably be put somewhere that will work the same with Windows bootstraps.

**Comment by pburkholder** [comment]
@coderanger I put in this PR to knife-windows: https://github.com/chef/knife-windows/pull/264

**Comment by mcquin** [comment]
LGTM

**Comment by coderanger** [comment]
Hmm, upon further reading I'm :-1: because if a sudo password is given, it will be shown unredacted. That seems like a footgun we shouldn't add.

**Comment by pburkholder** [comment]
@coderanger  Good point! I moved the debug to before we inject the sudo password. Thanks for catching that.

**Comment by lamont-granquist** [comment]
@coderanger you :+1: now?

i'm :+1:

**Comment by thommay** [comment]
yep, :+1: now that the password's not shown.

**Comment by coderanger** [comment]
I think this will still show unredacted versions of the client and validation keys, and probably the data bag secret? Makes me nervous :-/

**Comment by lamont-granquist** [comment]
Just the paths to them i think?

**Comment by lamont-granquist** [comment]
Oh right, we render the whole template as the awful shell command and it shows up in ps and everything terrible, dup of other bugs we have against it.

**Comment by thommay** [comment]
Sorry Peter, I think on balance we're not going to take this (or a moral equivalent thereof) until after we clean up `knife bootstrap` fully and make it safe.

**Comment by pburkholder** [comment]
Thanks Thom for getting back to me. I couldn't see a way to make it 'clean'
either at this juncture.

On Tue, Sep 15, 2015 at 2:01 PM, Thom May <notifications@github.com> wrote:

> Closed #3662 <https://github.com/chef/chef/pull/3662>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef/chef/pull/3662#event-410093568>.
>



-- 

*Peter Burkholder* — Customer Success Engineer

Unavailability: 4 August - 27 August -- OOO for Vacation/Conferences

301-204-5767 – pburkholder@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/pburkholder>  Twitter
<http://www.twitter.com/pburkholder>  Cal
<https://www.google.com/calendar/embed?src=pburkholder%40chef.io&mode=WEEK>
endar

*CHEF*

CHEF.IO <http://www.chef.io/>

TM

*chef.io* <http://www.chef.io/>   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>

**Pull request closed without merging**
