### PR TITLE
Update registry_key.rb

### PR DESCRIPTION
**Pull request by veetow**
Fixing typo?

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @veetow

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by btm** [comment]
looks correct, but clearly we need some unit tests in there.

**Comment by lamont-granquist** [comment]
Obvious fix.

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Pull request merged**
