### PR TITLE
Adding João Cravo to the list of Chef Provisioning maintainers.

### PR DESCRIPTION
**Pull request by joaogbcravo**

### CODE REVIEW

**Comment by tyler-ball** [comment]
Hey @joaogbcravo - thanks for this PR!  Can you re-run `bundle exec rake maintainers:generate` to update the .md file?  The toml looks great

**Comment by joaogbcravo** [comment]
I did that, I changed the toml file and then generate the MD one... 

What's got wrong?

**Comment by thommay** [comment]
:+1: LGTM

**Comment by thommay** [comment]
thanks @joaogbcravo

**Comment by tyler-ball** [comment]
:+1: 

Paging @chef/provisioning for some more maintainers!

**Comment by stuartpreston** [comment]
:+1:

**Pull request merged**
