### PR TITLE
Revert addition of x25519 gem to knife

### PR DESCRIPTION
**Pull request by lamont-granquist**

### CODE REVIEW

**Comment by tas50** [comment]
https://github.com/RubyCrypto/x25519/issues/22

**Comment by tarcieri** [comment]
FYI, the SIGILL errors should be fixed in `x25519` v1.0.9

**Comment by tas50** [comment]
Thanks @tarcieri !

**Comment by tas50** [comment]
Added back in https://github.com/chef/chef/pull/11903

**Pull request merged**
