### PR TITLE
Updating / fixing deps to fix acceptance

### PR DESCRIPTION
**Pull request by btm**

### CODE REVIEW

**Comment by btm** [comment]
Building in chef-build 152

**Comment by lamont-granquist** [comment]
you probably want to just leave bumping anything kitchen-tests out of it, that doesn't get used in the acceptance environment.

**Comment by lamont-granquist** [comment]
omnibus/Gemfile.lock should also be installed into the omnibus-toolchain ruby and not into /opt/chef so shouldn't be the source of any duplicated gems.  AFAIK only the root Gemfile.lock and acceptance/Gemfile.lock should need bumping to fix the issue.

**Comment by btm** [comment]
Well this is more correct, but doesn't appear to fix acceptance in manhattan still.

**Pull request merged**
