### PR TITLE
Fix backups on windows for the file resource

### PR DESCRIPTION
**Pull request by jdmundrawala**
The backup utility was using Dir.[], which on breaks with \ in
the path name. This code is replaces with listing the directory and
matching the correct files
Also, on windows, the creation part stripped the drive name, while the
part that searched for old backups did not.

This should solve #3394.

### CODE REVIEW

**Comment by jdmundrawala** [comment]
cc @chef/client-windows

**Comment by btm** [comment]
Add a regression test that uses backslashes in case someone tries to simplify that with Dir[]?

**Comment by jdmundrawala** [comment]
@btm modified the test and added a comment

**Comment by btm** [comment]
:+1: 

@chef/client-core this fixes a windows bug but is in core code. Need another thumb.

**Comment by danielsdeleo** [comment]
:+1: regression test is well written :stars:

**Comment by btm** [comment]
Rebased and merged to master.

**Pull request closed without merging**
