### PR TITLE
CHEF-4591: Knife commands to manipulate env_run_list on nodes

### PR DESCRIPTION
**Pull request by walbenzi**
Unit tests show that the following functions have been added: 

knife role env_run_list add ROLE ENV cookbook(s) (optional - :after)
knife role env_run_list clear ROLE ENV
knife role env_run_list remove ROLE ENV cookbook
knife role env_run_list replace ROLE ENV old_cookbook new_cookbook
knife role env_run_list set ROLE ENV cookbook(s)

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by walbenzi** [comment]
Sorry, When I did this, I had signed an agreement and it changed when I was not looking...

**Comment by lamont-granquist** [comment]
Can you rebase and squash commits?  I think we may be rejecting the should syntax now in ohai so all your spec tests may fail?  If I'm incorrect a rebase onto current master and squash would be useful so that we can see I'm wrong about that...

**Comment by lamont-granquist** [comment]
Oh my brain was still on ohai for some reason...  nevermind...

Still rebase and squash down to one commit would be useful for us.

**Comment by lamont-granquist** [comment]
Also, you can use the `transpec` gem to automate converting from rspec 2 to rspec 3 syntax -- you don't have to fix all that manually.

**Pull request closed without merging**
