### PR TITLE
fix rspec test to use rspec best practices

### PR DESCRIPTION
**Pull request by kmacgugan**
Addresses https://github.com/chef/chef/pull/3001/files#r25728843

### CODE REVIEW

**Comment by mcquin** [comment]
:100:

**Comment by ranjib** [comment]
:+1:

**Comment by jdmundrawala** [comment]
:+1:

**Comment by btm** [comment]
:+1: pending CI

**Comment by tyler-ball** [comment]
:+1:

**Comment by btm** [comment]
rebased and merged as  d75f48cda2839e96d2ee1de81aa9e08fddeae623

**Pull request closed without merging**
