### PR TITLE
Add Dockerfile to root

### PR DESCRIPTION
**Pull request by tduffield**
### Description

This Dockerfile will allow individuals, who wish to, to build Docker
images containing the latest Chef Client. Specifically, it can be used
inside testing frameworks like kitchen-dokken.

This Dockerfile will be used by internal Chef release engineering to
automatically post Docker images to the Docker Hub as part of our
standard artifact promotion pipeline.

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [x] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

Signed-off-by: Tom Duffield <tom@chef.io>

### CODE REVIEW

**Comment by someara** [comment]
Can we do something like this instead?

https://github.com/someara/chef-docker-images/blob/master/recipes/default.rb

^ That unpacks the EL5 build (the oldest glibc) and shoves it into an image from SCRATCH.

That's how I built chef/chef in the past.

**Comment by someara** [comment]
The Dockerfile in the PR won't work with dokken, and will only be useful for bind mounting on Ubuntu 16.04

**Comment by tduffield** [comment]
Why won't it work with dokken?

**Comment by tduffield** [comment]
The reason we did it this way is that it works natively with Docker. Anyone could pull it down and build their own Chef image.

**Comment by someara** [comment]
For a Chef container to be useful, it needs to be bind mounted by other containers.
It's missing two critical lines:

```
ADD opt /opt
VOLUME [ '/opt/chef' ]
```

Even if those were present, the resulting bits are built against the glibc that ships with Xenial.
If you were to try and run it from a Trusty image it'd explode.

**Comment by someara** [comment]
If only we had some sort of packaging technology we could use to describe dependencies and yield sparse images.... *rubs chin*

**Comment by tduffield** [comment]
Hmm, I'll have to think about this. The pipeline we have right now won't really support the chef recipe.

**Comment by someara** [comment]
You don't have to use the Chef recipe... that was for my own convenience.

The technique used by the Chef recipe is the important bit: 
1) Unpack the EL5 archive
2) shove into a container from scratch
3) expose `/opt/chef`

-s

**Comment by tduffield** [comment]
Right, the pipeline we have won't support that stuff. It's pretty simplistic. It just runs Dockerfiles.

**Comment by tduffield** [comment]
@someara what if we did this process, but on centos:5?

**Comment by tduffield** [comment]
I mean, we'd be shipping centos:5 (which isn't super optimized) but would it fix the "works with dokken" issue?

**Comment by someara** [comment]
I'll have to test it out... 

```
someara/chef  latest              db4fa58c4d18        5 weeks ago         150.2 MB
centos              5                    1ae98b2c895d        11 weeks ago        284.7 MB
```

**Comment by someara** [comment]
I'll have to test it out...  The overhead is pretty large. This would almost triple the pull time for CI systems.

```
someara/chef  latest              db4fa58c4d18        5 weeks ago         150.2 MB
centos              5                    1ae98b2c895d        11 weeks ago        284.7 MB
```

**Comment by someara** [comment]
I think the better thing to do would be to augment the build pipeline to have it spit out the optimized versions to Dockerhub as well as Omnitruck. I can't think of a way to have the Dockerhub automated build thing use FROM SCRATCH without shipping a copy of the RPM in the source repo

**Comment by tduffield** [comment]
@someara the first pull would be a little longer, sure. But subsequent builds _should_ only pull down the latest layer which should be the same size as your from scratch. Also, something is better than nothing, and right now there's nothing. If people are concerned about download time / image size they can continue to use alternatives, but I think the opportunity to have the latest packages readily available automatically provides great value. Once we have something then we can work on optimizing.

**Comment by someara** [comment]
Also, Dockerhub is going to build on each mater commit pushed to Github, so unless you already have the archive available at packages.chef.io, it'll fail to fetch it.

**Comment by someara** [comment]
True. Warm caches are nice. However, you don't get them on Travis and friends.

**Comment by tduffield** [comment]
We won't be using the automated builds from Docker Hub. We're using an internal build system that is triggered by events in artifactory. That build system, at the moment, isn't built to support the "from scratch" method you've mentioned. It would require work, which I'm not against doing, but at the moment I'd rather hook this up to that build system and move from there rather than continue to have nothing while we go back and pretty much rewrite the build system from scratch.

**Comment by someara** [comment]
PS: kitchen-dokken will continue to use the optimized version published at `someara/chef`

**Comment by tduffield** [comment]
That's fine. This is simply an alternative.

**Comment by tduffield** [comment]
FWIW I ran through a series of kitchen-dokken tests using the wheezy-slim image, one of those tests being centos:5, and Chef ran just fine :)

**Comment by someara** [comment]
I just did a quick spot check by against the httpd cookbook's config suites.

It works on all platforms except EL5.

```
/opt/chef/embedded/bin/ruby: /lib64/libc.so.6: version `GLIBC_2.8' not found (required by /opt/chef/embedded/lib/libruby.so.2.3)
/opt/chef/embedded/bin/ruby: /lib64/libc.so.6: version `GLIBC_2.6' not found (required by /opt/chef/embedded/lib/libruby.so.2.3)
/opt/chef/embedded/bin/ruby: /lib64/libc.so.6: version `GLIBC_2.9' not found (required by /opt/chef/embedded/lib/libruby.so.2.3)
```

**Comment by tduffield** [comment]
@someara I _think_ that should work. Can you confirm?

**Comment by tduffield** [comment]
I've built a test image using this Dockerfile. If you want to test it, you can use `tduffield/chef:test1`.

**Comment by btm** [comment]
I have no docker opinions. 👍 on whatever others want to do.

**Pull request merged**
