### PR TITLE
Also clear notifications when deleting a resource.

### PR DESCRIPTION
**Pull request by coderanger**
/cc @lamont-granquist @jkeiser @thommay 

This implements https://github.com/thommay/chef-rewind/commit/b69c9a510f1e7a85132dff0ee26fd883192ea12d for the new fancy API.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
dangling references are clearly bad...

👍

**Comment by coderanger** [comment]
I'm trying to think through what kind of weirdness could exist with nested contexts any notifications in a different run_context. Also this could still leave dangling `subscribes` I think?

**Comment by thommay** [comment]
Sweet, thanks!

**Comment by lamont-granquist** [comment]
The way i wrote the nested contexts notification stuff, at least for delayed notifies it should only queue up on the run_context that contains the resource.

**Pull request merged**
