### PR TITLE
Don't crash if the node has no tags set

### PR DESCRIPTION
**Pull request by thommay**
cc @chef/client-core

### CODE REVIEW

**Comment by lamont-granquist** [comment]
i thought we fixed this so that tags were always an array?

**Comment by thommay** [comment]
There are nodes in one of my hosted orgs that cause us to crash. So we should probably nail down where this isn't happening, but do we want to take this as well?

**Comment by danielsdeleo** [comment]
:\ https://github.com/chef/chef/blob/b60ad97446c064c71e5e1b03b94344eb0b5c136d/lib/chef/node.rb#L373-L377

**Comment by lamont-granquist** [comment]
am i missing the edge condition there?  although that could have been `normal_unless[:tags] = []` to use the correct API that was written and tested for that case...

**Comment by coderanger** [comment]
`attribute?` is (eventually) an alias for `has_key?` so if you had `{"tags": null}` in your node data it would fail.

**Comment by coderanger** [comment]
Or `{"tags": {}}`, but that seems less likely to have happened.

**Comment by lamont-granquist** [comment]
okay and previously that was perfectly legal and likely common...

**Comment by lamont-granquist** [comment]
^ fixed that issue in Chef::Node and an identical issue in set_unless in #4309

**Comment by lamont-granquist** [comment]
We should probably close this one now?

**Pull request closed without merging**
