### PR TITLE
[knife] Deprecate data bag secret (-s) short option due to conflict with --server-url option

### PR DESCRIPTION
**Pull request by vsingh-msys**
## Description

For `knife data bag` subcommands `-s` have different behavior for different subcommands.
1. `-s` refers  to as `--secret SECRET` for the following:
  - knife data bag create 
  - knife data bag edit
  - knife data bag show
  - knife data bag from file

2. `-s` refers to as `--chef-server-rul URL` for the following:
  - knife data bag delete
  - knife data bag list
 
Seems both `--server-url` and `--secret` has short option `-s` and mixlib-cli override the first one.
https://github.com/chef/chef/blob/cc6c31616126c38d93dafd1f0475ac3ae5815a65/lib/chef/application/knife.rb#L95-L98

https://github.com/chef/chef/blob/cc6c31616126c38d93dafd1f0475ac3ae5815a65/lib/chef/knife/data_bag_secret_options.rb#L37-L43

Also, some other subcommands like `knife bootstrap` included both helpers so `-s` refers to as `--secret`.

## Related Issue

https://github.com/chef/chef/issues/8647

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

### CODE REVIEW

**Comment by vsingh-msys** [comment]
One more issue related to this PR https://github.com/chef/chef/issues/4647

**Comment by lamont-granquist** [comment]
concern that i've got is if this is a breaking change for anyone that figured out how it worked the old way

**Comment by vsingh-msys** [comment]
Thant's true it breaking change.
At this stage, we can think of 
1. Deprecate the `-s` short option for data bag `secret`.
2. Remove the `-s` short option in major release version.

Let me know your thoughts on this @lamont-granquist  accordingly I will update the PR?

Thanks!

**Comment by vsingh-msys** [comment]
Added deprecation warning to data bag secret short option (-s) only if it's set. It will be removed in a future version.

**Comment by vsingh-msys** [comment]
@lamont-granquist & @tas50 any feedback after the latest changes?

**Comment by tas50** [comment]
Thanks @vsingh-msys

**Pull request merged**
