### PR TITLE
Update libxml2 and nokogiri to the latest

### PR DESCRIPTION
**Pull request by tas50**
This resolves multiple CVEs while still working on Windows

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/592#b4e8f633-38d1-4c0b-8d8d-de2208192e6d

**Comment by lamont-granquist** [comment]
My guess is that:

```
                          D | 2021-07-15T03:10:27+00:00 | checking for xml2-config... /opt/chef/embedded/bin/xml2-config
```

libxslt is now hitting that binary helper and something is wonky with that, and we probably need a flag to configure in libxslt to tell it to trust the flags we give it and not bother with that.

**Comment by tas50** [comment]
https://buildkite.com/chef/chef-chef-main-omnibus-release/builds/1469#725ccbed-17a2-4611-80c1-8d6f516a71b2

**Comment by lamont-granquist** [comment]
that was still red

**Comment by lamont-granquist** [comment]
gonna close this for now, still needs to get done, but probably in another PR, certainly before chef-18 release.

**Pull request closed without merging**
