### PR TITLE
Backport quiet feature

### PR DESCRIPTION
**Pull request by jasonwbarnett**
Backporting #7194 into Chef 13.

Literally just cherry-picked @coderanger commit from master

### CODE REVIEW

**Comment by coderanger** [comment]
Unlike the other core devs, I don't get paid to work on Chef, so I also am not signing up to support this. You will have to be on the hook for this permanently (or at least until Chef 13 goes EOL).

**Comment by jasonwbarnett** [comment]
I can commit to supporting this feature until April of 2019, but I don't feel strongly about this getting merged in because I realized I can easily monkey patch this functionality in a cookbook library.

**Comment by thommay** [comment]
Thanks for the PR;  we're only updating 13 for serious issues and security fixes, so I'm going to say that this isn't suitable for merge (that doesn't reflect on the value of the feature or on your request, we're just trying to be really clear about how our release cycle works).

**Comment by jasonwbarnett** [comment]
@thommay completely makes sense. Thanks for getting back and explaining the why.

**Pull request closed without merging**
