### PR TITLE
Launchd should not load launchagents as root. 

### PR DESCRIPTION
**Pull request by mikedodge04**
The Launchd resource will load launchagents as root when the mac is sitting on the login window. This is never a desired outcome and is hard to recover from. This change now will now check to see if a user is logged in before loading launchagents.

### CODE REVIEW

**Comment by mikedodge04** [comment]
@lamont-granquist when you get a chance can you take a look at this?

**Comment by lamont-granquist** [comment]
you should really rebase on top of master instead of pulling a merge commit into your branch.

**Comment by lamont-granquist** [comment]
shouldn't this throw an exception rather than swallowing the error and emitting a debug notice?

**Comment by mikedodge04** [comment]
Sorry I missed the email about this PR, I thought it was merged with the others I had up at the time. 

>shouldn't this throw an exception rather than swallowing the error and emitting a debug notice?

No. Apples docs aren't clear about this. But when a mac is sitting at the login window, the console user is root. If chef were to run it will load any managed LaunchAgents as root. But root doesn't have access to the Aqua session and is unable to launch gul applications. Any LaunchAgent can only be loaded once, so the user will never have it loaded for them.

**Comment by thommay** [comment]
@mikedodge04 you'll need to appease `chefstyle` but besides that I think this is a great change, thanks.

**Comment by mikedodge04** [comment]
@thommay passes chef style now.

**Comment by tas50** [comment]
@mikedodge04 Thanks for the lint update, but we're still seeing failures in AppVeyor. The specs are blowing up on Windows when it looks for /dev/console.

**Comment by tas50** [comment]
Also any chance you can squash this down to a single commit so we avoid the merges in history?

**Comment by lamont-granquist** [comment]
yeah unit tests need to get mocked correctly, can't get merged until those are fixed.

  i wonder if the squash + merge strategy on github could handle this PR or not...

**Pull request closed without merging**
