### PR TITLE
Update acceptance deps to the latest

### PR DESCRIPTION
**Pull request by tas50**
Silence a security warning from Github even though we're not using these

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
`git rm acceptance` instead?

**Comment by tas50** [comment]
I was pretty tempted to do that, but I think we should wait until we have an idea what to replace it with a

**Comment by lamont-granquist** [comment]
if anyone does that, they can always go back and find that info in git history...

**Comment by tas50** [comment]
PR incoming then

**Pull request closed without merging**
