### PR TITLE
Loosening up some gem dependencies so there are not conflicts in chef-dk

### PR DESCRIPTION
**Pull request by tyler-ball**
This should fix our chef-dk build issues on Windows

\cc @jdmundrawala @fnichol @danielsdeleo

### CODE REVIEW

**Comment by danielsdeleo** [comment]
:+1:

**Comment by fnichol** [comment]
Excellent!

**Comment by jdmundrawala** [comment]
:+1: Any idea why this fixes things?

**Comment by danielsdeleo** [comment]
@jdmundrawala https://github.com/chef/mixlib-shellout/blob/master/mixlib-shellout-x86-mingw32.gemspec has looser constraints, so if you activate mixlib-shellout first and you don't have dependencies properly in your gemspec for rubygems to know you might require chef later, it activates newer versions of those gems and then blows up when you require chef.

**Pull request merged**
