### PR TITLE
bump timeout up to 300 seconds

### PR DESCRIPTION
**Pull request by lamont-granquist**
seems to fix the timeouts on the exceedingly slow sparc boxes in CI

### CODE REVIEW

**Comment by lamont-granquist** [comment]
This basically lets the tests run as long as they need to.  Since it raises now we can be certain that if it works we are never hitting this timeout.  If it takes longer than 300 seconds something is wrong, it will go red, and someone should fix it -- we won't start silently leaking 5 minutes of time into all our test runs.  On our sparc boxes 30 seconds is too short (which is overall a problem, and I suspect that in the port to manhattan we lost some tuning that was done to the old-ci sparc boxen, but we have visibility into that simply via the whole test phases taking over an hour to run on sparc).

**Comment by lamont-granquist** [comment]
Yep, so the sparc cores that we've got just suck that badly and we're single threaded so we're gonna have to suck it.  We're CPU bound on a single core on a server that has like 100 of them.  This is the right patch and there's nothing else to be done...

*le sigh*

**Comment by lamont-granquist** [comment]
@client-core review and weep...

**Comment by danielsdeleo** [comment]
ugh. This is okay to merge but I can't make myself give it the thumbs up emoji.

**Comment by lamont-granquist** [comment]
appveyor fail is unrelated...

**Pull request merged**
