### PR TITLE
I think this was a bad search-and-replace, causes an infinite loop.

### PR DESCRIPTION
**Pull request by coderanger**
https://github.com/chef/chef/issues/3969 has the debugging stream of thought for this.

Ping @chef/client-core (and @jkeiser in particular) for review, but going to merge this ASAP so builds aren't broken over the weekend.

### CODE REVIEW

**Comment by coderanger** [comment]
Original change was earlier today in https://github.com/chef/chef/commit/424b2dda9b4a2a0ca3e7ca8c9a598643b303ec0f

**Comment by ranjib** [comment]
:+1:  :-(

**Comment by danielsdeleo** [comment]
o_O :+1:

**Comment by jkeiser** [comment]
Wow ... how in the world did the build not go immediately red

**Comment by coderanger** [comment]
@jkeiser Guessing the unit tests for deprecation stuff might either have a custom handler or run with formatters disabled? Definitely points to some missing unit tests :)

**Pull request merged**
