### PR TITLE
Add allowed_actions for each package type

### PR DESCRIPTION
**Pull request by gene1wood**
## Description

This will override the allowed_actions setting in the inherited package resource so that the allowed_actions reflects the actual supported actions of each package type.

This should enable a better error message from Chef when an unsupported action is called for a given package type as well as enabling the correct automatic generation of Chef documentation for each package type, listing the actual supported actions (instead of all actions). Currently this difference between the rake generated documentation and the real action list is hand corrected after rake generates it as mentioned in #13123. This should remove the need for that.

The allowed_actions for each package in this commit is derived from the methods supported by each of the associated Chef providers for each package resource.

## Related Issue

#13123

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by gene1wood** [comment]
Looks like some of these test failures are due to an invalid `tar` file being created?

```
 -----> Extracting chef from https://github.com/chef/chef/archive/af2813a5fe1ce014967ad7833075ac5bf831b8d4.tar.gz
       Unknown tar entry: pax_global_header type: g.
````

**Comment by gene1wood** [comment]
I force pushed a new commit with the current head of main incorporated (also to trigger a re-run of the tests to see if those test problems are resolved)

**Comment by johnmccrae** [comment]
@gene1wood can you rebase this to main? I think all these errors are corrected now

**Comment by tpowell-progress** [comment]
@gene1wood Now that GA has been released, can you please rebase so that we can confirm that tests still pass with these changes?

**Comment by gene1wood** [comment]
@tpowell-progress Sure thing, I've rebased and all tests are passing.

I'd still love it if someone at Chef could validate that my read on the source of this problem is correct and this is the correct approach to fix it. Any feedback would be welcome.

**Comment by gene1wood** [comment]
@tpowell-progress You may want to clear the `Status: Waiting on Contributor` label.

**Review by johnmccrae — APPROVED** [review]

**Pull request merged**
