### PR TITLE
deal with 0.37.2 renamed cops

### PR DESCRIPTION
**Pull request by lamont-granquist**
```
252  Style/TrailingCommaInLiteral
84   Style/TrailingCommaInArguments
15   Style/SpaceAroundKeyword
--
351  Total
```

We already dealt with SpaceAroundKeyword under its old name
SpaceBeforeModifierKeyword, it looks like it got stricter about
spaces after keywords.

TrailingComma also got split, and it looks like the
TrailingCommaInArguments behavior is new?

### CODE REVIEW

**Comment by lamont-granquist** [comment]
See https://github.com/chef/chefstyle/pull/22/files, this is just fallout from upgrading rubocop in chefstyle from 0.35.x to 0.37.x

**Comment by lamont-granquist** [comment]
i wonder if there's a style so that if there's only one thing it'll accept omitting the comma...

i'd prefer this to the alternative though...

**Comment by lamont-granquist** [comment]
@danielsdeleo thoughts?  i'm leaning towards TrailingCommaInArguments not adding a comma for multiline since it looks really odd in a lot of cases...

**Comment by thommay** [comment]
yeah, that looks really terrible, and it's totally going to annoy everyone.

**Comment by lamont-granquist** [comment]
just skimming the first few, this looks a hell of a lot better...

**Comment by lamont-granquist** [comment]
@danielsdeleo and @thommay this look okay?

**Comment by danielsdeleo** [comment]
I really hated the trailing comma in arguments. Array literals and argument lists are used very differently. I won't shed a tear.

:+1:

**Pull request merged**
