### PR TITLE
explicitly adding .bat to service executable called by service in cae users remove .bat from PATHEXT

### PR DESCRIPTION
**Pull request by mwrock**

### CODE REVIEW

**Comment by mwrock** [comment]
I also removed a `\` from the wix which is harmless but creates 2 backslashes in the service executable and looks weird

**Comment by danielsdeleo** [comment]
:+1:

**Comment by pburkholder** [comment]
Thanks for the quick fix, @mwrock !

**Comment by randomcamel** [comment]
:+1:

**Pull request merged**
