### PR TITLE
Dist windows powershell wrapper

### PR DESCRIPTION
**Pull request by bobchaos**
## Description
More work towards https://github.com/chef/chef/issues/8376 this one addresses the windows powershell extensions by templating the psm1 file and having Rake render it during builds. It also sneaks in a chef-apply distro constant for immediate use in the extensions.

## Related Issue
https://github.com/chef/chef/issues/8376

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] I have run the pre-merge tests locally and they pass.
- [NA] I have updated the documentation accordingly.
- [NA] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by bobchaos** [comment]
I'll fix that failure, likely tomorrow. Looks like the target folder for the template doesn't exist, because git doesn't pick it up thinking it's empty now that the only file that would be there is gitignored. I've got that folder locally, so my tests went through fine. I'll look into either adding a dummy file or making Rake create the folder structure.

**Comment by bobchaos** [comment]
The Rake job will now create the folder structure. This should be ready for review

**Comment by lamont-granquist** [comment]
you should probably unsneak the chef-apply stuff since that can definitely go, the other stuff i have no idea about, but tim seems to have some concerns

**Comment by bobchaos** [comment]
@tas50 I understand you had worries about the approach I'm proposing? How can I make this awesome?

**Comment by bobchaos** [comment]
as discussed during triage, I added a commit to properly remove the original file prior to gitignoring it,

**Pull request merged**
