### PR TITLE
Don't mask directory deletion errors

### LINKED ISSUE #4988: Recursive directory failure ignores failure
## Description

when deleting a directory using the `directory` resources, if `recursive` is set, chef does:

```
FileUtils.rm_rf(@new_resource.path)
```

Which ignores all errors, which means if this fails Chef falsely reports success.

Instead Chef should use ```FileUtils.rm_r(@new_resource.path)``` and catch errors.

You can simulate this by `mkdir -p /tmp/bananas; chattr +i /tmp/bananas` and then removing it with Chef. It'll fail but Chef will say it succeeded leading to unpredictable results later in the run. This is bad news bears.

## Chef Version

12.6.0

## Platform Version

CentOS 6 & 7

## Replication Case

mkdir -p /tmp/bananas
chattr +i /tmp/bananas
Run chef with `directory '/tmp/bananas' do action :delete, recursive true end`
notice /tmp/bananas is still there.

### PR DESCRIPTION
**Pull request by jaymzh**
closes #4988

### CODE REVIEW

**Comment by jaymzh** [comment]
CC @chef/client-core

**Comment by lamont-granquist** [comment]
yeah, that makes sense :+1:

**Comment by thommay** [comment]
seems good 👍

**Comment by btm** [comment]
Can you add a regression unit test to make sure we don't revert back and fix the existing copy-pasta on line 230 of the unit test while you're in there?


```
  describe "#run_action(:create)" do
    describe "when the directory exists" do
      it "deletes the directory" do
        directory.run_action(:delete)
        expect(File.exist?(tmp_dir)).to be false
      end
```

**Comment by jaymzh** [comment]
The typo is easy - but I have no idea how to write a test to simulate the OS failing the delete... :(

**Comment by btm** [comment]
being a unit test I was just thinking something like 

```
it "does not use rm_rf which silently consumes errors" do
  expect(FileUtils).not_to receive(:rm_rf)
end
```

**Comment by jaymzh** [comment]
Oh. I can do that. sure :)

**Comment by jaymzh** [comment]
Tests fixed/added.

**Comment by btm** [comment]
:+1: on green

**Comment by smurawski** [comment]
The appveyor build failure is not related - I looks like the appveyor build images just got a newer version of powershell which requires a different key usage type for the cert for password decryption.

**Pull request merged**
