### PR TITLE
Fix missing require and small error in REST implementation

### PR DESCRIPTION
**Pull request by tecracer-theinen**
## Description

Added missing require of `addressable/template` to parse REST URL templates.
Fixed returns from `rest_get` method

## Related Issue

none

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tecracer-theinen** [comment]
This isn't of type "documentation" (probably the "template" keyword?), but a bugfix for REST target mode.

**Comment by johnmccrae** [comment]
@jaymzh noted more investigation needed from the chef side because of anticipated failures adopting this.

**Comment by tecracer-theinen** [comment]
Any REST API things are currently broken due to the missing `require` and the wrong data handling of skipping `.data`. It will just crash if you want to do anything with it. Partially I guess that's some copy and paste problems from my Hackathon code.

Maybe we should talk about that somewhere more interactively?

**Comment by jaymzh** [comment]
> Any REST API things are currently broken due to the missing `require` and the wrong data handling of skipping `.data`. It will just crash if you want to do anything with it. Partially I guess that's some copy and paste problems from my Hackathon code.
> 
> Maybe we should talk about that somewhere more interactively?

Sorry for the delay here, I was in LA at SCALE.

My concern here is someone has noticed the bug and is doing something like:

```ruby
if res.is_a?(Array)
  # use .data on each element
else
  # use `res` directly as it has no .data
end
```

And if that's the case, this PR will for sure break them. And since this code is exposed through resources, it's plausible people are using it directly, found the bug, worked around the bug and such code exists somewhere.

So we can:
* Make a new `rest_get_v2` that doesn't have the breakage, move our stuff to use it, and note that the original will go away in the next major version
* Decide that since `rest_get` is only ever really used by the internals of the `rest` resource, and we just want to fix it
* You can correct me and point out no one could have used the code that way if I've somehow mis-understood things, and then we can just merge this.

**Comment by tecracer-theinen** [comment]
Need to stress that the code is bugged, it is only part of the as-of-unreleased version 18 - and not even documented yet.

In my opinion, the possibility of someone writing a workaround for a bug in undocumented code of an unreleased version can't be a breaking change...

We can debate all we want, but in the end, this just means there is no REST support in Chef 18.0.

**Comment by marcparadise** [comment]
We will pull this in after the 18 rc is released.

**Comment by jaymzh** [comment]
@tecracer-theinen - aahhhh - I hadn't realized this was a new resource! In that case you're 100% correct, this is safe/good to merge.

**Review by jaymzh — APPROVED** [review]

**Comment by tpowell-progress** [comment]
> This isn't of type "documentation" (probably the "template" keyword?), but a bugfix for REST target mode.

@tecracer-theinen "documentation" just applies to any commits that change resources. Admittedly, it's been a source of confusion for me as well.

**Comment by PrajaktaPurohit** [comment]
https://buildkite.com/chef/chef-chef-main-omnibus-adhoc/builds/1625#_

**Pull request merged**
