### PR TITLE
Sometimes chocolately doesn't appear on the path

### PR DESCRIPTION
**Pull request by tyler-ball**
Add choco to the path if it isn't already there.

\cc @mwrock @jaym

### CODE REVIEW

**Comment by schisamo** [comment]
:+1:

**Comment by mwrock** [comment]
So #4438 did not fix?

**Comment by mwrock** [comment]
:+1: just occured to me that the choco installer adjusts the path in a child process so it does make sense here

**Comment by lamont-granquist** [comment]
makes sense :+1:

**Pull request merged**
