### PR TITLE
WIP: Add microdnf resource

### PR DESCRIPTION
**Pull request by ttmgraham**
## Description

This introduces the `microdnf_package` resource and provider to conduct package management via [microdnf](https://github.com/rpm-software-management/microdnf).  Microdnf is written in C and removes the python dependency that the current dnf is implemented in.  This seems to be the direction [libdnf is moving](https://github.com/rpm-software-management/libdnf/tree/dnf-5-devel/microdnf). 

This feature uses the work done with `dnf` as a template and tries to match compatibility whenever possible.  

#### Open questions / features yet to be implemented
* This is missing the flush_cache property of the dnf resource, and I'd appreciate any feedback or tips on the best way to interact with the cache
* The allow_downgrade property doesn't exist in microdnf, but linking to the dnf_package one didn't seem like the correct course of action.  What would be the best thing to do here?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by lamont-granquist** [comment]
> This is missing the flush_cache property of the dnf resource, and I'd appreciate any feedback or tips on the best way to interact with the cache

Doesn't matter.  You're shelling out every time so there's no persistent in-memory cache in the ruby process or any persistent parallel in-memory cache in a python process.  Really that should be removed or just ignored for back-compat.

> The allow_downgrade property doesn't exist in microdnf, but linking to the dnf_package one didn't seem like the correct course of action. What would be the best thing to do here?

I thought allow_downgrade throws in dnf_package now in the resource, it definitely ignores it and just allows downgrades.

**Comment by lamont-granquist** [comment]
Big thing here would be to get the func tests ported over.

There could be some additional clean up since the design is now pretty funky without having the external python process attached, but I kind of think that we should get it tested and validated in the "ugly" state and merge, then clean up.

**Comment by rb2k** [comment]
Hi, I work with @ttmgraham on this at $DAYJOB :)

> You're shelling out every time so there's no persistent in-memory cache

We are planning on adding is two caches:

1. One cache for the installed packages (basically identical to what ohai does to populate node['packages']. grabbing it from rpm)
2. One cache for the available upstream packages (via repoquery)

Otherwise we shell out 100s of times during an average run, even without installing any packages. That is a pretty severe performance hit. So far our runs with this (vs yum_package) are about 10-20% slower. We believe that adding the two caches will make this at least as fast, presumably faster.

**Comment by lamont-granquist** [comment]
Heh you can't do that.  You're just redesigning the old old YumCache in the Chef-12/13 yum_package provider.  That was ripped out very deliberately.

If you can get adequate performance by shelling out to microdnf I would HIGHLY suggest just doing that.  Trying to store all the necessary information in a Hash in RAM in the chef process explodes the memory utilization and is a no-go.

You should also not rely on the ohai node information, too many ways for that to go wrong.

If the perf isn't acceptable shelling out then I'd suggest using ffi to talk to libdnf directly and then getting the caching of the dnf information from libdnf.

**Comment by rb2k** [comment]
Huh, interesting.

I wonder if we're talking about something different.
As far as memory consumption goes: I just created a random 250 package hash with the required version / release / ... and it seems to clock at < 3 mb on an ancient ruby 2.6. Given the memory footprint of chef, that doesn't seem too bad to save 500 fork/exec calls?

**Comment by lamont-granquist** [comment]
Yeah so the actually-installed-version cache might deal with roughly 1/3rd of the hits, but you have to be careful and not try to use that for the candidate_version or magic_version at all, and there's probably some complexity there around resolving virtual packages that you need to be very careful with.  Once you go beyond that then you wind up needing to reimplement too much of dnf/yum in ruby, and either you accept a very large software development effort, or you wind up burning up all the RAM in the world to try to do it cheap+easy.

**Comment by lamont-granquist** [comment]
So the other problem I've got with the installed version cache is that it'll be incorrect if someone installs something outside of this package provider and then forgets to reload the cache.  This happens all the time when someone works around our lack of support for something or just bugginess and reaches for an `execute` resource.

**Comment by tas50** [comment]
@ttmgraham Is this a PR you plan to continue working on? If not we'd like to close this one out to clear up our in progress work.

**Comment by tas50** [comment]
I'm going to close this one out. If you want to further pursue this resource do let us know and we can offer and guidance you need to make it a reality.

**Pull request closed without merging**
