### PR TITLE
let kitchen-appbundle-updater float

### PR DESCRIPTION
**Pull request by lamont-granquist**
i'm a bit surprised this still even works at all..

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core assuming this works, we should do this to automatically test new releases of kitchen-appbundle-updater and to get the new code (which should be somewhat faster and more reliable now).

**Comment by lamont-granquist** [comment]
can we just !#$%!#$%@#$% shoot everyone who thinks servers need to not have compilers in the 21st century and start including them by default on all base images?

the last time it made sense any sense was sometime in the 90s when you had to install compilers from CDROMs and they weren't available via a simple 'apt-get install build-essential' or 'yum install gcc' and therefore not having them on the boxes actually provided a barrier to hackers and users installing them...

**Comment by lamont-granquist** [comment]
@chef/client-core okay fixed kitchen-appbundle-updater to start installing git and build-essential

**Comment by danielsdeleo** [comment]
:+1:

**Comment by smurawski** [comment]
:+1:

**Pull request merged**
