### PR TITLE
set FORCE_FFI_YAJL on windows spec tests

### PR DESCRIPTION
**Pull request by lamont-granquist**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-windows this is either a no-op, or else it'll vastly improve our spec test performance on windows.

**Comment by lamont-granquist** [comment]
and no i haven't tested it, i've had three straight failed builds on the ruby-2.2.4/AIX/ffi stuff I'm testing.

**Comment by mwrock** [comment]
:+1:

**Comment by lamont-granquist** [comment]
tested, seems to be a NOP right now and just adds a sanity check, no perf boost.

**Pull request merged**
