### PR TITLE
backport to 17: flush package cache after registering or unregistering with rhsm_register

### PR DESCRIPTION
**Pull request by jasonwbarnett**
Backport https://github.com/chef/chef/pull/12828 to chef-17

### CODE REVIEW

**Comment by johnmccrae** [comment]
@jasonwbarnett can you rebase and try again please? We updated the certs and just merged the code to fix the windows certs issues.

**Comment by PrajaktaPurohit** [comment]
Thank you for the backport! The tests will need a rebase to pass.

**Comment by johnmccrae** [comment]
Sorry about that. My fault. NOW there is stuff to rebase onto that should fix the windows errors.

**Review by jaymzh — APPROVED** [review]

**Comment by jasonwbarnett** [comment]
> Sorry about that. My fault. NOW there is stuff to rebase onto that should fix the windows errors.

rebased.

**Pull request merged**
