### PR TITLE
Chef 15: bootstrap options --max-wait raises NoMethodError: undefined method /

### PR DESCRIPTION
**Pull request by vsingh-msys**
Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

## Description
- In order to fix Parse `--max-wait` options string to an integer.
- It would be good it we can provide the fixes on https://github.com/inspec/train side as well at location https://github.com/inspec/train/blob/ec41c1f1e6f38f6ab1c335955651064eaeb7028f/lib/train/transports/ssh_connection.rb#L138 or https://github.com/inspec/train/blob/ec41c1f1e6f38f6ab1c335955651064eaeb7028f/lib/train/transports/ssh_connection.rb#L44
## Related Issue
https://github.com/chef/chef/issues/8488

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by lamont-granquist** [comment]
`#to_f` might be more permissive than `#to_i` as well, as long as all that train cares about is getting a number which can be divided.

**Comment by vsingh-msys** [comment]
> The change looks good, but it would be good to also add simple validation, to avoid giving the operator surprise `0` from converting an invalid value.

@marcparadise should I add validation or let the train cares about it?

**Comment by vsingh-msys** [comment]
> `#to_f` might be more permissive than `#to_i` as well, as long as all that train cares about is getting a number which can be divided.

Okay noted, Actually I thought of SECONDS values should be like integer so added `#to_i` will change it to `#to_f`.
Thanks

**Comment by btm** [comment]
Created MSYS-1025 for followup, @vsingh-msys please write up a github issue based on it.

**Comment by vsingh-msys** [comment]
> Created MSYS-1025 for followup, @vsingh-msys please write up a github issue based on it.
Noted @btm thanks!

**Pull request merged**
