### PR TITLE
Implement action_class do ... end

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by coderanger** [comment]
Predicting future "well it worked for me before" regressions, we should test running it twice for the same class and test it with subclassing.

**Comment by jkeiser** [comment]
subclass permutations are already tested elsewhere, but it's easy enough to build one here, so here ya go.

**Comment by jkeiser** [comment]
@coderanger updated, I *think* it has the set of tests you were talking about now.

**Comment by coderanger** [comment]
:+1:

**Pull request merged**
