### PR TITLE
rspec-3-ify all the env-run-list specs

### PR DESCRIPTION
**Pull request by lamont-granquist**
broke master with #stub! which got removed.  fixed mechanically
via using transpec gem

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core @chef/client-engineers should fix master

**Comment by btm** [comment]
:+1: when it goes green.

**Comment by tyler-ball** [comment]
:+1:

**Comment by jdmundrawala** [comment]
:shipit:

**Pull request merged**
