### PR TITLE
chef-12: Add allow_downgrade to zypper_package resource

### PR DESCRIPTION
**Pull request by yeoldegrove**
### Description

Add allow_downgrade to zypper_package resource on chef 12

### Issues Resolved

none

### Check List

- [x] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by yeoldegrove** [comment]
The tests in https://travis-ci.org/chef/chef/builds/284071587?utm_source=github_status&utm_medium=notification fail with:
```
The command "gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)" failed and exited with 1 during .
```

This has nothing todo with my commit.

**Comment by yeoldegrove** [comment]
@lamont-granquist Do I need to fix anything or can this be merged?

**Comment by tas50** [comment]
@yeoldegrove There's some spec failures here. You might want to rebase this against the chef-12 branch and push again. We've fixed some CI failure in Travis / Appveyor that were causing problems.

**Comment by tas50** [comment]
I'm going to close this out at this point since we won't be releasing another version of Chef 12.

**Pull request closed without merging**
