### PR TITLE
adding docker to top_cookbooks

### PR DESCRIPTION
**Pull request by mwrock**

### CODE REVIEW

**Comment by adamedx** [comment]
I'm curious @mwrock  -- I see that it's exercising recipes, but what exactly does it do? Is inspec / serverspec being used to validate the result of the recipes?

**Comment by mwrock** [comment]
no this basically puts docker "through its paces" so to speak. Since the docker cookbook has no `default` recipe and is rather a collection of resources, it seemed best to tun it through the same recipes that its own kitchen yml uses. Otherwise we would have to create a separate "wrapper" cookbook to excercise its resources.

**Comment by chefsalim** [comment]
:+1:

**Comment by adamedx** [comment]
:+1:

**Pull request merged**
