### PR TITLE
Adding Chef::Command::Mixin back into the package provider

### PR DESCRIPTION
**Pull request by jdmundrawala**
I think we should add this back in. I don't like that we changed the public interface of the package provider.
Thoughts?

This fixes https://github.com/chef/chef/issues/3011

cc @chef/client-core @chef/client-engineers

### CODE REVIEW

**Comment by lamont-granquist** [comment]
`Chef::Mixin::Command` methods should call `Chef::Log.deprecation` or use `Chef::Mixin::Deprecation`

**Comment by tyler-ball** [comment]
Ditto to @lamont-granquist

**Comment by tyler-ball** [comment]
There are some other providers this is currently affecting:
```
[chef]$ ag run_command

lib/chef/provider/deploy.rb
204:            run_command(run_options(:command => @new_resource.migration_command, :cwd=>release_path, :log_level => :info))
224:              run_command(run_options(:command => @new_resource.restart_command, :cwd => @new_resource.current_path))

lib/chef/provider/group/aix.rb
37:          run_command(:command => command)
47:            run_command(:command => command)
53:          run_command(:command => "rmgroup #{@new_resource.group_name}")

lib/chef/provider/group/groupadd.rb
50:          run_command(:command => command)
58:          run_command(:command => command)
64:          run_command(:command => "groupdel #{@new_resource.group_name}")

lib/chef/provider/group/pw.rb
52:          run_command(:command => command)
61:            run_command(:command => command)
64:              run_command(:command => command + option)
71:          run_command(:command => "pw groupdel #{@new_resource.group_name}")

lib/chef/provider/ifconfig.rb
109:              run_command(
127:              run_command(
141:            run_command(
158:            run_command(

lib/chef/provider/package/easy_install.rb
116:          run_command(:command => "#{easy_install_binary_path}#{expand_options(@new_resource.options)} \"#{name}==#{version}\"")
124:          run_command(:command => "#{easy_install_binary_path }#{expand_options(@new_resource.options)} -m #{name}")

lib/chef/provider/route.rb
138:          run_command( :command => command )
151:          run_command( :command => command )

lib/chef/provider/user/pw.rb
34:          run_command(:command => command)
41:          run_command(:command => command)
48:          run_command(:command => command)
62:          run_command(:command => "pw lock #{@new_resource.username}")
66:          run_command(:command => "pw unlock #{@new_resource.username}")
```

**Comment by danielsdeleo** [comment]
I agree about the deprecation, but I think we should merge and ship this to un-break things, then do another pass to fix `Mixin::Command` usage in providers, then deprecate (in a separate PR targeted to 12.2).

:+1:

**Comment by jdmundrawala** [comment]
I'm with @danielsdeleo, I don't think we should spew deprecation warnings in core resources

**Comment by danielsdeleo** [comment]
@jdmundrawala IIRC, `Chef::Log.deprecation` will make tests fail for just that reason. But of course that means you have to fix internal usage of deprecated stuff before you can deprecate it.

**Comment by tyler-ball** [comment]
https://github.com/chef/chef/issues/3014

**Comment by jdmundrawala** [comment]
https://github.com/chef/chef/blob/f6a41f7c565c8ab6771efe7af0438237d1faa4fc/lib/chef/config.rb#L511

**Comment by lamont-granquist** [comment]
okay agreed with dan, i was under the impression it was more done than it was.

**Comment by btm** [comment]
I think this was cherry-picked into 12-stable as c66c5b66079934a51307907c15f4443235201d7b which went out in 12.1.1

**Pull request merged**
