### PR TITLE
print STDOUT from the powershell wrapper. fixes issue #3596

### PR DESCRIPTION
**Pull request by alexpop**
fixes issue #3596

### CODE REVIEW

**Comment by martinisoft** [comment]
This appears to be ok, but I'm not a powershell user (only confirmed usage via the docs). Anyone from @chef/maintainers able to lend a hand for review?

**Comment by danielsdeleo** [comment]
Same here, it looks fine but I'm not a subject matter expert

**Comment by jtimberman** [comment]
Paging @smurawski for :eyes:

**Comment by alexpop** [comment]
I've hacking with that powershell wrapper script. I don't like that the trap is making the use of $ErrorActionPreference impossible. @adamedx are you working on rewriting the powershell wrapper used by the powershell_script resource?

**Comment by adamedx** [comment]
I have some concerns about using `Write-Output` -- does that write to the pipeline? If so, that would affect the output of the script. Seems like it's passing on Windows so maybe that's ok, but I would think something that generated output without affecting the pipeline would be preferable.

**Comment by adamedx** [comment]
@alexpop my own involvement here is pretty light, but the maintainers may be able to help if you are running into some issues.

**Comment by adamedx** [comment]
Yeah, I think `Write-Output` is the wrong choice, it should be `Write-Host` instead. Also, we're missing some test coverage since some test should break if our wrapper alters the script output:

```ruby
% adamed@SEA-ADAMED1: 0x0100E0D0: C:\Users\edwardsa
2015.06.26 Fri 14:38:55.00-07:00> { }.invokereturnasis() -eq $null
True
% adamed@SEA-ADAMED1: 0x0100E0D0: C:\Users\edwardsa
2015.06.26 Fri 14:39:10.45-07:00> { write-output 'hi' }.invokereturnasis() -eq $null
False
% adamed@SEA-ADAMED1: 0x0100E0D0: C:\Users\edwardsa
2015.06.26 Fri 14:39:17.40-07:00> { write-host 'hi' }.invokereturnasis() -eq $null
hi
True
% adamed@SEA-ADAMED1: 0x0100E0D0: C:\Users\edwardsa
2015.06.26 Fri 14:39:22.63-07:00>
```

**Comment by alexpop** [comment]
Thanks @adamedx. If I use `Write-Host`, I don't get the stdout of the powershell script from kitchen or from a direct chef-client run.

With `Write-Output`, I get the stdout when I run chef-client on the box using the same command as kitchen:

```
$env:TEMP='C:\Users\vagrant\appdata\local\Temp'
chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level info --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889
```

With `Write-Output`, I don't get the stdout when I run `kitchen converge` from my laptop with info or debug log levels. This might be related to: https://github.com/test-kitchen/test-kitchen/issues/685

**Comment by ksubrama** [comment]
I gave this a quick test and it makes sense to me.  @adamedx - the write-output is after the invokereturnasis and is printing what powershell would otherwise have sent to stdout.  It was error case that I was worried about - I didn't know if printing the output there would cause any weirdness with the output happening after the script failed but I don't see anything particularly offensive about the current behavior.

**Comment by ksubrama** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Comment by smurawski** [comment]
Merged with https://github.com/chef/chef/pull/4087

**Pull request closed without merging**
