### PR TITLE
Nominate promoting myself to OS X Lt.

### PR DESCRIPTION
**Pull request by jtimberman**

### CODE REVIEW

**Comment by jdmundrawala** [comment]
:+1: .... if the specs pass :smile:

**Comment by charlesjohnson** [comment]
:+1:

**Comment by danielsdeleo** [comment]
:+1:

**Comment by ranjib** [comment]
:+1:  yay☺

**Comment by jonlives** [comment]
:+1:

**Comment by nathenharvey** [comment]
@sethvargo @btm @martinisoft as Lt.s, can you please weigh in on this?

**Comment by martinisoft** [comment]
:+1: as I agreed in the last IRC meeting too :)

**Comment by sethvargo** [comment]
:+1:

**Pull request merged**
