### PR TITLE
Remove remaining chef-config test warnings

### PR DESCRIPTION
**Pull request by jkeiser**
This fixes these two warnings:

```
rspec spec/unit/workstation_config_loader_spec.rb:284 spec/unit/workstation_config_loader_spec.rb:216
Run options:
  include {:focus=>true, :locations=>{"./spec/unit/workstation_config_loader_spec.rb"=>[284, 216]}}
  exclude {:windows_only=>true}

Randomized with seed 50388

ChefConfig::WorkstationConfigLoader
  loading the config file
    when no explicit config is specifed and no implicit config is found
/Users/jkeiser/src/chef/chef-config/lib/chef-config/path_helper.rb:238: warning: Dir.exists? is a deprecated name, use Dir.exist? instead
      skips loading
    when the config file exists
      and raises a ruby exception during evaluation
/var/folders/gf/0cklbzl144xg_pbtgpnj_4vc0000gq/T/Chef-WorkstationConfigLoader-rspec-test20160823-71386-1si9j4v:1: warning: unused literal ignored
/var/folders/gf/0cklbzl144xg_pbtgpnj_4vc0000gq/T/Chef-WorkstationConfigLoader-rspec-test20160823-71386-1si9j4v:2: warning: unused literal ignored
        raises a ConfigurationError

Finished in 0.04604 seconds (files took 0.25896 seconds to load)
2 examples, 0 failures
```

### CODE REVIEW

**Comment by thommay** [comment]
:+1: LGTM

**Comment by jkeiser** [comment]
To shorten review and ship cycle, I merged two other warning fixes. First, to fix this terrible windows warning:

```
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/library.rb:147:in `block in ffi_lib': no implicit conversion of Symbol into String. (LoadError)
Could not open library 'libkernel32.dylib': dlopen(libkernel32.dylib, 5): image not found
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/library.rb:100:in `map'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/library.rb:100:in `ffi_lib'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/win32-service-0.8.9/lib/win32/windows/functions.rb:22:in `<module:ServiceFunctions>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/win32-service-0.8.9/lib/win32/windows/functions.rb:4:in `<module:Windows>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/win32-service-0.8.9/lib/win32/windows/functions.rb:3:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/win32-service-0.8.9/lib/win32/daemon.rb:3:in `require_relative'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/win32-service-0.8.9/lib/wi  else
n32/daemon.rb:3:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
```

Next, to remove this duplication warning, also at the top of the tests:

```
WARNING: Shared example group 'with a chef repo' has been previously defined at:
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cheffish-3.0.0/lib/cheffish/rspec/repository_support.rb:12
...and you are now defining it at:
  /Users/jkeiser/src/chef/spec/support/shared/integration/integration_helper.rb:111
The new definition will overwrite the original one.
```

**Comment by mwrock** [comment]
based on travis/appveyor looks like something is not getting cleaned up propperly. Perhaps in the deleted code around `RSpec.shared_context "with a chef repo" do`?

**Comment by jkeiser** [comment]
@mwrock yeah, looks like some fixes to that method that were not brought over to `cheffish`.

**Comment by thommay** [comment]
We need to take another pass at all the rspec work; closing for now.

**Pull request closed without merging**
