### PR TITLE
CHEF-1940:Patch for https://github.com/opscode/chef/issues/1940

### PR DESCRIPTION
**Pull request by rekhajoshm**
Attached patch for - https://github.com/opscode/chef/issues/1940

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Can you look at signing the CLA in supermarket and address dan's point about the method argument whitespace and the tests?

**Comment by adamedx** [comment]
@rekhajoshm  have you had a chance to look at the CLA? It's pretty easy to sign now: https://supermarket.getchef.com/contributors?page=27. Once we have the CLA, along with some tests, we can merge this.

Thank you for the submission.

**Comment by lamont-granquist** [comment]
@rekhajoshm are you going to get a chance to address the review suggestions and sign the CLA?

**Comment by lamont-granquist** [comment]
@rekhajoshm if you can sign the CLA and address dan's comment we can accept this, but closing this for now.

**Pull request closed without merging**
