### PR TITLE
Chef-13:  Remove declare_resource create_if_missing API

### PR DESCRIPTION
**Pull request by lamont-granquist**
Likely nobody cares about this change, I added it and then a
release or two later introduced the better edit_resource style
of API.

I also changed "created_at" to be a proper named parameter, instead
of a positional parameter, which is a breaking change in an API that
has been around for quite some time -- makes the API consistent since
I added it as a named parameter to the new APIs when I wrote them.
(This one is very internal, though, so I suspect there's a shortlist of
things that muck about in chef internals that would be all that would break).

### CODE REVIEW

**Comment by lamont-granquist** [comment]
I'm giving roughly even odds that poise and/or chefspec goes red...

**Comment by coderanger** [comment]
Heh, if it doesn't go red on poise it definitely will on the application cookbook. I'll have to ponder how to deal with positional vs named param, I wish Ruby didn't make that so hard :-(

**Comment by lamont-granquist** [comment]
I don't suuuuuper care about fixing that latter one, it can get backed out.

**Comment by lamont-granquist** [comment]
You can always call it one way or the other and `rescue ArgumentError` it blows up with one either if you call it with the extra positional parameter, or with the named parameter it doesn't know about.

**Comment by coderanger** [comment]
That would break if we ever add another positional param in the future though, I'll probably just do an explicit version check and hold my nose :)

**Comment by lamont-granquist** [comment]
call it with the named parameter -- it validates that as well and will ArgumentError on Chef 12.

**Comment by lamont-granquist** [comment]
crazy it went green -- @coderanger could you throw an approval on this one if you've sorted out the application cookbook stuff?

**Pull request merged**
