### PR TITLE
use Chef::JSONCompat.parse for file_contents #2433

### PR DESCRIPTION
**Pull request by sawanoboly**
PR for #2433 and https://github.com/opscode/chef-zero/issues/99

HT: @cl-lab-k

### CODE REVIEW

**Comment by lamont-granquist** [comment]
dont we still need this it hasnt been merged?

**Comment by sawanoboly** [comment]
@lamont-granquist 

Oh, this fix has been included on  https://github.com/chef/chef/commit/e809bb40b1340309c86edac9fb5cf7f179f8f7ec by @jkeiser (but without no specs :anger: ) , and already shipped.

I seemed that this PR doesn't have to keep state open.

**Comment by lamont-granquist** [comment]
Heh, and git is smart enough to resolve the merge conflict from the identical edit.

The specs are still useful, like to get those merged so we don't ever regress.

**Comment by lamont-granquist** [comment]
closed by #2823

**Comment by sawanoboly** [comment]
Thanks! :+1:

**Pull request closed without merging**
