### PR TITLE
OpenSSL 3 bump for Chef 17

### PR DESCRIPTION
**Pull request by tpowell-progress**
## Description
* install openssl 3.2.0 to backfill for custom openssl
* Set OpenSSL version to 1.0.2zi for Windows due to FIPS challenges and 3.0.9 for others.
* `::File.exists?` -> `::File.exist?` for `ssl_policies.rb` 
* Fix `EC` and modulus length for OpenSSL 3 compatibility
* OpenSSL validation checks

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tpowell-progress** [comment]
@tpowell-progress redo `Gemfile.lock` for root and `omnibus`

**Comment by mikef-nl** [comment]
@tpowell-progress is there a timeline on Chef 17 supporting Openssl 3.0.7 on Rocky Linux 9?

**Review by johnmccrae — APPROVED** [review]

**Comment by johnmccrae** [comment]
@mikef-nl Chef-17 is tested on Rocky 8 and 9 currently. Not sure about the timeline for Openssl 3.0.7, we're working on it though. Do you need it soon?

**Comment by tpowell-progress** [comment]
> @tpowell-progress is there a timeline on Chef 17 supporting Openssl 3.0.7 on Rocky Linux 9?

@mikef-nl working to get everything green... a few things have triggered failures in the builds, but we're compiling release notes for when we get everything passing. I think on "weeks" time scale still. Currently assessing what is still broken and how much of it we have known fixes for.

**Comment by tpowell-progress** [comment]
Merging since the remainder of issues are going to be addressed separately.

**Pull request merged**
