### PR TITLE
Bootstrap: Set pty true only if required

### PR DESCRIPTION
**Pull request by vsingh-msys**
- `rescue` the exception and retry with pty: true if host configured with `requiretty`.
 - Remove the default pty: true for all node that causes the error in the window and other hosts while detecting the system.
## Description

- Earlier we provided `pty: true` for all node to bootstrap. But seems issue noticed for `Windows`, `AIX` or other `Unix` system.
- First tried without pty params.
- If fails with exception "_Sudo requires a TTY. Please see the README on how to configure_ "
https://github.com/inspec/train/blob/3ab9ad867972106f419a28ffd44d4291747dd360/lib/train/extras/command_wrapper.rb#L68 retry with `pty: true`.
- Add begin..rescue in `do_connect` seems unable to catch inside the `connect!` method.

### Note:
 - Warn message about pty request
 ```
WARNING: Sudo failed: Sudo requires a TTY. Please see the README on how to configure sudo to allow for non-interactive usage. - trying with pty request
```
- Pending to add test cases to cover these changes if any.
- Boolean check to retry again

## Related Issue

Issues: https://github.com/chef/chef/issues/8683, https://github.com/chef/chef/issues/8764

Dependent PRs: 
1. https://github.com/inspec/train/pull/508 which require to get the correct error message.
2. https://github.com/chef/chef/pull/8816 & https://github.com/chef/chef/pull/8795 to create temp dir.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

### CODE REVIEW

**Comment by vsingh-msys** [comment]
Added require test case and completed with testing part.
@btm, @tas50 @lamont-granquist could you please have a look and let us know further if any suggestion/feedback?

**Comment by vsingh-msys** [comment]
> Are there cases in which it would be breaking?
@marcparadise with chef-14 everything is working as expected with `requiretty`.

I have updated suggested changes could you please have a look again?

Thanks!

**Comment by tas50** [comment]
@vsingh-msys  can you confirm that this still works with the change that @marcparadise made in train here https://github.com/inspec/train/commit/50a87241ed1b4ebe9bf5e57876fdfedd1ada6895

**Comment by vsingh-msys** [comment]
Yes, @tas50 it working fine with those changes.

**Pull request merged**
