### PR TITLE
Nominating myself to maintain core, chefspec and ubuntu

### PR DESCRIPTION
**Pull request by ranjib**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:+1:

**Comment by tyler-ball** [comment]
Wahoo! :+1: 

\cc @chef/client-core

**Comment by danielsdeleo** [comment]
:+1:

**Comment by jdmundrawala** [comment]
:+1:

**Comment by jonlives** [comment]
:+1:

**Comment by mcquin** [comment]
:+1:

**Comment by adamhjk** [comment]
Lets do this. I also think @ranjib should consider being the LT for Ubuntu.

**Comment by adamhjk** [comment]
@ranjib needs a quick rebase, and then we should merge.

**Comment by btm** [comment]
rebased and merged as 7c1cec5b04ae6801723a9c85e95c1e04fda97296. How about it @ranjib, will you be our Ubuntu Lieutenant?

**Pull request closed without merging**
