### PR TITLE
Change audit DSL method controls to control_group.

### PR DESCRIPTION
**Pull request by mcquin**
This addresses https://github.com/opscode/chef/issues/2755.

\cc @tyler-ball @opscode/client-engineers

### CODE REVIEW

**Comment by tyler-ball** [comment]
:+1: Looks great!  Will you squash this into 1 commit when merging to master?  Also, did you do manual verification?

**Comment by mcquin** [comment]
Yeah, I can do a squash.

I verified against all the audit-test cookbook recipes. Much success.

**Comment by mcquin** [comment]
@tyler-ball squashed. Merge when ready, capt'n.

**Comment by smurawski** [comment]
@jonlives @jaymzh @lamont-granquist @danielsdeleo @jdmundrawala Can we get a few more +1's to merge?

**Comment by danielsdeleo** [comment]
LGTM :+1:

**Comment by jdmundrawala** [comment]
:+1:

**Comment by sersut** [comment]
:+1: Anything else needed for this @chef/client-core ?

**Pull request merged**
