### PR TITLE
Added fix for spaces in profile identifiers

### PR DESCRIPTION
**Pull request by natewalck**
Adds support for profiles with spaces in the identifiers. Not great to use spaces, but Apple supports it, so we must as well.

### CODE REVIEW

**Comment by natewalck** [comment]
This fixes #5150

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @natewalck

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by natewalck** [comment]
Added a spec, but it doesn't seem to work as I expect it to (and it seems to work in OTHER tests, like freebsd_service_spec.rb).

**Comment by jaymzh** [comment]
CC @chef/client-os-x

**Comment by lamont-granquist** [comment]
can we just remove the regexp and allow the shell command to explode?   generally this kind of validation of things to pass to commands is a whack-a-mole.

the error message also seems to be completely misleading, and doesn't give any indication of how to fix the problem.  As an example of how this can all go horribly wrong, the user_valid_regex that we have -- in the name of producing more user-understandable error messages -- has resulted in this abomination:

```
Chef::Exceptions::ValidationFailed: Option owner's value foo:bar does not match regular expression [/^[^-+~:,\t\r\n\f\0]+[^:,\t\r\n\f\0]*$/]
```

Which is 100% correct, and 100% worse UX than just letting the system call to set the user name fail...

**Comment by natewalck** [comment]
@lamont-granquist This name isn't being directly handed to the shellout command. We need to make sure it meets certain standards, otherwise we can get into a situation where the profile can be installed but never uninstalled and other nastiness (thanks Apple).

Also, I'm not sure where tht error came from...it *should* be throwing:

```
"...when removing using the identifier attribute, it must match the profile identifier"
```

**Comment by lamont-granquist** [comment]
okay then also fixing the error text while we're in here would be nice (plus travis busted, plus now a merge a conflict)

but :+1: on adding space to the regex

**Comment by natewalck** [comment]
@lamont-granquist Regarding the rspec I started on, what would your guidance be for testing this particular behavior? I tried modeling how freebsd service does it, but it does not work.

I am doing: 

```
    it "should work with spaces in the identifier" do
      new_resource.identifier "com.testprofile.screensaver settings"
      new_resource.action(:remove)
      provider.load_current_resource
      provider.define_resource_requirements
      expect { provider.process_resource_requirements }.not_to raise_error
    end
```

And if I tweak the regex to now allow spaces again, it still does not raise an error. I'm not sure what I am missing here.

**Comment by lamont-granquist** [comment]
yeah i don't see anything wrong with that test, it looks completely correct to me...

all i can think of is that there's some other state (from some `let` block?) way above you that is bleeding into your test and changing things?

**Comment by natewalck** [comment]
I was setting the action in the wrong place it seems. I'll confirm all tests as passing now.

I did have one struggle...when I tried to override `new_resource.name` thusly:

```
new_resource.name "com.testprofile.screensaver settings"
```

and then do an interactive pry sessions in the provider itself, it never got the new resource name. `@new_resource.profile_name` was always set to what was used on line 184 of this test:

```
let(:new_resource) { Chef::Resource::OsxProfile.new("Profile Test", run_context) }
```

I'm not sure why I couldn't change it, but it seems to be working as expected now. I suspect these unit tests may need some further love before too long.

**Comment by natewalck** [comment]
Needs final approval (and maybe tweaks to the rspec?) @jaymzh

**Comment by jaymzh** [comment]
:+1:

**Pull request merged**
