### PR TITLE
pry-remote for consistent remote diagnostics

### PR DESCRIPTION
**Pull request by pburkholder**
https://chefio.slack.com/archives/test-kitchen/p1436995105000034

@fnichol " i can think of one tweak that would help us out--adding pry-remote to our chef omnibus packages. that would mean we have all the software available and making some native pair of chef resources totally doable. having this in chef core could be a powerful help all over the place"

### CODE REVIEW

**Comment by coderanger** [comment]
:-1: This shouldn't be a dependency of Chef. Pull it into the packages for chef-client or chefdk perhaps, but not the actual gem.

**Comment by ranjib** [comment]
agree with noah

**Comment by lamont-granquist** [comment]
Yep, agree with noah, i'd like to see this in omnibus-chef/omnibus-software.

Really we should drop the pry dep as well, we don't actually dep on pry, I don't know how that wound up in there...   That should also probably get moved to omnibus-chef/omnibus-software.

Going to close this one.

**Comment by coderanger** [comment]
I think chef-shell uses pry? Or at least did at some point.

**Comment by lamont-granquist** [comment]
Nope, we have talked about it lots and lots, but its still irb based.

**Pull request closed without merging**
