### PR TITLE
Make ssh_port default to 22 for knife bootstrap.

### PR DESCRIPTION
**Pull request by ksubrama**
This is the behavior of knife-windows.

### CODE REVIEW

**Comment by ksubrama** [comment]
/cc @chef/client-windows .
Could one of you also cc chef-client-core?

**Comment by btm** [comment]
@ksubrama seems simple on the surface, but why are we adding it? Presumably all the underlying libraries make the right choice. I think we fixed our code where mixlib-cli defaults no longer override .ssh/config values, but I still worry about those kinds of repercussions with this kind of change.

@chef/client-core review?

**Comment by tyler-ball** [comment]
I agree with @btm - I don't think that adding this will change anything because I think the underlying libraries already default to 22.  Do we have any evidence to the contrary?

**Comment by lamont-granquist** [comment]
another agreement with btm.

**Comment by ksubrama** [comment]
This is good to know.  knife-windows explicitly sets it to 22.  Perhaps the better solution is to remove the default value there and check that the underlying library defaults correctly.

**Pull request closed without merging**
