### PR TITLE
Fix broken tests in jenkins

### PR DESCRIPTION
**Pull request by jdmundrawala**
These were not passing on windows in jenkins or on my local machine. Still not clear on why they passed in appveyor

cc @mcquin @chef/client-engineers

### CODE REVIEW

**Comment by btm** [comment]
huh. doesn't look like we're testing platform specific paths here, so this should be fine. :+1:

**Comment by lamont-granquist** [comment]
Plz to be whacking merge button, this trolled me.

**Comment by danielsdeleo** [comment]
I think it is a platform-specific path: https://github.com/chef/chef/blob/68bab0b362c47e5a75492e57094f72ecee1171ae/lib/chef/application/client.rb#L327 @jdmundrawala did you try expecting:

```ruby
allow(::File).to receive(:read).with(Chef::Config.platform_specific_path("/etc/chef/client.rb").and_return("")
```
?

**Comment by jdmundrawala** [comment]
@danielsdeleo i believe that was one of the things that I tried when debugging and IIRC, it worked. Not too different from what is here...neither is very unit testy in my opinion.

**Comment by jdmundrawala** [comment]
That being said, maybe I need to stub a few more things (`Chef::Platform.windows?`)...I'll look into that tomorrow

**Comment by danielsdeleo** [comment]
@jdmundrawala the thing I like a little better about using `Chef::Config.platform_specific_path("/etc/chef/client.rb")` is that you're matching an exact value rather than a regex which would match, say, "/etc/totally-wrong-path/client.rb". It is a little ugly but since the `platform_specific_path` logic is in `Chef::Config` and tested there I think it's okay.

**Comment by jdmundrawala** [comment]
@danielsdeleo updated

**Comment by danielsdeleo** [comment]
:+1: :shipit:

**Pull request merged**
