### PR TITLE
Copyright and author line update

### PR DESCRIPTION
**Pull request by coderanger**
Because I got annoyed with seeing this happen in unrelated changes.

This updates all copyright years for 2016 and unifies the formatting. It also updates all copyright lines from Opscode Inc to Chef Software Inc and all author emails from opscode.com/getchef.com to chef.io.

I did my best to skim the script output before committing but it's a doosey.

/cc @chef/client-core

### CODE REVIEW

**Comment by lamont-granquist** [comment]
"Sorry, we could not display the entire diff because too many files (1,279) changed."

:+1:

**Comment by lamont-granquist** [comment]
So I actually found a couple of bugs:

```
 git diff origin/master | egrep '^(\+|\-)' | egrep -v '^(\-\-\-|\+\+\+)' | egrep -v '^(\+|\-)#'
```

found these:

```
-Chef incorporates code modified from deep_merge (http://trac.misuse.org/science/wiki/DeepMerge), which is Copyright (c) 2008 Steve Midgley
+Chef incorporates code modified from deep_merge (http://trac.misuse.org/science/wiki/DeepMerge), which is Copyright 2008-2016, Steve Midgley
- * :copyright: Copyright 2007-2014 by the Sphinx team, see AUTHORS.
+ * :copyright: Copyright 2007-2016, by the Sphinx team, see AUTHORS.
- * :copyright: Copyright 2007-2014 by the Sphinx team, see AUTHORS.
+ * :copyright: Copyright 2007-2016, by the Sphinx team, see AUTHORS.
- * :copyright: Copyright 2007-2014 by the Sphinx team, see AUTHORS.
+ * :copyright: Copyright 2007-2016, by the Sphinx team, see AUTHORS.
- * :copyright: Copyright 2007-2014 by the Sphinx team, see AUTHORS.
+ * :copyright: Copyright 2007-2016, by the Sphinx team, see AUTHORS.
-      # Copyright (c) 2001 TAKAHASHI Masayoshi, GOTOU Yuuzou
-      # Copyright (c) 2002 Internet Programming with Ruby writers. All rights
+      # Copyright 2001-2016, TAKAHASHI Masayoshi, GOTOU Yuuzou
+      # Copyright 2002-2016, Internet Programming with Ruby writers. All rights
```

Also missed a couple straggling opscode.com's:

```
% git diff origin/master | egrep '^(\+|\-)' | egrep -v '^(\-\-\-|\+\+\+)' | egrep -v '^(\+|\-)#' | egrep opscode.com | egrep '^\+'
+ * Copyright 2008-2016, Adam Jacob <adam@opscode.com>
+ * Copyright 2009-2016, Christopher Brown <cb@opscode.com>
+    Copyright 2010-2016, Chef Software Inc. (<legal@opscode.com>)
+    Copyright 2010-2016, Chef Software Inc. (<legal@opscode.com>)
+    Copyright 2010-2016, Chef Software Inc. (<legal@opscode.com>)
```

**Comment by coderanger** [comment]
Which of those are bugs?

**Comment by lamont-granquist** [comment]
Hmmm, yeah, I guess its fine to update the dates, doesn't change the authorship...

**Comment by coderanger** [comment]
Yeah, their copyright continues for at least 95 years after initial publication so we should update those too :)

**Comment by coderanger** [comment]
We should do something with `NOTICE`, it's hugely inaccurate. The external copyright disclaimers should probably get moved to `COPYING` or something and remove the rest.

**Comment by lamont-granquist** [comment]
looks fine to me, whack merge when you want to (positive nothing added in those last two will make travis red, and appveyor will probably go red because chocolatey func test whenever you finally get virts to execute on...)

**Pull request merged**
