### PR TITLE
modernize shell_out method syntax

### PR DESCRIPTION
**Pull request by lamont-granquist**
**options has worked ever since we've deprecated ruby 1.9.x

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core trivial cleanup of ruby 1.8.7-era arguments mangling...

**Comment by danielsdeleo** [comment]
👍

**Comment by coderanger** [comment]
This seems like a lot of oddly duplicated code still.

**Comment by coderanger** [comment]
```ruby
      def shell_out(*args, **options)
        # For backwards compat, in case something below us modifies args?
        args = args.dup
        options = options.dup
        env_key = options.has_key?(:env) ? :env : :environment
        options[env_key] = {
            "LC_ALL" => Chef::Config[:internal_locale],
            "LANGUAGE" => Chef::Config[:internal_locale],
            "LANG" => Chef::Config[:internal_locale],
          }.update(options[env_key] || {})
        shell_out_command(*args, **options)
      end
```

That should be equivalent, right?

**Comment by lamont-granquist** [comment]
you still have to dup options[env_key] i think

**Comment by lamont-granquist** [comment]
oh wait...  parsing...

**Comment by coderanger** [comment]
I think that should be correct, it's a new hash object .update'd with the old one, should mutate the new object.

**Comment by lamont-granquist** [comment]
yeah, that works the same in my head, lets see if it works the same in the tests..

**Comment by coderanger** [comment]
We should have a comment on the `args.dup` one way or another, otherwise it looks unintentional since nothing in there mutates args :)

**Comment by lamont-granquist** [comment]
i think it is unintentional now and can be deleted?

**Comment by coderanger** [comment]
Or that, is there anything below this in the call stack that expects to modify the args but doesn't `dup` itself? If there is it's a huge bug but never say never ...

**Comment by lamont-granquist** [comment]
oh there's the deprecated options garbage...

**Comment by coderanger** [comment]
Yeah, might need to fix a few more functions at the same time :-(

**Comment by lamont-granquist** [comment]
yeah i got my yak trimmer out...

**Comment by lamont-granquist** [comment]
actually i think this works, #run_command_compatible_options does a #dup on args itself, and mixlib-shellout doesn't mangle its own args...

**Comment by coderanger** [comment]
:+1: the deprecation code is gross but this should work I think (travis failure looks unrelated)

**Comment by lamont-granquist** [comment]
yeah but the deprecation code all gets nuked from orbit, hopefully soonish, whenever we start with Chef-13.    i just want to make sure that when we grep for `Chef.log_deprecation` we find this and nuke it.

**Comment by lamont-granquist** [comment]
uh, lolwut?

**Pull request merged**
