### PR TITLE
Re-enable AIX mount functional test

### PR DESCRIPTION
**Pull request by juliandunn**
Use the NameFS filesystem type for the test which works inside both LPARs and WPARs.

@scotthain

### CODE REVIEW

**Comment by btm** [comment]
Can you run this through chef-12-trigger-ad_hoc on manhattan CI?

**Comment by scotthain** [comment]
Verified working via manual test on tester :+1:

**Comment by jaym** [comment]
:+1:

**Comment by scotthain** [comment]
@chef/client-maintainers @chef/client-core (sorry, not sure who else to at-mention)

**Comment by btm** [comment]
:+1:

**Pull request merged**
