### PR TITLE
add nokogiri to omnibus-chef

### PR DESCRIPTION
**Pull request by lamont-granquist**
implements first part of https://github.com/chef/chef-rfc/blob/master/rfc063-omnibus-chef-native-gems.md

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core trivial review.  all the hard work got done in omnibus-software libxml/libxslt

**Comment by thommay** [comment]
:clap: :tada: :+1:

**Comment by coderanger** [comment]
Our long nightmare is over. Now we can find whole new errors to be irrationally tableflip about!

**Comment by lamont-granquist** [comment]
http://manhattan.ci.chef.co/job/chef-12-build/138/

**Comment by lamont-granquist** [comment]
http://manhattan.ci.chef.co/job/chef-12-test/97/ (expected failures in windows + nexus-7 due to other issues on master right now)

**Comment by coderanger** [comment]
For bonus hilarity, nokogiri put out a security release this morning.

**Comment by lamont-granquist** [comment]
that would be more amusing the day after 12.7.0 ships...

**Comment by lamont-granquist** [comment]
actually we already build against our own libxslt/libxml2 so i think we've already fixed those in omnibus-software master...

**Comment by lamont-granquist** [comment]
https://github.com/chef/omnibus-software/pull/550

**Comment by coderanger** [comment]
@lamont-granquist @thommay Did we ever add the rest of the stuff from https://github.com/chef/chef-rfc/blob/master/rfc063-omnibus-chef-native-gems.md?

**Comment by lamont-granquist** [comment]
nope, i still have that written up on my whiteboard as a TODO.

i just got burned out fighting with our build system for awhile.

**Pull request merged**
