### PR TITLE
fix knife list_commands()

### PR DESCRIPTION
**Pull request by lamont-granquist**
this was not supposed to be private

Fixes this:

```
/Users/lamont/.rvm/gems/ruby-2.3.1/gems/chef-12.14.77/lib/chef/application/knife.rb:212:in `print_help_and_exit': private method `list_commands' called for Chef::Knife:Class (NoMethodError)
Did you mean?  subcommands
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/chef-12.14.77/lib/chef/application/knife.rb:176:in `validate_and_parse_options'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/chef-12.14.77/lib/chef/application/knife.rb:154:in `run'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/chef-12.14.77/bin/knife:25:in `<top (required)>'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/bin/knife:23:in `load'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/bin/knife:23:in `<main>'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/lamont/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
added the error for SEO

**Comment by JamesDawson** [comment]
Hi, can you give any indication when this fix will be available in an updated chefdk?

**Comment by thommay** [comment]
@JamesDawson should ship this week if we stay on schedule.

**Comment by JamesDawson** [comment]
Great - many thanks for the quick reply.

**Pull request merged**
