### PR TITLE
Allow unforked interval runs on Windows in solo

### PR DESCRIPTION
**Pull request by tas50**
This matches the behavior of chef-client. I also updated the messaging since no one cares that we allowed it in Chef 11.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
this is the wrong way, we want to disallow unforked interval runs across the board.

**Comment by lamont-granquist** [comment]
https://github.com/chef/chef/pull/6777/files

**Comment by tas50** [comment]
Didn't that not work at all though?

**Comment by tas50** [comment]
NM I see this is the new version of the original change.

**Pull request closed without merging**
