### PR TITLE
extract declare_resource to a mixin and extend API

### PR DESCRIPTION
**Pull request by lamont-granquist**
- extract to its own mixin so it can be included without
  method_missing and the rest of the resources DSL
- add ability to inject different run_context
- add ability to create_if_missing into the resource_collection

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core and @thommay @coderanger and @jkeiser in particular, plus maybe @danielsdeleo 

want to get thoughts on this.  i'll write specs if everyone is okay with it.

this is something that i've discussed with john before, which is pulling out declare_resource and build_resource into their own mixin so that classes could include them without pulling in the whole recipe DSL.   i've wanted this in my own classes that i've written.  i've also strongly considered adding this mixin to Chef::Resource and Chef::Provider directly (which i think was the direction dan wanted to take declare_resource and build_resource eventually).

by mixing this into Chef::Resource that is also one way to work around #4006 when you have a property called 'template' that overrides using the template resource in the DSL.

plus, there's the extensions to build_resource/declare_resource to better support writing accumulator patterns in resources instead of definitions.  this addresses #4117.  i was going to include a pointer to the multipackage resource that used this code, but i appear to not have pushed that remotely and my computer at home is powered down right now due to the windstorm power outage this AM...

comments?  suggestions?  better name for 'create_if_missing'?

**Comment by danielsdeleo** [comment]
> which i think was the direction dan wanted to take declare_resource and build_resource eventually

Mostly I wanted to make the method_missing shim as thin as possible, and expose the functionality so people could do whatever crazy things they wanted with recipe macros in a more responsible way.

That said, I do like the idea of being able to use a thing that's in between the full recipe DSL (which has the problems you describe, things like `template` and `file` get mixed in) and having to do fully manual resource instantiation (this would be less of a pain if the resource constructors took blocks, though now we have a whole new layer of indirection there, which would be nice to wrap up).

**Comment by thommay** [comment]
Needs tests for the new bits

**Comment by lamont-granquist** [comment]
@chef/client-core new bits now have tests

**Comment by tyler-ball** [comment]
:+1:

**Pull request merged**
