### PR TITLE
Added code to handle deletion of directories on Windows that are symlinks.

### PR DESCRIPTION
**Pull request by Aliasgar16**
In-progress.

### CODE REVIEW

**Comment by Aliasgar16** [comment]
Done.

**Comment by mwrock** [comment]
:+1: but would be cool to add an integration test

**Comment by Aliasgar16** [comment]
@mwrock as per the discussion with you, I have added functional specs for the fix added in this PR.

**Comment by btm** [comment]
:+1: travis failure is a known chef-zero issue.

**Comment by mwrock** [comment]
:+1: to functional test

**Pull request merged**
