### PR TITLE
pass ssh_password to session

### PR DESCRIPTION
**Pull request by sawanoboly**
This PR is part of #3959 

I want to recover regression of master to rescue integration testing my plugin. https://circleci.com/gh/higanworks/knife-zero/tree/integration_testedge

### CODE REVIEW

**Comment by coderanger** [comment]
:+1:

**Comment by coderanger** [comment]
Can be merged once we get confirmation from the CLA bot /cc @thommay @jaym

**Comment by coderanger** [comment]
@jkeiser This is a reversion from 12.4, so should end up in 12.5.

**Comment by thommay** [comment]
seems sensible :+1:

**Pull request merged**
