### PR TITLE
Use double quotes by default

### PR DESCRIPTION
**Pull request by thommay**
This is an entirely mechanically generated (rubocop -a) change, to go
along with chef/chefstyle#5 . We should pick something and use it
consistently, and my opinion is that double quotes are the appropriate
thing.

cc @chef/client-maintainers

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Popcorn

:+1:  for the record...

**Comment by sethvargo** [comment]
The diff crashes my browser, so I'll trust that you haven't snuck in any sneak codes :+1:

**Comment by ksubrama** [comment]
http://gifsec.com/wp-content/uploads/GIF/2014/04/Mr.-Trololo-Guy-GIF.gif?gs=a

:+1:

**Comment by stevendanna** [comment]
Using `git diff master~17..head --word-diff=porcelain --no-color -U0` on this branch and some truly horrible command line munging, I'm pretty confident our friend @thommay isn't trying to backdoor us. :D :+1:

**Pull request merged**
