### PR TITLE
[WIP]Update chef-foundation to pull in openssl 3.0.9

### PR DESCRIPTION
**Pull request by neha-p6**
`chef-foundation` 3.1.21 pulls in openssl 3.0.9. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tpowell-progress** [comment]
Waiting on Release of 18.4. I think we want to at least bump the minor version again prior and we definitely don't want to delay the readiness status of 18.4 with a bump yet.

**Comment by rahulgoel1** [comment]
@neha-p6  I and @tpowell-progress  had a chat. Chef foundation 3.1.17 has the open ssl upgrade but not 3.1.20 . We had to rollback that change and regenerate chef foundation to get a chef 18 release. However for all testing purposes we can use 3.1.17.

**Comment by neha-p6** [comment]
> @neha-p6 I and @tpowell-progress had a chat. Chef foundation 3.1.17 has the open ssl upgrade but not 3.1.20 . We had to rollback that change and regenerate chef foundation to get a chef 18 release. However for all testing purposes we can use 3.1.17.
Noted. Thanks for the update.

**Comment by neha-p6** [comment]
https://buildkite.com/chef/chef-chef-main-validate-adhoc/builds/1082

**Comment by tpowell-progress** [comment]
@neha-p6 chef-foundation 3.1.21 should be ready for testing OpenSSL 3.0.0

**Comment by neha-p6** [comment]
OpenSSL 3.0.9 https://buildkite.com/chef/chef-chef-main-validate-adhoc/builds/1252

**Pull request closed without merging**
