### PR TITLE
Add myself as a core maintainer.

### PR DESCRIPTION
**Pull request by coderanger**
I would really rather we split the DSL and Resource machinery in to a component because I'm definitely not able to call myself a maintainer for the "and everything else" part, but waiting to get my patches merged is getting annoying.

### CODE REVIEW

**Comment by jaym** [comment]
:cake:

**Comment by ranjib** [comment]
@coderanger which patches of yours are in queue ? i can take a look during the weekend

**Comment by mcquin** [comment]
:+1:

@coderanger It'd be really cool if we could have a DSL-focused maintainer subteam, I'd totes join it with you. =)

**Comment by coderanger** [comment]
Ping @adamhjk, what say ye about making "DSL plumbing" a component?

**Comment by adamhjk** [comment]
Lets talk about it at the next meeting. I'm all for more people having commit bits - I could also see this just being part of "core". (Mostly I'm thinking about how we talk about routing PRs and such to this proposed new team)

**Comment by mcquin** [comment]
@adamhjk I agree that routing PRs could be difficult.

@thommay Is there a way to ping/assign people based on which files are modified in the commit? For example, the DSL maintainers would be pinged/assigned if there were any changes to `lib/chef/dsl.rb`, `lib/chef/dsl/*`, `lib/chef/provider*.rb`, `lib/chef/provider/*`, `lib/chef/resource*.rb`, `lib/chef/resource/*`?

**Comment by ranjib** [comment]
similar to chef-config we can split chef-core . that will ease this as well as lot other things ... :-) .

**Comment by danielsdeleo** [comment]
We don't need a majority for any merges except when someone has protested/attempted a veto, so it's fine if the scope is a bit bigger than you feel comfortable with, you can just abstain if you don't feel qualified to review a particular patch. Anyway, :+1: to the question at hand.

**Comment by lamont-granquist** [comment]
We can logically split things up without actually splitting up the code.  After all that is how Windows, Ubuntu, etc is done.

The only real burdensome issue with being a core chef maintainer is getting the mailing list pings, but that can be dealt with e-mail filters, threaded mail readers and the delete key...

:+1:  anyway

**Comment by thommay** [comment]
@mcquin so the maintainers.toml has a concept of paths: https://github.com/chef/chef/blob/master/MAINTAINERS.toml#L53-L59
But they need filling out for the teams. Supermarket doesn't do anything with them (yet!).

I'm pretty neutral on adding a DSL maint team - I think as Dan says if you're only comfortable reviewing part of a PR, then just do that and make sure that your comments make it obvious that that's what's happened.

**Comment by thommay** [comment]
:+1: for this though. Merging!

**Pull request merged**
