### PR TITLE
fix chefstyle failures

### PR DESCRIPTION
**Pull request by lamont-granquist**
autocorrects some merges that will be broken when the next
chefstyle is released.

also runs chefstyle after the travis tests, because i'd rather know
how the code is broken rather than how its not pretty.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core this mostly just fixes stuff that we've already fixed before.

we need a chefstyle release to start enforcing all these rules.

the fact that we equality pin on chefstyle while travis does not do tests against rebased master is pretty annoying since people will only get whatever chefstyle rules were present when they forked.  we may actually want to let chefstyle float while having it equality pin rubocop...

**Comment by danielsdeleo** [comment]
> we may actually want to let chefstyle float while having it equality pin rubocop...

We should give this a go.

And :+1: on this PR, too

**Comment by lamont-granquist** [comment]
added removing the chefstyle pin to this PR...

**Comment by thommay** [comment]
I equality pinned because that's what we talked about in the RFC, but I think this makes much more sense, especially whilst we come up with a rule set. :+1:

**Comment by thommay** [comment]
(we could equally float on master, with the assumption that rules only get merged to chefstyle once they're fixed here)

**Comment by lamont-granquist** [comment]
I thought you were POETSing?  =)

I think we can start by floating on rubygems so that we can merge to master in chefstyle, and fix here and ohai, and then release the gem later to start enforcing.  I'm also testing rebasing chef/chef to master before running rspec in travis...

**Pull request merged**
