### PR TITLE
add Joe Miller as LT for OpenBSD

### PR DESCRIPTION
**Pull request by joemiller**
ref: https://github.com/chef/chef-rfc/pull/130

### CODE REVIEW

**Comment by fujin** [comment]
:+1:

**Comment by thommay** [comment]
:+1: :100: :tada:

**Comment by jonlives** [comment]
:+1:

**Comment by ranjib** [comment]
:+1: yay

**Comment by btm** [comment]
@joemiller I added you to @chef/maintainers, @chef/client-maintainers, and created @chef/client-openbsd.

**Pull request merged**
