### PR TITLE
[Chef-16] Backport: Updating Zypper to overcome repository errors

### PR DESCRIPTION
**Pull request by johnmccrae**
Signed-off-by: John <john.mccrae@progress.com>

s390x images were throwing errors when loading updates because they were attempting to connect to the localhost instead of the Internet to get updates.

## Description
The issue for this turned out to be that at some point in the automation process before the chef-client code runs, something is creating/adding Zypper respositories that point to the localhost. That is totally busted since there are no files locally to support that and there is no way to pull down new files outside of the busted local repos.

The cause of that issue has not been fully determined but we did workaround that issue by doing 2 things: 1) Sean manually deleted the borked repos on those images. (they don’t get recycled like other OS images do). and 2) I added to code to programmatically do what he did if/when new s390x images show up.

The fix is to 1) Simply nuke the existing repos, 2) Add my new chefzypper-repo and 3) Use gpg to sign the new repo so we don’t get weirdo crypto errors.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Review by tpowell-progress — APPROVED** [review]

**Review by neha-p6 — COMMENTED** [review]
@johnmccrae  Do we have an adhoc build testing this before we merge??

**Review by neha-p6 — CHANGES_REQUESTED** [review]
@johnmccrae  Do we have an adhoc build for chef16 testing this before we merge??

**Comment by neha-p6** [comment]
> @johnmccrae Do we have an adhoc build for chef16 testing this before we merge??

NVM. I created one https://buildkite.com/chef/chef-chef-chef-16-omnibus-adhoc/builds/141
Waiting for build to pass through.

**Comment by johnmccrae** [comment]
This PR was replaced by a script added to the /scripts folder called zypper_prep.sh that subsumes the corrections made here.

**Pull request closed without merging**
