### PR TITLE
Pin oc-chef-pedant to prevent unintended test slippage

### PR DESCRIPTION
**Pull request by jkeiser**
Because chef-zero is pinned, oc-chef-pedant must be pinned too (as its test suite). They must move forward together or not at all. This difference caused a Travis breakage the other day.

### CODE REVIEW

**Comment by stevendanna** [comment]
@jkeiser I thought that the problem was more about the Gemfile in the `chef-zero` gem itself, since during the test we cd into that gem and bundle install from there?

**Comment by jkeiser** [comment]
@stevendanna it absolutely is, but when we run chef-zero's tests, we honor any pins from `chef` itself if it has them. The previous PR from this branch had fixed `chef-zero` by pinning `oc-chef-pedant` to its older version.

These are `integration` pins only and will only affect the tests, so this is a way to get us where we want to be cheaply. Long run, we probably want to keep pins for the actual downstreams as well, but I'm not ready to make *another* pinning system right now.

**Comment by stevendanna** [comment]
> we honor any pins from chef itself if it has them.

Ahhh, missed that bit. Cool 👍

**Comment by mwrock** [comment]
If travis likes it I'm :+1:

**Comment by jkeiser** [comment]
Appveyor succeeded earlier, the rebase just cancelled. Merging.

**Pull request merged**
