### PR TITLE
Enforce chef_type validation #5086

### PR DESCRIPTION
**Pull request by cramaechi**
### Description

With `knife environment from file` or `knife role from file`, the
chef_type specification is not enforced. A user can easily upload an
environments JSON as a role by doing this: knife role from file
Dev.json, when Dev.json is really an environments file.

Signed-off-by: Chibuikem Amaechi <cramaechi@me.com>

### Issues Resolved

No preexisting issue(s).

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by cramaechi** [comment]
Updated pull request with unit tests.

**Comment by lamont-granquist** [comment]
validation should probably be done in the models themselves so it wouldn't load a role as an environment from a file at all then we don't have to sprinkle validation around the consumers of the model objects.

and should probably be common code across all the data models and not copypasta'd around between all the files.

**Comment by cramaechi** [comment]
Hi @lamont-granquist,

I centralized the validation code in `lib/chef/knife/core/object_loader.rb`, which will now be accessible to all relevant model classes.

**Comment by cramaechi** [comment]
Hi @lamont-granquist,

I centralized the validation code in `lib/chef/knife/core/object_loader.rb`, which will now be accessible to all relevant model classes.

**Comment by lamont-granquist** [comment]
closing this in favor of tracking it in #8829

**Pull request closed without merging**
