### PR TITLE
adding pry and pry-byebug to dev dependencies

### PR DESCRIPTION
**Pull request by mwrock**

### CODE REVIEW

**Comment by coderanger** [comment]
Any particular reason? If it's for interactive debugging of failed tests it might be good to put it in the Gemfile in a group that CI won't install, just to save some cycles. Might not matter much given that travis caches gems though.

**Comment by mwrock** [comment]
Yeah just for dev. I'll move to Gemfile.

**Comment by coderanger** [comment]
pry is, I think pure Ruby but byebug has some C heft to it so makes me pay slightly more attention to CI overhead :)

**Comment by mwrock** [comment]
glad someone is paying attention :)

**Comment by mwrock** [comment]
stripped out commented external test entries but I can put them back if they were left commented for a reason.

**Comment by coderanger** [comment]
I think that's still under the `:test` group, but upon further investigation this is moot for now. Appveyor doesn't use `--without development` and Travis caches compiled gems so benefit on either.

:shipit:

**Comment by lamont-granquist** [comment]
you could add pry-stack-explorer as well.   we already ship all three of these in the omnibus-chef package, so we know they're portable enough.

**Comment by mwrock** [comment]
added that @lamont-granquist had not heard of that - looks very cool.

**Comment by jkeiser** [comment]
:+1:

**Pull request merged**
