### PR TITLE
Disable Travis CI container infrastructure due to broken IPv6 support

### PR DESCRIPTION
**Pull request by juliandunn**
I think our IPv6 tests are failing on Travis because of this: https://github.com/travis-ci/travis-ci/issues/3302

Thoughts?

### CODE REVIEW

**Comment by jdmundrawala** [comment]
I say give it a shot, but they fail on my local box as well

**Comment by juliandunn** [comment]
Well that seemed to work @jdmundrawala so I'll merge this... trivial to roll it back if something unexpected happens.

**Comment by jdmundrawala** [comment]
@juliandunn those tests only run when you merge
https://travis-ci.org/chef/chef/builds/60470575 is the build for your merge

**Comment by juliandunn** [comment]
Sigh. Well, I tried :frowning:

**Comment by jdmundrawala** [comment]
@juliandunn can you revert this since it didn't work

**Comment by juliandunn** [comment]
all done

**Pull request merged**
