### PR TITLE
Update override path

### PR DESCRIPTION
**Pull request by scotthain**
@chef/client-core @chef/engineering-services

### CODE REVIEW

**Comment by thommay** [comment]
Some explanation in the comment as to why we shouldn't use `__FILE__` would be very helpful here.

**Comment by lamont-granquist** [comment]
yeah what happens to `__FILE__` that makes it so we can't use it?  i'm puzzled...

**Comment by scotthain** [comment]
@thommay @lamont-granquist updated comment as follows:
```
# Do not use __FILE__ after this point, use current_file. If you use __FILE__
# after this point, any dependent defs (ex: angrychef) that use instance_eval
# will fail to work correctly.
```

**Comment by thommay** [comment]
👍 thanks @scotthain

**Comment by lamont-granquist** [comment]
oh right...

👍

**Comment by scotthain** [comment]
@thommay y'alls do the merging yourself in chef/chef these days, right?

**Comment by schisamo** [comment]
@scotthain You can merge after you get enough 👍 's (which I think you have).

**Pull request merged**
