### PR TITLE
Properly use chef-shell in SoloSession by deprecating old behavior into SoloLegacySession

### PR DESCRIPTION
**Pull request by afiune**
### Description

As a person who debugs chef cookbooks with chef-shell, I should be able to connect to a local chef-zero instance with chef-shell, so that I can more easily debug my cookbooks in server mode.

### Issues Resolved

https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/8783605-chef-shell-with-chef-zero-local-client-mode-supp

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [x] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by tduffield** [comment]
This feels like something that would require some documentation updates, both in the RELEASE_NOTES and to docs.chef.io.

**Comment by rhass** [comment]
Looks like travis hit snag.

**Comment by tduffield** [comment]
Calling on @chef/client-core to get some reviews :) Would like to get this closed.

**Comment by thommay** [comment]
You'll need to re-push for RELEASE_NOTES once this has received enough reviewers.

**Pull request merged**
