### PR TITLE
let the ruby patchlevels float

### PR DESCRIPTION
**Pull request by lamont-granquist**
test latest 2.0.x, 2.1.x, 2.2.x

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core @chef/client-engineers i don't think anyone is actively bumping these so we should probably just let travis bump them automatically.

**Comment by jdmundrawala** [comment]
go for it

**Comment by danielsdeleo** [comment]
:+1:

**Comment by tyler-ball** [comment]
:+1:

**Pull request merged**
