### PR TITLE
Link to the knife docs when the knife config file is missing

### PR DESCRIPTION
**Pull request by tas50**
This is a pretty common first error message to experience with Chef. Let's point the users to a helpful location so they can quickly get up and running.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
ohai_hint resource snuck in here

**Comment by tas50** [comment]
let me nuke that out

**Comment by thommay** [comment]
If the user is using `config.rb` talking about `knife.rb` will be pretty confusing, but I like the intent.

**Comment by tas50** [comment]
I'd agree, but we never actually documented config.rb in the workstation and knife docs. I'm not sure how many people are using that.

**Comment by thommay** [comment]
I don't entirely understand why it's in the ChefDK docs, but the Configuration topic there is all about config.rb. So we are telling people about it.

**Comment by tas50** [comment]
Updated to not mention knife.rb specifically, but still send you to the docs

**Pull request merged**
