### PR TITLE
Fixed windows share is not idempotent when using local groups

### PR DESCRIPTION
**Pull request by sanga1794**
## Description
windows_share is not idempotent when using local groups

## Related Issue
Fixed: https://github.com/chef/chef/issues/9242

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tas50** [comment]
@sanga1794 Can you add some specs for the various scenarios of user inputs? We'll want to make sure whatever solution works for local users with the hostname, local users w/o the hostname, and domain users.

**Comment by sanga1794** [comment]
Hi @tas50, I have added some specs

   ```
when full_users are passed
    behaves like when users are passed
      add hostname to user with hostname
      add hostname to user without hostname
  when change_users are passed
    behaves like when users are passed
      add hostname to user with hostname
      add hostname to user without hostname
  when read_users are passed
    behaves like when users are passed
      add hostname to user with hostname
      add hostname to user without hostname
```


@tas50, if still missing something, please do inform

**Comment by sanga1794** [comment]
@tas50 Please review the change.
Thanks!!

**Comment by tas50** [comment]
Something went wrong in this rebase and it brought in a bunch of other commits.

**Comment by sanga1794** [comment]
Duplicate PR https://github.com/chef/chef/pull/10122

**Pull request closed without merging**
