### PR TITLE
Revert deprication commit to fix travis

### PR DESCRIPTION
**Pull request by mwrock**
Reverts chef/chef#5022 which is breaking the poise travis tests.

### CODE REVIEW

**Comment by coderanger** [comment]
:-1: This should be fixed on the Poise side.

**Comment by coderanger** [comment]
(and I'm working on that :)

**Comment by mwrock** [comment]
sweet @coderanger if you are on that and can get it green fairly quickly then I agree its the way to go.

**Comment by coderanger** [comment]
Poise master is green again.

**Pull request closed without merging**
