### PR TITLE
Add .mailmap for top contributors

### PR DESCRIPTION
**Pull request by stevendanna**

### CODE REVIEW

**Comment by nathenharvey** [comment]
@stevendanna can you look at the failed build?

**Comment by stevendanna** [comment]
Like 70% of the cases of failed builds for my PRs against this repo, the failure seems to have nothing to do with the change presented here.

**Comment by lamont-granquist** [comment]
@nathenharvey I've been using "incomplete contribution" to close PRs that don't have specs, etc where we can't rescue them so they're without prejudice (sorta like an incomplete grade).  the "waiting for contributor response" tag should be used as part of the normal workflow to kick it back to the contributor.

**Comment by lamont-granquist** [comment]
@stevendanna you wanna %s/opscode.com/chef.io/ and whack merge?

**Comment by nathenharvey** [comment]
thanks, @lamont-granquist!

**Comment by stevendanna** [comment]
@lamont-granquist I've updated this with chef.io for those in the top 25 who (1) have a chef.io address and (2) have been contributing under their Chef-related email address.

**Pull request merged**
