### PR TITLE
Bump to ruby 2.5.0

### PR DESCRIPTION
**Pull request by thommay**
Fixes: #6774

### CODE REVIEW

**Comment by tas50** [comment]
Probably wanna turn on 2.5 in AV too since they have the image now

**Comment by lamont-granquist** [comment]
appveyor looks busted for real-looking ruby 2.5 reasons?  certainly the Chef::Exception error looks like another class namespacing issue.

**Comment by lamont-granquist** [comment]
it's a christmas miracle!  appveyor is passing!

omnibus builds are super-hosed tho.

**Comment by lamont-granquist** [comment]
@chef/client-maintainers this is ready to go

**Pull request merged**
