### PR TITLE
Fixing Issue #2513 - the broken render of nested partial templates

### PR DESCRIPTION
**Pull request by ckaushik**
Adding the instance variable @template_finder to the new TemplateContext class for rendering partials

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @ckaushik

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by samdunne** [comment]
Can someone look at this?

**Comment by thommay** [comment]
This looks reasonable; :+1: 
@chef/client-core

**Comment by tyler-ball** [comment]
Can https://github.com/chef/chef/blob/master/spec/unit/mixin/template_spec.rb be updated with a test for this?

**Comment by danielsdeleo** [comment]
I'm okay to merge if we need it **now** to fix the broken, but this really deserves a regression test to ensure it works in the future.

**Comment by ckaushik** [comment]
Can we merge it now to fix the broken template rendering?

**Comment by samdunne** [comment]
I added regression testing here: https://github.com/ckaushik/chef/pull/1

@ckaushik will you merge this into your PR?

**Comment by ckaushik** [comment]
@danielsdeleo does this look good for merging?

**Comment by danielsdeleo** [comment]
Nice! :+1:

**Comment by tyler-ball** [comment]
:+1:

**Pull request merged**
