### PR TITLE
Update our PowerShell code with PSScriptAnalyser recommendations

### PR DESCRIPTION
**Pull request by johnmccrae**
## Description
I changed the function names to match approved PowerShell verbs and updated the call into 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tas50** [comment]
@johnmccrae Can you sign off this commit with the DCO so we can accept it? Also can you tell us why this change is being made in the PR description?

@stuartpreston @mwrock care to take a peak at this?

**Comment by stuartpreston** [comment]
This looks mostly to be PSScriptAnalyser reccomendations for changes, e.g. using verbs from the [Approved Verb List](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands), adjusting the fallthrough from if { } statements across the module and fixing the spacing in line with typical PS standards (though these are not strictly necessary), am I right @johnmccrae? Have we done a sweep across the codebase to ensure we don't call into these functions as an entrypoint from any other modules (e.g. in Chef Workstation?).

Also needs DCO signoff to proceed.

**Comment by johnmccrae** [comment]
Stuart, yes. That's pretty much it. I figured if we're going to publish modules, we should be following the standards.

**Comment by tas50** [comment]
@johnmccrae I'm with Stuart on this. Make sure we're not using any of the old method calls anywhere and then we can merge this.

**Comment by tas50** [comment]
Ping @johnmccrae can this get updated please?

**Comment by tas50** [comment]
@johnmccrae We haven't heard back from you so I'm going to close this out now. Feel free to open this up with the suggestions I left earlier.

**Pull request closed without merging**
