### PR TITLE
Remove test stuff from the changelog

### PR DESCRIPTION
**Pull request by tas50**
No need to add these to the changelog. Also fixup the wording of the
windows_task change since that's super important and people should know
about it.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
I'm kind of philosophically opposed to manually hacking up the ChangeLog and think we need to get back to PR titles being the source of truth and being able to regen the ChangeLog (completely) from information in github.   If we just had a log of which version numbers were promoted releases we would have all the information necessary to do that.

**Comment by thommay** [comment]
@lamont-granquist 🙈 we went away from that because it was such a total disaster. I think hacking up the changelog after the fact in general is not worth the time, but I definitely do not want us to change our current approach.

**Comment by tas50** [comment]
In the ideal world we'd just get the names right the first time and use the nice new labels to exclude appveyor and travis changes from the changelog. I updated this one primarily because the windows_task change is super significant and we have users waiting on that. The title of the PR was cryptic and not something you could search for. I try to tag things for exclusion and fixup the names as I see them, but it's a best effort sort of thing.

**Comment by lamont-granquist** [comment]
Driving the changelog entirely off the issues and PR titles worked great up until we went down the crazy CI version numbering route.   All we'd need to get back to that was a list of the promoted versions (which is 98% captured in rubygems.org) and we
could teach the changelog generator to construct changelogs entirely from the issue contents and that version log.  Where it all went horribly wrong is with the badly non-declarative approaches we tried to use to incrementally generate the changelog and mangled the crap out of it.  Before that it was working pretty well.

**Pull request closed without merging**
