### PR TITLE
use rb-readlin on unix as well as windows

### PR DESCRIPTION
**Pull request by lamont-granquist**
necessary for ruby-2.2.4

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core @chef/client-windows needs chef/omnibus-software#627

**Comment by mwrock** [comment]
:+1:

**Comment by ksubrama** [comment]
:+1:  Does that mean you can change the ruby software def to leave out libedit?

**Comment by lamont-granquist** [comment]
@ksubrama i think you already found that -- yep.

**Pull request merged**
