### PR TITLE
Make chef-fips pipeline build everything from source.

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by ksubrama** [comment]
@btm @jaym @adamedx @schisamo 

The Berksfile.lock we were using here was extremely stale and was breaking when I was attempting to use test-kitchen on local windows builders.  I've blown it away on advice from @schisamo.  I'll fixup Gemfile.lock once the omnibus-software PR is merged.

**Comment by btm** [comment]
looks good. I presume this is :construction: until it passes the chef-fips pipeline, and will note that it looks like it contains the git-cache stuff that we were discussing needs testing over on https://github.com/chef/omnibus/pull/613.

**Comment by ksubrama** [comment]
@btm Yes - I'm planning on manually leaving this pipeline pinned to that branch for a while to test it before it goes into master.

**Comment by ksubrama** [comment]
It's done!  chef-fips pipeline passes.

**Pull request merged**
