### PR TITLE
Change chef service to start as 'Automatic delayed start'.

### PR DESCRIPTION
**Pull request by ksubrama**
This pull request is blocked on https://github.com/djberg96/win32-service/issues/27
The tests won't pass until that is fixed and a new release cut.

### CODE REVIEW

**Comment by ksubrama** [comment]
Addresses part of #2814

**Comment by jaym** [comment]
nice... maybe pin the gem to a version without the bug?

**Comment by ksubrama** [comment]
I'd rather just wait.  The maintainer is cool and already has a patch out at https://github.com/djberg96/win32-service/pull/28.  I'll test that out.

**Comment by ksubrama** [comment]
@jaym Changed the pin to the new release.

**Comment by jaym** [comment]
:+1:

**Comment by ksubrama** [comment]
@chef/client-windows One more +1 ?

**Comment by smurawski** [comment]
:+1:

**Pull request merged**
