### PR TITLE
Adding Chef::Mixin::Command back to Package provider base class

### PR DESCRIPTION
**Pull request by jdmundrawala**
This was removed in #2924, however it breaks at least the yum
provider.

Without this patch, I was getting:
```
    NoMethodError
    -------------
    undefined method `output_of_command' for #<Chef::Provider::Package::Yum:0x00000003a5f278>
```
when trying to execute

```ruby
package "gdb" do
  action :install
end
```

on Centos 6.5

Chef was breaking in weird ways and it didn't produce a stacktrace.out,
which was a little concerning, however that's a different bug

This is required for Chef 12.1 as it a regression that would really suck to ship (it breaks the apache cookbook for sure).

cc @btm @lamont-granquist @jonlives

### CODE REVIEW

**Comment by lamont-granquist** [comment]
can we convert the output_of_command() calls to shell_out() instead?

**Comment by btm** [comment]
If we're no longer calling handle_command_failures we should be able to remove this line:
```
require 'chef/mixin/command' # handle_command_failures
```

**Comment by lamont-granquist** [comment]
LGTM

**Comment by tyler-ball** [comment]
:+1:

**Comment by danielsdeleo** [comment]
We should see if we can enable this rspec option: https://relishapp.com/rspec/rspec-mocks/v/3-0/docs/verifying-doubles/partial-doubles which would have failed the unit tests w/ this bug.

**Comment by jdmundrawala** [comment]
https://github.com/chef/chef/pull/2998

**Comment by btm** [comment]
:+1:

**Comment by lamont-granquist** [comment]
@danielsdeleo we could also try to get some integration test coverage that ran on centos and/or exercising this codepath in the e2e test that runs on centos out of T-K.

**Pull request merged**
