### PR TITLE
Fix for package upgrading

### PR DESCRIPTION
**Pull request by hulu1522**
`pkgin` has an issue where it sorts packages by string.  This fix will allow upgrading to happen successfully.

### CODE REVIEW

**Comment by hulu1522** [comment]
Fix for #3811

**Comment by hulu1522** [comment]
Don't know how to fix the tests but my image only has varnish `3.0.5` and your test is failing on varnish `2.3.4`.

```
~# pkgin se varnish
varnish-3.0.5nb1     High-performace HTTP accelerator

=: package is installed and up-to-date
<: package is installed but newer version is available
>: installed package has a greater version than available package
```

**Comment by lamont-granquist** [comment]
Those are unit tests which run on Linux and Windows (which definitely doesn't have varnish installable via pkgin), so the tests must be stubbing the underlying pkgin calls.  Something in your patch has broken the unit tests and needs to get fixed (likely the unit tests were incorrect and also need fixing for the new behavior).

**Comment by lamont-granquist** [comment]
This looks like it'd be easy enough to salvage, but we just don't have the time to do it ourselves.

**Comment by hulu1522** [comment]
I apologize for not responding to this.  I just don't know enough about the unit testing to be of assistance.  The main goal of the request was to organize the results so the latest version would be on bottom.  By default Chef will choose the last package in the list even if the version is not the latest.  I also don't have time to help solve this so I guess close it as a 'known issue' or hope someone else can pick it up.  Thanks.

**Pull request closed without merging**
