### PR TITLE
Test case execution incase FIPS  exists

### PR DESCRIPTION
**Pull request by ghatwala**
### Description

As requested in the issue to raise a PR to edit the readme so that the test cases pass on any linux box which has FIPS enabled.

chef#5533

@thommay - please kindly review the PR.

[Please describe what this change achieves]

### Issues Resolved
All test cases pass now in a linux box which has FIPS enabled once path has been exported .

Test cases were failing as mentioned in issue : https://github.com/chef/chef/issues/5533

### Check List
All tests pass

Signed-off-by: Amit Ghatwal ghatwala@us.ibm.com

### CODE REVIEW

**Comment by ghatwala** [comment]
Signed-off-by: Amit Ghatwal <ghatwala@us.ibm.com>

**Comment by lamont-granquist** [comment]
I'm not sure that's really the right way to go about fixing this.

Its very one-off and its likely that not very many people will have FIPS enabled and will hit this (certainly you're the first).  For 99% of the people reading that it is just additional cognitive overhead.

Really the specs should get fixed so that they just-work when FIPS is enabled on the box.

I'd actually kind of prefer just to close both issues, and let someone who google searches find the issue and find the workaround, rather than formally documenting the workaround.

**Comment by ghatwala** [comment]
Hi @lamont-granquist  ,

I had raised this PR on the comment given by @thommay  ( chef contributor ) 

**@ghatwala we'd be happy to accept a PR that adds that.** 

@thommay  -  could u comment on the above if this PR is needed  ?

**Comment by shortdudey123** [comment]
> Really the specs should get fixed so that they just-work when FIPS is enabled on the box.

Completely agree with this part, working around spec failures is never really a good idea

**Comment by ghatwala** [comment]
@shortdudey123, @lamont-granquist , @thommay  - I understand that working around specs failures isn't a good way to resolve the test case failures issue .

Are we planning to looking at failing test cases on a linux box where FIPS is enabled , if yes , do let me know if u guys need any more information from my end ?

Thanks for considering this issue.

**Comment by thommay** [comment]
After reflection, I agree with Lamont; let's just close this and let google turn up the issue. We clearly need to redo the specs to cope with FIPS mode, but that's a rather larger kettle of fish.
@ghatwala thanks for your patience with this, and thanks for the PR!

**Comment by ghatwala** [comment]
@thommay : Thanks for concluding no this for now . Please do include me in future threads about FIPS mode.

**Pull request closed without merging**
