### PR TITLE
add shell_out to resources

### PR DESCRIPTION
**Pull request by lamont-granquist**
allows for using shell_out! and friends in not_if/only_if blocks

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@client-core this one is pretty simple, not sure if its a bikeshed or not.  we did something similar pulling shell_out into Chef::Provider for convenience there.

**Comment by lamont-granquist** [comment]
Make that @chef/client-core to get the notification right.  Needs review.

**Comment by danielsdeleo** [comment]
https://github.com/garybernhardt/base :laughing: 

Joking aside, I think this is fine. :+1:

**Comment by lamont-granquist** [comment]
All About That Bass

**Comment by lamont-granquist** [comment]
@chef/client-core need another :+1:

**Comment by ranjib** [comment]
:+1:

**Pull request merged**
