### PR TITLE
#3266 Fix bad Windows securable_resource functional spec assumptions for default file owners/groups

### PR DESCRIPTION
**Pull request by dbjorge**
See also issue #3106.

It wasn't 100% clear what the most correct fix path was here. The options I considered were:

1) Update the Windows file providers to explicitly set newly created files with no user-specified group to use the None group SID.
2) Update the spec to always assume the group should be SID.current_user
3) Update the spec to query for the actual defaults and check against them

I avoided 1 because there didn't seem to be any compelling reason to prefer the None-group behavior - there isn't backwards compatibility concern (because the implementation doesn't do it today) and it would be confusing for Chef to make up its own default behavior on top of the OS's already-confusing default behavior.

I avoided 2 because I was concerned about execution cases that I'm apparently not seeing - presumably this test passes in a test kitchen in its current form, which makes me suspect perhaps current_user isn't as accurate as MSDN suggests if, say, a non-interactive service is creating the resource.

This PR implements option 3. It was a little bit more code, but I'm happier with how it turned out. And it does fix about 1/3 of the functional spec failures #3106 mentions (of those I repro on my desktop, at least).

### CODE REVIEW

**Comment by btm** [comment]
@chef/client-windows @ksubrama review?

**Comment by ksubrama** [comment]
:+1:  I read the MSDN specs for the function calls made and this pull request makes sense to me.

Thanks for the work!

**Comment by thommay** [comment]
@chef/client-windows can we get another review on this please?

**Comment by btm** [comment]
:+1:

**Comment by dbjorge** [comment]
Thanks all!

**Pull request merged**
