### PR TITLE
gem_package, chef_gem should not shell out to using https://rubygems.org

### PR DESCRIPTION
**Pull request by pburkholder**
Some users will not be able to use rubygems.org and will specify the remote source. If their source doesn't have the gem, then `gem` will try the next source. If DNS resolves, then you'll get timeouts. 

Or even if they are able to use rubygems.org, they may be unpleasantly surprised when the 'rubygems.org' version of a gem appears unexpectedly.

I've not added any specs for this, pending discussion, but I will if this seems like the right way to go.

Also, given that Hash options provides better control of gem_package options, should we issue a warning when shelling out?

--Peter

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Problem is that this might be a breaking change.  Right now some people may be dependent upon the rubygems.org source getting added when they don't specify it.  We probably need some kind of always_add_rubygems_source which defaults to true and people can set to false.  Wire it up with a Chef::Config default option that is where the true default comes from now and the people can globally disable it for their runs.  Then we can switch the default in the future as a breaking change.

The source should also probably be an array-or-string on the resource which gets coerced into an array with [ source ].flatten and supports multiple sources specified on the resource.  Then the always_add_rubygems_source default of false would just have the default value initialized to rubygems.org

**Comment by pburkholder** [comment]
Not sure I follow how this is a breaking change, as it would only apply when a source attribute explicitly is remote. If it does seem to be breaking change, then hold it for 12.2?

Also, the behavior should change _only_  if the user has been inadvertently fetching gems from rubygems.org instead of the designated source, and the breakage should be in the form of failure instead of switching the gem out from underneath (because the designated source failed to provide the gem, and now rubygems.org is no longer there to provide their version).

Still, I hear your reluctance....

**Comment by lamont-granquist** [comment]
Right, but someone may be bug dependent upon the behavior you're change and want the behavior of hitting their internal mirror first and then always hitting rubygems (e.g. their internal gem source being additive rather than a full rubygems mirror).  So your "inadvertently" becomes another person's "but that's exactly the behavior I wanted".  Gotta be careful there.

**Comment by stevendanna** [comment]
Perhaps add a new options include_rubygems (might need a better name that captures the nuance) which defaults to true.  We can then change the default to false in a future major version.

**Comment by pburkholder** [comment]
Yeah 'fallback_to_rubygems'   Good idea.

P.

On Sun, Feb 8, 2015 at 6:15 AM, Steven Danna <notifications@github.com>
wrote:

> Perhaps add a new options include_rubygems (might need a better name that
> captures the nuance) which defaults to true. We can then change the default
> to false in a future major version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef/chef/pull/2867#issuecomment-73406563>.
>



-- 

*Peter Burkholder* — Customer Success Engineer

Availability: no travel/OOO scheduled

301-204-5767 – pburkholder@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/pburkholder>  Twitter
<http://www.twitter.com/pburkholder>  Cal
<https://www.google.com/calendar/embed?src=pburkholder%40chef.io&mode=WEEK>
endar

*CHEF*

CHEF.IO <http://www.chef.io/>

TM

*chef.io* <http://www.chef.io/>   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>

**Comment by lamont-granquist** [comment]
yeah FWIW, i think i like `include_rubygems` over `always_add_rubygems_source` or `fallback_to_rubygems`

**Comment by pburkholder** [comment]
Turns out that Gem tries to use rubygems.org unless you also pass `--clear-sources`.  I'll work that in.

**Comment by pburkholder** [comment]
@lamont-granquist @stevendanna 

What do you think about about a gem_package resource attribute, `include_rubygems` or more accurately `clear_gem_sources`?  I'm uneasy about burying a setting deep within Chef::Config and this seems akin to the `compile_time` attribute in terms of changing deprecated behavior.

e.g.

```
gem_package 'my_gem' do
  clear_gem_sources true # defaults to false
  source 'https://my.gem.reop'
end
```

I suggest this because RubyGems includes http://rubygems.org by default, e.g.:

```
Thank you for installing Chef Server!
root@chefserver-0:~# which ruby
root@chefserver-0:~# /opt/opscode/embedded/bin/ruby -e 'p Gem.sources'
["http://rubygems.org/"]
```

so it seems we should provide the ability to remove rubygems.org from both the API and shellout invocations of gem_package (and also chef_gem).

**Comment by lamont-granquist** [comment]
Yeah, start with the resource attribute.  The `clear_gem_sources` option seems fine, although it seems to me like users would want the ability to set that by default as well as setting the default source via the Chef::Config to override everything at their site to point at their mirror.

**Comment by stevendanna** [comment]
@pburkholder I'm :+1: on just starting with the resource attribute for now.  This is a new feature and we can add something more global later if we want.  

> although it seems to me like users would want the ability to set that by default as well as setting the default source via the Chef::Config to override everything at their site to point at their mirror.

This is true of a lot of resource attributes.  In the past we've talked about a place where you could drop config to change the default for a resource attribute.  However, in a world of sharable cookbooks, I haven't thought of a way to design it such that it isn't an arms race of who can get earlier (or later?) in the run list.

**Comment by lamont-granquist** [comment]
jkeiser is working on functionality like that for DSLv2, but its more aimed and the repetition of user+group attrs on every file and directory resource in a recipe.

for this use case i'd think the Chef::Config override does the right thing.  in that case the sysadmin at the site is imposing site-wide policy that every gem_package resource must hit the local mirror instead of rubygems.

**Comment by pburkholder** [comment]
So I added the 'clear_sources' resource attribute and some specs around the functionality.  Some thoughts:

- I'm happy to change the attribute name
- I think we should add a deprecation warning to the stanza that adds '--source rubygems.org' that behavior will change in next major version
- I didn't add the Chef::Config `gem_source` option because I wasn't sure who wins at the global level vs. the local resource when the resource specifies the source. E.g.

```
# client.rb
gem_source https://gems.example.com

# resource
gem_package 'foo' do
  source http://devgems.example.com
end
```

I would say the local resource wins, AND that use of the `gem_source` config implies `clear_source true`

In fact, I'll probably punt on the Chef::Config entirely for a later PR.

**Comment by lamont-granquist** [comment]
LGTM :+1:

**Comment by smurawski** [comment]
:+1:

**Comment by btm** [comment]
Rebased to master as 312253ebfd88ac57b8433c2f859690068fe7cb14, 36f040b73d99f0b5aae5bdab716ffa1aac060266, 3f100678176cf81be8f40a6721b6bd4b44135c76.

**Pull request closed without merging**
