### PR TITLE
Add jkeiser to core and dev tools maintainers

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by thommay** [comment]
👍

**Comment by mcquin** [comment]
🎉

**Comment by tyler-ball** [comment]
🚀 🍰

**Comment by lamont-granquist** [comment]
👍

**Comment by mwrock** [comment]
:+1: :100:

**Comment by jkeiser** [comment]
@chef/maintainers I'm interested in being a maintainer of core chef so I can C/R features; please :+1: or :-1: this as you feel appropriate. Thanks!

**Comment by coderanger** [comment]
:+1:

**Comment by martinisoft** [comment]
👍

**Comment by stevendanna** [comment]
👍

**Comment by smurawski** [comment]
:+1:

**Comment by jtimberman** [comment]
👍

**Pull request merged**
