### PR TITLE
Deprecate the deploy resource and family

### PR DESCRIPTION
**Pull request by coderanger**
@tas50 has volunteered (really, I have witnesses) to make the migration cookbook.

### CODE REVIEW

**Comment by danielsdeleo** [comment]
pour one out

**Comment by coderanger** [comment]
@tas50 Updated :)

**Comment by coderanger** [comment]
Also I put up https://github.com/chef/chef-rfc/pull/282, covering this and two other resources I think should be on a path towards removal.

**Comment by jjasghar** [comment]
I still remember the first time I used `deploy` resource trying to convert from `capistrano`, I'll miss you `deploy`, you helped teach me`chef`!

**Comment by coderanger** [comment]
Going to merge this even though the RFC in question is still under discussion because it doesn't seem like there is any major objection to this (compared to the other two) and I want to get the warning in as soon as possible to start turning the migration crank.

**Comment by coderanger** [comment]
Hmm, except merging seems to be jammed because it thinks Travis didn't report in?

**Pull request merged**
