### PR TITLE
Remove experimental warning on audit mode.

### PR DESCRIPTION
**Pull request by juliandunn**
I'm going to suggest we remove this to avoid freaking out customers since we have been shipping this mode for some time.

/cc @chef/analytics-data-integrations

### CODE REVIEW

**Comment by jdmundrawala** [comment]
Did we solve the issue around audit mode mangling exceptions?

**Comment by juliandunn** [comment]
What do you mean by "mangling exceptions"?

**Comment by jdmundrawala** [comment]
https://github.com/chef/chef/commit/625373d40febafa1c6621aaf179852601d303e6c#diff-c34d08382bb25f61e44ecbd5f50f4166
This was one of the regressions in 12.2 and we ended up patching it. By making audit mode the default, those same people will break again.

**Comment by jdmundrawala** [comment]
I think the example we got was SystemExit and how this broke people's CI. Not sure if there is anything else that we need to consider.
cc @tyler-ball

**Comment by juliandunn** [comment]
My PR doesn't make audit mode the default; I don't know that we need to do that right now. I'm just removing warnings here.

**Comment by jdmundrawala** [comment]
My bad, I guess this is harmless then.

**Comment by tyler-ball** [comment]
@jdmundrawala If audit mode is disabled (the default) we don't wrap any raised exceptions, we just re-raise them - https://github.com/chef/chef/pull/3090

**Comment by tyler-ball** [comment]
:+1: On this change.  I could see people being concerned this message gets changed in a patch version.  Can we hold off on it until the next major version (12.4)?

**Comment by juliandunn** [comment]
@tyler-ball Sure, that's fine

**Comment by juliandunn** [comment]
Per @tyler-ball's message -- looks like we're on the cusp of releasing 12.4. Can I get this warning removal in there? /cc @chef/client-maintainers

**Comment by danielsdeleo** [comment]
:+1: as long as we're sufficiently confident that the design is fairly stable and we don't need to change it in incompatible ways in the future.

**Comment by jtimberman** [comment]
The main thing off the top of my head is this 

https://github.com/chef/chef/issues/3482

It's a bug fix but if people did the should syntax in their tests that change would break them.

**Comment by juliandunn** [comment]
@jtimberman I'm going to argue that whether that's a bug or not doesn't generally change the shape of the design of audit mode, and at this point we've got enough usage & published enough articles about it that we should just say it's shipped.

**Comment by danielsdeleo** [comment]
Well then you shouldn't break any working code. OTOH, that may be a moot point: https://github.com/chef/chef/issues/3482#issuecomment-108708561

**Pull request merged**
