### PR TITLE
Fix cookbook gem installer

### PR DESCRIPTION
**Pull request by brugidou**
Current gem installer does not work if multiple cookbook request the
same gem. The solution is to merge all the gem requirements for the same
gem.

If multiple cookbooks have conflicting constraints, the install will
fail anyway.

This bug affects Chef 12 too and make the feature almost unusable.

### CODE REVIEW

**Comment by brugidou** [comment]
Opened #5943 to fix the bundle-audit check

**Comment by lamont-granquist** [comment]
needs a test

**Comment by brugidou** [comment]
@lamont-granquist I added unit tests, I checked that they effectively fail without my patch.

**Comment by lamont-granquist** [comment]
good 'nuff.

note that you did a bunch of work to stub everything and we're not generally that religious about our unit tests being pure unit tests of only the object under test with everything else stubbed.  in particular mocking the filesystem usually ends in tears because there's too much API surface area (read: collaboration) between the object under test and the posix filesystem.  there's mockfs/fakefs solutions that attempt to double-down on unit testing, but i usually prefer to just create real files.  also wouldn't have minded creating a real CookbookCollection instead of stubbing it with a hash.

still way cleaner tests than we usually get, i don't think it really needs to be changed to be accepted, since those are just philosophical points...

**Pull request merged**
