### PR TITLE
Nominate myself as Windows Lt.

### PR DESCRIPTION
**Pull request by btm**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:+1:

**Comment by tyler-ball** [comment]
:+1: 

\cc @chef/client-core

**Comment by danielsdeleo** [comment]
:+1:

**Comment by jdmundrawala** [comment]
:+1: 
yay btm

**Comment by danielsdeleo** [comment]
Probably need the @adamhjk supreme decider power for this one since the LT roster is still getting filled out.

**Comment by mcquin** [comment]
:8ball:

**Comment by btm** [comment]
https://github.com/chef/chef-rfc/blob/master/rfc030-maintenance-policy.md#lieutenant

```
* Receive an absolute majority of existing lieutenants :+1:
* No veto from the current project lead
```

/cc @martinisoft @sethvargo

**Comment by martinisoft** [comment]
:+1: from me

**Comment by smurawski** [comment]
:+1:

**Pull request merged**
