### PR TITLE
Bump deps for net-ssh 7.x for RHEL 9 and Ubuntu 22.04 ssh

### PR DESCRIPTION
**Pull request by Stromweld**
## Description

Bump deps for net-ssh 7.x for RHEL 9 and Ubuntu 22.04 for new ssh algorithms support

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by johnmccrae** [comment]
Does net-sftp need to get added to the Gemfile? Builds are failing because they can't find it @Stromweld

**Comment by Stromweld** [comment]
Either a slight mod to the job to add —pre flag to allow the rc1 version of the gem, or we fork it and point to our own repo like ruby-shadow, or we get them to release the official 4.0 gem will fix the failing tests. I emailed the maintainer late last week and have a pr on their repo for the official release which is code wise same as rc1 just removing rc1 from version file.

**Comment by Stromweld** [comment]
looks like they just released the official release of net-sftp 4.0 about 15 minutes ago. So this should be fixed now. Can someone rerun the failing jobs? @johnmccrae @marcparadise @tpowell-progress @jaymzh @PrajaktaPurohit

**Comment by Stromweld** [comment]
looks like on october 27th the badsssl.com site updated it's self signed cert and the end to end cookbook test is using old cert in the trusted_certs directory to verify it can connect to the site. Since it doesn't the test is failing. Would it be better to have it run `knife ssl fetch badssl.com` to always get the current cert instead of this breaking every couple of years.

**Comment by Stromweld** [comment]
This PR also supersedes #13280

**Comment by johnmccrae** [comment]
@Stromweld This looks great. Merging.

**Review by johnmccrae — APPROVED** [review]

**Pull request merged**
