### PR TITLE
Prepare Chef 12.1.0

### PR DESCRIPTION
**Pull request by jdmundrawala**
cc @chef/client-engineers @chef/client-core

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Is the nillable stuff shipping in 12.1.0?  (I hadn't intended it to, but that's cool)

**Comment by btm** [comment]
it seems like good practice to pull in master and ship it, yeah? Just in terms of #alwaysbeshippin. :+1:

**Comment by tyler-ball** [comment]
:+1:

**Comment by jdmundrawala** [comment]
@lamont-granquist yep, everything that's merged in is going out...unless you don't want it

**Comment by btm** [comment]
(in which case we shouldn't merge to master going forward if its not releasable)

**Comment by jdmundrawala** [comment]
https://github.com/chef/chef/pull/3002 is ready to go if we don't want everything from master

**Comment by btm** [comment]
I'm still :+1: on shipping this.

**Comment by lamont-granquist** [comment]
Yeah, the risk is that we're pulling in changes that weren't in the rc, so rc testing doesn't guarantee that we're not shipping flagrantly busted code...  I'm okay with it in this case because I know the risk is low and we have func tests around the deploy resource that are actually fairly good (and somewhat slow)...

There is a kind of half-pregnant issue to be aware of here when we're in between the old release cycle and our intent of constantly shipping...  Something just to think about, I'm still :+1: as well.

**Comment by lamont-granquist** [comment]
Yeah, so the resource code is fine, but when I try adding a test for setting the actual nil argument it does this:

```
  1) Chef::Resource::DeployRevision when deploying a simple app setting resources to nil supports setting symlink_before_migrate to nil
     Failure/Error: deploy_to_latest_rev.run_action(:deploy)
     NoMethodError:
       deploy_revision[deploy-revision-unit-test] (dynamically defined) had an error: NoMethodError: undefined method `map' for nil:NilClass
     # ./lib/chef/provider/deploy.rb:305:in `run_symlinks_before_migrate'
     # ./lib/chef/provider/deploy.rb:192:in `migrate'
     # ./lib/chef/provider/deploy.rb:161:in `deploy'
     # ./lib/chef/provider/deploy.rb:110:in `block in action_deploy'
     # ./lib/chef/provider/deploy.rb:443:in `with_rollback_on_error'
     # ./lib/chef/provider/deploy.rb:109:in `action_deploy'
     # ./lib/chef/provider/deploy/revision.rb:39:in `action_deploy'
     # ./lib/chef/provider.rb:145:in `run_action'
     # ./lib/chef/resource.rb:561:in `run_action'
     # ./spec/functional/resource/deploy_revision_spec.rb:213:in `block (4 levels) in <top (required)>'
```

so while the nillable code isn't broken, its not going to be useful to users without additional code...

**Comment by jdmundrawala** [comment]
I say we don't ship it if it is known to be broken

**Comment by lamont-granquist** [comment]
Yeah, now I'm :-1: on shipping

**Comment by jdmundrawala** [comment]
Closing in favor of https://github.com/chef/chef/pull/3002

**Pull request closed without merging**
