### PR TITLE
Bump diff-lcs to get bugfix.

### PR DESCRIPTION
**Pull request by phiggins**
This fixes some errors I was seeing, but I'm getting different errors locally.

Signed-off-by: Pete Higgins <pete@peterhiggins.org>

### CODE REVIEW

**Comment by halostatue** [comment]
An update will be released shortly that fixes the issue outlined here.

**Comment by halostatue** [comment]
Released as 1.4.2.

**Comment by tas50** [comment]
Thanks for the quick turnaround @halostatue

**Comment by phiggins** [comment]
Thanks @halostatue!

**Pull request merged**
