### PR TITLE
Support SNI in 'knife ssl check'.

### LINKED ISSUE #3491: knife ssl check: support SNI
`knife ssl check` seems not to do SNI properly:

```bash
➜  chef git:(master) knife -v                            
Chef: 12.3.0
➜  chef git:(master) knife ssl check https://roland.io 
using /Users/rmoriz/sync/Projekte/devops/chef/site-cookbooks,/Users/rmoriz/sync/Projekte/devops/chef/cookbooks
Connecting to host roland.io:443
ERROR: The SSL cert is signed by a trusted authority but is not valid for the given hostname
ERROR: You are attempting to connect to:   'roland.io'
ERROR: The server's certificate belongs to 'www.dom.io'
```

(Also happens with ChefDK 0.6.0 knife)

See:
- http://en.wikipedia.org/wiki/Server_Name_Indication
- https://www.ssllabs.com/ssltest/analyze.html?d=roland.io&latest

### PR DESCRIPTION
**Pull request by juliandunn**
Fixes #3491.

### CODE REVIEW

**Comment by coderanger** [comment]
Clap

**Comment by thommay** [comment]
:+1:

**Comment by juliandunn** [comment]
Can I get one more :+1: from @chef/client-core? Unless @coderanger's Picard was meant to be one...

**Comment by coderanger** [comment]
Yep. :+1: from me.

**Pull request merged**
