### PR TITLE
Make Chef::VERSION be fancy

### PR DESCRIPTION
**Pull request by coderanger**
This is because if I have to write `Gem::Requirement.create('~> 12.0').satisfied_by?(Gem::Version.create(Chef::VERSION))` one more time I'm going to scream. Paradoxically because it's a version check API we won't actually be able to use it for a long while, but might as well start now.

This allows stuff like `Chef::VERSION =~ '~> 12.0'` or `case Chef::VERSION; when '>= 12.5' ...`.

### CODE REVIEW

**Comment by coderanger** [comment]
Might also be cool to do this for `node['platform_version']`, in the Ohai loading we could do something like `automatic['platform_version'] = VersionString.new(automatic['platform_version'])`.

**Comment by coderanger** [comment]
The `===` hack might be too much, would be cool if everyone else wants to just do the fancy `=~` operator and skip the `case` magic.

**Comment by lamont-granquist** [comment]
yeah probably not the monkeypatching of `===`

**Comment by coderanger** [comment]
Okay, the `===` trickery is gone and chef-config is no longer wrecked :)

**Comment by thommay** [comment]
chefstyle needs care and feeding

**Comment by coderanger** [comment]
And now fingers crossed that this doesn't some how jam the bumpbot :)

**Pull request merged**
