### PR TITLE
add get_rest etc calls to ServerAPI

### PR DESCRIPTION
**Pull request by thommay**
and note in rspec that we want these gone in 13
cc @chef/client-core

### CODE REVIEW

**Comment by coderanger** [comment]
:+1:

**Comment by tylercloke** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Comment by jaym** [comment]
:+1:

**Comment by danielsdeleo** [comment]
What are these for? To help folks switch from `Chef::REST`? If we're planning to nuke them, probably should have a deprecation warning?

**Comment by tylercloke** [comment]
@danielsdeleo Yeah, to make defaulting to ServerApi not a breaking change. Is there any reason to ever remove these methods? Seems pretty simple to just alias them and be backwards compatible.

**Comment by jaym** [comment]
i dont think these were ever part of ServerAPI. The reason knife-opc broke is because the `chef_rest` method started returning ServerAPI instead of REST, and it was calling the `_rest` methods on it.

**Comment by tylercloke** [comment]
Yeah, but we are removing `Chef::REST` long term in favor of ServerApi, so if we can easily make ServerApi backwards compatible with `Chef::REST`, why wouldn't we?

**Comment by danielsdeleo** [comment]
I think the `_rest` methods are really ugly and it'd be cool if they didn't exist, but realistically they're not hurting anything so if it makes everyone's lives easier to keep them, that's ok by me. Contrarily, returning un-inflated objects from the API calls is where the "real breakage" (i.e., requires actual thought to fix) is, and doing a find/replace for, e.g., `s/get_rest/get/g` would be the easy part, so maybe we take the opportunity to clean up our API.

In any case, the thing I really want is for deprecated methods to emit deprecation warnings. I'm fine with either way that could be made to happen.

**Comment by tylercloke** [comment]
I'm fine with listing them as deprecated if we actually do wanna get rid of these methods long term, but even if they are ugly, I feel like it is good to be backwards compatible unless there is a really compelling reason not to be.

This goes back to our lack of strong interfaces / policy around the interfaces in many places in the code, so I defer to you where you think that edge is here :)

**Comment by thommay** [comment]
> Contrarily, returning un-inflated objects from the API calls is where the "real breakage" (i.e., requires actual thought to fix) is

This is all done now, I think? ServerAPI returns un-inflated objects, and all the classes on top inflate as part of load.

Regarding the `_rest` calls, I think Tyler's point about stability is a fair point, so I'll just remove the deprecation test.

**Comment by danielsdeleo** [comment]
I'm totally fine with this outcome, just wanted to clarify my point. You can't really just gsub `s/Chef::REST/Chef::ServerAPI/g`, even if the `*_rest` methods are there, because the return types are different and not duck types of each other (except for cases where the server returns data without `json_class` stuff). Since users of `Chef::REST` have to deal with that, adding an additional gsub `s/get_rest/get/g`(and so on) isn't that big a deal.

Anyway, :+1: from me on un-deprecating.

**Pull request merged**
