### PR TITLE
focus snuck into a PR

### PR DESCRIPTION
**Pull request by lamont-granquist**
this reverts the focus and allows all the tests to run again

### CODE REVIEW

**Comment by ksubrama** [comment]
:+1: yay!

**Comment by coderanger** [comment]
Protip `config.filter_run(:focus) unless ENV['CI']`

**Comment by lamont-granquist** [comment]
This seems a little better since it'd actually fail the PR that introduced the `:focus`:

```
  config.before(:example, :focus) do
    raise 'This example was committed with `:focus` and should not have been'
  end if ENV['CI']
```

**Comment by lamont-granquist** [comment]
ah, that's just before syntax, just not used to reading it in the config block...

**Comment by lamont-granquist** [comment]
a799d90 is just for testing 652c773 to ensure it fails in CI and i'll be removing that commit before merging

**Comment by lamont-granquist** [comment]
#4226 broke the build but at the same time disabled all the tests from one, so merging this PR even though its red because now the red state of master will be accurate.

**Pull request merged**
