### PR TITLE
bump up timeout for travis

### PR DESCRIPTION
**Pull request by lamont-granquist**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Even if this burns roughly 100 extra seconds (4 failed tests * 25 seconds extra per test), that is vastly less than every time this timeout kicks off and we click 'reload' on a PR and we suck up a queue slot for another 20 minutes or so...

Maybe there's a better fix, but this is better than clicking reload...

**Comment by smurawski** [comment]
:+1:

**Comment by jkeiser** [comment]
:+1:

**Comment by jkeiser** [comment]
File a bug on it sometimes being super slow?
Also, might not fix it--it could be the issue is the server not starting at all.

**Comment by lamont-granquist** [comment]
I figure the fastest way to find out if the server isn't starting is to merge this...

**Comment by lamont-granquist** [comment]
(i'd also argue that this patch is correct anyway -- we should always be patient before timing out tests and forcing the user to click reload in the travis UI which is horribly expensive)

**Comment by lamont-granquist** [comment]
lol, dammit wrong branch...

**Pull request merged**
