### PR TITLE
do not accept exitstatus == 1 as success

### PR DESCRIPTION
**Pull request by rjbs**
status.exitstatus of 1 is a failure. In fact, it's a very common exit code for failures on cron.  Unless there is a specific reason that exit status 1 is supposed to be considered okay — and I strongly suspect that there is none — then it should not be treated as okay.  I think this is just an off-by-one error and that >= was meant instead of >, or 0 instead of 1.

We can avoid the question by using Process::Status#success? instead.

### CODE REVIEW

**Comment by thommay** [comment]
Closing due to inactivity

**Comment by lamont-granquist** [comment]
Yeah I'm positive exitstatus of 1 is expected on one or the other platform and that this issue is not as straight-forwards as it seems.  I recall beating my head against this years ago.

**Comment by rjbs** [comment]
I'm sad to see this closed.  The current behavior is busted on some platforms.  I realize that my PR is not a complete solution, but is there, now, any issue to track the actual broken behavior?

**Comment by lamont-granquist** [comment]
Its tagged incomplete which means we're always open to reopening it and accepting the contribution if it gets fixed up.  We're unlikely to prioritize this ourselves given the issues in front of it, so we've closed it since having hundreds of open issues+prs that we're never going to have the time to get to doesn't help us get work done.

**Pull request closed without merging**
