### PR TITLE
replace glibc resolver with ruby resolver

### PR DESCRIPTION
**Pull request by lamont-granquist**
also wires up file providers to reload /etc/resolv.conf when it changes.

### CODE REVIEW

**Comment by thommay** [comment]
😨 :+1:

**Comment by lamont-granquist** [comment]
code somewhat stolen from comment in #2894

**Comment by coderanger** [comment]
Do we need to do anything special for Windows?

**Comment by lamont-granquist** [comment]
appveyor seems to have died in flames, so i think so...

but really we only need this workaround for Linux/glibc AFAIK...

**Comment by coderanger** [comment]
👍

**Comment by coderanger** [comment]
One thing to note: this will break DNS for anyone using NIS for hostname lookups I think. That said, those people can literally DIAF.

**Comment by lamont-granquist** [comment]
Yeah, NIS for hostnames in addition to users and groups.

I'm considering this use case, and I think we fix it when that one person complains.

**Comment by lamont-granquist** [comment]
#5141 is the blocking issue that caused the revert of this PR

**Comment by maokt** [comment]
Instead of replacing the glibc resolver, we could use ffi to tell glibc to reload resolv.conf itself. I've been using this in a ruby_block in recipes where resolv.conf is updated:

```
        require 'ffi'
        module libc
            extend FFI::Library
            ffi_lib FFI::CURRENT_PROCESS
            # res_init in GNU libc is called __res_init, so try both
            [ :res_init, :__res_init ].detect do |ff|
                begin
                    attach_function :res_init, ff, [], :int
                    true
                rescue FFI::NotFoundError
                    false
                end
            end
        end
        libc.res_init() if defined? libc.res_init
```

**Pull request merged**
