### PR TITLE
Multitenant local mode by default

### PR DESCRIPTION
**Pull request by jkeiser**
This PR:

makes local mode multi-tenant by default (chef-zero runs in multi-org mode, providing orgs, acls, groups, etc.), setting chef_server_url = http://localhost:port/organizations/chef
adds the "organization" config parameter
adds the "chef_server_root" config option to specify the top level root
points at Hosted Chef by default when organization is set
infers organization and chef_server_root from chef_server_url when specified, and vice versa
All per opscode/chef-rfc#49

### CODE REVIEW

**Comment by stevendanna** [comment]
What still needs to happen here (other than a rebase)?  This PR includes a few features that I was about to implement myself (chef_server_root configuration option, organization configuration option, and the rest_root option) as they will make some other work (model objects for Chef 12 features and the related knife commands) a bit easier.

**Comment by nathenharvey** [comment]
@jkeiser can you rebase and see if there are other things in the comments to be addressed, please?

**Comment by lamont-granquist** [comment]
paging @jkeiser

**Comment by smurawski** [comment]
Closing due to age.

**Pull request closed without merging**
