### PR TITLE
fix package timeout attribute

### LINKED ISSUE #2441: gem_package installation fails with default timeout.
Installing berkshelf takes some time because it's compiling the gecode components.  
When specifying a timeout of 1200 or something, the <tt>Mixlib::ShellOut::Command</tt> times out after 600 seconds by default, like here below:
```
==> linux: Running chef-solo...
==> linux: [2014-11-18T11:46:57+00:00] INFO: Forking chef instance to converge...
==> linux: [2014-11-18T11:46:57+00:00] WARN:
==> linux: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> linux: SSL validation of HTTPS requests is disabled. HTTPS connections are still
==> linux: encrypted, but chef is not able to detect forged replies or man in the middle
==> linux: attacks.
==> linux:
==> linux: To fix this issue add an entry like this to your configuration file:
==> linux:
==> linux: ```
==> linux:   # Verify all HTTPS connections (recommended)
==> linux:   ssl_verify_mode :verify_peer
==> linux:
==> linux:   # OR, Verify only connections to chef-server
==> linux:   verify_api_cert true
==> linux: ```
==> linux:
==> linux: To check your SSL configuration, or troubleshoot errors, you can use the
==> linux: `knife ssl check` command like so:
==> linux:
==> linux: ```
==> linux:   knife ssl check -c /tmp/vagrant-chef-2/solo.rb
==> linux: ```
==> linux:
==> linux: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> linux: [2014-11-18T11:46:57+00:00] INFO: *** Chef 11.16.4 ***
==> linux: [2014-11-18T11:46:57+00:00] INFO: Chef-client pid: 2236
==> linux: [2014-11-18T11:46:58+00:00] INFO: Setting the run_list to ["recipe[sbp_berkshelf]"] from CLI options
==> linux: [2014-11-18T11:46:58+00:00] INFO: Run List is [recipe[sbp_berkshelf]]
==> linux: [2014-11-18T11:46:58+00:00] INFO: Run List expands to [sbp_berkshelf]
==> linux: [2014-11-18T11:46:58+00:00] INFO: Starting Chef Run for localhost
==> linux: [2014-11-18T11:46:58+00:00] INFO: Running start handlers
==> linux: [2014-11-18T11:46:58+00:00] INFO: Start handlers complete.
==> linux: [2014-11-18T11:47:03+00:00] INFO: package[autoconf] installing autoconf-2.63-5.1.el6 from base repository
==> linux: [2014-11-18T11:47:10+00:00] INFO: package[bison] installing bison-2.4.1-5.el6 from base repository
==> linux: [2014-11-18T11:47:11+00:00] INFO: package[flex] installing flex-2.5.35-9.el6 from base repository
==> linux: [2014-11-18T11:47:12+00:00] INFO: package[gcc] installing gcc-4.4.7-11.el6 from base repository
==> linux: [2014-11-18T11:47:33+00:00] INFO: package[gcc-c++] installing gcc-c++-4.4.7-11.el6 from base repository
==> linux: [2014-11-18T11:47:36+00:00] INFO: package[kernel-devel] installing kernel-devel-2.6.32-504.1.3.el6 from updates repository
==> linux: [2014-11-18T11:47:47+00:00] INFO: package[patch] installing patch-2.6-6.el6 from base repository
==> linux:
==> linux: ================================================================================
==> linux: Error executing action `install` on resource 'gem_package[berkshelf]'
==> linux: ================================================================================
==> linux:
==> linux:
==> linux: Mixlib::ShellOut::CommandTimeout
==> linux: --------------------------------
==> linux: Command timed out after 600s:
==> linux: Command exceeded allowed execution time, process terminated
==> linux: ---- Begin output of /opt/chef/embedded/bin/gem install berkshelf -q --no-rdoc --no-ri -v "3.2.1" ----
==> linux: STDOUT: Building native extensions.  This could take a while...
==> linux: Building native extensions.  This could take a while...
==> linux: Building native extensions.  This could take a while...
==> linux: STDERR:
==> linux: ---- End output of /opt/chef/embedded/bin/gem install berkshelf -q --no-rdoc --no-ri -v "3.2.1" ----
==> linux: Ran /opt/chef/embedded/bin/gem install berkshelf -q --no-rdoc --no-ri -v "3.2.1" returned
==> linux:
==> linux: Resource Declaration:
==> linux: ---------------------
==> linux: # In /tmp/vagrant-chef-2/chef-solo-1/cookbooks/sbp_berkshelf/recipes/default.rb
==> linux:
==> linux:
==> linux:  12: gem_package 'berkshelf' do
==> linux:
==> linux:  13:   version node['berkshelf']['version']
==> linux:
==> linux:  14:   timeout 1200
==> linux:
==> linux:  15: end
==> linux:
==> linux:
==> linux:
==> linux: Compiled Resource:
==> linux: ------------------
==> linux: # Declared in /tmp/vagrant-chef-2/chef-solo-1/cookbooks/sbp_berkshelf/recipes/default.rb:12:in `from_file'
==> linux:
==> linux:
==> linux:
==> linux: gem_package("berkshelf") do
==> linux:
==> linux:   provider Chef::Provider::Package::Rubygems
==> linux:
==> linux:   action :install
==> linux:
==> linux:   retries 0
==> linux:
==> linux:   retry_delay 2
==> linux:
==> linux:   guard_interpreter :default
==> linux:
==> linux:   package_name "berkshelf"
==> linux:
==> linux:   version "3.2.1"
==> linux:
==> linux:   timeout 1200
==> linux:   cookbook_name :sbp_berkshelf
==> linux:   recipe_name "default"
==> linux:   gem_binary "/opt/chef/embedded/bin/gem"
==> linux: end
==> linux:
==> linux: [2014-11-18T12:02:52+00:00] INFO: Running queued delayed notifications before re-raising exception
==> linux: [2014-11-18T12:02:52+00:00] ERROR: Running exception handlers
==> linux: [2014-11-18T12:02:52+00:00] ERROR: Exception handlers complete
==> linux: [2014-11-18T12:02:52+00:00] FATAL: Stacktrace dumped to /tmp/cache/chef-stacktrace.out
==> linux: [2014-11-18T12:02:52+00:00] ERROR: gem_package[berkshelf] (sbp_berkshelf::default line 12) had an error: Mixlib::ShellOut::CommandTimeout: Command timed out after 600s:
==> linux: Command exceeded allowed execution time, process terminated
==> linux: ---- Begin output of /opt/chef/embedded/bin/gem install berkshelf -q --no-rdoc --no-ri -v "3.2.1" ----
==> linux: STDOUT: Building native extensions.  This could take a while...
==> linux: Building native extensions.  This could take a while...
==> linux: Building native extensions.  This could take a while...
==> linux: STDERR:
==> linux: ---- End output of /opt/chef/embedded/bin/gem install berkshelf -q --no-rdoc --no-ri -v "3.2.1" ----
==> linux: Ran /opt/chef/embedded/bin/gem install berkshelf -q --no-rdoc --no-ri -v "3.2.1" returned
==> linux: [2014-11-18T12:02:52+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

Tracing this back, I see that the rubygems is not updating the <tt>Mixlib::ShellOut::CommandTimeout</tt> with respect to the value set within the provider
Would it be an idea to update the rubygem provider so it takes over the value specified within the new_resource if the timeout value is provided?  

Example:  
file: lib/chef/provider/package/rubygems.rb
```
        def install_via_gem_command(name, version)
          if @new_resource.source =~ /\.gem$/i
            name = @new_resource.source
          else
            src = @new_resource.source && "  --source=#{@new_resource.source} --source=http://rubygems.org"
          end
          timeout = @new_resource.timeout || 600
          if version
            shell_out!("#{gem_binary_path} install #{name} -q --no-rdoc --no-ri -v \"#{version}\"#{src}#{opts}", :env=>nil, :timeout=> timeout)
          else
            shell_out!("#{gem_binary_path} install \"#{name}\" -q --no-rdoc --no-ri #{src}#{opts}", :env=>nil, :timeout=> timeout)
          end
        end
```

### LINKED ISSUE #2943: Zypper Package Provider times out (with large packages)
###Scenario:
When trying to install large packages (with lots of dependencies) the shell_out command within the zypper provider uses a default timeout of 10 mins which - under certain conditions - is not enough for everything to be installed properly. 

### Steps to Reproduce:
I came across this problem when using the java cookbook to install openjdk. I was on an OpenSUSE 13.1 minimal installation (meaning hardly anything was already installed) and installing openjdk 7 required *around* 216 packages to be installed. On a Virtualbox provider, on a somewhat slow machine, 10 mins (the default) just wasn't enough time.   

### Expected Result:
The timeout parameter - though supported by shell_out, is not supported by the Zypper package provider. Other providers, like Apt, have recently supported this ( #1462 )  , so Zypper should support it also.

### PR DESCRIPTION
**Pull request by lamont-granquist**
updates all the shell_out calls to respect the timeout which is passed
on the new_resource.

the old `Chef::Config` yum timeout values are still respected and will
override the default.

the default of 900 seconds is preserved.

closes #2943 
closes #2944 
closes #2441 
closes #2444

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core today's yak shave for review.

this should help close many open issues around package timeouts.

**Comment by danielsdeleo** [comment]
:+1:

**Comment by btm** [comment]
Did you consider putting shell_out_with_timeout in Chef::Mixin::ShellOut? Seems like it'd be useful in other providers, but you'd have to factor out the default from add_timeout and let it be set on the resource again. Granted, it could be done later.

:+1: other than that though.

**Comment by lamont-granquist** [comment]
Yep, thought about it.  Could move the timeout to a method on the provider and set the default there (can't tell the difference from the default timeout on the resource and a user setting the default timeout so I don't want it there).  Then could have it expect to be mixed into a class with a timeout method to read or something like that...

But, decided to be more iterative and just get this done today...

**Comment by tb3088** [comment]
will this fix be back-ported to 11.18?

**Comment by lamont-granquist** [comment]
In the past 6 months we have only done security releases for 11.x and pushed out one fix to update cacerts since AWS (and knife-ec2, etc) was totally broken with 11.x

Based on that track record, I would say no, you need to upgrade to 12.

**Pull request merged**
