### PR TITLE
Rewrite NetLocalGroup things to use FFI

### PR DESCRIPTION
**Pull request by jaym**
This should now be less broken and works on both 32bit and 64 bit.

cc @adamedx @chefsalim @ksubrama @mcquin @smurawski

### CODE REVIEW

**Comment by ksubrama** [comment]
:+1: Yay FFI

**Comment by chefsalim** [comment]
@ksubrama can you repro the seg fault exception?  Adam and I can't repro any longer on the master branch.

**Comment by ksubrama** [comment]
Yes I can.  Are you running spec/functional/resource/group_spec.rb as Administrator?  You don't want to be running any of our functional tests on your development VM (or you can - just remember to snapshot and restore afterwards).

**Comment by ksubrama** [comment]
C:\repo\chef\chef-200-x64 [master +1 ~0 -0 !]> bundle exec rspec spec/functional/resource/group_spec.rb
DL is deprecated, please use Fiddle
WARNING: Shared example group 'with a chef repo' has been previously defined at:
  C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cheffish-1.3.0/lib/cheffish/rspec/repository_support.rb:12
...and you are now defining it at:
  C:/repo/chef/chef-200-x64/spec/support/shared/integration/integration_helper.rb:105
The new definition will overwrite the original one.
Run options:
  include {:focus=>true}
  exclude {:provider=>#<Proc:./spec/spec_helper.rb:165>, :arch=>#<Proc:./spec/spec_helper.rb:159>, :broken=>true, :openssl_lt_101=>true, :requires_root=>true, :chef_gte_13_only=>true, :selinux_only=>true, :supports_cloexec=>true, :aix_only=>true, :unix_only=>true, :solaris_only=>true, :windows_domain_joined_only=>true, :windows_powershell_no_dsc_only=>true, :windows32_only=>true, :win2k3_only=>true, :mac_osx_only=>true, :appveyor_only=>true, :volatile_from_verify=>false, :volatile=>true, :external=>true}

All examples were filtered out; ignoring {:focus=>true}

Chef::Resource::Group
  append should be false by default
  group create action
C:/repo/chef/chef-200-x64/lib/chef/util/windows/net_group.rb:82: [BUG] Segmentation fault
ruby 2.0.0p645 (2015-04-13) [x64-mingw32]

-- Control frame information -----------------------------------------------
c:0042 p:---- s:0171 e:000170 CFUNC  :call
c:0041 p:0022 s:0164 e:000163 METHOD C:/repo/chef/chef-200-x64/lib/chef/util/windows/net_group.rb:82
c:0040 p:0009 s:0160 e:000159 METHOD C:/repo/chef/chef-200-x64/lib/chef/provider/group/windows.rb:56
c:0039 p:0007 s:0157 e:000156 BLOCK  C:/repo/chef/chef-200-x64/lib/chef/provider/group.rb:129 [FINISH]
c:0038 p:---- s:0155 e:000154 CFUNC  :call
c:0037 p:0057 s:0152 e:000151 METHOD C:/repo/chef/chef-200-x64/lib/chef/mixin/why_run.rb:52
c:0036 p:0013 s:0147 e:000146 METHOD C:/repo/chef/chef-200-x64/lib/chef/provider.rb:175
c:0035 p:0065 s:0142 E:001108 METHOD C:/repo/chef/chef-200-x64/lib/chef/provider/group.rb:128
c:0034 p:0146 s:0139 e:000138 METHOD C:/repo/chef/chef-200-x64/lib/chef/provider.rb:144
c:0033 p:0207 s:0135 e:000134 METHOD C:/repo/chef/chef-200-x64/lib/chef/resource.rb:585
c:0032 p:0011 s:0126 e:000125 BLOCK  C:/repo/chef/chef-200-x64/spec/functional/resource/group_spec.rb:280 [FINISH]
c:0031 p:---- s:0124 e:000123 CFUNC  :instance_exec
c:0030 p:0021 s:0120 e:000119 BLOCK  C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206
c:0029 p:0006 s:0117 e:000116 BLOCK  C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430
c:0028 p:0006 s:0115 e:000114 BLOCK  C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388
c:0027 p:0006 s:0113 e:000112 BLOCK  C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478
c:0026 p:0030 s:0111 E:0005e0 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:616
c:0025 p:0115 s:0105 E:000260 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478
c:0024 p:0014 s:0099 E:0013d0 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388
c:0023 p:0026 s:0095 E:002080 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430
c:0022 p:0139 s:0091 E:0003e0 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:203
c:0021 p:0054 s:0085 e:000084 BLOCK  C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:559 [FINISH]
c:0020 p:---- s:0080 e:000079 CFUNC  :map
c:0019 p:0014 s:0077 e:000076 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555
c:0018 p:0079 s:0073 e:000072 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:521
c:0017 p:0010 s:0065 e:000064 BLOCK  C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522 [FINISH]
c:0016 p:---- s:0062 e:000061 CFUNC  :map
c:0015 p:0093 s:0059 e:000058 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522
c:0014 p:0011 s:0051 e:000050 BLOCK  C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115 [FINISH]
c:0013 p:---- s:0048 e:000047 CFUNC  :map
c:0012 p:0009 s:0045 e:000044 BLOCK  C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115
c:0011 p:0048 s:0043 e:000042 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627
c:0010 p:0009 s:0039 e:000038 BLOCK  C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114
c:0009 p:0017 s:0036 e:000035 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77
c:0008 p:0018 s:0032 e:000031 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113
c:0007 p:0022 s:0028 e:000027 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89
c:0006 p:0088 s:0023 e:000022 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73
c:0005 p:0024 s:0016 e:000015 METHOD C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41
c:0004 p:0023 s:0012 e:000011 TOP    C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/exe/rspec:4 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :load
c:0002 p:0118 s:0006 E:0002e8 EVAL   C:/tools/Ruby200-x64/bin/rspec:23 [FINISH]
c:0001 p:0000 s:0002 E:0002d8 TOP    [FINISH]

C:/tools/Ruby200-x64/bin/rspec:23:in `<main>'
C:/tools/Ruby200-x64/bin/rspec:23:in `load'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `map'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `run'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `map'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `block in run'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:521:in `run'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `run_examples'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `map'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:559:in `block in run_examples'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:203:in `run'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `with_around_example_hooks'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `run'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `block in run'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `block in run'
C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `instance_exec'
C:/repo/chef/chef-200-x64/spec/functional/resource/group_spec.rb:280:in `block (3 levels) in <top (required)>'
C:/repo/chef/chef-200-x64/lib/chef/resource.rb:585:in `run_action'
C:/repo/chef/chef-200-x64/lib/chef/provider.rb:144:in `run_action'
C:/repo/chef/chef-200-x64/lib/chef/provider/group.rb:128:in `action_create'
C:/repo/chef/chef-200-x64/lib/chef/provider.rb:175:in `converge_by'
C:/repo/chef/chef-200-x64/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/repo/chef/chef-200-x64/lib/chef/mixin/why_run.rb:52:in `call'
C:/repo/chef/chef-200-x64/lib/chef/provider/group.rb:129:in `block in action_create'
C:/repo/chef/chef-200-x64/lib/chef/provider/group/windows.rb:56:in `create_group'
C:/repo/chef/chef-200-x64/lib/chef/util/windows/net_group.rb:82:in `local_add'
C:/repo/chef/chef-200-x64/lib/chef/util/windows/net_group.rb:82:in `call'

-- C level backtrace information -------------------------------------------
C:\Windows\SYSTEM32\ntdll.dll(ZwWaitForSingleObject+0xa) [0x00007FFCF772120A]
C:\Windows\system32\KERNELBASE.dll(WaitForSingleObjectEx+0x98) [0x00007FFCF4B51118]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_bugreport+0x9d) [0x000000006F287B2D]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_name_err_mesg_new+0x838) [0x000000006F1422D8]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_bug+0x45) [0x000000006F143085]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_check_safe_str+0x3c1) [0x000000006F20BF21]
 [0x0000000000401A85]
C:\Windows\SYSTEM32\ntdll.dll(_C_specific_handler+0x96) [0x00007FFCF7712896]
C:\Windows\SYSTEM32\ntdll.dll(_chkstk+0x9d) [0x00007FFCF7723F0D]
C:\Windows\SYSTEM32\ntdll.dll(RtlRaiseException+0xf67) [0x00007FFCF76E4887]
C:\Windows\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x3a) [0x00007FFCF772309A]
C:\Windows\SYSTEM32\ntdll.dll(RtlInitUnicodeString+0x16) [0x00007FFCF76BA656]
C:\Windows\SYSTEM32\SAMCLI.DLL(NetValidatePasswordPolicy+0x6c5) [0x00007FFCEF174D45]
C:\Windows\SYSTEM32\SAMCLI.DLL(NetLocalGroupAdd+0x18f) [0x00007FFCEF17589F]
C:\Windows\SYSTEM32\SAMCLI.DLL(NetLocalGroupAdd+0x7c) [0x00007FFCEF17578C]
 [0x0000000066942061]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x000000006F272615]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_f_send+0x5a1) [0x000000006F2817C1]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1cf8) [0x000000006F276D08]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5bf9) [0x000000006F27AC09]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_funcall+0xd2e) [0x000000006F280AAE]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_funcall+0xec0) [0x000000006F280C40]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_invoke_proc+0x27) [0x000000006F280C87]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_block_proc+0x7a3) [0x000000006F150FC3]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x000000006F272615]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_f_send+0x5a1) [0x000000006F2817C1]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1cf8) [0x000000006F276D08]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5bf9) [0x000000006F27AC09]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_yield_refine_block+0x727) [0x000000006F283A67]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x000000006F272615]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_f_send+0x5a1) [0x000000006F2817C1]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1c91) [0x000000006F276CA1]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5bf9) [0x000000006F27AC09]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_yield+0x178) [0x000000006F284638]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_ary_push+0x124e) [0x000000006F10DACE]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x000000006F272615]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_f_send+0x5a1) [0x000000006F2817C1]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1c91) [0x000000006F276CA1]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5bf9) [0x000000006F27AC09]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_yield+0x178) [0x000000006F284638]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_ary_push+0x124e) [0x000000006F10DACE]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x000000006F272615]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_f_send+0x5a1) [0x000000006F2817C1]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1c91) [0x000000006F276CA1]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5bf9) [0x000000006F27AC09]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_yield+0x178) [0x000000006F284638]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_ary_push+0x124e) [0x000000006F10DACE]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x000000006F272615]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_f_send+0x5a1) [0x000000006F2817C1]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1c91) [0x000000006F276CA1]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5bf9) [0x000000006F27AC09]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_iseq_eval+0x193) [0x000000006F284A73]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_rubylevel_errinfo+0x5ea) [0x000000006F14BD2A]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_rubylevel_errinfo+0x10fe) [0x000000006F14C83E]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x000000006F272615]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_f_send+0x5a1) [0x000000006F2817C1]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1cf8) [0x000000006F276D08]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5bf9) [0x000000006F27AC09]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_iseq_eval_main+0x1e0) [0x000000006F284CA0]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(rb_check_copyable+0x3287) [0x000000006F148047]
C:\tools\Ruby200-x64\bin\x64-msvcrt-ruby200.dll(ruby_run_node+0x51) [0x000000006F14A8C1]
 [0x0000000000402D14]
 [0x00000000004013D7]
 [0x00000000004014F8]
C:\Windows\system32\KERNEL32.DLL(BaseThreadInitThunk+0x22) [0x00007FFCF52D13D2]

-- Other runtime information -----------------------------------------------

**Comment by ksubrama** [comment]
And with Jay's changes:

```
C:\repo\chef\chef-200-x64 [jdm/win-groups +1 ~0 -0 !]> bundle exec rspec spec/functional/resource/group_spec.rb
DL is deprecated, please use Fiddle
WARNING: Shared example group 'with a chef repo' has been previously defined at:
  C:/tools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cheffish-1.3.0/lib/cheffish/rspec/repository_support.rb:12
...and you are now defining it at:
  C:/repo/chef/chef-200-x64/spec/support/shared/integration/integration_helper.rb:105
The new definition will overwrite the original one.
Run options:
  include {:focus=>true}
  exclude {:provider=>#<Proc:./spec/spec_helper.rb:165>, :arch=>#<Proc:./spec/spec_helper.rb:159>, :broken=>true, :openssl_lt_101=>true, :requires_root=>true, :chef_gte_13_only=>true, :selinux_only=>true, :supports_cloexec=>true, :aix_only=>true, :unix_only=>true, :solaris_only=>true, :windows_domain_joined_only=>true, :windows_powershell_no_dsc_only=>true, :windows32_only=>true, :win2k3_only=>true, :mac_osx_only=>true, :appveyor_only=>true, :volatile_from_verify=>false, :volatile=>true, :external=>true}

All examples were filtered out; ignoring {:focus=>true}

Chef::Resource::Group
  append should be false by default
  group create action
    should create a group
    when group name is length 256
      should create a group
    when group name length is more than 256
      should not create a group
    should raise an error when same member is included in the members and excluded_members
      should raise an error
  group remove action
    when there is a group
      should remove a group
    when there is no group
      should be no-op
  group modify action
    when there is no group
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from C:/repo/chef/chef-200-x64/spec/functional/resource/group_spec.rb:355:in `block (4 levels) in <top (required)>'.
      should raise an error
    when there is a group
      behaves like correct group management
        when append is not set
          should remove the existing users and add the new users to the group
        when append is set
          when the users exist
            should add included members to the group
            when group contains some users
              should add the included users and remove excluded users
          when the users doesn't exist
            when append is not set
              should raise an error
            when append is set
              should raise an error
    when running on Windows
      behaves like an expected invalid domain error case
        when updating membership
          raises an error for a non well-formed domain name
          raises an error for a nonexistent domain
        when removing members
          raises an error for a non well-formed domain name
          raises an error for a nonexistent domain
  group manage action
    when there is no group
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from C:/repo/chef/chef-200-x64/spec/functional/resource/group_spec.rb:388:in `block (4 levels) in <top (required)>'.
      raises an error on modify
      does not raise an error on manage
    when there is a group
      behaves like correct group management
        when append is not set
          should remove the existing users and add the new users to the group
        when append is set
          when the users exist
            should add included members to the group
            when group contains some users
              should add the included users and remove excluded users
          when the users doesn't exist
            when append is not set
              should raise an error
            when append is set
              should raise an error
    running on windows
      behaves like an expected invalid domain error case
        when updating membership
          raises an error for a non well-formed domain name
          raises an error for a nonexistent domain
        when removing members
          raises an error for a non well-formed domain name
          raises an error for a nonexistent domain

Finished in 14.77 seconds (files took 4.86 seconds to load)
28 examples, 0 failures
```

**Comment by smurawski** [comment]
:+1:  Go for it

**Comment by thommay** [comment]
@jaym All the tests here need to be altered so that windows and unix expect different exceptions to be raised:
```
4) Chef::Resource::Group group manage action when there is a group behaves like correct group management when append is set when the users doesn't exist when append is set should raise an error
     Failure/Error: expect { group_resource.run_action(tested_action) }.to raise_error(Chef::Exceptions::Win32APIError)
       expected Chef::Exceptions::Win32APIError, got #<Mixlib::ShellOut::ShellCommandFailed: group[group4290] (dynamically defined) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '3'
```
etc.

**Comment by ksubrama** [comment]
D'oh!  All the winderrs devs ran the tests on non-unix :)  I'll take it and fix it.

**Comment by adamedx** [comment]
@ksubrama, I'm somewhat surprised -- we ran the tests on Unix with Travis, correct?

**Comment by ksubrama** [comment]
I'm not sure - do we run functional tests on Travis?  Also, this test itself was buggy (and have been since 2013).  It was failing badly on my Mac and I just refactored it to do the right thing (I hope).

**Comment by ksubrama** [comment]
We figured out that the tests weren't failing on travis because this test needs either root or windows admin.  That would explain why travis and appveyor were both happy with it.

**Pull request merged**
