### PR TITLE
Make Standardized Exit Codes The Default Behavior

### PR DESCRIPTION
**Pull request by smurawski**
### Description

Sets a default in Chef::Config for `exit_status` to `:enabled`.
Removes uses of deprecated exit codes from the Chef code base.
Changed the deprecation warning/error to a warning message when attempting to exit with a non-standard exit code while standard exit codes are enforced.

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by coderanger** [comment]
Is there a compelling reason to leave this configurable? If not, I vote to salt the earth and make it just how Chef works since it seems unilaterally better :)

**Comment by lamont-granquist** [comment]
yeah i'm actually even a bit more :-1: on configurability, since anyone tweaking that and using a cookbook which expects the RFC behavior on exit codes will be broken.  should cookbooks work under both cases?  should cookbooks that require the RFC raise if its not set correctly?  better solutions is probably to actually remove the choice...

i do normally promote the right to keep and bear footguns, but this is more like a footgun that when you pull the trigger a grenade will always go off in your face, its not really useful at all...

**Comment by coderanger** [comment]
If we want to leave in the ability to have manual control over exit codes, it should probably be something structural like a special exception class rather than configured.

**Comment by smurawski** [comment]
@lamont-granquist @coderanger I'm totally cool with removing the opt-out. :)

**Comment by coderanger** [comment]
I vote to purge with :fire: and add it back in 13.1 if someone complains hard enough

**Comment by smurawski** [comment]
The rspec failures will be fixed with https://github.com/chef/chef/pull/6009

**Pull request merged**
