### PR TITLE
Propose Steven Murawski as a maintainer for Chef Core

### PR DESCRIPTION
**Pull request by smurawski**
Opinions @chef/maintainers ?

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:+1:

**Comment by mcquin** [comment]
:balloon:

**Comment by ranjib** [comment]
:+1:

**Comment by jonlives** [comment]
:+1:

**Comment by tyler-ball** [comment]
:+1:

**Comment by thommay** [comment]
:+1:

**Comment by jdmundrawala** [comment]
:+1:

**Comment by btm** [comment]
:+1: needed 6 votes, accumulated 8. rebased and merged as bd4250090372c101bd1fb21dc7c8abffdf50756c.

Welcome to @chef/client-core @smurawski!

**Pull request closed without merging**
