### PR TITLE
A simple change to add periods at the end of sentences.

### PR DESCRIPTION
**Pull request by juliegund**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @juliegund

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by ksubrama** [comment]
Nice change Julie!  Just remember to sign the ICLA or the CCLA (I would think that Taos consulting would have a corporate agreement with Chef) in Supermarket and Currybot will automatically approve you for committing here.

**Comment by juliegund** [comment]
We do have a corporate agreement :) I will sign asap

Sent using a mouse-sized keyboard with feigned autocorrect intelligence

Julie Gunderson
Relationship and Community Manager


Direct: 408-324-2968<tel:408-324-2968>
Cell: 408-202-5712<tel:408-202-5712>
Email: jgunderson@taos.com<mailto:jgunderson@taos.com>

TAOS<http://www.taos.com/> | www.taos.com<http://www.taos.com/>
121 Daggett Dr. San Jose, CA 95134<x-apple-data-detectors://2> | Bay Area’s Top Workplace of 2011 & 2012 |

On Apr 2, 2015, at 1:05 PM, Kartik Null Cating-Subramanian <notifications@github.com<mailto:notifications@github.com>> wrote:


Nice change Julie! Just remember to sign the ICLA or the CCLA (I would think that Taos consulting would have a corporate agreement with Chef) in Supermarket and Currybot will automatically approve you for committing here.

—
Reply to this email directly or view it on GitHub<https://github.com/chef/chef/pull/3185#issuecomment-89027861>.


This communication is Confidential Information. By using this message and attachments you implicitly consent to terms and conditions set forth at http://www.taos.com/email_disclaimer. If you do not consent or received this message in error, please destroy it.

**Comment by juliegund** [comment]
What is your Twitter name

Sent using a mouse-sized keyboard with feigned autocorrect intelligence

Julie Gunderson
Relationship and Community Manager


Direct: 408-324-2968<tel:408-324-2968>
Cell: 408-202-5712<tel:408-202-5712>
Email: jgunderson@taos.com<mailto:jgunderson@taos.com>

TAOS<http://www.taos.com/> | www.taos.com<http://www.taos.com/>
121 Daggett Dr. San Jose, CA 95134<x-apple-data-detectors://2> | Bay Area’s Top Workplace of 2011 & 2012 |

On Apr 2, 2015, at 1:05 PM, Kartik Null Cating-Subramanian <notifications@github.com<mailto:notifications@github.com>> wrote:


Nice change Julie! Just remember to sign the ICLA or the CCLA (I would think that Taos consulting would have a corporate agreement with Chef) in Supermarket and Currybot will automatically approve you for committing here.

—
Reply to this email directly or view it on GitHub<https://github.com/chef/chef/pull/3185#issuecomment-89027861>.


This communication is Confidential Information. By using this message and attachments you implicitly consent to terms and conditions set forth at http://www.taos.com/email_disclaimer. If you do not consent or received this message in error, please destroy it.

**Comment by lamont-granquist** [comment]
Obvious fix.

**Pull request merged**
