### PR TITLE
Revert "Remove poise from the test matrix"

### PR DESCRIPTION
**Pull request by coderanger**
Reverts chef/chef#4477

My test systems are upgraded and good to go!

### CODE REVIEW

**Comment by jaym** [comment]
master is broken :(

**Comment by coderanger** [comment]
@jaym As in master is broken outside of this change?

**Comment by jaym** [comment]
yep

**Comment by coderanger** [comment]
Okay, any objection to merging anyway as the Poise part of the build matrix succeeded?

**Comment by jaym** [comment]
:+1: the failure has nothing to do with this change

**Pull request merged**
