### PR TITLE
Add package source suppport for openbsd_package

### PR DESCRIPTION
**Pull request by mafigit**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @mafigit

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by kmerz** [comment]
:+1:

**Comment by thommay** [comment]
Hey @mafigit , please can you add some tests to this to confirm that both branches (ie, with source or with name + version) work? Then we'd be happy to take this.
Thanks! (cc @chef/client-openbsd )

**Comment by thommay** [comment]
@mafigit we're going to close this PR since it's been hanging around for a while. If you'd like to add tests, we'd be happy to review and merge. Thank you!

**Pull request closed without merging**
