### PR TITLE
fix password property is sensitive for mount resource 

### LINKED ISSUE #4850: Mount provider should support sensitive property
## Description

I am using Chef-vault to try and keep my passwords secure. I am currently using one of the vault Items to try and mount a share. 

My problem is that the error output from chef printed the RAW password, not the encrypted or hashed out version, meaning anyone can circumvent the chef-vault by creating a bad mount recipe!

Would it not be better to hash out ALL 'password' attributes/fields in when printing them so that they are not shown to users (who might not be intended to see them!) or stored in log files?
## Chef Version

Chef: 12.6.0
## Platform Version

Windows 10
## Replication Case

  mount 'O:' do
    device '\\myShare\myFolder'
    action :mount
    domain 'myDomain'
    username testUser['username']
    password testUser['password']
  end
## Client Output

Error output:
    mount("O:") do
      action [:mount]
      supports {:remount=>false}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      mount_point "O:"
      device "'\\myShare\myFolder'"
      device_type :device
      fsck_device "-"
      fstype "auto"
      options ["defaults"]
      dump 0
      pass 2
      username "muUser"
      password "myPassword"
      domain "myDomain"
      declared_type :mount
      cookbook_name "sn_users"
      recipe_name "test_user"
    end

### PR DESCRIPTION
**Pull request by dimsh99**
Signed-off-by: dmitrys <dmitrys@northernlight.com>

### Description

Password properties become sensitive by default

### Issues Resolved

#4850

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by coderanger** [comment]
Not a fan of this approach. It's cute but too much magic for me to be in Chef core. 4850 should be fixed in the mount resource itself IMO.

**Comment by coderanger** [comment]
To expand, keying this off the name is not super robust. If a property was named `user_password`, for example, or if the code isn't written in English. It's not a bad assumption but it's overly narrow and we can't possibly parse all human-readable names into secret and not-secret. Better to use the existing explicit API of `property(:password, sensitive: true)`.

**Comment by lamont-granquist** [comment]
pretty sure we're following that pattern of marking the password property as sensitive on an individual resource now somewhere as well...

it looks like i was the one that mentioned doing this globally and that was probably not one of my best ideas...

**Comment by lamont-granquist** [comment]
`execute.rb:      property :password, String, sensitive: true`

**Comment by lamont-granquist** [comment]
`remote_file.rb:      property :remote_password, String, sensitive: true`

**Comment by coderanger** [comment]
This also makes the `username` property be sensitive, is that needed?

**Comment by dimsh99** [comment]
It doesn't make it sensitive, but it's my mistake made while removing old :password definition. I'm really sorry for that.

**Comment by thommay** [comment]
This is a great addition, thank you!

**Pull request merged**
