### PR TITLE
Resolve new spacing offenses in RuboCop 1.4

### PR DESCRIPTION
**Pull request by tas50**
If we really care we can turn this off, but it seems fine

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Review by phiggins — APPROVED** [review]
Not sure I'm a fan of this one...

**Comment by tas50** [comment]
@phiggins We can disable this particular part of the cop in chefstyle if you want

**Comment by phiggins** [comment]
If you like it you should keep it, it's not going to be my concern for too much longer. :)

**Comment by tas50** [comment]
I disabled the 1 offenses here, which made this much more reasonable: https://github.com/chef/chefstyle/pull/115

**Pull request merged**
