### PR TITLE
[WIP][Chef-16] Disable caching for adhoc build as it causes build failures

### PR DESCRIPTION
**Pull request by neha-p6**
Signed-off-by: Neha Pansare <neha.pansare@progress.com>

## Description

Disable caching in adhoc pipeline using environment variable IGNORE_CACHE, otherwise it results in failures ever since chef16 started getting built with ruby31.
Failures will be mostly on the lines of
```


I \| 2022-12-15T11:13:08+02:00 \| Deleted tag 'restore_here' (was 167c20b5)
--
  | The following shell command exited with status 128:
  |  
  | $ git -c core.autocrlf=false -c core.ignorecase=false --git-dir="/var/cache/omnibus/chef/cache/git_cache/opt/chef" --work-tree="/opt/chef" checkout -f restore_here
  |  
  | Output:
  |  
  | (nothing)
  |  
  | Error:
  |  
  | fatal: bad object refs/heads/master


```

UPDATE: This is currently blocked with packages team as even if the IGNORE_CACHE is set config.yml, buildkite builds don't pick up the set value until we explicitly set it when triggering the build via UI or CLI, e.g builds referenced in comments below.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by neha-p6** [comment]
Adhoc build testing this https://buildkite.com/chef/chef-chef-chef-16-omnibus-adhoc/builds/71

**Review by johnmccrae — APPROVED** [review]

**Comment by johnmccrae** [comment]
I updated a couple of things to get past the windows and mac build errors. I also tried to fix the amazon linux issue

```ruby
      def current_rhel_tz
        return nil unless ::File.exist?("/etc/sysconfig/clock")

        # https://rubular.com/r/aoj01L3bKBM7wh
        /ZONE="(.*)"/.match(::File.read("/etc/sysconfig/clock"))[1]
      end
```
That code, taken from timezone.rb line 99 or so was originally called for Amazon Linux. The problem is that /etc/sysconfig/clock doesn't exist so the return is nil and then a failure in parsing time data. 

Calling `timedatectl status` can return a failure if not run as root. However chef-client should be running elevated when this is executed. So I'm a little stumped as to why that fails. The code also fails if you try to change the timezone while not elevated as well.

**Comment by neha-p6** [comment]
Latest build https://buildkite.com/chef/chef-chef-chef-16-omnibus-adhoc/builds/86

**Comment by neha-p6** [comment]
The issue is no longer there in adhoc builds, hence closing

**Pull request closed without merging**
