### PR TITLE
Bump ruby to 2.2.5

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
reverting the revert of 2.2.4 needs to happen as well:

https://github.com/chef/chef/pull/4779/files

plus we need to drop 2.1.x out of the matrix and bump the required_ruby_version

**Comment by lamont-granquist** [comment]
the ffi github branch can be replaced by pinning to `>= 1.9.11` which is where my patch to fix the solaris builds got released.

**Comment by lamont-granquist** [comment]
👍

**Comment by danielsdeleo** [comment]
I think we need to get https://github.com/chef/chef-rfc/pull/211 accepted before we ship anything. If this is urgent, let's try to expedite that?

**Comment by mwrock** [comment]
:+1: with aggreement to @danielsdeleo

**Comment by danielsdeleo** [comment]
I'm 👍 on the actual patch once we vote to let ourselves merge it

**Comment by lamont-granquist** [comment]
looks like history is not rewritten by the victors, it is rewritten by the force push...

**Comment by thommay** [comment]
once the necessary bits of #4779 are pulled back in 👍

**Comment by jkeiser** [comment]
I think we figured out 2.3; leaving this open while figuring that out.

**Pull request closed without merging**
