### PR TITLE
use threads to workaround Process.spawn buginess in chef-solo unit test

### PR DESCRIPTION
**Pull request by lamont-granquist**
there's a WONTFIX closed bug in ruby-lang.org on this bug:

https://bugs.ruby-lang.org/issues/10583

they seem to be favoring speed over usability with the result
that if you're doing I/O synchronization (like our run_lock?)
inside of a Process.spawn chain like this that you have to
wrap the spawn calls inside of threads.

probably a best practice to wrap every spawn call with a
Thread.

this probably also explains why we had the silly-long 20
second timeout?

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core brace yourselves, more than you ever wanted to know about Process.spawn...

**Comment by lamont-granquist** [comment]
@btm this is the fix

**Comment by lamont-granquist** [comment]
@btm @thommay mashing the green button will make our tests better, you know you wanna...

**Comment by stevendanna** [comment]
The most satisfying part of this PR is `--l debug` -> `-l debug`.

**Comment by stevendanna** [comment]
I'm 👍.  Mixing threads+fork is usually something I'm wary of (maybe urban legends?) but this is in test code and we we are doing pretty straightforward.

**Comment by lamont-granquist** [comment]
http://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them

so spawn isn't exactly fork and i'm not sure what exactly it is on unix, but thread+fork()+execve() works mostly right and we don't care about cloexec races.

**Comment by lamont-granquist** [comment]
I'm also pretty certain that ruby >= 2.0.0 sets the cloexec flag by default when it opens fds so even that race is removed

**Pull request merged**
