### PR TITLE
remove use of self.provides?

### PR DESCRIPTION
**Pull request by lamont-granquist**
the block to provides can handle this case

### CODE REVIEW

**Comment by coderanger** [comment]
Not sure I like this direction, makes things gross for subclassing core providers.

**Comment by lamont-granquist** [comment]
Hmmm, well @jkeiser suggested this.  He also wanted to try to eliminate self.supports? as well and pass resource and action into provides blocks, but that call is buried inside of node_map, which on first glance would require surgery to the node_map API.

**Comment by coderanger** [comment]
Putting in blocks like that means it isn't accessible to a subclass though, not sure why it makes things any better in the long run?

**Comment by lamont-granquist** [comment]
Makes it a bit more DSLey and eliminates one more thing.  I think john also wanted to try to eliminate provides? entirely now that we're not doing descendants tracking scanning and clean up the code internally.  He'll have to pop in here after he gets back from vacay though.

**Comment by coderanger** [comment]
Yeah, we should probably have a longer talk about the semantics of subclassing/extending resources and providers.

**Comment by lamont-granquist** [comment]
paging @jkeiser into this discussion again.

after thinking about this, the problem is that when you subclass you only get `#provides?` and not the provides methods, which is not going to be useful to subclasses of these classes anyway.   by merging this it makes it so none of the provides logic is inherited which seems actually better than half of the provides logic being inherited.  so, i'd argue that this should go in.

there's a larger argument about the utility or wisdom of inheriting `provides` and `provides?` in subclasses and if `provides?` should still exist or not, which i think i'm slightly biased against, but ultimately agnostic about.  if `provides?` is used in poise to inherit behavior in subclasses i think thats fine, but i don't see the utility in these specific cases.

**Comment by jkeiser** [comment]
If it's possible, we should remove either `provides?` or blocks sent to `provides`, just to reduce what is already a sprawlingly-large number of toggles and knobs on this feature. It seems like you *can* implement either one in terms of the other, and the DSL form of `def provides` is more granular. It seems like the model works better if we can put the block in the DSL entry rather than the provider class, just to make the lookup code wholly concerned about that entry and not concerned about the class.

Here's one thing I hadn't considered: we could make it so that if you don't specify a block to the DSL, it will default to calling `provides?`, but if you do, it won't. That gets rid of the code that implements the `provides?` knob, at least.

I'm really kind of ignorant as to what logic we put here. In the `provides` cases we already have, it sounds like most of this stuff *shouldn't* be inherited? Is that right?

**Comment by coderanger** [comment]
When I talk about subclasses I mean people subclassing core providers, not anything in Poise. Like wanting to customize the behavior of your service provider, so you subclass it and tweak some methods. I think it is rare enough (the majority of those cases would be applying the provider manually thus making all the lookup plumbing moot) that I'm behind simplifying the code, but we should figure out something for the long term to make it not required to copy-pasta the whole `provides()` call in a subclass. Maybe something like a method you can call at the class level which says "I provide the same things as my base class, make it so"? I've been [experimenting with that for resources recently](https://github.com/poise/poise/blob/master/lib/poise/helpers/resource_subclass.rb), but a lot of same ideas apply.

**Comment by lamont-granquist** [comment]
paging @chef/client-core and @thommay in particular into this convo

**Comment by tyler-ball** [comment]
I'm partial to removing `provides?` and adding some kind of `protected` method that subclasses can call to copy the `provides` behavior from the parent (AKA, @coderanger's suggestion).

If we do add this ability, the subclass would still need to be able to modify the `provides` logic in case it needs to add or remove specifications.

**Comment by lamont-granquist** [comment]
For now can we merge this?  The existing code allowing half-inheritance of `provides?` but not `provides` isn't offering anything useful.

**Comment by lamont-granquist** [comment]
(BTW @tyler-ball `protected` doesn't do what you think it does -- you probably meant a `private` method--which is still accessible to subclasses in ruby...   the utility of `protected` over `private` is very narrow in ruby...)

**Comment by coderanger** [comment]
:+1: on merging this as long as it isn't used as future justification to remove `#provides?` itself :)

**Comment by tyler-ball** [comment]
:+1:

**Comment by lamont-granquist** [comment]
Yep, will keep `#provides?` just won't be using it here.

**Pull request merged**
