### PR TITLE
Cherry pick omnibus commit

### PR DESCRIPTION
**Pull request by scotthain**
Signed-off-by: Scott Hain <shain@chef.io>

@mwrock pending success of http://manhattan.ci.chef.co/job/angrychef-build/6/

### CODE REVIEW

**Comment by scotthain** [comment]
@chef/engineering-services 

(this pulls in the omnibus commit that reflects the correct GCC for sles 11)

**Comment by schisamo** [comment]
Doesn't the bump bot take care of this automatically?

**Comment by scotthain** [comment]
@schisamo as far as I know, it doesn't... I don't know all the details of how it works, but the history leads me to believe it doesn't: https://github.com/chef/chef/commits/master/omnibus/Gemfile.lock

**Comment by mwrock** [comment]
no @schisamo the bump bot just bumps the version and submits a release build

**Comment by schisamo** [comment]
@mwrock What is the dep update stuff for then?
https://github.com/chef/lita_versioner#dependency-update

**Comment by mwrock** [comment]
right there is a timer based action that does update deps. TBH: I'm not familiar with the details of its current status and believe there is a card to address it more formally.

**Pull request merged**
