### PR TITLE
Add gemspec files to allow bundler to run from the gem

### PR DESCRIPTION
**Pull request by ksubrama**
/cc @jkeiser @chef/client-core

### CODE REVIEW

**Comment by danielsdeleo** [comment]
:+1: please just run through a gem build/install to make sure we don't have any issues like extraneous files (like in the ChefDK version of this).

**Comment by lamont-granquist** [comment]
:+1:

**Comment by ksubrama** [comment]
@danielsdeleo Yep - again one extra issue identified (chef-config is not available at the path specified in the Gemfile) that wouldn't have hurt gem build/install but did cause bundler to freak out.  Fixed that.

**Comment by danielsdeleo** [comment]
Cool, :+1:

**Pull request merged**
