### PR TITLE
Re-add #priority.

### PR DESCRIPTION
**Pull request by coderanger**
Possible fix for https://github.com/chef/chef/issues/3561.

### CODE REVIEW

**Comment by jkeiser** [comment]
Yuck!  Is someone using it?  I thought this was @api private.

**Comment by coderanger** [comment]
Back in 12.2 it was the only API to add stuff, and definitely not private: https://github.com/chef/chef/blob/12.2.0/lib/chef/platform/provider_priority_map.rb#L77-L79

**Comment by coderanger** [comment]
12.3 added `set_priority_array` as basically an alias for `priority` but it still wasn't private.

**Comment by jkeiser** [comment]
Right then, can't remove it. :+1:

**Comment by coderanger** [comment]
Also `get_priority_array` and `set_priority_array` probably shouldn't be private.

**Comment by jdmundrawala** [comment]
do we want to ask people not to use this?

**Comment by coderanger** [comment]
Deprecating it would be fine but printing a warning might annoy people since the code to switch to a different-but-identical function that didn't exist in 12.2 is kind of aggravating.

**Comment by jdmundrawala** [comment]
:+1:

**Pull request merged**
