### PR TITLE
Core: set use_inline_resources in package superclass

### PR DESCRIPTION
**Pull request by lamont-granquist**
allows subclasses to use_inline_resources (hab_package
will most likely want this)

### CODE REVIEW

**Comment by lamont-granquist** [comment]
i don't believe this changes any existing behavior.

**Comment by coderanger** [comment]
I subclass the package provider a whole bunch, so it might break some of my stuff.

**Comment by lamont-granquist** [comment]
hrm, can you test and get back if it fails and how it fails?

i'd mostly guess that you turn on something similar which might get into a fight with this, but we should find out what that is and resolve any impedence mismatch there before chef 13 anyway...

**Comment by coderanger** [comment]
I just did a quick lookover of the code for `python_package` and `node_package`, both look like they should be okay. Neither uses `notifying_block` anywhere, it's all straight `shell_out` calls. :+1: to merge and see if anything breaks :)

**Comment by lamont-granquist** [comment]
looks like i need to add a mock to some windows unit tests...

**Pull request merged**
