### PR TITLE
Save Key secret in HKEY_CURRENT_USER

### LINKED ISSUE #13402: Regression: Unable to run chef on windows if diffrent users perform chef runs
## Description

We are runinning chef in local mode on windows with 2 diffrent users.
We are performing one chef run as system user and a second chef run with the current logged in user wich is a user without admin rights.
The problem is that chef is encrypting the client certificate with user 1 and user 2 can not decrypt the Secure-String wich was created by user 1.
This is working on chef version 17.10.0.

## Chef Version

Chef Infra Client: 18.0.185

## Platform Version

Microsoft Windows [Version 10.0.19044.2251]

## Replication Case
Run chef in local mode as user 1 on windows.
Create user 2 and try to run chef in local mode.
Chef fails to run with the stacktrace below.

## Stacktrace

```
Generated at 2022-12-06 14:16:14 +0100
ChefPowerShell::PowerShellExceptions::PowerShellCommandFailed: Unexpected exit in PowerShell command: ["ConvertTo-SecureString: Key not valid for use in specified state.\r\n\nAt line:1 char:515\r\n+ ... e340283997ac58324acb50c492e42a3242f20fec1eb\" | ConvertTo-SecureString\r\n+                                                    ~~~~~~~~~~~~~~~~~~~~~~", ": Exception calling \"SecureStringToBSTR\" with \"1\" argument(s): \"Value cannot be null.\r\nParameter name: s\"\nAt line:2 char:1\r\n+ $string = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"]
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-powershell-1.0.13/lib/chef-powershell/powershell.rb:63:in `error!'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-powershell-1.0.13/lib/chef-powershell/powershell_exec.rb:128:in `powershell_exec!'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:215:in `decrypt_pfx_pass'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:177:in `block in get_cert_password'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:175:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:175:in `get_cert_password'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:222:in `retrieve_certificate_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:98:in `retrieve_certificate_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:140:in `load_signing_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:45:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:104:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:104:in `block in initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:103:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:103:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/server_api.rb:40:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/client.rb:393:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/client.rb:393:in `rest'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/client.rb:266:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:281:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/local_mode.rb:42:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:264:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application/base.rb:352:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:67:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.0.185/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/embedded/bin/chef-client:32:in `load'
C:/opscode/chef/embedded/bin/chef-client:32:in `<main>'
```

### PR DESCRIPTION
**Pull request by floh96**
Save the PfxPass in HKEY_CURRENT_USER so that a Windows User without admin rights can create the key.

## Description

At the moment the key is saved in HKEY_LOCAL_MACHINE and a windows user without admin rights can not save the key in this location.
Therefore at the moment a windows user without admin rights gets the following error when trying to run chef:

```
[2022-12-07T13:55:56+01:00] WARN: Authentication Hive and values not present in registry, creating them now

Running handlers:
[2022-12-07T13:55:57+01:00] ERROR: Running exception handlers
Running handlers complete
[2022-12-07T13:55:57+01:00] ERROR: Exception handlers complete
Infra Phase failed. 0 resources updated in 21 seconds
[2022-12-07T13:55:57+01:00] FATAL: Stacktrace dumped to C:/Users/Berater/.chef/state/cache/chef-stacktrace.out
[2022-12-07T13:55:57+01:00] FATAL: ---------------------------------------------------------------------------------------
[2022-12-07T13:55:57+01:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
[2022-12-07T13:55:57+01:00] FATAL: ---------------------------------------------------------------------------------------
[2022-12-07T13:55:57+01:00] DEBUG: Win32::Registry::Error: Zugriff verweigert
C:/opscode/chef/embedded/lib/ruby/3.1.0/win32/registry.rb:289:in `OpenKey'
C:/opscode/chef/embedded/lib/ruby/3.1.0/win32/registry.rb:431:in `open'
C:/opscode/chef/embedded/lib/ruby/3.1.0/win32/registry.rb:542:in `open'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/win32/registry.rb:81:in `set_value'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:196:in `rescue in get_cert_password'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:166:in `get_cert_password'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:222:in `retrieve_certificate_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:98:in `retrieve_certificate_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:140:in `load_signing_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:45:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:104:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:104:in `block in initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:103:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:103:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/server_api.rb:40:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/client.rb:393:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/client.rb:393:in `rest'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/client.rb:266:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:281:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/local_mode.rb:42:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:264:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application/base.rb:352:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:67:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.0.185/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/embedded/bin/chef-client:32:in `load'
C:/opscode/chef/embedded/bin/chef-client:32:in `<main>'

>>>> Caused by Chef::Exceptions::Win32RegKeyMissing: Chef::Exceptions::Win32RegKeyMissing
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:172:in `get_cert_password'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:222:in `retrieve_certificate_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:98:in `retrieve_certificate_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:140:in `load_signing_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:45:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:104:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:104:in `block in initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:103:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:103:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/server_api.rb:40:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/client.rb:393:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/client.rb:393:in `rest'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/client.rb:266:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:281:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/local_mode.rb:42:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:264:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application/base.rb:352:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:67:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.0.185/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/embedded/bin/chef-client:32:in `load'
C:/opscode/chef/embedded/bin/chef-client:32:in `<main>'
[2022-12-07T13:55:57+01:00] FATAL: Win32::Registry::Error: Zugriff verweigert
```

This also fixes #13402 because now each user gets it's own PfxPassword. (Strings encrypted mit ConvertTo-Secure-String can only be decrypted by the user wich encrypted the string.)
I have tested the change on a windows vm and can run chef with a user without admin rights with this change.

## Related Issue

#13402

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by floh96** [comment]
cc @johnmccrae you implemented the feature in #12426.
I see that my change broke some tests unfortunally I'm not a ruby expert maybe you could hop in and finish this?
Would be awesome.

**Comment by floh96** [comment]
@johnmccrae thank you for looking into it!
> I put that key under local machine so Chef would always be able to get to it.
If you are using ConvertTo-SecureString to encrypt the key the key must be user specific because strings that are encrypted with ConvertTo-SecureString can only be decrypted from the same user [(stackoverflow explanation)](https://stackoverflow.com/questions/46006674/convertto-securestring-run-without-key-on-different-user-account-is-there-a-way)
At the moment if you try to run chef with two diffrent users on the same machine you will get the Key not valid for use in specified state error i got in #13402.

**Review by jaymzh — CHANGES_REQUESTED** [review]
OK this is a bit more complicated than it looks. We discussed this at length in the PR review meeting this week and this is my attempt to sum up the conclusions.

Background: We write keys to the registry instead of the filesystem now (as of 18)

It looks like from the use case that you have two runs, that share the same key. Having two seperate runs if fine, but having them hare a key is a dangerous way to have two separate runs on the same system (and probably not supportable and never intended) - I'll talk about that below, but... Even in 17 this would only work in the SYSTEM chef run ran first to create the key, and that's (I believe) true here too - if the SYSTEM run ran first, the key should be readable by the non-system users. You're failing to write, not read, and back in the 17 (filesystem) days, the non-admin user wouldn't have been able to write to the chef directory either (without permission hacking).

To have two separate runs on the same system, they should have separate `nodename`s and (presumably) separate runlists, which probably means separate config dirs. Separate `nodename`s imply separate keys. In the filesystem days throwing two separate config dirs at it, would Just Work(TM) - you'd have different places to write keys, probably different log directories, etc. But now, that doesn't work anymore... because of the registry.

Which leads to this PR. This PR isn't the right fix - at the very least it'll break existing users who will fail to find their keys. We probably need a configuration flag like `--auth-key-registry-type [MACHINE|USER]`. For system runs, you can leave it off and have it default to `MACHINE`. For user runs, you could pass in `--auth-key-registry-type USER`, and that users would get their own key in their own user key.

At that point, the supportable way to do what you're doing is to have two separate runs, one with nodename of the hostname or wahtever you use today and then one of "#{hostname}-#{username}" (`$HOSTNAME-Berater` in this case), with two separate configs, the latter of which specifies in its config file `auth_key_registry_type USER`. This would:

1. Ensure separate runlists on the server
2. Ensure separate stats on the server
3. Ensure ordering of chef runs does not matter, ever

In the short-term, it seems like making sure your system-level chef run happens first should be a temporary work around (I think, but I"m guessing a lot about your environment, and I'm not a Windows expert).

**Comment by floh96** [comment]
Closing this pr since I'm not able to implement the proposed solution.
Thanks for the discussion which is continuing in #13402

**Pull request closed without merging**
