### PR TITLE
Make apt package provider use_multipackage_api aware

### PR DESCRIPTION
**Pull request by lamont-granquist**
general modernization of apt_package

- removing/purging virtual packages works now ( at least a virtual package with only one option -- which is all that we support installing)

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core i think this is good for today

**Comment by thommay** [comment]
👍

**Comment by lamont-granquist** [comment]
for future reference - this still does not fix the purge-vs-remove issue (need to pull the pattern out of the dpkg provider that i used to fix that)

**Comment by lamont-granquist** [comment]
Cool, I do promise that I'll get to FreeBSD eventually, but RHEL is a bit of a disaster these days and takes precedence unfortunately...

**Pull request merged**
