### PR TITLE
Fix faulty umask logic used in spec tests.

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by btm** [comment]
What was wrong with the previous values?

**Comment by ksubrama** [comment]
The subtraction being performed was incorrect.  umask gets "masked out" from the default permissions, not subtracted.  So if your umask was 077 and you attempted to create a file with 666, you'd get 600.  Instead the test expected 666-077 = 567, which is incorrect.

**Comment by btm** [comment]
Got it. So these would pass previously out of the box, but they potentially wouldn't for someone who has changed their system umask default?

/cc @chef/client-windows review?

**Comment by ksubrama** [comment]
Yep - that's how I ran into it.  The tests were passing for @smurawski and on the CI but not for me because I changed my umask to 077 in my bashrc.

**Comment by lamont-granquist** [comment]
Why is `010666` getting changed to `0666`, any idea what that was doing there previously?

**Comment by ksubrama** [comment]
I believe it's mostly due to copy-pasta or some dodgy math.  AFAIK, you only have 3 more permissions bits: sticky, suid and sgid.  The 1 in 010666 was getting masked out by & 07777 anyway - so I can't think of a good reason why it's there.  I would guess that someone in the past put a leading 1 to prevent underflow during subtraction but subtraction is the wrong operation to be performing anyway - so *shrug*.

**Comment by ranjib** [comment]
:+1:  i have hit this before. i.e test failures due to wrong mode (i was getting 02 prepended on the expected file mode),

**Comment by lamont-granquist** [comment]
:+1:

**Pull request merged**
