### PR TITLE
Add Salim as a windows maintainer

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by smurawski** [comment]
:+1:

**Comment by ksubrama** [comment]
:+1:

**Comment by btm** [comment]
https://github.com/chef/chef-rfc/blob/master/rfc030-maintenance-policy.md#maintainer-1

Technically there needs to be more than 50% positive votes from the component maintainers/LTs. Since there are four existing LT/maintainers, that means 3 votes.

So I'll toss in an ex post facto :+1: to put you back on the good side of the law.

**Pull request merged**
