### PR TITLE
Add support for specifying ETHTOOL_OPTS

### PR DESCRIPTION
**Pull request by tomdoherty**
### Description

Allow specifying ETHTOOL_OPTS via ethtool_opts on Red Hat

### Issues Resolved

None - improvement

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core needs another review and a merge

**Comment by adamleff** [comment]
I'll merge once the tests go green.

**Comment by tomdoherty** [comment]
Cheers guys – I think I have fixed the unit tests now. Thanks for all the help – please let me know if there’s anything additional I need to do to get these changes in!

**Comment by tas50** [comment]
Merging this change isn't why the proxy tests are failing

**Comment by tas50** [comment]
@tomdoherty Congrats on your first contribution

**Comment by tomdoherty** [comment]
Thank you! Can't wait to roll it out accross our fleet :-)
Thank you to all they guys on Slack for their constant support and patience!

**Pull request merged**
