### PR TITLE
Use upstart goal state as service status

### PR DESCRIPTION
**Pull request by evan2645**
Solves #5204

### CODE REVIEW

**Comment by evan2645** [comment]
test failures look unrelated. some due to 503 from chef download in kitchen, one other from error installing a gem. lmk if we need anything else here

**Comment by thommay** [comment]
:+1: LGTM. I gave travis a quick kick. @chef/client-core

**Comment by ranjib** [comment]
:+1:

**Comment by ranjib** [comment]
i'll take a look at the specs, its chef-zero related and failing consistently across PRs

**Comment by thommay** [comment]
@ranjib it seems like it was a busted cache, so we cleared them and now travis is happy!

**Comment by ranjib** [comment]
yeah.. i am manually kicking some of the PRs failed job. Travis has been shaky for us internally as well.

**Pull request merged**
