### PR TITLE
Fix functional tests for group resource - fix #3728

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by ksubrama** [comment]
Related to https://github.com/chef/chef/pull/3728

**Comment by ksubrama** [comment]
We figured out that the tests weren't failing on travis because this test needs either root or windows admin. That would explain why travis and appveyor were both happy with it.  I've manually run the test on a non-domain joined Windows box and on my Mac (as root).  If anyone else wants to try a different platform, you're welcome to do so :)

**Comment by thommay** [comment]
Looks reasonable to me :+1:

**Comment by ksubrama** [comment]
Merging to unbreak omnibus.

**Pull request merged**
