### PR TITLE
Reduce size of json nested entries

### LINKED ISSUE #3101: json_compat unit tests cause systemstackerror on freebsd 10.1 i386
The unit tests in ```spec/unit/json_compat_spec.rb ``` that test ~300 deep nested hash raise a "stack level too deep (SystemStackError)" exception:

```
-bash-4.3$ uname -a
FreeBSD ip-10-194-8-88 10.1-RELEASE-p6 FreeBSD 10.1-RELEASE-p6 #0: Tue Feb 24 18:57:59 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  i386
-bash-4.3$ /opt/chef/embedded/bin/rspec -fd spec/unit/json_compat_spec.rb 
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1226: stack level too deep (SystemStackError)
```

The amd64 version of this system does not have this error.

I tried increasing the stacksize from 65536kb to 524288kb as displayed by ```limits``` This matches the amd64 system, but had no effect.

Something is limited to only 254 levels deep. Which still seems like plenty, recalling the purpose of these tests to begin with. Perhaps we should disable the 300/301 tests on freebsd i386?

### PR DESCRIPTION
**Pull request by btm**
On FreeBSD 10.1 i386 we're seeing rspec 3.2.2 raise SystemStackError if the expect line has
a nested hash of 255 levels. I'm going to guess we don't even need this many. I lowered this
test from 1000 to 300 arbitrarily some time ago.

Fixes #3101

### CODE REVIEW

**Comment by btm** [comment]
@martinisoft got a better idea about why this is happening?

@chef/client-core review?

**Comment by lamont-granquist** [comment]
I'm sort of curious as to why ffi-yajl throws a SystemStackError only on FreeBSD and what is going on there?   YAJL_MAX_DEPTH is 128 and I don't think we bump that up at all, so you could drop the nesting down to that level.  Although I think the purpose of the test might be to catch issues exactly like this.

**Comment by btm** [comment]
The purpose of the test is definitely to catch nesting issues, but we never have specified how deep of nesting we need.

I'm curious too. It works fine on the x64 tester.

**Comment by danielsdeleo** [comment]
These test failures are odd. Anyone know what's up with them?

```
  1) Chef::Resource::Execute when parent resource sets :cwd guard inherits :cwd from resource and runs
     Failure/Error: expect(resource).to be_updated_by_last_action
       expected `<execute[foo_resource] @name: "foo_resource" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :run] @action: "run" @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: nil @guard_interpreter: nil @default_guard_interpreter: :execute @elapsed_time: 0.290983172 @sensitive: false @resource_name: :execute @command: "echo hello" @backup: 5 @creates: nil @cwd: "/home/travis/build/chef/chef/spec/data" @environment: nil @group: nil @path: nil @returns: 0 @timeout: nil @user: nil @umask: nil @is_guard_interpreter: false>.updated_by_last_action?` to return true, got false
     # ./spec/functional/resource/execute_spec.rb:71:in `block (3 levels) in <top (required)>'
  2) Chef::Resource::Execute when parent resource sets :cwd guard inherits :cwd from resource and does not run
     Failure/Error: expect(resource).not_to be_updated_by_last_action
       expected `<execute[foo_resource] @name: "foo_resource" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :run] @action: "run" @updated: true @updated_by_last_action: true @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: nil @guard_interpreter: nil @default_guard_interpreter: :execute @elapsed_time: 0.348037213 @sensitive: false @resource_name: :execute @command: "echo hello" @backup: 5 @creates: nil @cwd: "/home/travis/build/chef/chef/spec/data" @environment: nil @group: nil @path: nil @returns: 0 @timeout: nil @user: nil @umask: nil @is_guard_interpreter: false>.updated_by_last_action?` to return false, got true
     # ./spec/functional/resource/execute_spec.rb:78:in `block (3 levels) in <top (required)>'
```

As for the change itself, IIRC the JSON gem has a default max nesting level of 20 and some users were running into issues with that, which is why the test was written. I'd definitely prefer to fix the ruby build if we can since this could maybe be a problem if we use a recursive algorithm for something. Is the FreeBSD issue occurring with omnibus-built ruby?

**Comment by btm** [comment]
@danielsdeleo yeah, it's the last remaining issue to get a build passing in manhattan: http://manhattan.ci.opscode.us/view/Chef/job/chef-test/36/

**Comment by danielsdeleo** [comment]
@btm that's weird, presumably it works in old Ci. Do we have any idea what the difference could be?

**Comment by btm** [comment]
In addition to playing with the system ulimits, I modified these environment variables to match other systems, and RubyVM::DEFAULT_PARAMS showed it was being affected, but the test was still failing with SystemStackError:
* RUBY_THREAD_MACHINE_STACK_SIZE
* RUBY_THREAD_VM_STACK_SIZE
* RUBY_FIBER_MACHINE_STACK_SIZE
* RUBY_FIBER_VM_STACK_SIZE

I then installed ruby/gems via pkg on the tester, and it runs the tests fine. It appears to be something in the Ruby that we're building.

**Comment by btm** [comment]
I kicked up the stack size on the builder to 524288, ran another build through, and saw the same issue on the tester. @schisamo maybe we should rebuild the freebsd10 x86 +x64 builders on the 10.1 AMI too, just in case? Probably easier than digging into the ruby source right now.

**Comment by danielsdeleo** [comment]
I wonder if the difference is in the parser. In any case, it seems like we've spent enough time investigating, I'd probably accept the easier fix at this point.

**Comment by schisamo** [comment]
@btm Roger that. will rebuild those slaves now.

**Comment by schisamo** [comment]
@btm OK the FreeBSD 10 builders (32-bit and 64-bit) have both been re-provisioned off the 10.1 AMI. Hoping this fixes your issues.

**Comment by btm** [comment]
This branch should pass the tests, as I wrote the tests on the tester. It's just that we don't understand what the builder is doing that's limiting the stack size.

**Comment by schisamo** [comment]
@danielsdeleo We don't build or test on FreeBSD 10 in old CI...that's the 'difference' presumably.

**Comment by schisamo** [comment]
@btm OK sent a build through with this branch of chef:
http://manhattan.ci.chef.co/job/chef-trigger-ad_hoc/25/downstreambuildview/

**Comment by martinisoft** [comment]
@btm I honestly am not sure why this would be happening. Didn't get the notification of the mention so I am chiming in kind of late here. Approving of the fix at this point provided the build can get to passing here.

**Comment by Aevin1387** [comment]
@btm This is pretty interesting because I tried this on a (mostly) fresh 10.1-p6 i386 install in virtualbox, and did not get the error. I wonder what the difference is in the AMI vs a base install of freebsd.

**Comment by btm** [comment]
@Aevin1387 you tried running out of a git checkout with a system ruby, or?

I suspect the issue is with the builder and the build of ruby we produce rather than the tester. I'll be working on this some more next week.

**Comment by Aevin1387** [comment]
@btm, git checkout with both ruby from RVM and from the embedded ruby in chef client. To make sure RVM wasn't polluting the environment, I also retried with a system that didn't have RVM installed. The chef client install was direct from the chef.io install, though that is technically meant for FreeBSD 9

**Comment by jdmundrawala** [comment]
I think we should merge this in. This is preventing us from getting nightlies out, and I'm not sure who is going to have json that deeply nested.
So :+1:

**Comment by btm** [comment]
@chef/maintainers so we're thinking we should just go with this, because 254 levels of nesting on the node object is beyond crazy anyway, right? This is blocking us from moving forward with the new build system that produces nightlies and other nice things and I've spent a bunch of hours trying to figure out why the FreeBSD 10 x86 build are being special in terms of stack size to no avail. Have I convinced you?

**Comment by btm** [comment]
@Aevin1387 yeah, so we're only seeing the failure when using the omnibus build that is being created on the FreeBSD 10 x86 builder we made (which we've remade and such as seen in the notes above). The tests pass for me with the other Rubies I've come up with.

**Comment by schisamo** [comment]
If it helps our FreeBSD 10.1 i386 builders and testers are EC2 instances provisioned with `ami-41fcb771`.

**Comment by danielsdeleo** [comment]
Yeah, I'm cool to just go with this. IIRC the original problem was that the json gem limits you to something like ~20 levels of nesting by default and people were barely hitting that, so I think we're good. If the core problem causes other issues on FreeBSD we can re-evaluate.

**Comment by lamont-granquist** [comment]
:+1:

**Comment by thommay** [comment]
:+1:

**Pull request merged**
