### PR TITLE
Strip spaces from apt_repository repo_name.

### PR DESCRIPTION
**Pull request by williamtheaker**
The filenames of .list files in `/etc/apt/sources.list.d` can't contain spaces or they get ignored by apt. This is already mentioned in the property description.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Review by johnmccrae — APPROVED** [review]

**Comment by jaymzh** [comment]
Please bear with us, we're still working on fixing CI on `main`.

**Comment by tpowell-progress** [comment]
@williamtheaker if you get a chance, please rebase off of `main` so that a cleaner CI run can validate these changes. Thanks!

**Comment by jaymzh** [comment]
Per discussion in meeting, these tests are still broken on main but unrelated to this PR so we'll merge.

**Comment by jaymzh** [comment]
Thanks for your patience!

**Pull request merged**
