### PR TITLE
remove Chef::Platform::HandlerMap

### PR DESCRIPTION
**Pull request by lamont-granquist**
seems like an entirely unnecessary level of indirection

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@coderanger unless this actually hoses some of your code, I think I'm arguing this is an implicit `@api private` that nobody should have been poking around in.

**Comment by lamont-granquist** [comment]
should probably use composition and delegation rather than inheriting from NodeMap as well, but not today...

**Comment by coderanger** [comment]
I'll read it tonight if I've got postconference brains left, I can also run a few of my test suites against it and see what shakes loose :)

**Comment by btm** [comment]
@tduffield this is a sort of thing that I'd want the changelog generator to pick up but it fits under a different category like 'deprecations' or 'notices'

**Comment by lamont-granquist** [comment]
"code cleanup"  or "tech debt"

**Pull request merged**
