### PR TITLE
We should not change how exceptions are raised if audit mode is disabled

### PR DESCRIPTION
**Pull request by jdmundrawala**
Patch for #3078

This is not the final solution, we need to think hard about the way we do this now that we know how people will break.

cc @chef/client-core

### CODE REVIEW

**Comment by btm** [comment]
:+1: this look right. it's a little hairy because a lot happens in the rescue block in #run, at least in this case we get back up there eventually. I'm not that familiar with the audit mode stuff.

@coderanger @tyler-ball thoughts?

**Comment by mcquin** [comment]
I'm fine with this as a temporary solution.

**Comment by tyler-ball** [comment]
Because our plan is to eventually enable `:audit_mode` by default, I think this just delays this issue until it pops back up.  I'm a bigger fan of [my comment](https://github.com/chef/chef/issues/3078#issuecomment-81142453) where we only wrap an error if both the converge phase and the audit phase raised an error.

But your code looks fine, and this fixes the error.  If more people support this solution then so do I.

If we take this patch, can you remove the `log.error` messages from the converge and audit rescue blocks per @coderanger's [comment](https://github.com/chef/chef/issues/3078#issuecomment-81241878)

**Comment by tyler-ball** [comment]
Also, my `RunFailedWrappingError` may be a terrible idea.  Whatever we do today, I think we should make an RFC for 'how we deal with exceptions in unrelated phases of chef'

**Comment by coderanger** [comment]
:+1: from me. Pinging https://github.com/sethvargo/chefspec/pull/572 so this is show as related over there too.

**Comment by jonlives** [comment]
:+1:

**Comment by thommay** [comment]
:+1: on this. I totally agree with @tyler-ball that we need an RFC around exception handling.

**Comment by btm** [comment]
pulled out the Chef::Log.error from the regular run as @tyler-ball suggested, but left the audit mode logging for now. Updated commit:

master: 625373d40febafa1c6621aaf179852601d303e6c
12-stable: 6c623de6c9c667213df582a81bade95adb2a03b4

**Pull request closed without merging**
