### PR TITLE
Don't print fips warning in test environment

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by ksubrama** [comment]
@jaym @btm

**Comment by btm** [comment]
Actually, I would like to remove that warning altogether now. We've another thing we want to do, but there's a complete set of functionality.

**Comment by btm** [comment]
somewhere else we print that we're running in FIPS mode too.

**Comment by ksubrama** [comment]
Yeah we do print that we've entered FIPS mode elsewhere.

**Comment by jaym** [comment]
:+1:

**Comment by btm** [comment]
:+1:

**Pull request merged**
