### PR TITLE
[MSYS-722] Fixes of Knife search not working with forward slash.

### PR DESCRIPTION
**Pull request by piyushawasthi**
**Knife search not working with forward slash**
**Pass:**
```
knife search node 'stack_id:arn\:aws\:cloudformation\:eu-west-1\:569478613970\:stack//*'
knife search node 'stack_id:arn\:aws\:cloudformation\:eu-west-1\:569478613970\:stack/*'
```
```
$ bundle exec knife search node 'stack_id:arn\:aws\:cloudformation\:eu-west-1\:569478613970\:stack//*'
2 items found

Node Name:   ammy-cnt
Environment: _default
FQDN:        ammy-cnt.ammy-cnt.d7.internal.cloudapp.net
IP:          10.158.218.44
Run List:    
Roles:       
Recipes:     
Platform:    centos 7.1.1503
Tags:        

Node Name:   msys
Environment: _default
FQDN:        msys-Lenovo-E41-80
IP:          192.168.101.66
Run List:    recipe[cache_replication_group]
Roles:       
Recipes:     cache_replication_group, cache_replication_group::default
Platform:    ubuntu 16.04
Tags:        

$ bundle exec knife search node 'stack_id:arn\:aws\:cloudformation\:eu-west-1\:569478613970\:stack/*'
2 items found

Node Name:   ammy-cnt
Environment: _default
FQDN:        ammy-cnt.ammy-cnt.d7.internal.cloudapp.net
IP:          10.158.218.44
Run List:    
Roles:       
Recipes:     
Platform:    centos 7.1.1503
Tags:        

Node Name:   msys
Environment: _default
FQDN:        msys-Lenovo-E41-80
IP:          192.168.101.66
Run List:    recipe[cache_replication_group]
Roles:       
Recipes:     cache_replication_group, cache_replication_group::default
Platform:    ubuntu 16.04
Tags:        
```

Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>

### Description

[Please describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by piyushawasthi** [comment]
Please don't merge, as per @btm suggestion we have to add unit test cases for forward slash.
as: `it "returns search results when the query contains a slash"`

**Comment by piyushawasthi** [comment]
@btm - I have added some test cases please review PR, and let me know in case of any concerns.

**Comment by piyushawasthi** [comment]
Thanks for valuable question @stevendanna 
1: if `query_string` contain single forward_slash then Chef::ServerAPI will return `Net::HTTPServerException: 400 "Bad Request"` error.
2: Yes as per issue it's related to the node.
3: I think Chef::ServerAPI.

**Comment by stevendanna** [comment]
> 1: if query_string contain single forward_slash then Chef::ServerAPI will return Net::HTTPServerException: 400 "Bad Request" error.

Yes, but why?

**Comment by btm** [comment]
fixed in https://github.com/chef/chef-server/pull/1444

**Pull request closed without merging**
