### PR TITLE
Remove freeze of defaults, add warning for array/hash constant defaults

### PR DESCRIPTION
**Pull request by jkeiser**
Relies on https://github.com/chef/mixlib-log/pull/10

### CODE REVIEW

**Comment by coderanger** [comment]
I'm guessing there was some internal discussion about this that would be good to know as context?

**Comment by jkeiser** [comment]
@coderanger yeah, the issue is it showed up in another cookbook (this one using `set_or_return` directly). Much as I really want to simply fix the issue for everyone, I'm starting to worry that it will cause enough breaks that it will become an upgrade blocker for people. ("Please upgrade the cookbooks you depend on and restart your whole process.").  Upgrade blockers = less adoption, and dot releases aren't supposed to do that (much).

**Comment by coderanger** [comment]
That is fair. I'll leave it in Poise as that is opt-in so it should be safe and we can put reverting this on the Chef 13 checklist?

**Comment by jkeiser** [comment]
@coderanger Sounds good! I've removed the `warn_once` functionality until we get mixlib-log worked out; you mind C/Ring it?

This should be less chatty than some warnings due to the fact that it happens on declaration rather than on use.

**Comment by coderanger** [comment]
:+1: shouldn't block 12.5 on the warn_once stuffs.

**Comment by coderanger** [comment]
Would you say that freezing defaults should be on the slate for 13? I can add it to the list :)

**Comment by jkeiser** [comment]
Yeah. It's in the RFC. I think we need to be a little more proactive about fixing cookbooks--like, add a rule to foodcritic or something. It would suck if 13 required an upgrade of all cookbooks everywhere rather than being *mostly* compat.

**Pull request merged**
