### PR TITLE
Re-allow nameless resources

### PR DESCRIPTION
**Pull request by coderanger**
A potential fix for #3416. Probably check that ticket for discussion as to if this is the right approach.

### CODE REVIEW

**Comment by coderanger** [comment]
To confirm, this does fix my failing tests in Poise and Poise Application.

```
Finished in 0.44149 seconds (files took 2.87 seconds to load)
21 examples, 0 failures
```

**Comment by jkeiser** [comment]
Why name.empty? Is that disallowing something that wasn't disallowed before?

What I would love is if the DSL could be overridden in provides, to take any arguments you want. Like `provides :blah, invoke: proc { ... }`.  Or perhaps something on the resource class, like `MyResource.declare(parent, *args, &block)`. Obviously desiring to exactly what we do now. Then you could override yours with `name=nil` without affecting anyone else or forcing special checking.

But it shouldn't block this. Other than the name empty question, this looks good to me.

**Comment by coderanger** [comment]
Yeah, currently `package []` would be allowed I think, which could happen if you are trying to do a multi-package install but your code is wrong (or somesuch). That also checks for `package ''` which should similarly not be allowed for reasons of general sanity.

As to adding this to the DSL, my issue with that is I want this to work on all resources not just my own (in an optimal world at least). Allowing it to be a per-resource thing would solve it more cleanly for my own application_* resources but I would have to build more wrappers for core resources and 3rd party cookbooks to make them act the same way, certainly not the end of the world but the inconsistency would be frustrating.

**Comment by jkeiser** [comment]
If possible I'd rather not add more restrictions on things, both for backwards compatibility purposes, and for the fact that there can be genuine things whose identity is an empty string.

**Comment by jkeiser** [comment]
As for working on all resources, you mean if name is declared with a default value, honoring that when instantiating the resource? That seems like a great feature to add and I would totally support such a patch.

**Comment by jkeiser** [comment]
Though it would be super nice if we used some other method than a `nil` sentinel to detect the missing argument :)

**Comment by coderanger** [comment]
I don't think it could be an upstream patch, the default name is a feature of the application resource's override of `declare_resource`. If it sees no name was provided, it fills one in there based on the application config.

**Comment by coderanger** [comment]
Nuked the `empty?` check, though perhaps it should be done as a deprecation warning?

**Comment by jkeiser** [comment]
If there were lazy defaults, I bet it could ... :)

**Comment by coderanger** [comment]
The default name is not a feature of the resource being named. It is part of the subresource DSL code https://github.com/poise/poise/blob/master/lib/poise/helpers/subresources/container.rb#L94-L111

**Comment by jkeiser** [comment]
Oh! This is all about nesting, gotcha. I'm still not resolved on the right way to get nesting onto mainline (only that I really, really want it).

**Comment by coderanger** [comment]
Yahr, that situation I use this is stuff like

```ruby
application '/path'
  rails do
     # some options
  end
end
```

`rails` gets a default name of `'/path'` so the author doesn't have to type it twice (or do something weird looking like `rails name do`.

**Comment by danielsdeleo** [comment]
@coderanger can you add a regression test somewhere?

:+1: from me on the fix itself.

@chef/client-core

**Comment by danielsdeleo** [comment]
@thommay BTW this looks like a regression that we should fix before 12.4 final

**Comment by danielsdeleo** [comment]
https://www.youtube.com/watch?v=zSAJ0l4OBHM

**Comment by coderanger** [comment]
Added some specs, for `Chef::DSL::Resources` in general as well as this case.

**Comment by danielsdeleo** [comment]
Travis failure is unrelated, see https://github.com/chef/chef/pull/3454

**Comment by danielsdeleo** [comment]
:+1:

**Comment by danielsdeleo** [comment]
A rebase should fix up the travis tests

**Pull request merged**
