### PR TITLE
Fix call to install_snaps which is missing an argument

### PR DESCRIPTION
**Pull request by gene1wood**
## Description

This fixes the case of calling the `snap_package` resource without a `source` attribute
which triggers a ruby error of `ArgumentError: wrong number of arguments (given 1, expected 2)`

## Related Issue

#13024

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Review by johnmccrae — APPROVED** [review]

**Comment by gene1wood** [comment]
@johnmccrae I have the bandwidth but not the knowledge of how to add an integration test. If you have a moment to "teach a man to fish" and can give me some pointers I can give it a try

* Pointer to an example of an existing integration test
* File location of where I'd put a new integration test for this fix in the chef code hierarchy
* Pointer to how to get a dev environment setup so I can run the tests
* Command to run to execute the integration tests (to see if my new test works)

I'd love to know how to do so (so that I can include tests in future fixes)

**Comment by johnmccrae** [comment]
@gene1wood Can you also update lines 80, and 86 as well to account for the missing versions there as well?

**Comment by johnmccrae** [comment]
@gene1wood re: testing - Sure, happy to help. Will put a little something together for you and post in shortly.

**Comment by jaymzh** [comment]
We should add some tests here, it's sad this broke so bad. If you add some `snap` resources in this recipe:

https://github.com/chef/chef/blob/main/kitchen-tests/cookbooks/end_to_end/recipes/_snap.rb

And then you add some `inspec` to verify the right things happened in a new _snap.rb in this directory:

https://github.com/chef/chef/tree/main/kitchen-tests/test/integration/end-to-end

Do you feel up to that?

**Comment by gene1wood** [comment]
> Can you also update lines 80, and 86 as well to account for the missing versions there as well?

@johnmccrae Do you mean [line 80](https://github.com/chef/chef/blob/83fdbf86661ebd63acf5b726de26fcfce7fbe97a/lib/chef/provider/package/snap.rb#L80) where the `update_snaps` method is called and only `names` is passed not `versions`

and [line 86](https://github.com/chef/chef/blob/83fdbf86661ebd63acf5b726de26fcfce7fbe97a/lib/chef/provider/package/snap.rb#L86) where the `uninstall_apps` method is called with `names` but not `versions`?

Those two methods are only expecting the `names` argument (not a `versions` argument) and looking in those methods, I don't think they have any need for the `versions` variable.

**Comment by johnmccrae** [comment]
@gene1wood You're right there. I had incorrectly assumed if you uninstall v 3.2 of an app but want to keep v 3.1 of that app that would need to pass a version constraint. But the uninstall method doesn't take that. I changed directions on the testing too. I think a simple way to get started is to add a 'test' to the end-to-end cookbook. 

- [ ] Load Chef Workstation
- [ ] Clone Chef
- [ ] Change to the chef repo locally and run `gem install bundle`
- [ ] Then run `bundle install `to get all the gems you need installed
- [ ] Go to /kitchen-tests/cookbooks/end-to-end/recipes/_snap.rb and add a couple of snap_package actions in to add with version, remove, update, etc.
- [ ] You'll need to update the Linux.rb file at around line 138 to include the _snap file. You'll note a comment from Tim Smith 2 years ago talking about problems with running snap in a docker container. You can ignore that for now. Once written, can you push that up here and let's see what happens?

**Comment by gene1wood** [comment]
@johnmccrae 

I'm sorry this may be over my head.

* I installed Chef Workstation
* I've got a fork of this repo and it's cloned locally and I've got my branch checked out with this PR in it
* I ran `gem install bundle` which failed because `You don't have write permissions for the /var/lib/gems/2.5.0 directory` after doing the same with `sudo` I switched to `gem install --user-install bundle` after some reading
* After some troubleshooting it looks like the gem is called `bundler` not [`bundle`](https://rubygems.org/gems/bundle/versions/0.0.1)
* `bundle install` was throwing an exception of `/usr/lib/ruby/2.5.0/rubygems.rb:289:in 'find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)` so it looks like I have to match the bundler version to the one in [`Gemfile.lock`](Gemfile.lock). I ran `gem install --user-install bundler -v 2.3.12` which got `bundle install` to run.
* `bundle install` gave [this warning](https://github.com/rubygems/rubygems/pull/5177) so I ran `gem update --system 3.2.3` which failed [as mentioned here](https://github.com/rubygems/rubygems/issues/4186) because I have the `rubygems-integration` apt package installed. I've now got `rubygems-update` 3.2.3 installed but the install didn't complete due to `gem update` throwing an exception. I'll hope that rubygems isn't screwed up.
* The `bundle install` command gave the error `Your bundle is locked to chef (18.0.124-universal-mingw32) from source at `.`, but that version can no longer be found in that source. That means the author of chef (18.0.124-universal-mingw32) has removed it. You'll need to update your bundle to a version other than chef (18.0.124-universal-mingw32) that hasn't been removed in order to install.` which I think is because the version of chef at the HEAD of `main` doesn't exist on [rubygems](https://rubygems.org/gems/chef/versions/) which makes sense. Just gotta figure out how to get `bundle install` to look for gems in the local directory instead of rubygems.org. `bundle install --local` doesn't do it.

So long story, I may not have enough familiarity to get a working chef dev environment where I can add a test and then execute that test to see if it works. If there's any documentation that you can point me to that gives more detail on getting a dev environment setup, I'm happy to dig in further.

For this PR, I'm happy to
* Follow further docs on getting a dev env for chef
* Leave this PR open until a repo maintainer someone more skilled than I can add the test to this PR
* Close this PR and leave it to someone else to give a stab at writing the test (the fix for the bug is obviously very simple so it wouldn't be hard for someone to re-implement in a new PR)
* Some other solution I'm not thinking of

@jaymzh 

> Do you feel up to that?

I think if I can get an environment where I can run a command that executes the new test that I add so I can see if it works, I'm down, I just haven't managed getting to that point yet.

**Comment by gene1wood** [comment]
@johnmccrae Any thoughts on https://github.com/chef/chef/pull/13025#issuecomment-1169545830 ?

If there's any documentation that you can point me to that gives more detail on getting a dev environment setup, I'm happy to dig in further.

**Comment by marcparadise** [comment]
@gene1wood  - a couple things might help: 

1) make sure chef-workstation's bin dir is in your path: `/opt/chef-workstation/bin`
2) instead of 'gem install', use `chef gem install`.  This will install the gem in the context of your chef-workstation installation instead of system ruby, which should behave better for you.

**Comment by gene1wood** [comment]
> instead of 'gem install', use chef gem install. This will install the gem in the context of your chef-workstation installation instead of system ruby, which should behave better for you.

Thanks @marcparadise that helped a lot. I ran

```
cd chef
chef gem install --user-install bundler -v 2.3.12
~/.chefdk/gem/ruby/3.0.0/bin/bundle install
cd kitchen-tests
~/.chefdk/gem/ruby/3.0.0/bin/bundle install
~/.chefdk/gem/ruby/3.0.0/bin/bundle exec kitchen list
```

and the installation worked.

I'm unclear though why I should have this installed as it sounds like it's not possible to make a change to `chef/kitchen-tests/cookbooks/end_to_end` in a local repo and then run `kitchen test` against that local repo, because kitchen-tests can only be used to test code that's committed and up on GitHub, is that right?

I ask because of @johnmccrae 's [comment above](https://github.com/chef/chef/pull/13025#issuecomment-1169264594)

> Once written, can you push that up here and let's see what happens?

And [this line in `chef/kitchen-tests/README.md`](https://github.com/chef/chef/tree/main/kitchen-tests#configuring-your-tests) that says

> You cannot use a local commit at this time.

If that's true, should I modify [the recipe](https://github.com/chef/chef/blob/main/kitchen-tests/cookbooks/end_to_end/recipes/_snap.rb) as John suggested and just commit it to this branch, hoping that it will work (as I'll only know after committing)?

**Comment by gene1wood** [comment]
So the tests are failing for these reasons

1. A failure on Windows-2019 and Windows-2022 due to being unable to install git
2. A failure to provision `/etc/resolv.conf` due to Errno::EBUSY: Device or resource busy on all of the Linux variants
3. A buildkite issue on Windows with Ruby 2.7 of "unable to find registered ruby matching `271`"
4. A buildkite issue for Windows Plan of "The term 'install-habitat' is not recognized as the name of a cmdlet, function, script file, or
operable program"

I don't suspect these problems are related to this PR.

And because the Ubuntu GitHub actions are failing with that `/etc/resolv.conf` issue, I can't see if the `end_to_end` kitchen tests are working or not.

**Comment by marcparadise** [comment]
@gene1wood we've made progress in getting our pipelines cleaner; if you rebase and force-push we should see a lot more green.  Thanks for your patience and persistence while we get this sorted.

**Comment by gene1wood** [comment]
@marcparadise Ok, so there's more green, but the unit tests I've added aren't getting executed. There are two problems causing this.

# When kitchen-tests fails, the GitHub Action still reports success

When kitchen-tests runs you can see here on and after [line 2888](https://github.com/chef/chef/runs/7982489128?check_suite_focus=true#step:4:2889) of the GitHub Actions kitchen-tests run that regardless of what happens, it reports success

In this case, the [chef-client run fails at line 2287](https://github.com/chef/chef/runs/7982489128?check_suite_focus=true#step:4:2288) but the GitHub Action reports success

# There's a problem with `linux_user[hab]` in `end_to_end::_habitat_package`

Execution of the `end_to_end` kitchen-test fails before it can get to my tests because the `_habitat_package` recipe fails.

[Here's the relative position of this recipe and the snap tests](https://github.com/gene1wood/chef/blob/fix_install_snaps_call/kitchen-tests/cookbooks/end_to_end/recipes/linux.rb#L156-L162)

This recipe fails because, as part of [running `habitat_install "default"`](https://github.com/chef/chef/blob/964236952f9fad2398a6a3a2501774e430b17b6d/kitchen-tests/cookbooks/end_to_end/recipes/_habitat_package.rb#L3-L5) because [when `habitat_install` provisions the `hab` user](https://github.com/chef/chef/blob/d9c9b787f2b384c68eab33208e855cabde9e9c45/lib/chef/resource/habitat_install.rb#L121-L124), the `user` resource calls the command `usermod hab` with no arguments resulting in this error

```
usermod: no options
             Usage: usermod [options] LOGIN
             
             Options:
        -b, --badnames                allow bad names
        -c, --comment COMMENT         new value of the GECOS field
...snip...
        -Z, --selinux-user SEUSER     new SELinux user mapping for the user account
```

This sounds like a bug in the [`user` resource related to the invocation of `usermod`](https://github.com/chef/chef/blob/964236952f9fad2398a6a3a2501774e430b17b6d/lib/chef/provider/user/linux.rb#L47) You shouldn't be able to invoke the `user` resource and get it to execute an invalid `usermod` argument set.

# Summary

Until this bug in `habitat_install` or in the `user` resource is fixed, I can't see if my tests pass or fail. I know that my fix works because I've used it locally.

What's the best way to deal with this?

**Comment by jaymzh** [comment]
This is great, the tests all look good (thanks!) the failing test isn't your fault. We'll merge this as soon as the 18RC is out the door.

**Review by jaymzh — APPROVED** [review]

**Comment by gene1wood** [comment]
@jaymzh Yes, but my new tests aren't actually being run to indicate either if the tests are correct or if the new code is correct.

The entire test suite is failing before my tests run, and falsely reporting success.

I would hold on merging this since nobody (including me) has yet seen if the tests I added work or not.

**Comment by gene1wood** [comment]
And I worry that this PR is in `Status : Waiting on Release` when my tests have never run (and we don't know if they pass or fail)

**Comment by jaymzh** [comment]
yes. getting the test piplines working is part of getting the RC out the door. It wont' be merged without the tests passing. :)

**Comment by tpowell-progress** [comment]
@gene1wood Now that GA has been released, can you please rebase so that we can confirm that tests still pass with these changes?

**Comment by gene1wood** [comment]
@tpowell-progress Sure thing.

I've rebased this PR. This got my new tests running for the first time. I found a bug in the tests which I fixed in 30f41a13f93127cf7c3737c4156a065ce7aa5869

Once fixed the tests run successfully with the following output

```
       Recipe: end_to_end::_snap
         * apt_package[snapd] action upgrade (up to date)
         * service[snapd] action start
           - start service service[snapd]
         * execute[sleep 5] action run
           - execute sleep 5
         * snap_package[hello] action install
           - install version 2.10 of package hello
         * snap_package[hello] action upgrade
           - upgrade(allow_downgrade) package hello from 2.10 to 2.12
         * snap_package[hello] action remove
           - remove package hello
         * snap_package[hello] action install
           - install version 2.10 of package hello
         * snap_package[hello] action purge
           - purge  package hello
         * snap_package[hello] action install
           - install version 2.10 of package hello
         * snap_package[hello] action remove
           - remove package hello
         * snap_package[hello, expect] action install
           - install version 2.10 of package hello
           - install version 5.45-7snap0 of package expect
```

Note : The issue where the kitchen tests fail but return a zero exit code indicating success continues. This means that of this big collection of kitchen tests, just because they show as green, doesn't mean their actually passing. The only way to tell is to read the output from the kitchen run to see it throw an exception. I'm opening a separate issue on this topic.

From my perspective this PR is ready now given that the unit tests which would have failed before this fix are present and are passing.

**Pull request merged**
