### PR TITLE
Add myself as a maintainer

### PR DESCRIPTION
**Pull request by thommay**
for both core chef-client and for ubuntu specific bits

### CODE REVIEW

**Comment by thommay** [comment]
@jonlives @lamont-granquist @btm @danielsdeleo @fujin @mcquin @adamhjk could i get some love or hate? :)

**Comment by jonlives** [comment]
:+1: !!!

**Comment by danielsdeleo** [comment]
:+1: BTW, you can notify `@chef/client-core` (which reminds me, need to make sure that's up to date).

**Comment by btm** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Comment by nathenharvey** [comment]
@ranjib mind weighing in on this, too?

Thanks!

**Comment by ranjib** [comment]
:+1:

**Comment by martinisoft** [comment]
:+1: but also know there is a separate proposal now for him to be Core LT on #2949

**Comment by lamont-granquist** [comment]
We've got enough thumbs up, do we need @adamhjk to mergeify?

**Comment by adamhjk** [comment]
I am the decider, and I approve this message.

**Pull request merged**
