### PR TITLE
[9431] Add remote_file support to archive_file

### LINKED ISSUE #9431: archive_file needs to accept accept remote files similar to poise_archive
### Describe the Enhancement:
poise_archive allowed the user to set the source as a remote file. We should handle this same scenario since that's one of the most common archive scenarios. This allows us to migrate users off poise_archive more easily.

### Describe the Need:

Add missing behavior from https://github.com/poise/poise-archive

### PR DESCRIPTION
**Pull request by damacus**
Fixes #9431

Signed-off-by: Daniel Webb <dan.webb@damacus.io>

### CODE REVIEW

**Comment by damacus** [comment]
The failure here doesn't look like it's related to the resource update

**Comment by tas50** [comment]
@damacus I really want to get the URL functionality added to Infra Client 16 (and backported to 15 eventually), but I'm not sure this is quite the way to go about handling it. Take a look at the UX of https://github.com/poise/poise-archive where you can just pass a URL and it does the right thing. I think that's what we want to adopt partially because I'd like to eventually autocorrect those resources to use archive_file and it would be much easier to do that if the API was somewhat similar. Take a look at https://github.com/poise/poise-archive/blob/master/lib/poise_archive/resources/poise_archive.rb#L89 for some idea of how Noah went about doing that. Not all of that is relevant, but the simple regex to determine if it's a path of a URL is something you could potentially run with. Let me know if you want to chat about it. You know where to find me.

**Comment by damacus** [comment]
Sounds like a plan, this really was just to start the conversation off with the most minimal effort possible. 
I'll dig that code out some time soon. 

Thanks!

**Comment by tas50** [comment]
Closing this out since we need to take a different approach

**Pull request closed without merging**
