### PR TITLE
Bump multiple dependencies to bump inspec-core to 6

### PR DESCRIPTION
**Pull request by neha-p6**
## Description

Inspec 6 pulls in bunch of dependencies like `chef-licensing` and `activesupport`, latest `train-core`, so we have to bump all the dependencies to get past the lock. 
`bundle update inspec`
=>
```
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies....................
Using rake 13.2.1
Using concurrent-ruby 1.3.4 (was 1.2.2)
Using minitest 5.25.1
Using public_suffix 6.0.1 (was 5.0.1)
Using mixlib-cli 2.1.8
Using tomlrb 1.3.0
Using aws-eventstream 1.3.0
Using aws-partitions 1.958.0
Using libyajl2 2.1.0
Using hashie 4.1.0
Using mixlib-log 3.0.9
Using rack 2.2.6.4
Using webrick 1.8.1
Using ffi 1.17.0 (was 1.16.3)
Using diff-lcs 1.5.1 (was 1.5.0)
Using erubis 2.7.0
Using fuzzyurl 0.9.0
Using iniparse 1.5.0
Using uri 0.13.1
Using logger 1.6.1
Using base64 0.2.0
Using uuidtools 2.2.0
Using bigdecimal 3.1.8
Using tty-cursor 0.7.1
Using byebug 11.1.3
Using rainbow 3.1.1
Using json 2.7.2 (was 2.6.3)
Using chef-vault 4.1.11
Using ruby-progressbar 1.13.0
Using tty-color 0.6.0
Using strings-ansi 0.2.0
Using debug_inspector 1.1.0
Using tty-screen 0.8.2 (was 0.8.1)
Using bundler 2.3.7
Using parslet 1.8.2
Using coderay 1.1.3
Using rspec-support 3.13.1 (was 3.11.1)
Using rubyzip 2.3.2
Using multipart-post 2.4.1 (was 2.3.0)
Using sslshake 1.3.1
Using thor 1.2.2 (was 1.2.1)
Using net-ssh 7.3.0 (was 7.1.0)
Using mixlib-authentication 3.0.10
Using method_source 1.1.0 (was 1.0.0)
Using wisper 2.0.1
Using ipaddress 0.8.3
Using ast 2.4.2
Using parallel 1.26.3 (was 1.22.1)
Using proxifier2 1.1.0
Using jmespath 1.6.2
Using unicode-display_width 2.6.0 (was 2.4.2)
Using syslog-logger 1.6.8
Using mime-types-data 3.2023.0218.1
Using http-accept 1.7.0
Using netrc 0.11.0
Using erubi 1.13.0
Using httpclient 2.8.3
Using multi_json 1.15.0
Using ed25519 1.3.0
Using regexp_parser 2.7.0
Using unf_ext 0.0.8.2
Using builder 3.3.0
Using ruby-shadow 2.5.0 from https://github.com/chef/ruby-shadow (at lcg/ruby-3.0@3b8ea40)
Using little-plugger 1.1.4
Using date 3.3.4
Using tzinfo 2.0.6
Using chef-utils 19.0.32 from source at `chef-utils`
Using timeout 0.4.1
Using addressable 2.8.7 (was 2.8.2)
Using i18n 1.14.6
Using plist 3.7.0
Using wmi-lite 1.0.7
Using corefoundation 0.3.13
Using rb-readline 0.5.5
Using ffi-libarchive 1.1.14
Using mixlib-archive 1.1.7
Using unicode_utils 1.4.0
Using net-http 0.4.1
Using rubyntlm 0.6.5
Using nori 2.7.1
Using tty-spinner 0.9.3
Using binding_of_caller 1.0.0
Using rspec-core 3.13.1 (was 3.11.0)
Using rspec-expectations 3.13.3 (was 3.11.1)
Using rspec-mocks 3.13.2 (was 3.11.2)
Using net-scp 4.0.0
Using net-sftp 4.0.0
Using mixlib-config 3.0.27
Using pry 0.13.0
Using tty-reader 0.9.0
Using parser 3.2.2.0
Using mime-types 3.4.1
Using ffi-yajl 2.6.0
Using net-protocol 0.2.2
Using pastel 0.8.0
Using rexml 3.2.5
Using fauxhai-ng 9.3.0
Using faraday-net_http 3.3.0 (was 3.0.2)
Using gssapi 1.3.1
Using aws-sigv4 1.9.0
Using rspec 3.13.0 (was 3.11.0)
Using rubocop-ast 1.28.0
Using pry-byebug 3.10.1
Using pry-stack_explorer 0.6.1
Using logging 2.4.0
Using activesupport 7.0.8.5
Using hashdiff 1.0.1
Using strings 0.2.1
Using semverse 3.0.2
Using aws-sdk-core 3.201.3
Using rspec-its 1.3.0
Using unf 0.1.4
Using tty-box 0.7.0
Using chef-zero 15.0.11
Using tty-prompt 0.23.1
Using aws-sdk-secretsmanager 1.102.0
Using vault 0.18.2
Using license-acceptance 2.1.13
Using stringio 3.1.1
Using rubocop 1.25.1
Using psych 5.1.2
Using aws-sdk-kms 1.88.0
Using chefstyle 2.2.2
Using aws-sdk-s3 1.156.0
Using rdoc 6.4.1.1
Using domain_name 0.5.20190701
Using time 0.3.0
Using faraday 2.12.0 (was 2.7.4)
Using tty-table 0.12.0
Using faraday-http-cache 2.5.1
Using faraday-follow_redirects 0.3.0
Using cookstyle 7.32.8
Using net-ftp 0.3.7
Using gyoku 1.4.0
Using http-cookie 1.0.5
Using winrm 2.3.8
Using rest-client 2.1.0 from https://github.com/chef/rest-client (at jfm/ucrt_update1@badd0be)
Using crack 0.4.5
Using winrm-fs 1.3.5
Using winrm-elevated 1.2.3
Using webmock 3.19.1
Using train-winrm 0.2.13
Using mixlib-shellout 3.3.3 (was 3.2.8)
Using cheffish 17.1.5
Using chef-config 19.0.32 from source at `chef-config`
Using appbundler 0.13.4
Using train-core 3.12.7 (was 3.10.7)
Using train-rest 0.5.0
Using ohai 19.0.3 from https://github.com/chef/ohai.git (at main@38116d1)
Using chef-licensing 1.0.4
Using chef-telemetry 1.1.1
Using inspec-core 6.8.1 (was 5.22.40)
Using inspec-core-bin 6.8.1 (was 5.22.40)
Using chef 19.0.32 from source at `.`
Using chef-bin 19.0.32 from source at `chef-bin` and installing its executables
Bundle updated!

```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by johnmccrae** [comment]
The failing tests in the verify pipeline are throwing something odd. The profile that is being tested is written to a random json file sitting in the /tmp folder. It is listed as the report_file. When I dump that file out I see that it has an error about a missing license key in it and NOT the contents of files listed just above in the spec.rb. Checking with the Inspec team to see if I need a license key for this.

**Comment by johnmccrae** [comment]
The offending command appears to be : https://github.com/chef/chef/blob/1483fd1336d61cd61d29f5046fe4cf75ce90ea96/spec/integration/compliance/compliance_spec.rb#L65C16-L65C120

If you run that command inside PRY you get this pile back:


```ruby
[1] pry(#<RSpec::ExampleGroups::ChefClientWithCompliancePhase::WhenTheChefRepoHasACustomProfile>)> shell_out!("#{chef_client} --local-mode --json-attributes #{path_to("attributes.json")}", cwd: chef_dir)
=> <Mixlib::ShellOut#7220: command: 'bundle exec chef-client --minimal-ohai --always-dump-stacktrace --local-mode --json-attributes /tmp/chef_repo20241028-26604-dmfohn/attributes.json' process_status: #<Process::Status: pid 26695 exit 0> stdout: '[2024-10-28T19:33:59+00:00] WARN: No config file found or specified on command line. Using command line options instead.
[2024-10-28T19:33:59+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /home/azureuser/localrepo/chef.
Chef Infra Client, version 19.0.41
Patents: https://www.chef.io/patents
Infra Phase starting
Resolving cookbooks for run list: []
Synchronizing cookbooks:
Installing cookbook gem dependencies:
Compiling cookbooks...
Loading Chef InSpec profile files:
Loading Chef InSpec input files:
Loading Chef InSpec waiver files:
[2024-10-28T19:34:01+00:00] WARN: Node chef19-ubuntu-dev.e4owijrat2fe5ggd3mv5syu0jf.xx.internal.cloudapp.net has an empty run list.
Converging 0 resources

Running handlers:
Running handlers complete
Infra Phase complete, 0/0 resources updated in 01 seconds
**[2024-10-28T19:34:01+00:00] ERROR: Chef InSpec has raised a runtime exception. Generating a minimal failed report.
[2024-10-28T19:34:01+00:00] ERROR: Unable to obtain a License Key.**

Compliance report:' stderr: '' child_pid: 26695 environment: {"LC_ALL"=>"en_US.UTF-8", "LANGUAGE"=>"en_US.UTF-8", "LANG"=>"en_US.UTF-8", "PATH"=>"/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/bin:/home/azureuser/.rbenv/versions/3.1.6/bin:/usr/lib/rbenv/libexec:/home/azureuser/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"} timeout: 600 user:  group:  working_dir: /home/azureuser/localrepo/chef/spec/integration/compliance/../../.. >
[2] pry(#<RSpec::ExampleGroups::ChefClientWithCompliancePhase::WhenTheChefRepoHasACustomProfile>)>
RSpec is shutting down and will print the summary report... Interrupt again to force quit (warning: at_exit hooks will be skipped if you force quit).
rake aborted!
Interrupt:
/home/azureuser/.rbenv/versions/3.1.6/bin/bundle:25:in `load'
/home/azureuser/.rbenv/versions/3.1.6/bin/bundle:25:in `<main>'
Tasks: TOP => spec:integration
(See full trace by running task with --trace)

```

**Comment by johnmccrae** [comment]
Following the instructions here to sort out a license: https://www.chef.io/blog/chef-inspec-6-licensing-tiers-how-to-access-the-license-keys

when I call "inspec shell" - I get a huge debug dump about conflicting gems and whatnot


```ruby
zsh/2 99  (git)-[neha-p6/chef19_bump_to_inspec6]-% /home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-bin-6.8.1/bin/inspec shell
[27078, #<Thread:0x00007b12f87cfc78 run>, #<Gem::LoadError: can't activate aws-sdk-core-3.201.3, already activated aws-sdk-core-3.190.3>, ["/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/specification.rb:2278:in `check_version_conflict'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/specification.rb:1415:in `activate'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:117:in `block in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:116:in `each'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:116:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-core/plugins/sign.rb:3:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-sts/client.rb:34:in `<top (required)>'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-sts.rb:19:in `require_relative'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-sts.rb:19:in `<top (required)>'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-core.rb:111:in `require_relative'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-core.rb:111:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/train-aws-0.2.41/lib/train-aws/transport.rb:4:in `<top (required)>'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/train-aws-0.2.41/lib/train-aws.rb:19:in `require_relative'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/train-aws-0.2.41/lib/train-aws.rb:19:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:68:in `block in load_all'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:51:in `each'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:51:in `load_all'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/cli.rb:629:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-bin-6.8.1/bin/inspec:10:in `<main>'"]]
[27078, #<Thread:0x00007b12f87cfc78 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-core/plugins/sign.rb:3:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-sts/client.rb:34:in `<top (required)>'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-sts.rb:19:in `require_relative'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-sts.rb:19:in `<top (required)>'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-core.rb:111:in `require_relative'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-core.rb:111:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/train-aws-0.2.41/lib/train-aws/transport.rb:4:in `<top (required)>'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/train-aws-0.2.41/lib/train-aws.rb:19:in `require_relative'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/train-aws-0.2.41/lib/train-aws.rb:19:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:68:in `block in load_all'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:51:in `each'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:51:in `load_all'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/cli.rb:629:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-bin-6.8.1/bin/inspec:10:in `<main>'"]]
[27078, #<Thread:0x00007b12f87cfc78 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-sts/client.rb:34:in `<top (required)>'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-sts.rb:19:in `require_relative'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-sts.rb:19:in `<top (required)>'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-core.rb:111:in `require_relative'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.190.3/lib/aws-sdk-core.rb:111:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/train-aws-0.2.41/lib/train-aws/transport.rb:4:in `<top (required)>'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/train-aws-0.2.41/lib/train-aws.rb:19:in `require_relative'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/train-aws-0.2.41/lib/train-aws.rb:19:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:68:in `block in load_all'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:51:in `each'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:51:in `load_all'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/cli.rb:629:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-bin-6.8.1/bin/inspec:10:in `<main>'"]]
[27078, #<Thread:0x00007b12f87cfc78 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/train-aws-0.2.41/lib/train-aws/transport.rb:4:in `<top (required)>'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/train-aws-0.2.41/lib/train-aws.rb:19:in `require_relative'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/train-aws-0.2.41/lib/train-aws.rb:19:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:68:in `block in load_all'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:51:in `each'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:51:in `load_all'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/cli.rb:629:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-bin-6.8.1/bin/inspec:10:in `<main>'"]]
[2024-10-28T19:48:57+00:00] ERROR: Could not load plugin train-aws: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true
[2024-10-28T19:48:57+00:00] ERROR: Could not load plugin train-kubernetes: Unable to activate ms_rest_azure-0.12.0, because faraday-2.12.0 conflicts with faraday (>= 0.9, < 2.0.0)
[2024-10-28T19:48:57+00:00] ERROR: Errors were encountered while loading plugins...
[2024-10-28T19:48:57+00:00] ERROR: Plugin name: train-aws
[2024-10-28T19:48:57+00:00] ERROR: Error: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true
[2024-10-28T19:48:57+00:00] ERROR: Plugin name: train-kubernetes
[2024-10-28T19:48:57+00:00] ERROR: Error: Unable to activate ms_rest_azure-0.12.0, because faraday-2.12.0 conflicts with faraday (>= 0.9, < 2.0.0)
[2024-10-28T19:48:57+00:00] ERROR: Run again with --debug for a stacktrace.
[27078, #<Thread:0x00007b12f87cfc78 run>, #<SystemExit: exit>, ["/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:97:in `exit'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:97:in `exit_on_load_error'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/cli.rb:630:in `<top (required)>'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'", "<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'", "/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-bin-6.8.1/bin/inspec:10:in `<main>'"]]
<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
        from <internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'
        from /home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-bin-6.8.1/bin/inspec:10:in `<main>'
/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:97:in `exit': exit (SystemExit)
        from /home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/plugin/v2/loader.rb:97:in `exit_on_load_error'
        from /home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-core-6.8.1/lib/inspec/cli.rb:630:in `<top (required)>'
        from <internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from /home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-bin-6.8.1/bin/inspec:10:in `<main>'
<internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- inspec/cli (LoadError)
        from <internal:/home/azureuser/.rbenv/versions/3.1.6/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/azureuser/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/inspec-bin-6.8.1/bin/inspec:10:in `<main>'

```

**Comment by neha-p6** [comment]
Current failures are due to license entitlement bug in inspec 6, which is fixed in latest version yet to be released. Hence we are going to merge this pr and pull the latest inspec after it is released

**Pull request merged**
