### PR TITLE
bump openssl to 1.0.2h

### PR DESCRIPTION
**Pull request by lamont-granquist**
does what it says on the tin, gets us to openssl 1.0.2h

### CODE REVIEW

**Comment by lamont-granquist** [comment]
for testing

**Comment by lamont-granquist** [comment]
we'd want to merge 1.0.2h instead, but we already have this software definition in omnibus-software and i want to try this because it'll be easy and we'll get an idea of how deep the yak hairs go

**Comment by lamont-granquist** [comment]
@chef/client-core i'm still waiting for a green-enough result from manhattan.ci but this should be ready to review

**Comment by lamont-granquist** [comment]
the omnibus-software change rebases the old branch on master of omnibus-software and brings in openssl, some licensing-related changes and a logrotate change that shouldn't affect the client at all.

**Comment by thommay** [comment]
Let's try and get all the omnibus branches merged before we merge this. I hate having both omnibus and omnibus-software on unrelated branches cc @sersut @ksubrama . otherwise 👍

**Comment by lamont-granquist** [comment]
i already tried to fight that battle...

**Pull request merged**
