### PR TITLE
Allow values to be appended when modifying environment values

### PR DESCRIPTION
**Pull request by MichaelPereira**
Hi,
After hitting this problem and seeing that this issue was brought up several times ( https://github.com/chef/chef/issues/2262 https://github.com/chef/chef/issues/3540 https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/8786671-add-support-for-appending-values-in-env-resource ) without being implemented, I've made the change myself in this Pull Request.

Let me know if this needs anything more.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
needs `bundle exec chefstyle -a` run on it

**Comment by MichaelPereira** [comment]
@lamont-granquist thanks for the tip, I've run it and fixed the reported issues.

**Comment by lamont-granquist** [comment]
@chef/client-core ready for review

**Comment by danielsdeleo** [comment]
Just wondering it it would be more consistent with other things in Chef for it to be action append or have an append flag as done here. :+1: on the code as written, assuming we like the shape of it.

**Comment by ksubrama** [comment]
I'm actually a bit confused with the PR.

```
(current_values.delete_if { |value| new_values.include?(value) } + new_values).uniq.join(@new_resource.delim)
```

should produce the exact same results as

```
(new_values + current_values).uniq.join(@new_resource.delim)
```

The issue I had identified in the original bug report was that I didn't see us setting `delim` anywhere because both `current_values` and `new_values` only get split when `delim` is defined.

**Comment by ksubrama** [comment]
The harder question to figure out is whether to prepend or append - that's why I hadn't gone in and fiddled with it.  Currently, `new_values + current_values` creates prepended values because `uniq` maintains order.  It would actually move any values to be added to the beginning of the list.  This might be a strange behavior for someone who tries to append "foo:bar" to "baz:foo:bar:qux" because regardless of whether we're using the code path in this PR or the older code path, as long as delim is defined, we'll get "foo:bar:baz:qux" or "baz:qux:foo:bar" - which to me is fairly confusing.

**Comment by MichaelPereira** [comment]
@danielsdeleo : I thought about creating a new property with the `:modify` action, where it should be defined to one of the three following options: `:prepend`, `:append`, `:replace`. But it looks a lot more complicated to implement than the current proposition just to add the append mode

@ksubrama : Now that the default behavior has been to prepend, wouldn't it be dangerous to change it and possibly break existing cookbooks if the chef-client is upgraded?

**Comment by lamont-granquist** [comment]
So I think if I was writing this today I'd want an action that took `:prepend` or `:append` and a property of `uniq` that took a boolean and twiddled the condition that @ksubrama is concerned about.

I'm kind of thinking we go down that route, and deprecate `:modify` entirely...

**Comment by thommay** [comment]
Hi,
we're really grateful for this PR, but as Lamont says, we're more likely to reshape this provider and deprecate `:modify`. With that in mind, I'm going to close this PR. If you'd like to have a bash at creating a prepend action, that would be amazing and we'd love to help you there.
Thanks again,
-Thom

**Pull request closed without merging**
