### PR TITLE
Enable travis build for chef-12 branch

### PR DESCRIPTION
**Pull request by akitada**
### Description

Enable travis build for chef-12 branch

### Issues Resolved

N/A

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [x] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by akitada** [comment]
I also wanted to enable appveyor and tried it but it failed. Apparently it's due to https://github.com/chef/omnibus/issues/756.
Enabling travis only for now.

**Comment by tas50** [comment]
@akitada It might be useful to break the nokogiri change into it's own change so we make sure to note it in the changelog. It'll get close under the title of this PR as is

**Comment by lamont-granquist** [comment]
fixing appveyor in  #6141

**Comment by akitada** [comment]
removed the nokogiri change as requested.

**Comment by akitada** [comment]
nokogiri is going to be updated in https://github.com/chef/chef/pull/6107

**Comment by coderanger** [comment]
Fixed in https://github.com/chef/chef/commit/6e0fa8d995513b4aa5835673856e98f5ea2523c4

**Pull request closed without merging**
