### PR TITLE
bryant-lippert-maintainer

### PR DESCRIPTION
**Pull request by AgentMeerkat**
I'm requesting to be made a maintainer on the FreeBSD team. Cheers!

### CODE REVIEW

**Comment by smurawski** [comment]
Paging the @chef/client-freebsd maintainers

**Comment by tbunnyman** [comment]
:+1:

**Comment by martinisoft** [comment]
:+1: from me. This came about with my assistance at the Chef Summit Hack Day.

**Comment by lamont-granquist** [comment]
:+1:

**Comment by lamont-granquist** [comment]
needs to be added to the toml and the md regenerated..

**Comment by lamont-granquist** [comment]
(marked ready-to-merge even though we can't merge it)

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by AgentMeerkat** [comment]
I've signed the ICLA. Thanks!

**Comment by martinisoft** [comment]
@lamont-granquist Do I or @AgentMeerkat need to add that name to the toml as well before merge?

**Comment by btm** [comment]
@AgentMeerkat should edit MAINTAINERS.toml instead of the markdown, run `bundle exec rake maintainers:generate`, then push both files.

**Comment by AgentMeerkat** [comment]
@btm @martinisoft I followed the instructions that btm said to follow. The tests have finished running, this should be good to go now.

**Comment by btm** [comment]
:+1:

**Comment by AgentMeerkat** [comment]
Thanks everyone!

**Pull request merged**
