### PR TITLE
quote git remote_url

### PR DESCRIPTION
**Pull request by hoprocker**
for issue #6248

### CODE REVIEW

**Comment by coderanger** [comment]
Seems reasonable to support but we should use shellwords instead. And should check for weird interactions with cmd.exe on windows.

**Comment by lamont-granquist** [comment]
i think this is probably acceptable as it is.  we commonly just throw quotes around args to protect windows against files-with-spaces.

what we really need to do is get *argv support into mixlib-shellout on windows and then port stuff like this to it, and solve it right at that level and then unburden consumers from having to care so deeply about it...

**Comment by thommay** [comment]
@hoprocker thanks for the PR, and sorry we've been a bit slow getting it merged. We need a think from you, which is to mark your commit with a DCO sign off. Since you have a single commit, please run `git commit --amend -s`, and then `git push -f` to update the branch here. Once that's done we'll get this merged.
Thanks again!

**Comment by lamont-granquist** [comment]
it has a chefstyle issue as well:

```
Offenses:
lib/chef/provider/git.rb:216:75: C: Style/PercentLiteralDelimiters: %-literals should be delimited by { and }.
              git("config", "--replace-all", "remote.#{remote_name}.url", %("#{remote_url}"), cwd: cwd)
                                                                          ^^^^^^^^^^^^^^^^^^
1611 files inspected, 1 offense detected
RuboCop failed!
```

**Comment by tas50** [comment]
Merged with the chefstyle + spec fix in #7014

**Pull request closed without merging**
