### PR TITLE
 when calling process_events_until_done, skip events that are empty (nil) in event_list

### PR DESCRIPTION
**Pull request by komealy**
This is a proposed fix to #8825 

In the case where the event_list is empty, it errors out and gets this stack trace:

```
sh-4.2$ sudo cat /var/chef/.chef/local-mode-cache/cache/chef-stacktrace.out
Generated at 2019-08-16 15:12:23 +0000
ArgumentError: wrong number of arguments (given 0, expected 1+)
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/event_dispatch/dispatcher.rb:59:in `call_subscribers'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/event_dispatch/dispatcher.rb:84:in `process_events_until_done'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/event_dispatch/dispatcher.rb:31:in `enqueue'
(eval):2:in `updated_cookbook_file'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/cookbook/synchronizer.rb:290:in `sync_file'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/cookbook/synchronizer.rb:176:in `block (2 levels) in sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/util/threaded_job_queue.rb:52:in `block (3 levels) in process'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/util/threaded_job_queue.rb:50:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/util/threaded_job_queue.rb:50:in `block (2 levels) in process'
```

## Description
return sentinel clause to not do anything if the event_list is empty when process_events_until_done is invoked

## Related Issue
https://github.com/chef/chef/issues/8825

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tas50** [comment]
@komealy It looks like you might have run rubocop or cookstyle on this PR based on the quote change at the top. Can you run Chefstyle on this file to make sure the style matches our style guide?

**Comment by komealy** [comment]
Upon further inspection, it looks like this sentinel clause actually should be looking at the element itself, and not the list. Before we move forward, I'll want to add another commit with some unit tests includes as well.

**Comment by komealy** [comment]
@tas50 I ran `chefstyle` and even added in the rules that it was enforcing into the `rubocop.yml` so my auto-format option in VSCode doesn't break me 😁 
I also changed my sentinel clause to handle another scenario that I found. It needs to skip not just the first one, but any events that are actually nil.

**Comment by komealy** [comment]
Didn't mean to close it, the close and comment button is too close to Comment 🤦‍♂

**Comment by komealy** [comment]
@jaywhy13  I have not found a workaround other than this fix. My particular situation only happens once, then when I just try again, it works...

**Comment by lamont-granquist** [comment]
This is almost certainly a race condition caused by multithreaded access from the cookbook synchronizer to the queueing functions.  This is probably not the correct fix.

**Comment by komealy** [comment]
Looks like the proper fix is in #8950

**Pull request closed without merging**
