### PR TITLE
Update changelog for upcoming release

### PR DESCRIPTION
**Pull request by afiune**
cc/ @scottopherson @tduffield @rhass 

Signed-off-by: Salim Afiune <afiune@chef.io>

### CODE REVIEW

**Comment by tduffield** [comment]
Looking good so far.

**Comment by tas50** [comment]
@afiune I updated the wording on a few of the PRs. Can you regenerate the changelog for those please?

**Comment by afiune** [comment]
@tas50 With pleasure! Could you give me the list of PR you changed? Thanks...

**Comment by tas50** [comment]
I don't know off the top of my head. I excluded a few and reworded several others.

**Comment by afiune** [comment]
Alright then, we will try to use the new automation that @tduffield did 💛 👍

**Pull request merged**
