### PR TITLE
Revert nillable resource attributes

### PR DESCRIPTION
**Pull request by jdmundrawala**
This change had many unforeseen consequences. Reverting until we can figure out a way to do this that does not break people

cc @chef/client-engineers @chef/client-core

### CODE REVIEW

**Comment by danielsdeleo** [comment]
okay. :+1:

**Comment by adamedx** [comment]
Best to err on the side of avoiding regressions. @jdmundrawala, where specifically did we encounter strange behavior?

**Comment by jdmundrawala** [comment]
The issue is that many people use `resource.attribute(nil)` to mean noop, and this has worked until now  because that triggers that getter. These changes break that functionality, as nil is a valid value to set.

**Comment by lamont-granquist** [comment]
Yeah people do this:

```
deploy.scm_resource new_resource.scm_resource
```

Instead of either of these:

``
deploy.scm_resource new_resource.scm_resource if scm_resource
deploy.scm_resource new_resource.scm_resource unless scm_resource.nil?
```

And the behavior there is that if new_resource.scm_resource is nil then they expect it to be ignored and get the default, while my change makes this set the scm_resource parameter to nil and override the default which changes behavior and actually breaks things.  This immediately breaks the application cookbook which is what this example is from.

And the problem is that its so easy to do lazy coding in cookbooks and introduce this dependency on the behavior of nil that we can't really introduce this functionality anywhere so it all needs to be reverted.

**Comment by lamont-granquist** [comment]
:+1:

**Pull request merged**
