### PR TITLE
Don't call get_last_error for net api

### PR DESCRIPTION
**Pull request by jdmundrawala**
This should fix our internal CI
cc @thommay @chef/client-windows

### CODE REVIEW

**Comment by thommay** [comment]
well, appveyor likes it, and it looks like the MS docs agree with you, so :+1:

**Comment by btm** [comment]
:+1: 

As an aside, I noticed NERR_BadUsername from #net_api_error! isn't listed on: 
https://msdn.microsoft.com/en-us/library/windows/desktop/aa370659%28v=vs.85%29.aspx

**Comment by ksubrama** [comment]
@btm  That was them reusing a system error code from https://msdn.microsoft.com/en-us/library/windows/desktop/ms681386(v=vs.85).aspx

In the original PR, I had figured out how to fetch the various error codes and string from their various sources but it was pretty insane how hard it was to do something that simple - so it's on our backlog instead :).

**Comment by ksubrama** [comment]
:+1:

**Pull request merged**
