### PR TITLE
Remove copyright dates

### PR DESCRIPTION
**Pull request by lamont-granquist**
Legally incredibly dubious, particularly since we don't follow it
strictly as policy, and we have git history instead, which does it right.
This is just a waste of time and a cargo cult.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
regexp fail, one second...

**Comment by lamont-granquist** [comment]
Auditing the commits with 2020 dates, the highest date on the file is right less than half the time:

```
   1 2015
  39 2016
   4 2017
  16 2018
  22 2019
  76 2020
```

Pretty sure that if there was any conceivable value from this policy that the fact that we do not adhere to the policy nullifies any potential benefit.  Policies that aren't followed don't have any utility.

**Comment by lamont-granquist** [comment]
Also corporate copyrights last for 95 years which means that the game of updating it every time the file is touched to eek one more year out of the copyright is a bit academic.

**Comment by lamont-granquist** [comment]
Yeah that makes a bit more sense since then if someone sees the file out of context somehow, the copyright owner and license is clear.

**Comment by tas50** [comment]
We should backport this just to make the diffs easier for now

**Comment by lamont-granquist** [comment]
we should stop generating diffs against the copyright lines now though?

**Comment by tas50** [comment]
if you diff chef-15 and master branches it's 100% red now

**Comment by lamont-granquist** [comment]
heh, i guess i never do that...

**Pull request merged**
