### PR TITLE
Use dev version in master

### PR DESCRIPTION
**Pull request by jdmundrawala**

### CODE REVIEW

**Comment by smurawski** [comment]
@chef/maintainers Looks like a minor change, can we get a few +1's to merge?

**Comment by btm** [comment]
:+1:

**Comment by danielsdeleo** [comment]
:shipit:

**Comment by tyler-ball** [comment]
:+1:

**Comment by ranjib** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Pull request merged**
