### PR TITLE
moved 'purge is off' msg to correct location

### PR DESCRIPTION
**Pull request by jeremymv2**
Signed-off-by: Jeremy J. Miller <jm@chef.io>

### Description

The original ui message `ui.output ("Not deleting extra entry #{dest_path} (purge is off)") if ui` was being output under the wrong condition since it was nested under the incorrect `if/else` block, confusing the user.

This commit changes it to be associated with the `if options[:purge]` condition, not the `if src_entry.parent.can_have_child?(dest_entry.name, dest_entry.dir?)`:

```
              if options[:purge]
                # If we would not have uploaded it, we will not purge it.
                if src_entry.parent.can_have_child?(dest_entry.name, dest_entry.dir?)
```

Tested and validated works as expected.

### Issues Resolved

n/a

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by echohack** [comment]
We also updated some of the verbage here to be in line with the rest of the output (using "-ing" verbs). Hurray cleaner, accurate logs!

Fixing this item reduces some confusion around using the --purge option.

👍

**Comment by jeremymv2** [comment]
The result of the failures unfortunately stems from downstream tests NOT expecting any ui output - even though the output is innocuous and purely informational.

Hmm... how to skin this?

**Comment by thommay** [comment]
@jeremymv2 hey, we'd love to get this done if you've got a spare round tuit?

**Comment by tas50** [comment]
Closing this out due to lack of response. If you want to finish this up with some tests @jeremymv2 we'd love to get it merged.

**Pull request closed without merging**
