### PR TITLE
Add git support for uploadpack.allowReachableSHA1InWant

### PR DESCRIPTION
**Pull request by joshburt**
Adds support to chef-client git HWRP to leverage uploadpack.allowReachableSHA1InWant where possible.

**What is uploadpack.allowReachableSHA1InWant?**
Introduced in git version 2.5, the documentation [here](https://github.com/git/git/blob/v2.5.0/Documentation/config.txt#L2570) states:

```
Allow `upload-pack` to accept a fetch request that asks for an
	object that is reachable from any ref tip. However, note that
	calculating object reachability is computationally expensive.
	Defaults to `false`.

```
Basically allowing fetches for references that aren't tags or branches.

**Notes**
This PR, requires https://github.com/chef/chef/pull/4771 to be merged first.

**Use Case**
We have a number of instances were we manage web assets (think javascript, etc). We use the git resource to handle the checkout of the repository. Up until now we have been requiring either branches or tags to be targeted for checkout during convergence. With the addition of this feature we will now be able to fetch/checkout unadvertised refs on our remote servers.

In conjunction with prune and depth options it allows us to keep the git footprint small on the front-end servers. To accomplish this another route will require a full clone before checkout of a specified unadvertised ref.

**Background**
Introduced in git 2.5 | uploadpack.allowReachableSHA1InWant
https://github.com/git/git/blob/v2.5.0/Documentation/config.txt#L2570

Thoughtworks [Go] (https://www.thoughtworks.com/go/) is also adding similar functionality https://github.com/gocd/gocd/issues/313#issuecomment-174103478

**Current Areas of Discussion**

1. Attribute name, currently 'uploadpack_allow_reachable_sha1_in_want'
2. Implementation/gating mechanism utilized

### CODE REVIEW

**Comment by joshburt** [comment]
I'm seeing some functional test breakage and will investigate.  Thanks!

**Comment by joshburt** [comment]
The failures resemble this:

```
NoMethodError:
       deploy_revision[deploy-revision-unit-test] (dynamically defined) had an error: NoMethodError: undefined method `uploadpack_allow_reachable_sha1_in_want' for Chef::Resource::DeployRevision

```
Running this functional test locally successes:
	bundle exec rspec ./spec/functional/resource/deploy_revision_spec.rb

	
Can anyone provide guidance on this failure?
Thanks!

**Comment by joshburt** [comment]
Any update on this?
Thanks!

**Comment by lamont-granquist** [comment]
the deploy and git resources are tightly coupled and the API for the deploy resource is a superset of the git (or scm) resources.

its all mildly horrible and very old code.

you probably need to update Chef::Resource::Deploy with this property as well.

**Comment by joshburt** [comment]
We've had enough changes around the pre-req PRs that I'll be resubmitting this.  Thanks everyone!

**Pull request closed without merging**
