### PR TITLE
Make YAML recipes more useful

### PR DESCRIPTION
**Pull request by aleksey-hariton**
Add ERB templating support for YAML recipes

## Description

1. Added possibility to define resources in `type[name]` format

```
resources:
- name: package[apache2]
```

2. Now its possible to use Ruby code, helper methods and node attributes

```
resources:
<%- if node['platform_family'] == 'debian' %>
- name: package[apache2]
<%- else %>
- name: package[httpd]
<%- end %>

<%- value = "Chef rocks!" %>
- name: file[/etc/someconfig]
  content: |
    # Generated by Chef cookbook <%= cookbook_name %>
    option = <%= value %>
```
3. Support of `notifies/subscribes`

```
- name: package[nginx]
- name: service[nginx]
  subscribes: 
    - restart
    - package[nginx]
    - delayed
  action:
    - enable
    - start
- name: file[/etc/nginx/conf.d/vhost.conf]
  notifies:
    - reload
    - service[nginx]
    - delayed
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

P.S.

BTW, why https://github.com/chef-cft/chef-examples/blob/master/examples/ChefYAMLRecipes.md is only place I one can read about this feature?!

### CODE REVIEW

**Comment by aleksey-hariton** [comment]
@lamont-granquist @btm probably you can be interested in this feature.

Also created PR for YAML recipes documentation - https://github.com/chef-cft/chef-examples/pull/68

**Comment by lamont-granquist** [comment]
This was the first thing I did with the yaml recipes when I implemented them.  I ripped it out because it would permanently break any hope we had of converting YAML recipes back to ruby synax:

https://github.com/chef/chef/pull/8653#issuecomment-501504178

There's a better proposal for something like this which uses YAML tags to embed ruby into the YAML, which could then be read by the conversion script and rendered into correct ruby.  If you then added control flow in YAML syntax you'd get something much more functional but which could be converted back without just ERB templating YAML.

I also just fail to understand the appeal of jamming ruby templating all around YAML.  That's dramatically worse, not better.  There's a reason why software engineers keep flow logic separate from templating/rendering.

**Comment by lamont-granquist** [comment]
So ruby tags would look something like:

```
- name: file[/etc/whatever.conf]
  - owner: !!ruby node['owner']
```

(modulo whatever i don't know about edge conditions in YAML parsing off the top of my head)

**Comment by lamont-granquist** [comment]
And the useful thing about the node tag syntax would be that we could actually render it to be `lazy { node.read('foo', 'bar', 'baz') }` for the user which would auto-lazy all node attributes sent into properties and ensure nobody would see a NoMethodError on NilClass any more, which is some significant actual value add.

**Comment by aleksey-hariton** [comment]
From your comment:

> customers would forever get stuck on in YAML-chef.

Not getting, why its bad? :)

**Comment by aleksey-hariton** [comment]
I'm fan of Ruby, for almost decade, but from my point of view, we're seeing such products like Terraform, Ansible, Helm only because Opscode/CHEF Inc. still keeping to rely on Ruby.

**Comment by lamont-granquist** [comment]
ERB templated YAML does nothing to get away from ruby though.  You now have three layers where you have an dynamic ruby layer which is assembling a YAML document which is then compiled into the underlying ruby layer.  That is even more layers of ruby to worry about.

And I never said 'no' to YAML.  Please read what I wrote again, I gave an alternative implementation as a suggestion where there is a top YAML layer and control flow and tags are implemented in that layer without resorting to just dumping a ruby ERB layer on top of it.

I'm suggesting an implementation which has much LESS ruby in it than the one in this PR.

**Comment by gscho** [comment]
If we set aside the ERB discussion for a minute, how about the other 2 items. Seems like support for notifications would be nice to have?

**Pull request closed without merging**
