### PR TITLE
Mac: Validate that a machine has a computer level profile

### PR DESCRIPTION
**Pull request by gbatye**
### Description

NoMethodError: osx_profile is raised if a machine has profiles installed but none are computer level profiles. Validating hash has correct key versus an empty hash. 

I work at facebook and we've been running this change within code base for the past month without errors. 

PhilD will do the final merge.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
travis is sad, but 👍

**Comment by thommay** [comment]
Hi, thanks for the submission. Please can you fix chefstyle ( just run `bundle exec chefstyle -a` ) and repush.

**Comment by gbatye** [comment]
Fixed chefstyle. :-)

**Comment by thommay** [comment]
@jaymzh you'll need to add a signed-off-by and then you can feel free to merge

**Comment by gbatye** [comment]
@jaymzh can you merge when you have time?

**Comment by mikedodge04** [comment]
@jaymzh can you merge when you have time?

**Comment by jaymzh** [comment]
You no longer need me to do the final merge, see the updated internal process. 

Add a signed-off-by line, and anyone can merge it! :)

**Comment by mikedodge04** [comment]
:) didnt know that went retro active

**Comment by thommay** [comment]
@gbatye if you don't want to wrangle git, you can just put your sign off in to the PR and we'll do a squash merge and include it

**Comment by gbatye** [comment]
Not able to merge until I follow the new internal process. Have meeting schedule with Phild to get final approval.

**Comment by gbatye** [comment]
I ran "git commit -s --amend" and synced changes in github desktop. Anything else I need to do to get this change merged?

**Comment by thommay** [comment]
@gbatye thanks for your contribution!

**Pull request merged**
