### PR TITLE
Volunteer to assist as a FreeBSD maintainer.

### PR DESCRIPTION
**Pull request by tbunnyman**
I would be happy to help maintain Chef's FreeBSD support.

### CODE REVIEW

**Comment by thommay** [comment]
ping @martinisoft @Aevin1387

**Comment by martinisoft** [comment]
Yay! I am :+1: for adding @tbunnyman as we discussed this at ChefConf.

**Comment by Aevin1387** [comment]
Also a :+1: on adding @tbunnyman

**Comment by martinisoft** [comment]
Think we just need @jonlives as sign off to merge.

**Comment by jonlives** [comment]
Signed off!

@martinisoft you don't need decider approval for adding maintainers to your component, a simple majority suffices. I (and you as Lt) retain optional veto

**Comment by btm** [comment]
:smile:

**Comment by btm** [comment]
Merged to master.

**Pull request closed without merging**
