### PR TITLE
guard against somehow being called by the package resource

### PR DESCRIPTION
**Pull request by thommay**

### CODE REVIEW

**Comment by ccope** [comment]
aww, I had hoped this issue was fixed since my original pr :-(

**Comment by thommay** [comment]
Yeah we really need to fix this properly.

**Comment by lamont-granquist** [comment]
eh wut?  this should be only a unit testing failure?

**Comment by thommay** [comment]
> eh wut? this should be only a unit testing failure?

@lamont-granquist we have a number of functional tests that create `Chef::Resource::Package` and then do stuff with it, which is obviously bad but we need to get this test back to green first.

**Comment by lamont-granquist** [comment]
think should fix it, but have to see what travis thinks.

**Pull request merged**
