### PR TITLE
Enable Solaris Sparc packages for Chef-16

### PR DESCRIPTION
**Pull request by jaymalasinha**
Signed-off-by: Jaymala Sinha <jsinha@chef.io>

Enable Solaris Sparc packages for Chef-16

## Description
Enable Solaris Sparc packages for Chef-16

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by jaymalasinha** [comment]
Test build https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/362

**Comment by btm** [comment]
```

The following shell command exited with status 1:
--
  |  
  | $ pkgdepend resolve -m /tmp/chef20201002-12264-ajyhy9/chef.p5m.4
  |  
  | Output:
  |  
  | (nothing)
  |  
  | Error:
  |  
  | /tmp/chef20201002-12264-ajyhy9/chef.p5m.4 has unresolved dependency '
  | depend type=require fmri=__TBD pkg.debug.depend.file=env \
  | pkg.debug.depend.path=usr/local/bin \
  | pkg.debug.depend.reason=opt/chef/embedded/lib/ruby/gems/2.7.0/gems/racc-1.4.16/bin/racc2y \
  | pkg.debug.depend.type=script'.
  | /tmp/chef20201002-12264-ajyhy9/chef.p5m.4 has unresolved dependency '
  | depend type=require fmri=__TBD pkg.debug.depend.file=env \
  | pkg.debug.depend.path=usr/local/bin \
  | pkg.debug.depend.reason=opt/chef/embedded/lib/ruby/gems/2.7.0/gems/racc-1.4.16/bin/y2racc \
  | pkg.debug.depend.type=script'.


```

**Comment by jaymalasinha** [comment]
https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/363 build in progress after omnibus IPS fix

**Comment by jaymalasinha** [comment]
Enabled Solaris x86 chef-16 builds after upgrade to gcc-5.  Test build https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/365 in progress

**Comment by tas50** [comment]
Adhoc https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/375#55dddff2-58af-4d24-b5c2-605c83dd6f0c

**Comment by tas50** [comment]
This was done and shipped in 16.8.9. Thanks for all the help on the backend @jaymalasinha

**Pull request closed without merging**
