### PR TITLE
Fix data fetching when explicit attributes are passed

### PR DESCRIPTION
**Pull request by ranjib**

### CODE REVIEW

**Comment by ranjib** [comment]
https://github.com/chef/chef/issues/3018

**Comment by ranjib** [comment]
we need a spec as well,

**Comment by jdmundrawala** [comment]
cc @chef/client-engineers @chef/client-engineers 

We should get this in the next release

**Comment by danielsdeleo** [comment]
:+1: on this and getting in to 12.1.1. Wouldn't block it on lack of spec, but this behavior absolutely needs to be tested better than it is.

**Comment by lamont-granquist** [comment]
Yeah, kind of hard to see what broke and how it was fixed, but the replacement code I can at least read + understand what is going on....  So, :+1:?

**Comment by jdmundrawala** [comment]
Merging for the pending 12.1.1 release

**Comment by eherot** [comment]
Is the Chef core codebase supposed to be observing the SemVer standard? Because it's worth noting that this is actually a breaking change, even though it is a) a definite improvement and b) causes Chef to behave like the documentation says it should. Many of us had to write workarounds in order to get Chef 12 to work in production and this change breaks our workarounds.

**Comment by lamont-granquist** [comment]
That's an abusive use of the SemVer standard.  We did the right thing and documented the interface.  Our implementation had a bad bug in it which got fixed.  Code written against the documented public interface now works, code written against the buggy implementation that was not documented got broken.  If SemVer doesn't allow us to do this, then the standard needs to be fixed to clarify this use case, otherwise you wind up in a perverse situation where clear bugs become codified and can't be fixed.

**Comment by mhenrixon** [comment]
What documentation @lamont-granquist ? I haven't found any examples on how the data output is supposed to look. Right now inside my specs I get 

```ruby
[ 
  { url: 'something', data: { attribute: 'value' } }
]
```

Currentlly ChefSpec gives me one thing and Kitchen another.

**Comment by btm** [comment]
@mhenrixon see https://github.com/chef/chef/issues/2679

**Pull request merged**
