### PR TITLE
post release version bump to 12.8.2

### PR DESCRIPTION
**Pull request by mwrock**

### CODE REVIEW

**Comment by coderanger** [comment]
Just for my own education, is the plan that this is how we do the version bumps going forward or is the goal to move this to a CI-initiated process that will bump before building nightlies or similar?

**Comment by mwrock** [comment]
You are right. We will soon be moving to CI powered bumps.

**Comment by thommay** [comment]
Hey @mwrock , I guess we want to bump to 12.9 by now, and also you should update the VERSION file in the root and use the rake task to update all the other version numbers...

**Comment by mwrock** [comment]
closing in favor of #4713

**Pull request closed without merging**
