### PR TITLE
Add deprecation warnings to Chef::REST and all json_creates

### PR DESCRIPTION
**Pull request by thommay**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:+1:

**Comment by thommay** [comment]
Not sure what's going on with the appveyor failure. ping @chef/client-core

**Comment by stevendanna** [comment]
Key, Org, User, and UserV1 all alias json_create to from_hash but I don't see those modified here to include the deprecation.  I think we probably still want to since calling json_create usually implies that auto-inflation is being used.

**Comment by danielsdeleo** [comment]
:+1:

**Comment by stevendanna** [comment]
:+1:

**Pull request merged**
