### PR TITLE
Updating to the latest release of net-ssh to consume https://github.com/net-ssh/net-ssh/pull/280

### PR DESCRIPTION
**Pull request by tyler-ball**
All the components of the ChefDK are being updated.  See https://github.com/chef/chef-dk/pull/640 for more details.

\cc @chef/maintainers

### CODE REVIEW

**Comment by jkeiser** [comment]
:+1:

**Comment by danielsdeleo** [comment]
:+1:

**Comment by cheeseplus** [comment]
Just in case - we ran into an issue with TK that required some additional love https://github.com/test-kitchen/test-kitchen/commit/bd08208d64549c8887f6479d07a8198eb778e0c5

**Comment by lamont-granquist** [comment]
:+1:

**Comment by tyler-ball** [comment]
Thanks @cheeseplus - I already went through Chef, Test Kitchen, Train and Chef Provisioning core fixing the exception.  I'm going to look through the other Provisioning drivers now

**Comment by cheeseplus** [comment]
Figured since you fixed it initially you'd be all over it @tyler-ball :rocket:

**Pull request merged**
