### PR TITLE
fix typo to make knife bootstrap -j work

### PR DESCRIPTION
**Pull request by lamont-granquist**
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
user reported on slack, i haven't tested.

**Comment by lamont-granquist** [comment]
apparently doesn't fix it?  but this is certainly one bug of potentially several...

**Comment by coderanger** [comment]
I don't think that's a typo https://github.com/chef/chef/blob/master/lib/chef/knife/core/bootstrap_context.rb#L192

**Comment by lamont-granquist** [comment]
ah you are correct, nevermind then...

**Pull request closed without merging**
