### PR TITLE
add specs for nilling deploy parameters

### PR DESCRIPTION
**Pull request by lamont-granquist**
This finishes #2956 with the provider half of the changes.  Adds deploy provider func tests for the case where the array/hash things are cleared and set to nil.  This will make it substantially easier for users to clear out the capistrano bias from the deploy resource and will make our docs work.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core @chef/client-engineers needs review

**Comment by lamont-granquist** [comment]
@chef/client-core @chef/client-engineers pinging again for review

**Comment by danielsdeleo** [comment]
:+1:

**Comment by tyler-ball** [comment]
:+1:

**Pull request merged**
