### PR TITLE
Send search count to stderr

### LINKED ISSUE #2980: knife poisons stdout, making pipelining hard
`knife` is fond of emitting non-actionable data to stdout in some cases. To wit:

```bash
$ knife search node -i -F text 'tags:zookeeper'
3 items found

zookeeper.test-cloud.infra.edddbb17
zookeeper.test-cloud.infra.ff2adb0f
zookeeper.test-cloud.infra.9095d1bf
```

This forces a consuming user to blunder around with `head` or `grep` to get something I can pipeline to other commands. Idiomatic Unix commands generally emit something like that header row (if they emit a header row at all) to stderr. If a user wishes to combine the two for output, `2>&1` is right there for her use--the opposite is not true.

`knife node list` doesn't exhibit the same behavior, which is good.

### PR DESCRIPTION
**Pull request by danielsdeleo**
Fixes #2980 

:construction: this passes unit tests but I haven't run it for real. Also, what's the risk of people w/ hardcoded workarounds getting broken, how much do we care (I presume they'll be happy about it in the long term)?

### CODE REVIEW

**Comment by danielsdeleo** [comment]
@chef/client-core thoughts?

**Comment by stevendanna** [comment]
:+1:

**Comment by jonlives** [comment]
:+1: - I'm struggling to think of workaround cases this might break where people wouldn't be happy this fix was made :p

**Comment by thommay** [comment]
:+1: (and I imagine most "workarounds" are simply `grep` that would still be ok!)

**Pull request merged**
