### PR TITLE
Switch notifications from Hipchat to Slack (#open-source channel)

### PR DESCRIPTION
**Pull request by juliandunn**
I'm assuming the token is global to our org, so it's not tied to me... but if someone finds out otherwise please let me know.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
can we get this changed to `#chef-core-eng-team`, the `#open-source` channel no longer exists.

**Comment by lamont-granquist** [comment]
pingles?

**Comment by lamont-granquist** [comment]
also we probably want to send this to the same room we're going to be sending the build notifications to, not to the main chef-core-eng-team channel since that'll create too much noise, but i'm not sure if we have that room setup yet.

**Comment by juliandunn** [comment]
I'm going to close this in favor of having the right people (i.e. @chef/engineering-services) generate the right token.

**Pull request closed without merging**
