### PR TITLE
backport to 16: flush package cache after registering or unregistering with rhsm_register

### PR DESCRIPTION
**Pull request by jasonwbarnett**
Backport https://github.com/chef/chef/pull/12828 to chef-16

### CODE REVIEW

**Comment by johnmccrae** [comment]
@jasonwbarnett can you rebase and try again please? We updated the certs and just merged the code to fix the windows certs issues.

**Comment by jasonwbarnett** [comment]
@PrajaktaPurohit The branch is up-to-date. There is nothing to rebase (that I can see). Am I missing something obvious here?

**Review by jaymzh — APPROVED** [review]

**Comment by jaymzh** [comment]
This may be a "we didn't backport the fixes to 16" - we'll check that and then you can rebase. @johnmccrae is looking at it.

**Comment by johnmccrae** [comment]
@jaymzh What are your thoughts?

**Comment by jaymzh** [comment]
@johnmccrae  - you were going to go figure out which test-fixes were never backported to 16 ;)

**Comment by jasonwbarnett** [comment]
@johnmccrae Any updates on this one?

**Comment by marcparadise** [comment]
We will be getting our 16 pipelines back in running order after the 18 pre-release; we'll be able to rebase this at that time and get to passing tests.

**Comment by jaymzh** [comment]
OK - looks like @johnmccrae is OOO for a bit. @tpowell-progress to have a look at this.

FWIW, @jasonwbarnett getting the 16 builds passing is on the roadmap, but getting the 18 pre-release has taken up everyone's time, but this will definitely happen.

**Comment by jaymzh** [comment]
Just an update: we're getting closer to 16 having a clean pipeline - probably ~2 weeks or so. Once that's done, we should be able to rebase this and merge it. Sorry for the delay.

**Comment by neha-p6** [comment]
@jasonwbarnett Thank you for your patience. We have the pipelines back to green now. Could rebase to latest `chef-16` branch?

**Comment by jasonwbarnett** [comment]
> @jasonwbarnett Thank you for your patience. We have the pipelines back to green now. Could rebase to latest chef-16 branch?

@neha-p6 rebase complete.

**Review by neha-p6 — APPROVED** [review]

**Pull request merged**
