### PR TITLE
fix a batch of cops

### PR DESCRIPTION
**Pull request by lamont-granquist**
applying auto-fixes for:

Style/NegatedWhile
Style/ParenthesesAroundCondition
Style/WhileUntilDo
Style/WordArray
Performance/ReverseEach
Style/ColonMethodCall

will be disabled:

Style/TrivialAccessors - buggy should IgnoreClassMethods: true at least if we ever use it.
Style/UnneededPercentQ - buggy

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core todays batch of rubocop fixes.

**Comment by lamont-granquist** [comment]
looks like i broke rubocop and i'm having a hard time pull in the current released version.

**Comment by danielsdeleo** [comment]
I'm a big fan of the Style/ColonMethodCall rule but I'm not sure about the rest of them. I would like the trivial accessor thing a lot more if you could exclude class methods. I don't find:

```ruby
class << self
  attr_whatever :foo
end
```

particularly better than the `def self.foo` way

**Comment by lamont-granquist** [comment]
Yeah TrivialAcessor broke, and looks kinda rough, the UnneededPercentQ one broke as well.

**Comment by lamont-granquist** [comment]
@chef/core this is better now and passing tests.

**Comment by thommay** [comment]
:+1:

**Comment by danielsdeleo** [comment]
I don't really see the value in Style/WordArray either, e.g., if you change `["foo", "bar", result_of_method_call]` to just `["foo", "bar"]`, then it kinda feels like having to change single quotes to doubles to add interpolation. Not really motivated to argue about it though.

:+1: either way

**Comment by lamont-granquist** [comment]
hmmm, feels like that happens a lot less often to me, and %w is pretty commonly considered a best-practice (one that i try to practice...)

**Comment by lamont-granquist** [comment]
@chef/client-core polling anyone else for opinions?

**Comment by lamont-granquist** [comment]
Welp, I talked to @thommay about this and he was gonna :+1: this PR with some words, but he's busy CBGB'ing.

@danielsdeleo we gave your argument quite a bit of thought, but in the end felt that enforcing WordArray is a really common ruby style guide and the exception doesn't happen with anywhere near the frequency that the string interpolation ones does...

And if it pisses us off too much we can always rip it back out again...

**Pull request merged**
