### PR TITLE
Run activesupport tests in Travis

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by thommay** [comment]
I'm mostly :-1: on this; seems like a lot of overhead just to worry about json formatting.

**Comment by jkeiser** [comment]
@thommay I am super confused about that comment. Was that on the wrong PR?

**Comment by jkeiser** [comment]
@thommay and I worked it out: we're not adding the tests anymore, but removing compat_resource from the Gemfile/lockfile.

**Comment by randomcamel** [comment]
👍 with rebase, this includes the `github_changelog_generator` change.

**Pull request merged**
