### PR TITLE
support why-run by default

### LINKED ISSUE #5341: Mark all LWRPs and Custom Resources why-run safe by default
Our current policy mostly creates boilerplate code to enable why-run on an LWRP when most LWRPs that are correctly written are why-run safe naturally.

We should flip the default so that the onus is on the authors of bad code to write mark their code as being not why-run safe.

Can't do this until chef-13 though.

### PR DESCRIPTION
**Pull request by lamont-granquist**
this should fix several bugs in providers that look like they should
support whyrun but fail to declare it.

closes #5341

### CODE REVIEW

**Comment by tas50** [comment]
This seems incredibly dangerous for a lot of LWRPs out there. While a well written LWRP is why-run safe a lot of the ones that Chef itself wrote are not. I support making custom resources why-run by default, but LWRP convergence was almost never done correctly by end users / employees.

**Comment by shortdudey123** [comment]
Probably need to make sure this gets documented with a link on how to make sure an LWRP is why-run safe

**Comment by lamont-granquist** [comment]
so @tas50 do most people actually use the flag correctly or do they copypasta setting it to true and then write a broken LWRP?

and i don't really see how why-run bugs are any more "incredibly dangerous" than any other bug in a provider.

and there's nothing magical in custom resources that prevents people from writing whyrun bugs -- you write basically the same code -- if you support it for custom resources, you should support this.

@shortdudey123 the TL;DR is to either use sub-resources to do all the work or properly use converge_by blocks around code that change the system state, thats it.  and i believe that those are documented (at least i wrote the documentation for the doc site at least once or twice).

**Comment by shortdudey123** [comment]
Searching https://docs.chef.io for `converge_by` only shows it in code blocks without anything actually saying what it is or what goes in it.  Only `converge_if_changed` is really covered.

I do see it mentioned in https://blog.chef.io/2015/11/06/custom-resources-in-chef-client-12-5/ though

**Comment by lamont-granquist** [comment]
this is where i wrote them:

https://github.com/chef-boneyard/chef-web-docs-2016/pull/647

**Comment by lamont-granquist** [comment]
Also we flipped the default on custom resources end of last year after they'd been around for over a year and we'd been telling everyone to use them:

https://github.com/chef/chef/pull/5339

So far exactly zero people have cared.

**Comment by coderanger** [comment]
It has been on for Poise stuff by default since the 11.x days, though that's probably too small a sample to be useful :)

**Comment by lamont-granquist** [comment]
@chef/client-core reviewage?

**Pull request merged**
