### PR TITLE
Raise error and retry with PTY on sudo password prompt

### PR DESCRIPTION
**Pull request by rveznaver**
Signed-off-by: Robert Vežnaver <rveznaver@users.noreply.github.com>

## Description

The `knife ssh` command will silently fail if it starts with `sudo` and will not prompt for a password. The proposed change shall error out of `open_session` on `sudo` complaining about not having a TTY and will retry the command with a PTY.

## Related Issue

This fixes a regression introduced in #9482 by requesting a PTY only when `open_session` errors out. In addition, it also requires `tty-prompt` as once a PTY is allocated the prompt fails with #10705.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by phiggins** [comment]
> In addition, it also requires tty-prompt as once a PTY is allocated the prompt fails with #10705.

#10705 was fixed a few days ago in #10706.

**Comment by tas50** [comment]
@rveznaver Can you run `chefstyle -a` against the file to fix the style issues?

**Comment by rveznaver** [comment]
@dheerajd-msys: given you are the original author of #9482, could you please check this works well with Windows machines? It should not reintroduce any bugs, but if you have time to double check it that would be great!

**Comment by tas50** [comment]
Thanks for the fix @rveznaver

**Pull request merged**
