### PR TITLE
tweak 3694 warnings

### PR DESCRIPTION
**Pull request by lamont-granquist**
- clean up "ZenMaster" resource
- clean up 3694 detection to use properties
- unlazy the resource_name in the trivial resource check
- fixes an issue with resources-as-definitions pattern emitting
  3694 errors for trivial resources

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core fairly simple.  i ran into this with lamont-cookbooks/multipackage#7

**Comment by lamont-granquist** [comment]
@coderanger poise gets angry at this -- but it looks like in your test you're creating an object that just has a method defined on it, and doesn't declare an attribute or a property...

i ran into this with the old ZenMaster resource and converted the methods to properties and figured anyone not using the properties/attributes interface was not following the API guidelines... IDK if you've got a use case i'm not aware of though...

**Comment by coderanger** [comment]
Just that Poise has to support before those APIs existed so I have to test with them. We also support that for Chef though, so you'll need to fix the code :)

**Comment by lamont-granquist** [comment]
But attributes are ancient...  like 0.8.x era or something...  do we seriously need to support syntax back that old?

**Comment by coderanger** [comment]
Which API do you mean? You're using `.properties` which is very new. `def whatever() set_or_return_value end` is definitely something we should support given that until recently it was the only way implement most fancy transforms, lazy values, etc.

**Comment by lamont-granquist** [comment]
oh yeah, good point, all of core chef did that until recently...  meh...

**Comment by coderanger** [comment]
Sorry for buzzkill :) Some day we can have nice things? A few strategic `respond_to?` might be enough here though.

**Comment by lamont-granquist** [comment]
i can revert the cleanup, i didn't actually need that, i suspect that most of the problem.

**Comment by lamont-granquist** [comment]
@coderanger fixed

**Comment by coderanger** [comment]
:+1: Can add this to the "Chef 13 Happy Fun Times" list.

**Comment by lamont-granquist** [comment]
probably not, i think we still need to clean up a bunch of uses of methods directly on resources.  until that gets done we can't do the cleanup here.

**Pull request merged**
