### PR TITLE
Allow encrypting a previously unencrypted data bag

### LINKED ISSUE #8282: knife data bag edit <bag> <item> --encrypt will corrupt unencrypted data bags
when created with `knife data bag create creds whatever --encrypt` a `knife data bag edit creds whatever --encrypt` pops up an editor window to this and works:

```
{
  "id": "whatever",
  "foo": "bar"
}
```

when created with `knife data bag create creds whatever` (no --encrypt) a `knife data bag edit creds whatever --encrypt` pops up an editor window to this and fails:

```
{
  "name": "data_bag_item_creds_whatever",
  "json_class": "Chef::DataBagItem",
  "chef_type": "data_bag_item",
  "data_bag": "creds",
  "raw_data": {
    "id": "whatever",
    "foo": "bar"
  }
}
```

saving it then results in corruption:

```
% knife data bag show creds whatever
ERROR: Chef::Exceptions::ValidationFailed: Property data_bag's value {"encrypted_data"=>"tP5mvplwGL2TfsJs/G13c6VVn4ldg2hn\n", "iv"=>"7TmYwNI59Xbmuik7\n", "auth_tag"=>"pLJ9cerNIQqHSPnJzOgSSw==\n", "version"=>3, "cipher"=>"aes-256-gcm"} does not match regular expression /^[\-[:alnum:]_]+$/
```

it looks like `knife data bag edit --encrypt` is assuming that the data bag is already encrypted and then corrupting a non-encrypted data bag.  users expect the data bag to be encrypted (although do they expect it to be magically decrypted if you forget the --encrypt?  probably they expect an error in that case).

note that this has nothing to do with the format on disk and this is knife communicating with the chef-server directly and not interacting with the chef-repo/chef-fs/chef-zero.

```
% knife --version
Chef: 14.11.21
```

### PR DESCRIPTION
**Pull request by vijaymmali1990**
### Description

After creating an unencrypted data bag, and trying to edit/encrypt, It was raising exception as shown below.
There was a minor miss while editing. If data is not encrypted, we should be returning data only instead of returning the entire item.

```
// Creating an unencrypted Data Bag
> knife data bag create test box 
Data bag test already exists
Created data_bag_item[box]

// Edit and add encryption
> knife data bag edit test box  --secret 'ab'
Encrypting data bag using provided secret.
Saved data_bag_item[box]

// Raises Exception:
> knife data bag show test box 
ERROR: Chef::Exceptions::ValidationFailed: Property data_bag's value {"encrypted_data"=>"zuDd2Da3eyZiuPehburpE3DD+oJt2TA=\n", "iv"=>"jPNhkdghdNd+IsEP\n", "auth_tag"=>"V772V241NSkUwy+102R6Dg==\n", "version"=>3, "cipher"=>"aes-256-gcm"} does not match regular expression /^[\-[:alnum:]_]+$/
```

### Issues Resolved
Fixes #8282 

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [x] RELEASE\_NOTES.md has been updated if required (not required for bugfixes, required for API changes)
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by Vasu1105** [comment]
@tas50 and @btm This LGTM. Please review it from your side.

**Comment by btm** [comment]
We had a little further discussion at code review and we could add a missing set of tests to `spec/integration/knife/data_bag_edit_spec.rb` (the file doesn't exist yet) that fake an editor by modifying JSON directly. We should do that.

**Comment by lamont-granquist** [comment]
yeah if we had functional tests this would probably break those for the other use case.

and the correct patch should look like a patch to the object model itself, not to knife.  so Chef::DataBagItem would need to probably have `def self.from_hash` modified to be able to accept either format.

but then that also needs to get done for data bags, roles, and environments at a minimum.

and there needs to be some attention made to DRY'ing up this code.

**Comment by lamont-granquist** [comment]
ah, i think i see now.

i think this fixes #8282 which i just cut, and i deleted all the comments in #4815 which had nothing to do with the original issue.  my prior comment only makes sense in the context of where i thought this was addressing what is now #4815.

so, yes, this might fix #8282 

could really use some func or integration tests though.

**Comment by btm** [comment]
This has functional tests now. Should be good to go.

**Pull request merged**
