### PR TITLE
OSX maintainer

### PR DESCRIPTION
**Pull request by mikedodge04**
I have helped contribute multiple commits for the osx chef client, and help run our large fleet of macs at facebook. @jaymzh  and I were talking, and it seems like it makes sense that I get added.

### CODE REVIEW

**Comment by jaymzh** [comment]
:+1: 
CC @jtimberman

**Comment by mikedodge04** [comment]
@tduffield updated, let know know if this is what you were looking for

**Comment by jaymzh** [comment]
@mikedodge04 you need a signed-off-by line

**Comment by tduffield** [comment]
If you can, can you also run the `bundle exec rake maintainers` command?

**Comment by thommay** [comment]
Great to have you on board!

**Comment by jtimberman** [comment]
Sweet! Totally missed this, sorry. Retroactive 👍 for sure :1st_place_medal:

**Pull request merged**
