### PR TITLE
Fix sudoer.erb

### PR DESCRIPTION
**Pull request by hunter86bg**
Fixes broken erb template

## Related Issue
Fixes Case# 01234688 / CHEF-2186

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] I have run the pre-merge tests locally and they pass.
- [X] I have updated the documentation accordingly.
- [X] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tpowell-progress** [comment]
@hunter86bg thanks for the contribution. Upon first perusal, everything looks great, but do you happen to have any details on how to set up the error that occurred before that can be added to the PR description?

**Comment by hunter86bg** [comment]
@tpowell-progress ,

I provided a reproducal in ticket and I will try to upload it here too.

**Comment by hunter86bg** [comment]
@tpowell-progress , I've sent it to @Stromweld and he will upload it to the Jira.

**Comment by tpowell-progress** [comment]
@hunter86bg It looks like `kitchen-tests/cookbooks/end_to_end/recipes/_sudo.rb` is referencing `:command_list` whereas 
sudo.rb only has `commands`... so perhaps the kitchen-test needs to be changed as well? Thoughts?

**Review by tpowell-progress — APPROVED** [review]
Approving as this is from a customer's patching of the sudoer.erb directly.

**Comment by hunter86bg** [comment]
@tpowell-progress , can we have it back-ported to v17 also?

**Comment by tpowell-progress** [comment]
@hunter86bg yes, although looks like there was a false negative in kitchen-tests and there is some breakage that I will resolve first

**Pull request merged**
