### PR TITLE
[chef-17] backport Bump deps for net-ssh 7.x for RHEL 9 and Ubuntu 22.04 ssh

### PR DESCRIPTION
**Pull request by Stromweld**
## Description

Backport of bump deps for net-ssh 7.x for RHEL 9 and Ubuntu 22.04 ssh new algorithms support, update chef gemfile.lock with bundler update

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Review by tpowell-progress — APPROVED** [review]

**Review by jaymzh — APPROVED** [review]

**Comment by Stromweld** [comment]
@jaymzh @tpowell-progress @PrajaktaPurohit @johnmccrae This PR has balooned a little into fixed pipelines for chef-17 branch. I almost have them fixed. I'm not sure what is causing the unit test for gems from non api website spec to fail. The other windows failures are around habitat and failure to find chef-utils 17.10.26 gem. Do you guys have any insights into how to fix these?

**Comment by tpowell-progress** [comment]
Let's put this near the top of the priority for Chef 17 merges

**Comment by Stromweld** [comment]
Reverted pipeline fixes and moved them to a new PR #13399

**Comment by acrewdson** [comment]
@Stromweld 👋 thank you for this PR; can I ask if there's a possibliity it will be merged soon? it's causing major problems for folks on chef 17 🙏

**Comment by acrewdson** [comment]
@Stromweld thank you for this PR

@tpowell-progress can I ask if there's a possibliity this will be merged soon? it's causing major problems for folks on chef 17 🙏

**Pull request merged**
