### PR TITLE
don't remove trailing newlines on json output

### PR DESCRIPTION
**Pull request by kisoku**
permits ChefFS to produce json objects that don't make git complain

### CODE REVIEW

**Comment by kisoku** [comment]
This was suggested by @jkeiser after I complained about ChefFS gobbling my newlines when running 'knife download'

**Comment by coderanger** [comment]
I feel like this is going to wreck all kinds of havoc given how deep this is in the code. Is there somewhere closer to the edge where we can re-add the newline?

**Comment by jkeiser** [comment]
@coderanger I'm curious what sort of havoc? It feels like newlines are a good thing for editor software/etc.

@kisoku OTOH, if you want to just affect knife download and upload, go through all uses of this in `lib/chef/chef_fs` and add the newline at the end there.

**Comment by lamont-granquist** [comment]
@jkeiser it causes 28 failing rspec tests at a minimum.

**Comment by kisoku** [comment]
I can take a stab at fixing those 28 tests if you think it's worth the time and effort. If not I will focus on knife download

**Comment by thommay** [comment]
Definitely feels like it would be better to fix up `knife` rather than something so deep in the core (that could be considered part of the API contract).

**Comment by lamont-granquist** [comment]
yeah, i feel like for better or for worse this is part of our Chef::JSONCompat API and we can't touch it without making a breaking change, so :-1: on this approach.

i think the spec failures are likely a symptom of how much chaos this will cause if we let it loose in the world.

i'm more okay with fixing the output on the knife download with a more restricted change.

**Comment by thommay** [comment]
I think given the concerns around bustage and our API we're gonna close this PR. thanks mate!

**Pull request closed without merging**
