### PR TITLE
Do not raise if we can't close win resource handle

### PR DESCRIPTION
**Pull request by marcparadise**
On Windows 2012, we are seeing frequent errors during the finalizer for
Win32::Handle, which invokes CloseHandle:

'The handle is invalid' (error code 6)

Debugging and testing has shown that every instance of this error is
caused by the handle 18446744073709551615 (which converts to "ffffffffffffffff").  We have also seen
that this matches the value passed into the constructor of Handle,
provided directly from GetCurrentHandle.

We were previously comparing this to the const `ffffffff` and skipping
the CloseHandle call on the assumption that `ffffffff == (HANDLE)-1`
based on the docs here: http://msdn.microsoft.com/en-us/library/windows/desktop/ms683179(v=vs.85).aspx

But given that we are directly seeing the GetCurrentHandle returning
"ffffffffffffffff", it seems HANDLE (a LPVOID) is 64 bit instead of 32, so the 
default pseudo-handle is more likely to be `ffffffffffffffff` than `ffffffff`. 

 Instead of worrying about the correct value of that const, this PR
 makes it so that we're following the recommended approach in the link
 above - if we want to check if a handle == current process pseudo-handle , we
 compare it to GetCurrentHandle instead of the const.

 In the process, it resolves the errors we're seeing on the Windows
 Server 2012 platform, where we are failing when CloseHandle returns
 "invalid handle".

Signed-off-by: Marc A. Paradise <marc.paradise@gmail.com>
Signed-off-by: John McCrae <john.mccrae@progress.com>

### CODE REVIEW

**Comment by PrajaktaPurohit** [comment]
Should we include the context for why we are changing the handler instead of making changes to the specs?

**Comment by marcparadise** [comment]
I have updated the description - still don't include that information, because it's no longer relevant (that is, this is the correct fix now, not a workaround ).  Assuming it passes through the pipeline; if not I'll revert to the change that prevents us from raising the exception and update comment accordingly.

**Comment by marcparadise** [comment]
buildikite failure is due to the solaris builder issue w/ invalid repository checksum and is not related.

**Comment by marcparadise** [comment]
The opensuse failures are an ongoing issue with those builders, and are not related to this change

**Review by tpowell-progress — APPROVED** [review]

**Pull request merged**
