### PR TITLE
3618 run list mutation issue

### PR DESCRIPTION
**Pull request by danielsdeleo**
See #3618 for details. This needs to get back ported to 12.4.1

@chef/client-core

### CODE REVIEW

**Comment by jaym** [comment]
:+1:

**Comment by btm** [comment]
@danielsdeleo what's the significant change to `lib/chef/run_list/versioned_recipe_list.rb`?

**Comment by danielsdeleo** [comment]
@btm https://github.com/chef/chef/commit/bc8e574ab8d423ae2d08882c0413910fcc867219#diff-f519758d7f26b7856f410d4e725feec8R182 explains it in RSpec-ese. Basically if you got to the right branch of the code, the recipe string got mutated with `recipe_name << "@#{version}"`

**Comment by mcquin** [comment]
LGTM

**Comment by thommay** [comment]
LGTM! :+1: (pending travis)

**Comment by lamont-granquist** [comment]
:+1:

**Comment by ranjib** [comment]
:+1:

**Pull request merged**
