### PR TITLE
Make windows event log tests faster

### PR DESCRIPTION
**Pull request by jaym**
Using SecureRandom is slow if it is not initialized.
Random is good enough for this test.

### CODE REVIEW

**Comment by ksubrama** [comment]
:+1:

**Comment by mwrock** [comment]
:+1: yeah. securerandom and uuidtools load native win32 libraries on first call to create a guid and its a total bummer. dont know why that takes like 2-5 seconds.

**Comment by smurawski** [comment]
Looks like the build failure was exceeding execution time. :+1:

**Comment by jaym** [comment]
@smurawski https://github.com/chef/chef/pull/4509 will fix the build failure execution time issue

**Comment by tyler-ball** [comment]
:+1:

**Pull request merged**
