### PR TITLE
Use Ruby 2.3.1

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by mwrock** [comment]
should we adjust the travis external tests to use 2.3.1?

**Comment by jkeiser** [comment]
Yes, yes we should!

**Comment by mwrock** [comment]
cool. :+1: on green

**Comment by lamont-granquist** [comment]
did you already pull in the fix that adamedx did for 2.2.x?  i can't remember what class that was patching again and can't find the old PRs (my old PR for ruby 2.2 and the PR that reverted it)

**Comment by lamont-granquist** [comment]
i think you're missing:

https://github.com/chef/chef/commit/e25b75e9fcd26ccc9c9094a43b614306de1047db

**Comment by lamont-granquist** [comment]
the referenced PR in this comment has also been merged, so either this should track the released gem again or should track master or something of the project:

https://github.com/chef/chef/blob/bd2dfa481e7525e1c4a64450a6b018a0b1fcd3f9/Gemfile#L78-L79

**Comment by lamont-granquist** [comment]
and https://github.com/travis-ci/travis.rb/pull/426 needs some more attention to unpin it here:

https://github.com/chef/chef/blob/bd2dfa481e7525e1c4a64450a6b018a0b1fcd3f9/Gemfile#L85-L86

**Comment by jkeiser** [comment]
The latter two issues I'll deal with in another thread; I'll check whether I pulled the long names fix in at any point.

**Comment by jkeiser** [comment]
@lamont-granquist I added e25b75e to the branch in the above commit ^^

**Comment by lamont-granquist** [comment]
👍

**Comment by jkeiser** [comment]
Commits all check out, rebased against master. Merging.

**Pull request merged**
