### PR TITLE
Added timeout during removing of windows package

### PR DESCRIPTION
**Pull request by dheerajd-msys**
Fix for issue https://github.com/chef/chef/issues/4361

### CODE REVIEW

**Comment by dheerajd-msys** [comment]
The testing is complete, can someone help me in below spec failure I am getting on `Travis`, I am not sure if it is related to my code or not.


```
1) chef-solo when the chef repo has a cookbook with a recipe with sleep while running solo concurrently
     Failure/Error: expect(run_log.lines.reject { |l| !l.include? "INFO: Chef Run complete in" }.length).to eq(2)
     
       expected: 2
            got: 0
```

**Comment by btm** [comment]
I've restarted the Travis test, might be a transitive failure.

Can you add a unit test for this?

**Comment by btm** [comment]
The travis failure looks related to 57d627615cd8aad87dbeed5fd6d0444c15ca1dfa, @lamont-granquist, have you seen this?

**Comment by lamont-granquist** [comment]
nope, that's the first i've seen that.   there's an obvious code bug i think some perl deep within my brain just escaped into that...   but really with all the retries that should never happen either.   it looks like its just a sunspot and should go away with a restart.   i'll see if i can meditate on how it would have happened...

**Comment by btm** [comment]
:+1:

**Comment by thommay** [comment]
:+1: LGTM

**Pull request merged**
