### PR TITLE
[CHEF-2205] Set '--no-create-home'

### PR DESCRIPTION
**Pull request by johnwilliams**
http://tickets.opscode.com/browse/CHEF-2205

Set '--no-create-home' so we don't attempt to create a home directory on RHEL/CentOS systems

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Dunno why this got dropped.  Legit bug does not seem to be fixed, but needs a rebase.

**Comment by smurawski** [comment]
@chef/maintainers We should get this rebased and merged.

**Comment by btm** [comment]
> This could come as a surprise to someone, since they don't have to specify that they want a home directory when they use useradd on the command line, but since we default to false, they would have to specify as much. I don't see any way around that.

The reason we hadn't merged this is because it means that we're currently creating home directories (with the default login.defs file) when you just say

```user "bob"```

but after this change we will only create home directories for:
```
user "bob" do
  manage_home true
end
```

Which we had considered to be a breaking change.

**Comment by lamont-granquist** [comment]
Do we have a difference between Ubuntu and RHEL right now as to if the user resource creates the homedir or not?  Switching the behavior would definitely be a breaking change though.  Could we set manage_home to true by default to preserve the existing behavior?

**Comment by martinisoft** [comment]
@lamont-granquist To my knowledge of Ubuntu (think RHEL useradd is similar) the same flag exists.

I agree here on setting `manage_home true` as a reasonable default since this seems to already be expected behavior. Would any other Ubuntu/RHEL maintainers/lieutenants be able to chime in here to get this ready for merge?

**Comment by btm** [comment]
@chef/ubuntu thoughts?

**Comment by lamont-granquist** [comment]
Looks like this just needs to have the conflicts resolved and have manage_home set back to true to preserve the existing defaults.

**Comment by SaltwaterC** [comment]
Hi. Any updates on this issue? I don't think it's unreasonable to expect Chef not to create a home directory when I'm passing `manage_home false` under RH-based distros.

Under its current incarnation, manage_home is as useful as a hair dryer under water. Any combo will create an actual home dir. I know what login.defs says, that's the behaviour I'm _trying to override_ with manage_home. Thanks.

**Comment by btm** [comment]
@SaltwaterC Do you want to submit a rebased pull request with "manage_home set back to true to preserve the existing defaults." ?

**Pull request closed without merging**
