### PR TITLE
Pin win32-eventlog to 0.6.3 to avoid clashing CreateEvent definition

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by ksubrama** [comment]
Can be un-pinned when https://github.com/djberg96/win32-eventlog/issues/20 is resolved.

**Comment by btm** [comment]
@ksubrama should we add a comment with that?

**Comment by ksubrama** [comment]
Done!

**Comment by mwrock** [comment]
:+1:

**Comment by btm** [comment]
:+1:

**Comment by schisamo** [comment]
:+1:

**Pull request merged**
