### PR TITLE
WIP Fixes for duplicate logs spec is remaining

### PR DESCRIPTION
**Pull request by piyushawasthi**
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>

### Description

Fixes for duplicate log 
```
chef$ bundle exec bin/chef-client -c ../.chef/knife.rb 
Starting Chef Client, version 14.4.57
[2018-08-29T13:52:16+05:30] INFO: *** Chef 14.4.57 ***
[2018-08-29T13:52:16+05:30] INFO: Platform: x86_64-linux
[2018-08-29T13:52:16+05:30] INFO: Chef-client pid: 28477
[2018-08-29T13:52:16+05:30] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
[2018-08-29T13:52:20+05:30] INFO: Run List is []
[2018-08-29T13:52:20+05:30] INFO: Run List expands to []
[2018-08-29T13:52:20+05:30] INFO: Starting Chef Run for msys
[2018-08-29T13:52:20+05:30] INFO: Running start handlers
[2018-08-29T13:52:20+05:30] INFO: Start handlers complete.

chef$ bundle exec bin/chef-apply ~/chef-repo/cookbooks/elasticsearch/recipes/default.rb
[2018-08-29T13:53:36+05:30] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-08-29T13:53:36+05:30] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-08-29T13:53:36+05:30] FATAL: LoadError: cannot load such file -- chef/provisioning/aws_driver
```

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] RELEASE\_NOTES.md has been updated if required (not required for bugfixes, required for API changes)
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
https://github.com/chef/chef/pull/7491/files

that is probably the correct fix, but needs a lot of QA and ideally tests written around it.

**Comment by piyushawasthi** [comment]
Thanks @lamont-granquist let me verify more on that.

**Comment by piyushawasthi** [comment]
@lamont-granquist : I have verified these changes for chef-client, chef-apply, chef-solo, knife bootstrap and etc. for all that's changes working fine.

**Comment by btm** [comment]
Just to keep these linked together, the top level issue is: https://github.com/chef/chef/issues/7184

Over many attempts to tune this we have had a pile of attempted or considered solutions here:
```
Chef::Config.is_default?(:log_location) && Chef::Config[:log_location].tty? && !Chef::Config[:daemonize]
Chef::Config.is_default?(:log_location) && STDOUT.closed? && Chef::Config[:daemonize]
!( chef_config[:log_location].is_a?(IO) && chef_config[:log_location].tty? ) && !chef_config[:daemonize]
!(Chef::Config.is_default?(:log_location) || STDOUT.closed? || Chef::Config[:daemonize])
```

so @piyushawasthi, I agree we would really like tests here, or at least some comments on the nuance.

**Comment by lamont-granquist** [comment]
so way back in the day this used to work:

```
      ( Chef::Config[:log_location] != STDOUT ) && STDOUT.tty? && (!Chef::Config[:daemonize]) && (Chef::Config[:force_logger])
```

then we dropped force_logger in 13:

```
      ( Chef::Config[:log_location] != STDOUT ) && STDOUT.tty? && (!Chef::Config[:daemonize])
```

now we ran into the `STDOUT != STDOUT` issue, so introduced `Chef::Config.is_default?` and since the default is STDOUT, then `!= STDOUT` should translate to `!is_default?`

```
      ( !Chef::Config.is_default?(:log_location)) && STDOUT.tty? && (!Chef::Config[:daemonize])
```

then i introduced the proposal to change `STDOUT.tty?` to `!STDOUT.closed?` 

```
      ( !Chef::Config.is_default?(:log_location)) && !STDOUT.closed? && (!Chef::Config[:daemonize])
```

then i just applied De Morgan's Law to get rid of most of those '!'s:

```
       !(Chef::Config.is_default?(:log_location) || STDOUT.closed? || Chef::Config[:daemonize])
```

the fact that we somehow went through that process and then i wound up with something which is the negation of the correct code is painfully weird.

```
       Chef::Config.is_default?(:log_location) && STDOUT.closed? && Chef::Config[:daemonize]
```

so this will work all the time on the command line because STDOUT.closed? will be false so the expression will be false, so of course you will not get an additional logger.  `Chef::Config[:daemonize]` will also always be false here on the command line which is another one that forces it to false.  

yeah i think this has mostly fixed the double logging by breaking the feature entirely.

the point is that a user should be able to point Chef::Config[:log_location] to e.g. "/var/log/chef/client.rb" and when chef-client is run on the command line, the logger is setup to log_location but then you also get the additional STDOUT logger so that the user on the cli gets it.

**Comment by lamont-granquist** [comment]
yeah so here's another test.

- add a line to /etc/chef/client.rb:

log_location "/var/log/chef/client.log"

- run `sudo chef-client -l trace`

the existing line of code is broken and only produces a bit of debugging output from shellcommands but all the debug/trace/info lines are missing.

this proposed patch is broken in the same way.

both patches seem to be equivalent to:

```
def want_additional_logger?
  false
end
```

which indeed will prevent all double-logging problems.

but i'm surprised we don't have users complaining now that they can't get `-l debug` and `-l trace` output on servers.

**Comment by piyushawasthi** [comment]
@lamont-granquist : I will look `-l debug` and `-l trace` as well.

**Comment by Vasu1105** [comment]
@lamont-granquist closing this PR since this needs to be revisited. We will consider all your review comments for debugging more into it.

**Pull request closed without merging**
