### PR TITLE
Simplify macos platform detection in the specs + add macOS Big Sur testers

### PR DESCRIPTION
**Pull request by tas50**
This backports 3 different changes we made in master to add Big Sur packages.

### CODE REVIEW

**Comment by phiggins** [comment]
Some of the test failures look legit:

```

 1) Chef::Resource::Link when supported on platform is a hard link when the link destination is a symbolic link to a real file and the link does not yet exist links to the target file
     Failure/Error: skip("OS X/FreeBSD/AIX/Solaris symlink? and readlink working on hard links to symlinks") if os_x? || freebsd? || aix? || solaris?
 
     NoMethodError:
       undefined method `os_x?' for #<RSpec::ExampleGroups::ChefResourceLink::WhenSupportedOnPlatform::IsAHardLink::WhenTheLinkDestinationIsASymbolicLink::ToARealFile::AndTheLinkDoesNotYetExist:0x000055930e4d0138>
     # ./spec/functional/resource/link_spec.rb:659:in `block (7 levels) in <top (required)>'
     # ./spec/spec_helper.rb:298:in `block (2 levels) in <top (required)>'
```

**Comment by tas50** [comment]
yeah since this was a cherry pick of a few different PRs I don't have the full history. Looks like I need to update some other spots first.

**Comment by tas50** [comment]
@phiggins Fixed now by bringing in another commit

**Review by phiggins — APPROVED** [review]

**Comment by tas50** [comment]
Confirmed this works in an adhoc

**Pull request merged**
