### PR TITLE
Update usage of @new_resource.destination to `cwd` within the git hwrp

### PR DESCRIPTION
**Pull request by joshburt**
We have access to a method within the git HWRP to handle resolution of the cwd (current working directory) to @new_resource.destination.

Would it make sense to make more use of this method and replace instances of @new_resource.destination with it?

Would enjoy some feedback on this. Thanks!

### CODE REVIEW

**Comment by coderanger** [comment]
Is there a reason to not go the other way and remove the helper? Notably use of `@new_resource` is kind of gross and breaks all kinds of scoping stuff :)

**Comment by joshburt** [comment]
We certainly could!  The result would be some other code that gets longer / less clear in a number of conditions:



**Examples**

From:
`	result = git("rev-parse", "HEAD", cwd: cwd, returns: [0, 128]).stdout.strip`
To:
`	result = git("rev-parse", "HEAD", cwd: @new_resource.destination, returns: [0, 128]).stdout.strip`

From:
`	FileUtils.rm_rf(::File.join(cwd, ".git"))`
To:
`	FileUtils.rm_rf(::File.join(@new_resource.destination, ".git"))`

**Comment by smurawski** [comment]
:+1:

**Comment by lamont-granquist** [comment]
i'd just suggest to use Forwardable and `def_delegator :@new_resource, :destination, :cwd`

**Comment by joshburt** [comment]
The Forwardable / def_delegator was a nice suggestion!  I've updated the implementation accordingly.  Thanks everyone!

**Comment by thommay** [comment]
:+1: LGTM

**Comment by joshburt** [comment]
Looks like the travis-ci run had a few instances of `Timeout::Error`.  I'll kick this off again as it doesn't seem related to the code changes within this PR.  Thanks!

**Comment by joshburt** [comment]
Second run went through just fine!

**Pull request merged**
