### PR TITLE
Use a streaming request to download cookbook

### LINKED ISSUE #4549: knife cookbook site download fails
```
13:21 ~/work/chef % be knife cookbook site download chef-solo-search   [master]
Downloading chef-solo-search from Supermarket at version 0.5.1 to /Users/thom/work/chef/chef-solo-search-0.5.1.tar.gz
ERROR: knife encountered an unexpected error
This may be a bug in the 'cookbook site download' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `sign_on_redirect=' for #<Chef::HTTP::SimpleJSON:0x007ff4c6893a88>
[1]    91706 exit 100   bundle exec knife cookbook site download chef-solo-search
```

### PR DESCRIPTION
**Pull request by thommay**
fixes #4549

### CODE REVIEW

**Comment by lamont-granquist** [comment]
so how did the bug show up and are there any more occurrences?

**Comment by tyler-ball** [comment]
:+1: 

@lamont-granquist I checked the code for other uses of `sign_on_redirect` and only found it in specs or as attributes on a class

**Comment by thommay** [comment]
That's the only place we try and do a streaming request with noauth_rest (which used to be `get(path, true)`. I'm checking everything else through.

I stumbled upon this because I happened to have a post 12.6.0 chefdk installed and needed to download a cookbook from supermarket.

**Comment by thommay** [comment]
@chef/client-core this is ready for review

**Comment by jkeiser** [comment]
@thommay I'm not seeing (here or in the other bug) how precisely this caused the issue to happen and how this fixes it. Can you elaborate?

**Comment by danielsdeleo** [comment]
* `Chef::REST#get`: https://github.com/chef/chef/blob/7755b93c72ef33d5041b6a9c4b53bcf29814579d/lib/chef/rest.rb#L116
* `Chef::HTTP#get`: https://github.com/chef/chef/blob/7755b93c72ef33d5041b6a9c4b53bcf29814579d/lib/chef/http.rb#L109

So it looks at first glance that we just missed this in the mass switch from REST->HTTP. Though I would have expected to get a more type-related error (probably NoMethodError) when passing `true` instead of a `Hash`.

This covers all the instances I am able to find with `git grep '\.get' -- lib |grep ','` (that finds more false positives than not but gets the job done.

:+1: though I'd be in favor of someone else independently looking for instances of this error and making sure we got them all.

**Comment by lamont-granquist** [comment]
:+1:

**Comment by thommay** [comment]
@danielsdeleo so we did a NoMethodError (`[]` for true) once that was no longer masked by `sign_on_redirect` being missing. 

@jkeiser as Dan says, this was just overlooked in the move to Chef::HTTP  - mainly I was looking for instances of `get_rest` and relying on tests to catch the rest.

**Comment by jkeiser** [comment]
Got it, :+1:

**Comment by SolverDude** [comment]
But wait!  There's more!!!
 `knife supermarket show -VV -m 'https://chefstore.chq.ei' -c ~/.chef/knife_prod.rb expd_infrastructure
INFO: Using configuration from /home/chq-anthonyr/.chef/knife_prod.rb
/home/chq-anthonyr/.chefdk/gem/ruby/2.1.0/gems/knife-supermarket-0.2.1/lib/chef/knife/supermarket_show.rb:38:in `get_cookbook_data': undefined method `get_rest' for #<Chef::HTTP::SimpleJSON:0x000000022815e8> (NoMethodError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/cookbook_site_show.rb:28:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:416:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:415:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:50:in `load'
	from /opt/chefdk/bin/knife:50:in `<main>'`

This with 0.11.0 chefdk, and knife-supermarket 0.2.1.  Granted, supermarket isn't here, but i thought I should mention here since we're talking chef-client innards.

**Comment by SolverDude** [comment]
@tyler-ball, I'm unclear if i should have posted this above, or a better place, but at the time it seemed to make sense here.  If i'm wrong, happy to put in better place.  I'm advising you of this as my timing with daniel's branch deletion might have obscured my comment...

**Comment by thommay** [comment]
@SolverDude please raise a bug against knife-supermarket with this.

**Pull request merged**
