### PR TITLE
Add ruby-cleanup to clear the bundler/gems and cache folder

### PR DESCRIPTION
**Pull request by poorndm**
Signed-off-by: poorndm@progress.com
## Description
The size of the installer on platforms has doubled after moving to chef-foundation.

Fix Includes cleanup of the bundler caches. This will remove ohai,rest-client,ruby-proxifier,and ruby-shadow caches. On cleaning the cache and bundler folder reduces the overall package size.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by poorndm** [comment]
Test Build - https://buildkite.com/chef/chef-chef-main-validate-adhoc/builds/384

**Comment by tpowell-progress** [comment]
[pre and post chef-foundation](https://github.com/chef/chef/compare/v18.0.208...v18.2.9) versions seem to indicate that the ruby-cleanup dependency was removed. Shouldn't we start with reintroducing the dependency first (or has that already been tried and I'm missing that detail?)

**Comment by poorndm** [comment]
@tpowell-progress 
I have already tried adding a ruby-cleanup dependency. Build failed [Error] ](https://buildkite.com/chef/chef-chef-main-validate-adhoc/builds/369#01876b25-45f2-4d3c-af0b-3f0f41252e35/310-1603)
```
bundler: failed to load command: omnibus (/opt/omnibus-toolchain/embedded/lib/ruby/gems/3.1.0/bin/omnibus)
/opt/omnibus-toolchain/embedded/lib/ruby/3.1.0/fileutils.rb:367:in `symlink': File exists @ syserr_fail2_in - /opt/chef/embedded/ssl/cert.pem (Errno::EEXIST)
```
 Since the cert files already get copied with the chef-foundation install. It is throwing the above error.
 The cacerts dep comes from ruby-cleanup --> ruby --> openssl --> cacerts
Hence I made a  project local copy of ruby-cleanup and removed the ruby dep in it as ruby would already be there on the build agent.

**Comment by vkarve-chef** [comment]
@poorndm what if we removed the ruby dependency in the original `ruby-cleanup` omnibus-software definition? i believe we will still be able to get successful builds for other products that rely on `ruby-cleanup` minus that.

**Review by vkarve-chef — APPROVED** [review]

**Review by tpowell-progress — APPROVED** [review]

**Comment by poorndm** [comment]
[Test Build](https://buildkite.com/chef/chef-chef-main-validate-adhoc/builds/433)

**Comment by tpowell-progress** [comment]
BadSSL errors will be fixed in an upcoming PR.

**Pull request merged**
