### PR TITLE
Log cause chain for exceptions

### PR DESCRIPTION
**Pull request by jaym**
Thoughts?
cc @chef/client-maintainers

### CODE REVIEW

**Comment by lamont-granquist** [comment]
We still ship and support ruby 2.0 don't we so you'd need to `respond_to?(:cause)` check this or something?

**Comment by danielsdeleo** [comment]
I think Lamont is correct. :+1: once that's fixed up

**Comment by jdmundrawala** [comment]
:(
but i wanted it for windows. I'm guessing there's no way for ruby 2.0?

**Comment by danielsdeleo** [comment]
@jdmundrawala it's way harder, so depends on how motivated you are. Anyway, you can roll your own nested exceptions with something like:

```ruby

class SomeException
  attr_reader :cause
  def initialize(*args)
    @cause = $!
    super
  end
end
```

You could extract that into a module and then use module prepending to add it to all of our exceptions.

But even then we can only do this for Chef's own exceptions, so stuff from inside libraries won't have this.

**Comment by tyler-ball** [comment]
@jdmundrawala are we still building chef with Ruby 2.0 for Windows?  We use 2.1.5 for the ChefDK

**Comment by jdmundrawala** [comment]
still 2.0

**Comment by tyler-ball** [comment]
:cry:

**Comment by thommay** [comment]
:+1: LGTM

**Comment by lamont-granquist** [comment]
yeah now that we're off of 2.0 everywhere we should :shipit:

**Pull request merged**
