### PR TITLE
ChefFS & knife environment matching the output

### PR DESCRIPTION
**Pull request by vsingh-msys**
## Description

Added default params in `knife download /environments` so that it's matched with `knife environment show  --format=json`

## Related Issue

Fixes https://github.com/chef/chef/issues/4213

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Can you validate that if you create a minimal role/environment, that when you upload that to the server that `knife diff` will not produce any diffs?

In other words, does knife diff go through a different codepath where it is still being minimized?  Or does it in some other way force minimization of the json data?

**Comment by Vasu1105** [comment]
As per my observations if you have other information added for environment knife download that information

**Comment by Vasu1105** [comment]
As per my observation 

If we have other information set for environment knife download . / knife download /environments does download that information.

Data after download of the environments 
for default.json
```
{
  "name": "_default",
  "description": "The default Chef environment"
}
```
for development.json where I have added some more data about environment.
```
{
  "name": "development",
  "description": "Used for developement environment",
  "cookbook_versions": {
    "starter": "1.0.0"
  }
}
```
What I feel is if we are setting any data in knife download if we are having any data loss that will be bug then as we use same data to upload also. So it may be this behavior is correct to bring minimal data at the download time and to not create any additional information which is not required at the time of download. As it may increase the time for download. These are just my thoughts.

**Comment by vsingh-msys** [comment]
@lamont-granquist As per the knife diff concern, the normalized environment does not produce any diff content because in `#campare_to` it minizine the both local and server content before comparing.

https://github.com/chef/chef/blob/b7025a006710bbbf9bc9c05b21a083ca7e53a65f/lib/chef/chef_fs/file_system/chef_server/rest_list_entry.rb#L145-L155


@Vasu1105  That's true, there is no loss of the data if we upload environment data keys with the respective non-empty value.

But if we upload or create the environment with:
```
{
  "name": "dev",
  "description": "",
  "cookbook_versions": {

  },
  "default_attributes": {

  },
  "override_attributes": {

  },
  "json_class": "Chef::Environment",
  "chef_type": "environment"
}

```
when downloading environments it always returns
```
{
 "name": "dev"
}
```

**Comment by vsingh-msys** [comment]
@lamont-granquist, For now, I have tested/verified these changes only for the environments. 

For roles, it's testing is still pending.

**Comment by vsingh-msys** [comment]
Roles also working as expected with the latest changes. This PR is good to review again Thanks!

**Comment by lamont-granquist** [comment]
Marked this as breaking change since it looks breaking, it is correct but it should only go into Chef-16.0

**Pull request merged**
