### PR TITLE
Fix train platform detection error

### PR DESCRIPTION
**Pull request by dheerajd-msys**
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>

## Description

- This handles the platform detection error while bootstrapping the machine.
## Related Issue

Fixes https://github.com/chef/knife-ec2/issues/572
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by marcparadise** [comment]
This is resolved with https://github.com/chef/chef/pull/8506 - looks like the MsysTechnologiesllc/chef repository is out of date.

**Comment by dheerajd-msys** [comment]
Hi @marcparadise, 

I am facing `Train::PlatformDetectionFailed` issue with latest `chef v15.0.293` as well and could be able to resolve with this PR  https://github.com/chef/chef/pull/8523 updates. 

For stacktrace please take a look https://github.com/chef/knife-ec2/issues/572#issuecomment-492201362

Reopening the PR. Please let me know if there is anything.

**Comment by marcparadise** [comment]
@dheerajd-msys could you explain how this fixes the error? The issue resolved by #8506 was to make sure that `config_source` works correctly by initialize @original_config in the constructor.

**Comment by dheerajd-msys** [comment]
Hi @marcparadise,

Actually `--ssh-user` is available in `config` but not in `Chef::Config[:knife]` so if we don't set the `user` in `config.rb` it won't be available and could not be mapped to `--connection-user`.

 https://github.com/chef/chef/blob/cdcbe629ef44b8206e74db00148b04803a333892/lib/chef/knife/bootstrap.rb#L994-L1005

Mistakenly I was giving `--ssh-user` in command-line instead of setting it into `config.rb` which was the culprit here. Due to this `--connection-user` was not mapped to `--ssh-user` and it's value converted to `root` during connection and caused `platform detection failure`.

Lately I set the `knife[:ssh_user]` in `config.rb` and got passed this error.

Closing this PR.

Thank you!

**Comment by marcparadise** [comment]
Thanks @dheerajd-msys - should we have an issue for ssh_user not being available from config? The intent was that it would fall back to that if the user was not given on CLI. (Same for winrm_user)

**Comment by dheerajd-msys** [comment]
Sure, I will open an issue for `ssh_user` @marcparadise

**Comment by dheerajd-msys** [comment]
@marcparadise FYI, https://github.com/chef/knife-ec2/issues/574 Thanks

**Pull request closed without merging**
